import CRNT.Stoich.Subspace
import Mathlib.Algebra.BigOperators.Ring.Finset
import Mathlib.Algebra.BigOperators.Pi

/-!
# Consistent networks (positive dependence of the reaction vectors)

A reaction network is **consistent** when its reaction vectors are *positively dependent*: there
is a strictly positive weighting `α : ℛ → ℝ₊` of the reactions under which the weighted reaction
vectors cancel,

```text
∑_{y→y'} α_{y→y'} (y' − y) = 0.
```

This is the first of the three conditions in the definition of a *regular* network underlying
Feinberg's Deficiency One Algorithm (Ji, *Uniqueness of equilibria for complex chemical reaction
networks*, Ohio State University, 2011, §1.6; Feinberg, *Foundations of Chemical Reaction Network
Theory*, Springer, 2019). It is exactly the condition that a positive complex mixture can be held
at steady state by some choice of reaction rates — equivalently, that `0` lies in the relative
interior of the cone generated by the reaction vectors.

* `IsConsistent` — the positive-dependence predicate;
* `inner_reactionVector_eq_zero_of_isConsistent_of_nonneg` — a Stiemke-type consequence: any linear
  functional that is nonnegative on every reaction vector is in fact **zero** on every reaction
  vector. So a one-signed functional against the reaction vectors is forced to be a conservation
  law, orthogonal to the entire stoichiometric subspace.

This module is **stable** and `sorry`-free. Depends on: `CRNT.Stoich.Subspace`,
`Mathlib.Algebra.BigOperators.Ring.Finset`, `Mathlib.Algebra.BigOperators.Pi`.
-/

namespace CRNT

namespace Network

open scoped BigOperators

variable {S : Type} [DecidableEq S] [Fintype S]

/-- **Consistency.** The reaction vectors are positively dependent: some strictly positive
weighting of the reactions makes the weighted reaction vectors cancel. -/
def IsConsistent (N : Network S) : Prop :=
  ∃ α : N.R → ℝ, (∀ r, 0 < α r) ∧ ∑ r, α r • N.reactionVector r = 0

/-- **A nonnegative functional against the reaction vectors of a consistent network vanishes on
them.** If `w` has `⟪w, y'−y⟫ ≥ 0` for every reaction, then consistency forces `⟪w, y'−y⟫ = 0` for
every reaction: the strictly positive weights turn the global cancellation into a termwise one.
This is the Stiemke alternative specialised to the reaction vectors. -/
theorem inner_reactionVector_eq_zero_of_isConsistent_of_nonneg (N : Network S)
    (h : N.IsConsistent) {w : S → ℝ}
    (hw : ∀ r, 0 ≤ ∑ s, w s * N.reactionVector r s) (r : N.R) :
    ∑ s, w s * N.reactionVector r s = 0 := by
  obtain ⟨α, hαpos, hα⟩ := h
  -- The weighted reaction-vector sum vanishes in every species coordinate.
  have hαs : ∀ s, ∑ r, α r * N.reactionVector r s = 0 := by
    intro s
    have := congrFun hα s
    simpa [Finset.sum_apply, Pi.smul_apply, smul_eq_mul] using this
  -- Pair `w` against the cancellation: `∑_r α_r ⟪w, v_r⟫ = ⟪w, ∑_r α_r v_r⟫ = 0`.
  have hexpand : ∀ r : N.R, α r * (∑ s, w s * N.reactionVector r s)
      = ∑ s, w s * (α r * N.reactionVector r s) := by
    intro r
    rw [Finset.mul_sum]
    exact Finset.sum_congr rfl fun s _ => mul_left_comm (α r) (w s) (N.reactionVector r s)
  have hsum : ∑ r, α r * (∑ s, w s * N.reactionVector r s) = 0 := by
    simp_rw [hexpand]
    rw [Finset.sum_comm]
    refine Finset.sum_eq_zero fun s _ => ?_
    rw [← Finset.mul_sum, hαs s, mul_zero]
  -- A nonnegative sum that vanishes is termwise zero; positivity of `α r` finishes.
  have hterm0 : α r * (∑ s, w s * N.reactionVector r s) = 0 :=
    (Finset.sum_eq_zero_iff_of_nonneg fun r _ => mul_nonneg (hαpos r).le (hw r)).mp hsum r
      (Finset.mem_univ r)
  exact (mul_eq_zero.mp hterm0).resolve_left (hαpos r).ne'

end Network

end CRNT
