import CRNT.Geometry.ConeFace

/-!
# `CompleteFan`: a constructive, proof-carrying API for complete pointed polyhedral fans

This module is the shared vocabulary for everything in this swarm that needs a fan: the
polyhedral fans of Craciun v3 (arXiv:1501.02860), fans generated by a finite set of rays,
normal fans of polytopes, and the cones consumed by `CRNT.Geometry.PolyhedralBarrier` and
`CRNT.Geometry.FanFaceLattice`.

`CRNT.Geometry.ConeFace` already states the fan axioms as the predicate
`CRNT.IsPolyhedralFan`, whose covering and common-face clauses are *hypotheses*: nothing in
the tree discharges them for a concretely described fan.  `CompleteFan` below is the same
information packaged so that the clauses are **fields of a structure that constructions
actually fill**.  `CompleteFan.ofFunctionalSystem` in `Scaffold.Geometry.FanArrangement` is a
worked instance; `Scaffold.Geometry.FanExamples` contains three more (square, triangle, braid).

## What is provided

* `coneOf`, `ineqCone`: polyhedral cones given by finitely many weak inequalities, built as
  genuine `ProperCone ℝ E` (hence closed and pointed) rather than as bare sets.
* `CompleteFan`: a `Finset`-indexed family of proper cones **together with proofs** of
  * intersection-closure (`inter_closed`),
  * covering (`covers`),
  * closure under exposed faces (`faces_closed`),
  * the zero face (`zero_face_mem`).
* Derived theory, all proved, none assumed:
  * `CompleteFan.isPolyhedralFan` — an inhabitant *is* a `CRNT.IsPolyhedralFan`, so every
    existing consumer (`FanFaceLattice.deltaCore_mem`, `ToricFan.toricField`, …) applies;
  * `CompleteFan.complete` — every point of `E` lies in a cone of the fan;
  * `CompleteFan.inf_mem` — every **nonempty finite intersection of fan cones is a fan cone**
    (this is what makes the δ-core of `FanFaceLattice` land back inside the fan);
  * `CompleteFan.faces C` — a **finite face enumeration**: the `Finset` of fan cones
    contained in `C`, proved finite (`faces_card_le`), closed under `⊓`
    (`faces_inter_closed`), containing the zero face (`faces_zero_mem`) and containing every
    exposed face of `C` (`faces_of_exposedFace`).

## What is *not* provided (do not assume it)

* **No join operation.** The family is closed under `⊓`, not under suprema: the lattice join of
  two cones is generally not a cone of the fan, so no `join` is exposed here.
* **No polyhedral-face theory.** Faces are the *exposed* faces of `CRNT.Geometry.ConeFace`;
  the general face lattice of a polyhedral cone (minimal faces, vertex–face incidence,
  rational vertex enumeration) is not formalized.
* **No extremal-ray enumeration.** Nothing here computes the extreme rays of a cone.
* **No rationality certificate.** `CompleteFan` carries no rationality field; rationality is
  supplied *by construction* by callers whose cone-defining data is rational.
* The ambient space is assumed `T1Space` so that `ProperCone.mem_bot` applies; every use in
  the tree (`E = EuclideanSpace ℝ S`) satisfies it.

Depends on: `CRNT.Geometry.ConeFace` (Mathlib pointed/proper cones, exposed faces, the
`IsPolyhedralFan` predicate).  Nothing here is an axiom or a `sorry`.
-/

namespace CRNT

open scoped InnerProductSpace

/-! ## Polyhedral cones from finitely many inequalities -/

section IneqCone

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
  [T1Space E]

/-- **Package a set as a proper cone.** The set must contain `0`, be closed under addition and
under multiplication by nonnegative scalars, and be closed.  This is the single place where the
`ProperCone ℝ E` (closed pointed cone) machinery of Mathlib is instantiated, so every cone
below inherits its cone and closedness structure rather than being a bare set. -/
noncomputable def coneOf (s : Set E) (hz : (0 : E) ∈ s)
    (hadd : ∀ x y : E, x ∈ s → y ∈ s → x + y ∈ s)
    (hsmul : ∀ (c : ℝ) (x : E), 0 ≤ c → x ∈ s → c • x ∈ s) (hclosed : IsClosed s) :
    ProperCone ℝ E :=
  ⟨{ carrier := s, zero_mem' := hz, add_mem' := fun hx hy => hadd _ _ hx hy,
     smul_mem' := fun ⟨c, hc⟩ x hx => hsmul c x hc hx }, hclosed⟩

theorem isClosed_ineqSet (f : Finset (E →L[ℝ] ℝ)) :
    IsClosed {x : E | ∀ g ∈ f, g x ≤ 0} := by
  have hset : {x : E | ∀ g ∈ f, g x ≤ 0} = ⋂ g ∈ f, {x : E | g x ≤ 0} := by
    ext x; simp
  rw [hset]
  refine isClosed_biInter fun g hg => ?_
  have : Continuous (fun x : E => g x) := g.continuous
  exact isClosed_le this continuous_const

/-- **The inequality cone** `{x | ∀ g ∈ f, g x ≤ 0}` for a finite family `f` of continuous real
linear functionals: the polyhedral cone cut out by the weak inequalities `g x ≤ 0`.  It is a
`ProperCone ℝ E`, hence closed and pointed. -/
noncomputable def ineqCone (f : Finset (E →L[ℝ] ℝ)) : ProperCone ℝ E :=
  coneOf {x | ∀ g ∈ f, g x ≤ 0} (by simp)
    (fun x y hx hy g hg => by rw [map_add]; exact add_nonpos (hx g hg) (hy g hg))
    (fun c x hc hx g hg => by
      have h := hx g hg
      have hg' : g (c • x) = c * g x := by simp
      rw [hg']
      exact mul_nonpos_of_nonneg_of_nonpos hc h)
    (by
      have hset : {x : E | ∀ g ∈ f, g x ≤ 0} = ⋂ g ∈ f, {x : E | g x ≤ 0} := by
        ext x; simp
      rw [hset]
      refine isClosed_biInter fun g hg => ?_
      have : Continuous (fun x : E => g x) := g.continuous
      exact isClosed_le this continuous_const)

@[simp] theorem mem_ineqCone {f : Finset (E →L[ℝ] ℝ)} {x : E} :
    x ∈ ineqCone f ↔ ∀ g ∈ f, g x ≤ 0 := Iff.rfl

/-- The zero cone is contained in every inequality cone. -/
theorem bot_le_ineqCone (f : Finset (E →L[ℝ] ℝ)) : (⊥ : ProperCone ℝ E) ≤ ineqCone f := by
  intro x hx
  rw [ProperCone.mem_bot] at hx
  subst hx
  rw [mem_ineqCone]
  intro g _
  simp

/-- Finite union of two sets of continuous linear functionals.  Spelled out because `Finset`'s
union operator needs a `DecidableEq` on the element type, and there is none for continuous linear
maps. -/
noncomputable def clmUnion (f g : Finset (E →L[ℝ] ℝ)) : Finset (E →L[ℝ] ℝ) := by
  classical
  exact f ∪ g

@[simp] theorem mem_clmUnion {f g : Finset (E →L[ℝ] ℝ)} {k : E →L[ℝ] ℝ} :
    k ∈ clmUnion f g ↔ k ∈ f ∨ k ∈ g := by
  classical
  simp [clmUnion]

end IneqCone

/-! ## `CompleteFan` -/

section CompleteFan

noncomputable section

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
  [T1Space E]

/-- **A complete pointed polyhedral fan, with the fan axioms as proved fields.**

A `CompleteFan` is a finite family of proper cones (`ProperCone ℝ E`, i.e. closed and pointed)
together with the four pieces of evidence that make it a fan:

* `inter_closed` — the meet of two cones of the family is a cone of the family;
* `covers` — the cones cover the ambient space;
* `faces_closed` — every exposed face of a cone of the family is a cone of the family;
* `zero_face_mem` — the zero cone is a cone of the family.

These are *fields*, so an inhabitant carries proofs; they are never asserted without proof.
`CompleteFan.isPolyhedralFan` converts an inhabitant into the `CRNT.IsPolyhedralFan` predicate
used elsewhere in the tree.  See `Scaffold.Geometry.FanArrangement` for a construction. -/
structure CompleteFan (E : Type*) [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    [CompleteSpace E] where
  /-- The cone family. -/
  toFan : Fan E
  /-- **Closure under intersection.** -/
  inter_closed : ∀ C ∈ toFan, ∀ D ∈ toFan, C ⊓ D ∈ toFan
  /-- **Completeness.** The cones cover the ambient space. -/
  covers : (⋃ C ∈ toFan, (C : Set E)) = Set.univ
  /-- **Closure under exposed faces.** -/
  faces_closed : ∀ C ∈ toFan, ∀ D : ProperCone ℝ E, IsExposedFaceOf D C → D ∈ toFan
  /-- **The zero face is a cone of the family.** -/
  zero_face_mem : (⊥ : ProperCone ℝ E) ∈ toFan

namespace CompleteFan

variable {F : CompleteFan E}

/-- **A `CompleteFan` is a `CRNT.IsPolyhedralFan`.** This is the bridge to the rest of the
tree: `FanFaceLattice`, `ToricFan` and `PolyhedralBarrier` consume `IsPolyhedralFan`. -/
theorem isPolyhedralFan : IsPolyhedralFan F.toFan := by
  refine ⟨F.faces_closed, ?_, F.covers⟩
  intro C hC D hD
  refine ⟨C ⊓ D, F.inter_closed C hC D hD, ?_⟩
  show (C ⊓ D : Set E) = (C : Set E) ∩ (D : Set E)
  ext x
  simp

/-- **Completeness, pointwise.** Every point of the ambient space lies in a cone of the fan.
This is the geometric content of a *complete* fan and the first thing any consumer needs. -/
theorem complete (x : E) : ∃ C ∈ F.toFan, x ∈ C := by
  have hx : x ∈ (⋃ C ∈ F.toFan, (C : Set E)) := by
    rw [F.covers]
    exact Set.mem_univ x
  rw [Set.mem_iUnion₂] at hx
  obtain ⟨C, hC, hxC⟩ := hx
  exact ⟨C, hC, hxC⟩

/-- **The meet of two cones of the fan is a cone of the fan.** -/
theorem inter_mem {C D : ProperCone ℝ E} (hC : C ∈ F.toFan) (hD : D ∈ F.toFan) :
    C ⊓ D ∈ F.toFan :=
  F.inter_closed C hC D hD

/-- **A nonempty finite family of fan cones has a least element inside the fan.**
Concretely: for a nonempty finite subfamily of the fan there is a cone `G` of the fan contained
in every member of the subfamily.  This is the step that lets a finite intersection of nearby fan
cones — the δ-core of `CRNT.Geometry.FanFaceLattice`, or `faceRelevantCore` of
`CRNT.Dynamics.FaceDirectionCone` — be *named* as a cone of the fan rather than merely as a
subset of one. -/
theorem exists_mem_le_finset (s : Finset (ProperCone ℝ E)) (hs : s.Nonempty)
    (h : ∀ C ∈ s, C ∈ F.toFan) :
    ∃ G ∈ F.toFan, ∀ C ∈ s, G ≤ C := by
  classical
  induction s using Finset.induction_on with
  | empty => exact absurd hs (by simp)
  | insert a t ha ih =>
    have haF : a ∈ F.toFan := h a (Finset.mem_insert_self a t)
    by_cases ht : t.Nonempty
    · obtain ⟨G, hG, hGle⟩ := ih ht fun c hc => h c (Finset.mem_insert_of_mem hc)
      refine ⟨G ⊓ a, F.inter_closed G hG a haF, fun C hC => ?_⟩
      rcases Finset.mem_insert.mp hC with hCa | hCt
      · rw [hCa]
        exact inf_le_right
      · exact (inf_le_left.trans (hGle C hCt) : G ⊓ a ≤ C)
    · refine ⟨a, haF, fun C hC => ?_⟩
      rcases Finset.mem_insert.mp hC with hCa | hCt
      · rw [hCa]
      · exact absurd hCt (fun hwt => ht ⟨C, hwt⟩)

/-- The zero face is the least cone of the family: it lies in every cone of the fan. -/
theorem zero_face_le {C : ProperCone ℝ E} (hC : C ∈ F.toFan) : (⊥ : ProperCone ℝ E) ≤ C :=
  bot_le

/-- An exposed face of a fan cone lies in that cone. -/
theorem face_le {C D : ProperCone ℝ E} (hD : IsExposedFaceOf D C) : D ≤ C := by
  obtain ⟨a, _, hset⟩ := hD
  intro x hx
  have hx2 : x ∈ ((D : PointedCone ℝ E) : Set E) :=
    SetLike.mem_coe (A := PointedCone ℝ E) |>.mpr hx
  rw [hset] at hx2
  exact SetLike.mem_coe (A := PointedCone ℝ E) |>.mp ((mem_exposedFace.1 hx2).1)

/-! ### Finite face enumeration -/

local instance properConeDecidableLE (C : ProperCone ℝ E) :
    DecidablePred (fun D : ProperCone ℝ E => D ≤ C) := fun _ => Classical.propDecidable _

/-- **The face enumeration of a fan cone `C`.**  This is the `Finset` of cones of the fan that
are contained in `C`: every exposed face of `C` is one of them (`faces_of_exposedFace`), and
`⊥` and `C` are among them.  Being a `Finset`, the enumeration is finite by construction. -/
noncomputable def faces (C : ProperCone ℝ E) : Finset (ProperCone ℝ E) :=
  F.toFan.filter fun D => D ≤ C

@[simp] theorem mem_faces {C D : ProperCone ℝ E} :
    D ∈ F.faces C ↔ D ∈ F.toFan ∧ D ≤ C := Finset.mem_filter

/-- The face enumeration of a fan cone is finite, and no larger than the fan. -/
theorem faces_card_le {C : ProperCone ℝ E} : (F.faces C).card ≤ F.toFan.card :=
  Finset.card_le_card (F.toFan.filter_subset _)

/-- The face enumeration is contained in the fan. -/
theorem faces_subset_fan {C : ProperCone ℝ E} : ↑(F.faces C) ⊆ ↑F.toFan :=
  fun _ h => (mem_faces.1 h).1

/-- Everything in the face enumeration is contained in `C`. -/
theorem faces_le {C : ProperCone ℝ E} : ∀ ⦃D⦄, D ∈ F.faces C → D ≤ C :=
  fun _ h => (mem_faces.1 h).2

/-- **The zero face is in the face enumeration** of every cone of the fan. -/
theorem faces_zero_mem {C : ProperCone ℝ E} (hC : C ∈ F.toFan) : (⊥ : ProperCone ℝ E) ∈ F.faces C :=
  mem_faces.2 ⟨F.zero_face_mem, bot_le⟩

/-- The cone itself is in its own face enumeration. -/
theorem faces_top_mem {C : ProperCone ℝ E} (hC : C ∈ F.toFan) : C ∈ F.faces C :=
  mem_faces.2 ⟨hC, le_rfl⟩

/-- **The face enumeration is closed under intersection.** -/
theorem faces_inter_closed {C : ProperCone ℝ E} {D E' : ProperCone ℝ E}
    (hD : D ∈ F.faces C) (hE : E' ∈ F.faces C) :
    D ⊓ E' ∈ F.faces C :=
  mem_faces.2 ⟨F.inter_closed D (mem_faces.1 hD).1 E' (mem_faces.1 hE).1,
    (inf_le_left : D ⊓ E' ≤ D) |>.trans (F.faces_le hD)⟩

/-- **Every exposed face of a fan cone occurs in its face enumeration.**  Together with
`faces_zero_mem` and `faces_inter_closed` this makes `F.faces C` a finite family of fan cones
closed under `⊓`, containing `⊥`, `C`, and all exposed faces of `C`. -/
theorem faces_of_exposedFace {C D : ProperCone ℝ E} (hC : C ∈ F.toFan)
    (hD : IsExposedFaceOf D C) : D ∈ F.faces C :=
  mem_faces.2 ⟨F.faces_closed C hC D hD, face_le hD⟩

end CompleteFan

end

end CompleteFan

end CRNT