-- GENERATED by scripts/gen_lakefile.py -- do not edit by hand.
-- Frontier aggregator: 42 modules: every one the frontier target has ever covered, of which 0 are still unverified and on scripts/unverified_modules.txt.
-- To change it, edit scripts/unverified_modules.txt and re-run
-- `python3 scripts/gen_lakefile.py`.

import CRNT.Dynamics.GlobalAttractorTheorem
import CRNT.Dynamics.HighCodimensionSiphonFace
import CRNT.Multistationarity.TrueChemistrySRCriterion
import CRNT.Oscillation
import CRNT.Oscillation.CompatibilityAdapters
import CRNT.Oscillation.DHopfOpenness
import CRNT.Oscillation.DiagonalScaling
import CRNT.Oscillation.FisherFullerScaling
import CRNT.Oscillation.FloquetOrbitalStability
import CRNT.Oscillation.FloquetPersistenceGeneral
import CRNT.Oscillation.GlobalHopfIndex
import CRNT.Oscillation.GlobalHopfIndexTheorem
import CRNT.Oscillation.GlobalHopfSpectralCrossing
import CRNT.Oscillation.HalfPlanePolynomial
import CRNT.Oscillation.HurwitzBordering
import CRNT.Oscillation.OscillationKernelBundle
import CRNT.Oscillation.ParameterRichGlobalHopf
import CRNT.Oscillation.PlanarAdjacentReturnLoop
import CRNT.Oscillation.PlanarDivergenceRegularity
import CRNT.Oscillation.PlanarEndToEnd
import CRNT.Oscillation.PlanarFlowRegularity
import CRNT.Oscillation.PlanarGreenGrid
import CRNT.Oscillation.PlanarGreenJordanApproximation
import CRNT.Oscillation.PlanarGreenRectangle
import CRNT.Oscillation.PlanarJordanBoundaryCurrent
import CRNT.Oscillation.PlanarJordanCrossingOrder
import CRNT.Oscillation.PlanarJordanDyadic
import CRNT.Oscillation.PlanarJordanTopology
import CRNT.Oscillation.PlanarLocalReturnLoops
import CRNT.Oscillation.PlanarLocalReturns
import CRNT.Oscillation.PlanarPoincareBendixson
import CRNT.Oscillation.PlanarReturnMonotonicity
import CRNT.Oscillation.PlanarSectionHitIsolation
import CRNT.Oscillation.ReducedKineticContinuation
import CRNT.Oscillation.SimpleNegativeSpectrum
import CRNT.Oscillation.SmoothGlobalHopf
import CRNT.Oscillation.SpectralOpenness
import CRNT.Oscillation.StableCodimOneDHopf
import CRNT.Oscillation.VassenaPrincipal
import CRNT.Theorems.DeficiencyOne.DegreeExistence
import CRNT.Theorems.DeficiencyOne.Theorem
import CRNT.Theorems.DeficiencyOne.WeaklyReversibleExistence

/-!
# Frontier aggregator.

This target is allowed to fail; its elaboration-error count is the tracked metric.
Every module it imports is elaborated by `lake build CRNTFrontier`, including the
ones that have graduated into the verified `CRNT` target -- that is what makes the
count monotone instead of a function of which modules happen to be unverified today.
-/
