import CRNT.Equilibria.TreeConstantBinomials
import CRNT.Deficiency.LinkageDeficiency
import CRNT.Equilibria.TreeConstantKernelBasis

/-!
# Tree-constant characterization of complex balance

For a weakly reversible mass-action system the positive kernel of the kinetic Laplacian
is one-dimensional on each linkage class and is generated by the tree constants.
Therefore complex balance is equivalent to the classical tree-constant binomial
relations inside every linkage class.
-/

namespace CRNT
namespace Network

variable {S : Type} [DecidableEq S] [Fintype S]

/-- Complex balance is exactly kinetic-kernel membership of the complex-monomial vector. -/
theorem isComplexBalanced_iff_complexMonomial_kineticKernel
    (N : Network S) (κ : N.RateConstants) (x : Concentration S) :
    N.IsComplexBalanced κ x ↔ N.kineticMap κ (N.complexMonomial x) = 0 := by
  change N.IsComplexBalanced κ x ↔ N.kineticMap κ (N.complexMonomialVector x) = 0
  exact N.isComplexBalanced_iff_kineticMap κ x

/-- Tree-constant binomial system. -/
def SatisfiesTreeConstantBinomials (N : Network S) (κ : N.RateConstants)
    (x : Concentration S) : Prop :=
  ∀ i j : N.ComplexIdx, N.Linked i.1 j.1 →
    N.treeConstant κ j * N.complexMonomial x i =
      N.treeConstant κ i * N.complexMonomial x j

/-- Complex balance implies all tree-constant binomials. -/
theorem satisfiesTreeConstantBinomials_of_complexBalanced
    (N : Network S) (κ : N.RateConstants) (hwr : N.WeaklyReversible)
    {x : Concentration S} (hx : x.Positive) (hcb : N.IsComplexBalanced κ x) :
    N.SatisfiesTreeConstantBinomials κ x := by
  intro i j hij
  exact N.treeConstant_binomial_of_complexBalanced κ hwr hx hcb hij

/-- Under weak reversibility, the tree-constant binomials are sufficient for positive
complex balance. -/
theorem complexBalanced_of_treeConstantBinomials
    (N : Network S) (κ : N.RateConstants) (hwr : N.WeaklyReversible)
    {x : Concentration S} (hx : x.Positive)
    (hbin : N.SatisfiesTreeConstantBinomials κ x) :
    N.IsComplexBalanced κ x := by
  classical
  let rep : Quotient N.linkedSetoid → N.ComplexIdx :=
    fun q => Classical.choose (Quotient.exists_rep q)
  have hrep (q : Quotient N.linkedSetoid) : N.classOf (rep q) = q := by
    simpa [rep, classOf] using (Classical.choose_spec (Quotient.exists_rep q))
  let a : Quotient N.linkedSetoid → ℝ := fun q =>
    N.complexMonomial x (rep q) / N.treeConstant κ (rep q)
  have hparam : ∀ c : N.ComplexIdx,
      N.complexMonomial x c = a (N.classOf c) * N.treeConstant κ c := by
    intro c
    have hlinked : N.Linked c.val (rep (N.classOf c)).val := by
      exact Quotient.exact ((hrep (N.classOf c)).symm)
    have hbin' := hbin c (rep (N.classOf c)) hlinked
    have hK : 0 < N.treeConstant κ (rep (N.classOf c)) :=
      N.treeConstant_pos_of_weaklyReversible κ hwr _
    dsimp [a]
    field_simp [hK.ne']
    simpa [mul_comm] using hbin'
  apply (N.isComplexBalanced_iff_complexMonomial_kineticKernel κ x).2
  have hv : N.complexMonomial x = N.treeKernelCoordinates κ a := by
    funext c
    rw [hparam c]
    simp [treeKernelCoordinates, classTreeVector]
  rw [hv, ← LinearMap.mem_ker,
    ← N.range_treeKernelCoordinates_eq_kineticKernel κ hwr]
  exact ⟨a, rfl⟩

/-- **Classical tree-constant criterion.** -/
theorem complexBalanced_iff_treeConstantBinomials
    (N : Network S) (κ : N.RateConstants) (hwr : N.WeaklyReversible)
    {x : Concentration S} (hx : x.Positive) :
    N.IsComplexBalanced κ x ↔ N.SatisfiesTreeConstantBinomials κ x := by
  exact ⟨N.satisfiesTreeConstantBinomials_of_complexBalanced κ hwr hx,
    N.complexBalanced_of_treeConstantBinomials κ hwr hx⟩

/-- Classwise scalar parametrization of a positive complex-balanced monomial vector by
its tree constants. -/
theorem exists_linkage_scalars_of_complexBalanced
    (N : Network S) (κ : N.RateConstants) (hwr : N.WeaklyReversible)
    {x : Concentration S} (hx : x.Positive) (hcb : N.IsComplexBalanced κ x) :
    ∃ a : Quotient N.linkedSetoid → ℝ,
      (∀ q, 0 < a q) ∧
      ∀ c : N.ComplexIdx,
        N.complexMonomial x c = a (N.classOf c) * N.treeConstant κ c := by
  classical
  have hker : N.kineticMap κ (N.complexMonomial x) = 0 :=
    (N.isComplexBalanced_iff_complexMonomial_kineticKernel κ x).1 hcb
  have hpos : ∀ c : N.ComplexIdx, 0 < N.complexMonomial x c := by
    intro c
    exact Complex.massActionMonomial_pos hx c.val
  obtain ⟨a, ha, hv⟩ :=
    (N.positive_kineticKernel_iff_treeCoefficients κ hwr (N.complexMonomial x)).1
      ⟨hker, hpos⟩
  refine ⟨a, ha, ?_⟩
  intro c
  have hc := congrFun hv c
  simpa [treeKernelCoordinates, classTreeVector] using hc

/-- Conversely, any positive classwise tree-constant parametrization is complex-balanced. -/
theorem complexBalanced_of_linkage_scalars
    (N : Network S) (κ : N.RateConstants) (hwr : N.WeaklyReversible)
    {x : Concentration S} (hx : x.Positive)
    {a : Quotient N.linkedSetoid → ℝ}
    (ha : ∀ q, 0 < a q)
    (hparam : ∀ c : N.ComplexIdx,
      N.complexMonomial x c = a (N.classOf c) * N.treeConstant κ c) :
    N.IsComplexBalanced κ x := by
  apply N.complexBalanced_of_treeConstantBinomials κ hwr hx
  intro i j hij
  rw [hparam i, hparam j]
  have hclass : N.classOf i = N.classOf j := Quotient.sound hij
  rw [hclass]
  ring

end Network
end CRNT
