import CRNT.Equilibria.Wegscheider
import CRNT.Stoich.Transpose

/-!
# Wegscheider theorem: cycle conditions, potentials, and detailed balance

This module closes the converse direction left open in `CRNT.Equilibria.Wegscheider`.
For a reversible channel pairing, the following are equivalent:

1. every stoichiometric cycle has zero logarithmic affinity (Wegscheider conditions);
2. the affinity vector is a stoichiometric potential gradient;
3. there exists a positive concentration satisfying reactionwise detailed balance.

The only linear-algebra input is the structural identity
`range Sᵀ = (ker S)ᗮ` from `CRNT.Stoich.Transpose`.
-/

namespace CRNT

open Matrix

namespace Network

variable {S : Type} [DecidableEq S] [Fintype S]

/-- **Wegscheider converse.** An affinity vector annihilates every stoichiometric cycle
iff it is generated by a species potential. -/
theorem satisfiesWegscheider_iff_hasWegscheiderPotential
    (N : Network S) (ρ : ReversiblePairing N) (κ : RateConstants N) :
    N.SatisfiesWegscheider ρ κ ↔ N.HasWegscheiderPotential ρ κ := by
  unfold SatisfiesWegscheider HasWegscheiderPotential
  exact N.mem_orthSum_ker_iff_exists_stoichPotential
    (N.logEquilibriumConstant ρ κ)

/-- The logarithmic Wegscheider cycle conditions are exactly membership of the affinity
vector in the row space of the stoichiometric matrix. -/
theorem satisfiesWegscheider_iff_affinity_mem_stoichTransposeRange
    (N : Network S) (ρ : ReversiblePairing N) (κ : RateConstants N) :
    N.SatisfiesWegscheider ρ κ ↔
      N.logEquilibriumConstant ρ κ ∈ LinearMap.range N.stoichTransposeMap := by
  rw [N.satisfiesWegscheider_iff_hasWegscheiderPotential ρ κ]
  unfold HasWegscheiderPotential
  constructor
  · rintro ⟨μ, hμ⟩
    refine ⟨μ, ?_⟩
    funext r
    rw [N.stoichTransposeMap_apply]
    exact (hμ r).symm
  · rintro ⟨μ, hμ⟩
    refine ⟨μ, ?_⟩
    intro r
    have hr := congrFun hμ r
    rw [N.stoichTransposeMap_apply] at hr
    exact hr.symm

/-- **Classical Wegscheider theorem, reactionwise form.** For positive rate constants and
a chosen involutive reverse-channel pairing, the cycle conditions hold iff a positive
reactionwise detailed-balanced state exists. -/
theorem satisfiesWegscheider_iff_exists_positive_reactionwiseDetailedBalanced
    (N : Network S) (ρ : ReversiblePairing N) (κ : RateConstants N) :
    N.SatisfiesWegscheider ρ κ ↔
      ∃ x : Concentration S, x.Positive ∧
        N.IsReactionwiseDetailedBalanced ρ κ x := by
  rw [N.satisfiesWegscheider_iff_hasWegscheiderPotential ρ κ,
    N.hasWegscheiderPotential_iff_exists_positive_reactionwiseDetailedBalanced ρ κ]

/-- Every set of rate constants satisfying the Wegscheider conditions admits a positive
aggregate detailed-balanced state, and therefore a positive complex-balanced steady state. -/
theorem exists_positiveDetailedBalanced_of_satisfiesWegscheider
    (N : Network S) (ρ : ReversiblePairing N) (κ : RateConstants N)
    (hW : N.SatisfiesWegscheider ρ κ) :
    ∃ x : Concentration S, N.IsPositiveDetailedBalanced κ x := by
  exact N.exists_positiveDetailedBalanced_of_hasWegscheiderPotential ρ κ
    ((N.satisfiesWegscheider_iff_hasWegscheiderPotential ρ κ).mp hW)

/-- In particular, Wegscheider-compatible reversible mass-action systems possess a
positive complex-balanced steady state. -/
theorem exists_positiveComplexBalanced_of_satisfiesWegscheider
    (N : Network S) (ρ : ReversiblePairing N) (κ : RateConstants N)
    (hW : N.SatisfiesWegscheider ρ κ) :
    ∃ x : Concentration S, x.Positive ∧ N.IsComplexBalanced κ x := by
  obtain ⟨x, hxdb⟩ := N.exists_positiveDetailedBalanced_of_satisfiesWegscheider ρ κ hW
  exact ⟨x, N.positiveComplexBalanced_of_positiveDetailedBalanced κ x hxdb⟩

/-- And hence a positive mass-action steady state exists. -/
theorem exists_positiveSteadyState_of_satisfiesWegscheider
    (N : Network S) (ρ : ReversiblePairing N) (κ : RateConstants N)
    (hW : N.SatisfiesWegscheider ρ κ) :
    ∃ x : Concentration S, x.Positive ∧ N.IsMassActionSteadyState κ x := by
  obtain ⟨x, hx, hcb⟩ :=
    N.exists_positiveComplexBalanced_of_satisfiesWegscheider ρ κ hW
  exact ⟨x, hx, hcb.isMassActionSteadyState N κ⟩

end Network
end CRNT
