import CRNT.LinearAlgebra.OrientedMatroidConditions
import CRNT.Kinetics.GeneralizedConditions

/-!
# Equal-coordinate nondegeneracy for pairs of realizable oriented matroids

The generalized Birch/bijectivity literature uses, in addition to uniqueness and face
compatibility, a nondegeneracy condition.  Its computational form searches for vectors whose
positive equal-coordinate blocks can be generated by nonnegative circuits, while their positive
support fails the required cocircuit support condition.

This file records that geometry independently of a choice of matrix representation.  Circuits of a
realizable subspace `A` are cocircuits of `Aᗮ`; this keeps row-space/kernel-matrix conventions out of
the theorem statements.
-/

namespace CRNT

variable {ι : Type*} [DecidableEq ι] [Fintype ι]

/-- Positive support of a real vector. -/
noncomputable def positiveSupport (v : ι → ℝ) : Finset ι :=
  Finset.univ.filter fun i => 0 < v i

/-- Coordinates in `P` form one strictly positive equal-value block of `v`. -/
def IsPositiveEqualBlock (v : ι → ℝ) (P : Finset ι) : Prop :=
  P.Nonempty ∧ ∃ a : ℝ, 0 < a ∧ ∀ i ∈ P, v i = a

/-- A realizable circuit of `A`, represented as a cocircuit of the orthogonal complement. -/
def IsRealizableCircuit (A : Submodule ℝ (ι → ℝ)) (σ : ι → SignType) : Prop :=
  IsRealizableCocircuit (orthSum A) σ

/-- A nonnegative realizable circuit. -/
def IsNonnegativeCircuit (A : Submodule ℝ (ι → ℝ)) (σ : ι → SignType) : Prop :=
  IsRealizableCircuit A σ ∧ SignVector.Nonnegative σ

/-- `P` can be covered by supports of nonnegative circuits of `A`, each contained in `P`. -/
def CircuitCoverable (A : Submodule ℝ (ι → ℝ)) (P : Finset ι) : Prop :=
  ∃ F : Finset (ι → SignType),
    (∀ σ ∈ F, IsNonnegativeCircuit A σ ∧ σ.support ⊆ P) ∧
    P ⊆ F.biUnion SignVector.support

/-- Every strictly positive equal-coordinate level of `v` can be decomposed into nonnegative
circuit supports of `A`. -/
def PositiveEqualLevelsCircuitCoverable
    (A : Submodule ℝ (ι → ℝ)) (v : ι → ℝ) : Prop :=
  ∀ P : Finset ι, IsPositiveEqualBlock v P →
    (∀ i ∈ P, ∀ j, 0 < v j → v j = v i → j ∈ P) → CircuitCoverable A P

/-- The positive support of `v` contains a nonnegative cocircuit of `A`. -/
def PositiveSupportContainsCocircuit
    (A : Submodule ℝ (ι → ℝ)) (v : ι → ℝ) : Prop :=
  ∃ σ : ι → SignType, IsNonnegativeCocircuit A σ ∧ σ.support ⊆ positiveSupport v

/-- A representation-independent degeneracy witness for the pair `(A,B)`.

The witness lies in `B`; its positive equal-coordinate blocks are circuit-coverable from `A`, but
its positive support contains no admissible nonnegative cocircuit of `A`.  This is the geometric
content certified by the `sign_crn` nondegeneracy search, separated from its matrix algorithm. -/
def HasEqualCoordinateDegeneracyWitness
    (A B : Submodule ℝ (ι → ℝ)) : Prop :=
  ∃ v : ι → ℝ, v ∈ B ∧ v ≠ 0 ∧ (positiveSupport v).Nonempty ∧
    PositiveEqualLevelsCircuitCoverable A v ∧
    ¬ PositiveSupportContainsCocircuit A v

/-- Equal-coordinate nondegeneracy of a pair of realizable subspaces. -/
def EqualCoordinateNondegenerate
    (A B : Submodule ℝ (ι → ℝ)) : Prop :=
  ¬ HasEqualCoordinateDegeneracyWitness A B

/-- If `A` has no nonnegative circuit, equal-coordinate degeneracy cannot occur through a
nonempty positive equal block.  This is the easy certificate used by the implementation. -/
theorem equalCoordinateNondegenerate_of_no_nonnegativeCircuit
    (A B : Submodule ℝ (ι → ℝ))
    (hA : ∀ σ, ¬ IsNonnegativeCircuit A σ) :
    EqualCoordinateNondegenerate A B := by
  intro h
  rcases h with ⟨v, hvB, hv0, hp, hcover, hsupport⟩
  let i := hp.choose
  have hi : 0 < v i := by
    exact Finset.mem_filter.mp hp.choose_spec |>.2
  let P : Finset ι := Finset.univ.filter fun j => v j = v i
  have hiP : i ∈ P := by simp [P]
  have hP : IsPositiveEqualBlock v P := by
    refine ⟨⟨i, hiP⟩, v i, hi, ?_⟩
    intro j hj
    exact Finset.mem_filter.mp hj |>.2
  have hmax : ∀ j ∈ P, ∀ k, 0 < v k → v k = v j → k ∈ P := by
    intro j hj k hkpos hkj
    have hjv : v j = v i := Finset.mem_filter.mp hj |>.2
    simp [P, hkj, hjv]
  rcases hcover P hP hmax with ⟨F, hF, hPF⟩
  have hFne : F.Nonempty := by
    have hiU : i ∈ F.biUnion SignVector.support := hPF hiP
    rcases Finset.mem_biUnion.mp hiU with ⟨σ, hσF, _⟩
    exact ⟨σ, hσF⟩
  let σ := hFne.choose
  exact hA σ (hF σ hFne.choose_spec).1

/-- The nondegeneracy condition is invariant under replacing `B` by an equal subspace. -/
theorem equalCoordinateNondegenerate_congr_right
    (A B C : Submodule ℝ (ι → ℝ)) (hBC : B = C) :
    EqualCoordinateNondegenerate A B ↔ EqualCoordinateNondegenerate A C := by
  subst C
  rfl

/-- Bundle the four sign-geometric conditions used for robust generalized CBE theory. -/
structure OrientedMatroidCBEConditions
    (A B : Submodule ℝ (ι → ℝ)) : Prop where
  closure : TopeClosureCondition A B
  uniqueness : OrientedMatroidUniquenessCondition A B
  face : CocircuitFaceCondition A B
  nondegenerate : EqualCoordinateNondegenerate A B

end CRNT
