import CRNT.Stochastic.FosterLyapunov
import Mathlib.Algebra.Module.Submodule.Basic
import Mathlib.Data.Int.ModEq

/-!
# Integer stoichiometric lattice and stochastic communication obstructions

The stochastic CRN lives on `ℕ^S`, so real stoichiometric compatibility is not the whole
story.  Every reaction changes the count by an *integer* stoichiometric vector.  The
subgroup generated by these vectors controls lattice communication classes; parity and
other congruence obstructions are special cases.
-/

namespace CRNT
namespace Network

open scoped BigOperators

variable {S : Type} [DecidableEq S] [Fintype S]

/-- Integer reaction vector. -/
def integerReactionVector (N : Network S) (r : N.R) : S → ℤ :=
  fun s => (N.reaction r).target s - (N.reaction r).source s

/-- Integer stoichiometric lattice generated by reaction moves. -/
noncomputable def integerStoichLattice (N : Network S) : Submodule ℤ (S → ℤ) :=
  Submodule.span ℤ (Set.range N.integerReactionVector)

/-- Signed difference of two count vectors. -/
def countDifference (m n : S → ℕ) : S → ℤ :=
  fun s => (m s : ℤ) - (n s : ℤ)

/-- Two count states lie in the same integer stoichiometric coset. -/
def SameIntegerStoichClass (N : Network S) (m n : S → ℕ) : Prop :=
  countDifference m n ∈ N.integerStoichLattice

@[refl] theorem sameIntegerStoichClass_refl (N : Network S) (n : S → ℕ) :
    N.SameIntegerStoichClass n n := by
  have h0 : countDifference n n = 0 := by funext s; simp [countDifference]
  rw [SameIntegerStoichClass, h0]
  exact Submodule.zero_mem _

@[symm] theorem sameIntegerStoichClass_symm (N : Network S) {m n : S → ℕ}
    (h : N.SameIntegerStoichClass m n) : N.SameIntegerStoichClass n m := by
  have : countDifference n m = - countDifference m n := by
    funext s; simp [countDifference]
  rw [SameIntegerStoichClass, this]
  exact Submodule.neg_mem _ h

@[trans] theorem sameIntegerStoichClass_trans (N : Network S) {a b c : S → ℕ}
    (hab : N.SameIntegerStoichClass a b) (hbc : N.SameIntegerStoichClass b c) :
    N.SameIntegerStoichClass a c := by
  have hsum : countDifference a c = countDifference a b + countDifference b c := by
    funext s; simp [countDifference]
  rw [SameIntegerStoichClass, hsum]
  exact Submodule.add_mem _ hab hbc

/-- One enabled stochastic reaction step. -/
def CountStep (N : Network S) (n m : S → ℕ) : Prop :=
  ∃ r : N.R, N.Enabled n r ∧ m = N.fireCount n r

/-- Finite stochastic reachability generated by enabled reaction firings. -/
def CountReachable (N : Network S) (n m : S → ℕ) : Prop :=
  Relation.ReflTransGen N.CountStep n m

/-- An enabled firing changes the count by exactly the integer reaction vector. -/
theorem countDifference_fireCount (N : Network S) {n : S → ℕ} {r : N.R}
    (hen : N.Enabled n r) :
    countDifference (N.fireCount n r) n = N.integerReactionVector r := by
  funext s
  simp [fireCount, hen, countDifference, integerReactionVector]
  have hs := hen s
  omega

/-- Every enabled firing stays in the same integer stoichiometric class. -/
theorem sameIntegerStoichClass_fireCount (N : Network S) {n : S → ℕ} {r : N.R}
    (hen : N.Enabled n r) :
    N.SameIntegerStoichClass (N.fireCount n r) n := by
  rw [SameIntegerStoichClass, N.countDifference_fireCount hen]
  exact Submodule.subset_span ⟨r, rfl⟩

/-- One-step stochastic motion cannot leave the integer stoichiometric coset. -/
theorem sameIntegerStoichClass_of_countStep (N : Network S) {n m : S → ℕ}
    (h : N.CountStep n m) : N.SameIntegerStoichClass m n := by
  rcases h with ⟨r, hen, rfl⟩
  exact N.sameIntegerStoichClass_fireCount hen

/-- **Lattice obstruction to communication.** Any finitely reachable state lies in the
same integer stoichiometric coset. -/
theorem sameIntegerStoichClass_of_reachable (N : Network S) {n m : S → ℕ}
    (h : N.CountReachable n m) : N.SameIntegerStoichClass m n := by
  induction h with
  | refl => exact N.sameIntegerStoichClass_refl _
  | tail hreach hstep ih =>
      exact N.sameIntegerStoichClass_trans
        (N.sameIntegerStoichClass_of_countStep hstep) ih

/-- Full integer-lattice generation: reaction moves generate all of `ℤ^S`. -/
def GeneratesFullIntegerLattice (N : Network S) : Prop :=
  N.integerStoichLattice = ⊤

/-- Integer linear observable on count states. -/
def integerObservable (q : S → ℤ) (n : S → ℕ) : ℤ :=
  ∑ s : S, q s * (n s : ℤ)

/-- A modular conservation law: every reaction changes `q·n` by a multiple of `d`. -/
def IsCongruenceInvariant (N : Network S) (d : ℕ) (q : S → ℤ) : Prop :=
  ∀ r : N.R, Int.ModEq d (∑ s : S, q s * N.integerReactionVector r s) 0

/-- A congruence invariant is preserved by one enabled firing. -/
theorem integerObservable_modEq_fireCount (N : Network S)
    {d : ℕ} {q : S → ℤ} (hq : N.IsCongruenceInvariant d q)
    {n : S → ℕ} {r : N.R} (hen : N.Enabled n r) :
    Int.ModEq d (integerObservable q (N.fireCount n r)) (integerObservable q n) := by
  have hΔ := hq r
  have hdiff : integerObservable q (N.fireCount n r) - integerObservable q n =
      ∑ s : S, q s * N.integerReactionVector r s := by
    unfold integerObservable
    rw [← Finset.sum_sub_distrib]
    apply Finset.sum_congr rfl
    intro s _
    have hs := congrFun (N.countDifference_fireCount hen) s
    simp [countDifference] at hs
    linear_combination (q s) * hs
  refine Int.modEq_iff_dvd.mpr ?_
  have hneg : integerObservable q n - integerObservable q (N.fireCount n r)
      = -(∑ s : S, q s * N.integerReactionVector r s) := by
    rw [← hdiff]; ring
  rw [hneg]
  exact dvd_neg.mpr (Int.modEq_zero_iff_dvd.mp hΔ)

/-- Congruence invariants are preserved along arbitrary finite stochastic paths. -/
theorem integerObservable_modEq_of_reachable (N : Network S)
    {d : ℕ} {q : S → ℤ} (hq : N.IsCongruenceInvariant d q)
    {n m : S → ℕ} (h : N.CountReachable n m) :
    Int.ModEq d (integerObservable q m) (integerObservable q n) := by
  induction h with
  | refl => exact Int.ModEq.refl _
  | tail hreach hstep ih =>
      rcases hstep with ⟨r, hen, rfl⟩
      exact (N.integerObservable_modEq_fireCount hq hen).trans ih

/-- A nontrivial modular invariant separates states with distinct residues, proving they
cannot communicate. -/
theorem not_reachable_of_congruence_separation (N : Network S)
    {d : ℕ} {q : S → ℤ} (hq : N.IsCongruenceInvariant d q)
    {n m : S → ℕ}
    (hsep : ¬ Int.ModEq d (integerObservable q m) (integerObservable q n)) :
    ¬ N.CountReachable n m := by
  intro h
  exact hsep (N.integerObservable_modEq_of_reachable hq h)

end Network
end CRNT
