import CRNT.Design.EmergentCycles
import CRNT.LinearAlgebra.OrthogonalComplement

/-!
# Emergent and lost conservation laws of a structural subnetwork

This file gives a basis-independent formulation of the conservation-law objects used in
buffering/RPA theory.  It mirrors the `S11` and `S_tilde` constructions without choosing
nullspace bases or pseudoinverses.
-/

namespace CRNT
namespace Network

variable {S : Type} [DecidableEq S] [Fintype S]

/-- Extend a vector on selected species by zero to the full species space. -/
def speciesExtension (V : Finset S) : (↥V → ℝ) →ₗ[ℝ] (S → ℝ) where
  toFun u := fun s => if hs : s ∈ V then u ⟨s, hs⟩ else 0
  map_add' u v := by
    funext s
    by_cases hs : s ∈ V <;> simp [hs]
  map_smul' a u := by
    funext s
    by_cases hs : s ∈ V <;> simp [hs]

@[simp] theorem speciesRestriction_extension (V : Finset S) (u : ↥V → ℝ) :
    speciesRestriction V (speciesExtension V u) = u := by
  funext s
  simp [speciesRestriction, speciesExtension, s.property]

/-- Stoichiometric directions generated by selected reactions, observed only on the
selected species.  This is the intrinsic image of the `S11` block. -/
noncomputable def localStoichSubspace (N : Network S) (γ : StructuralSubnetwork N) :
    Submodule ℝ (↥γ.species → ℝ) :=
  LinearMap.range ((N.internalStoichMap γ).domRestrict
    (N.supportedReactionSubspace γ.reactions))

/-- Conservation laws of the isolated `S11` block. -/
noncomputable def localConservationSubspace (N : Network S)
    (γ : StructuralSubnetwork N) : Submodule ℝ (↥γ.species → ℝ) :=
  orthSum (N.localStoichSubspace γ)

/-- Zero-padded internal stoichiometric directions. -/
noncomputable def paddedLocalStoichSubspace (N : Network S)
    (γ : StructuralSubnetwork N) : Submodule ℝ (S → ℝ) :=
  (N.localStoichSubspace γ).map (speciesExtension γ.species)

/-- Intrinsic version of the augmented matrix `S_tilde`: the original stoichiometric
image together with an additional zero-padded copy of the internal `S11` image. -/
noncomputable def augmentedStoichSubspace (N : Network S)
    (γ : StructuralSubnetwork N) : Submodule ℝ (S → ℝ) :=
  N.stoichSubspace ⊔ N.paddedLocalStoichSubspace γ

/-- Conservation laws of the augmented `S_tilde` system. -/
noncomputable def augmentedConservationSubspace (N : Network S)
    (γ : StructuralSubnetwork N) : Submodule ℝ (S → ℝ) :=
  orthSum (N.augmentedStoichSubspace γ)

/-- Restrictions to `Vγ` of conservation laws that survive the augmentation. -/
noncomputable def inheritedLocalConservationSubspace (N : Network S)
    (γ : StructuralSubnetwork N) : Submodule ℝ (↥γ.species → ℝ) :=
  (N.augmentedConservationSubspace γ).map (speciesRestriction γ.species)

/-- Emergent local conserved quantities: local `S11` conservation laws orthogonal to all
conservation laws inherited from the full augmented system. -/
noncomputable def emergentConservationSubspace (N : Network S)
    (γ : StructuralSubnetwork N) : Submodule ℝ (↥γ.species → ℝ) :=
  N.localConservationSubspace γ ⊓ orthSum (N.inheritedLocalConservationSubspace γ)

/-- Global conserved quantities lost when the internal `S11` image is added to the full
stoichiometric image.  Since `(coker S_tilde)^⊥ = im S_tilde`, this is exactly the
basis-independent counterpart of `coker S ∩ (coker S_tilde)^⊥`. -/
noncomputable def lostConservationSubspace (N : Network S)
    (γ : StructuralSubnetwork N) : Submodule ℝ (S → ℝ) :=
  orthSum N.stoichSubspace ⊓ N.augmentedStoichSubspace γ

noncomputable def localConservationDim (N : Network S)
    (γ : StructuralSubnetwork N) : ℕ :=
  Module.finrank ℝ (N.localConservationSubspace γ)

noncomputable def inheritedLocalConservationDim (N : Network S)
    (γ : StructuralSubnetwork N) : ℕ :=
  Module.finrank ℝ (N.inheritedLocalConservationSubspace γ)

noncomputable def emergentConservationDim (N : Network S)
    (γ : StructuralSubnetwork N) : ℕ :=
  Module.finrank ℝ (N.emergentConservationSubspace γ)

noncomputable def lostConservationDim (N : Network S)
    (γ : StructuralSubnetwork N) : ℕ :=
  Module.finrank ℝ (N.lostConservationSubspace γ)

/-- Every augmented conservation law is an original conservation law. -/
theorem augmentedConservation_le_global (N : Network S)
    (γ : StructuralSubnetwork N) :
    N.augmentedConservationSubspace γ ≤ orthSum N.stoichSubspace := by
  intro w hw
  rw [mem_orthSum]
  intro z hz
  exact hw z (Submodule.mem_sup_left hz)

/-- Dot-product adjointness of restriction and zero-padding: pairing a restricted vector
against `u` on `V` is the same as pairing the original against the zero-padded `u`.  Both
sums collapse to the part supported on `V`. -/
theorem sum_speciesRestriction_mul (V : Finset S) (w : S → ℝ) (u : ↥V → ℝ) :
    ∑ t : ↥V, speciesRestriction V w t * u t
      = ∑ s : S, w s * speciesExtension V u s := by
  classical
  have hrhs : ∑ s : S, w s * speciesExtension V u s
      = ∑ s ∈ V, w s * speciesExtension V u s := by
    refine (Finset.sum_subset (Finset.subset_univ V) ?_).symm
    intro s _ hs
    simp [speciesExtension, hs]
  rw [hrhs, ← Finset.sum_coe_sort V (fun s => w s * speciesExtension V u s)]
  refine Finset.sum_congr rfl fun t _ => ?_
  simp [speciesRestriction, speciesExtension, t.property]

/-- An inherited local conservation law is indeed a conservation law of the isolated
internal stoichiometric block. -/
theorem inheritedLocalConservation_le_local (N : Network S)
    (γ : StructuralSubnetwork N) :
    N.inheritedLocalConservationSubspace γ ≤ N.localConservationSubspace γ := by
  classical
  rintro v ⟨w, hw, rfl⟩
  rw [localConservationSubspace, mem_orthSum]
  intro z hz
  -- `w` kills the augmented stoichiometric space, and the zero-padding of `z` lies in it.
  have hpad : speciesExtension γ.species z ∈ N.augmentedStoichSubspace γ :=
    Submodule.mem_sup_right (Submodule.mem_map_of_mem hz)
  have := hw (speciesExtension γ.species z) hpad
  rw [← sum_speciesRestriction_mul] at this
  exact this

/-- The local conservation space decomposes orthogonally into inherited and emergent
parts.  This is the intrinsic form of the nullspace split in RPAFinder. -/
theorem localConservation_eq_inherited_sup_emergent (N : Network S)
    (γ : StructuralSubnetwork N) :
    N.localConservationSubspace γ =
      N.inheritedLocalConservationSubspace γ ⊔ N.emergentConservationSubspace γ := by
  -- `emergent` is by definition `local ⊓ inheritedᗮ`, so this is exactly the orthogonal
  -- decomposition of `local` relative to `inherited`, which sits inside it.
  exact (sup_inf_orthSum_of_le (N.inheritedLocalConservation_le_local γ)).symm

/-- Dimension decomposition for local conserved quantities. -/
theorem localConservationDim_eq_inherited_add_emergent (N : Network S)
    (γ : StructuralSubnetwork N) :
    N.localConservationDim γ =
      N.inheritedLocalConservationDim γ + N.emergentConservationDim γ := by
  -- `emergent` is `local ⊓ inheritedᗮ`, so this is the dimension form of the orthogonal
  -- decomposition of `local` relative to `inherited`.
  exact (finrank_add_finrank_inf_orthSum_of_le
    (N.inheritedLocalConservation_le_local γ)).symm

/-- Original global conservation laws split into those surviving the augmentation and
those lost by it. -/
theorem globalConservation_eq_augmented_sup_lost (N : Network S)
    (γ : StructuralSubnetwork N) :
    orthSum N.stoichSubspace =
      N.augmentedConservationSubspace γ ⊔ N.lostConservationSubspace γ := by
  -- Decompose the global conservation space relative to the augmented one, then rewrite
  -- `(orthSum augmentedStoich)ᗮ` back to `augmentedStoich` via `orthSum_orthSum`.
  have hle := N.augmentedConservation_le_global γ
  have hdec := sup_inf_orthSum_of_le hle
  rw [augmentedConservationSubspace, orthSum_orthSum] at hdec
  rw [lostConservationSubspace, augmentedConservationSubspace]
  exact hdec.symm

/-- Corresponding dimension identity for global conserved quantities. -/
theorem globalConservationDim_eq_augmented_add_lost (N : Network S)
    (γ : StructuralSubnetwork N) :
    Module.finrank ℝ (orthSum N.stoichSubspace) =
      Module.finrank ℝ (N.augmentedConservationSubspace γ) +
        N.lostConservationDim γ := by
  have hdim := finrank_add_finrank_inf_orthSum_of_le (N.augmentedConservation_le_global γ)
  rw [augmentedConservationSubspace, orthSum_orthSum] at hdim
  rw [lostConservationDim, lostConservationSubspace, augmentedConservationSubspace]
  exact hdim.symm

/-- Vanishing emergent-conservation dimension means every isolated internal conservation
law is inherited from the augmented full system. -/
theorem emergentConservationDim_eq_zero_iff (N : Network S)
    (γ : StructuralSubnetwork N) :
    N.emergentConservationDim γ = 0 ↔
      N.localConservationSubspace γ = N.inheritedLocalConservationSubspace γ := by
  rw [emergentConservationDim, Submodule.finrank_eq_zero]
  constructor
  · intro hbot
    have hdec := N.localConservation_eq_inherited_sup_emergent γ
    rw [hbot, sup_bot_eq] at hdec
    exact hdec
  · intro heq
    rw [emergentConservationSubspace, heq, inf_orthSum_eq_bot]

end Network
end CRNT
