import CRNT.Multistationarity.StrongConcordance
import CRNT.Multistationarity.ReducedJacobian
import Mathlib.LinearAlgebra.Eigenspace.Basic

/-!
# Differential consequences of strong concordance

The injectivity theorem for strong concordance has a differential counterpart.
For differentiably two-way monotonic kinetics, strong concordance forces the
species-formation derivative restricted to the stoichiometric subspace to be
nonsingular.  Strong concordance of the fully open extension further excludes
positive real reduced eigenvalues; under weak normality this gives strict
negativity of every real reduced eigenvalue.

These statements formalize the classical Shinar--Feinberg Theorem 9.10 and its
corollary.  The hard spectral separation arguments are intentionally localized.
-/

namespace CRNT
namespace Network

open scoped BigOperators

variable {S : Type} [DecidableEq S] [Fintype S] {N : Network S}

namespace Kinetics

/-- Differential two-way monotonicity at a positive composition, represented by
one gradient for every reaction.  The gradient has the sign of
`source-target`: positive reactant influence, negative product influence, and
zero elsewhere. -/
structure DifferentiablyTwoWayMonotonicAt (K : Kinetics N)
    (x : Concentration S) where
  gradient : N.R → S → ℝ
  directionalDerivative : ∀ (r : N.R) (h : S → ℝ),
    HasDerivAt (fun t : ℝ => K.rate r (x + t • h))
      (∑ s : S, gradient r s * h s) 0
  sign_gradient : ∀ (r : N.R) (s : S),
    SignType.sign (gradient r s) = SignType.sign (N.reactionDirectionSign r s)

/-- Linearized species-formation map generated by the reaction-rate gradients. -/
noncomputable def twoWayLinearization (K : Kinetics N) (x : Concentration S)
    (h : K.DifferentiablyTwoWayMonotonicAt x) : (S → ℝ) →ₗ[ℝ] (S → ℝ) where
  toFun := fun σ => ∑ r : N.R, (∑ s : S, h.gradient r s * σ s) • N.reactionVector r
  -- `intro` with no names introduces only ONE binder; `map_add'`/`map_smul'` take two.
  map_add' := by
    intro x y
    ext s
    simp only [Pi.add_apply, mul_add, Finset.sum_add_distrib, Finset.sum_apply,
      Pi.smul_apply, smul_eq_mul]
    rw [← Finset.sum_add_distrib]
    apply Finset.sum_congr rfl
    intro r _
    ring
  map_smul' := by
    intro m x
    ext s
    simp only [Pi.smul_apply, smul_eq_mul, Finset.sum_apply, RingHom.id_apply]
    rw [Finset.mul_sum]
    apply Finset.sum_congr rfl
    intro r _
    have hsum : (∑ i : S, h.gradient r i * (m * x i)) =
        m * ∑ i : S, h.gradient r i * x i := by
      rw [Finset.mul_sum]
      apply Finset.sum_congr rfl
      intro i _
      ring
    rw [hsum]
    ring

/-- The differential map preserves the stoichiometric subspace. -/
theorem twoWayLinearization_mem_stoich
    (K : Kinetics N) (x : Concentration S)
    (h : K.DifferentiablyTwoWayMonotonicAt x) (σ : S → ℝ) :
    K.twoWayLinearization x h σ ∈ N.stoichSubspace := by
  unfold twoWayLinearization
  exact Submodule.sum_mem _ fun r _ =>
    Submodule.smul_mem _ _ (N.reactionVector_mem_stoichSubspace r)

/-- Restriction of the differential to the stoichiometric tangent space. -/
noncomputable def twoWayReducedDerivative
    (K : Kinetics N) (x : Concentration S)
    (h : K.DifferentiablyTwoWayMonotonicAt x) :
    N.stoichSubspace →ₗ[ℝ] N.stoichSubspace :=
  (K.twoWayLinearization x h).domRestrict N.stoichSubspace |>.codRestrict
    N.stoichSubspace (fun σ => K.twoWayLinearization_mem_stoich x h σ)

end Kinetics

private theorem Kinetics.promotes_of_gradient_mul_pos
    {K : Kinetics N} {x : Concentration S}
    (hK : K.DifferentiablyTwoWayMonotonicAt x)
    (r : N.R) (σ : S → ℝ) (s : S)
    (hpos : 0 < hK.gradient r s * σ s) :
    N.Promotes r σ s := by
  rcases (mul_pos_iff.mp hpos) with h | h
  · rcases h with ⟨hg, hs⟩
    refine ⟨?_, ?_⟩
    · calc
        SignType.sign (σ s) = 1 := sign_pos hs
        _ = SignType.sign (hK.gradient r s) := (sign_pos hg).symm
        _ = SignType.sign (N.reactionDirectionSign r s) := hK.sign_gradient r s
    · intro hz
      have hh := hK.sign_gradient r s
      rw [hz, sign_zero, sign_pos hg] at hh
      norm_num at hh
  · rcases h with ⟨hg, hs⟩
    refine ⟨?_, ?_⟩
    · calc
        SignType.sign (σ s) = -1 := sign_neg hs
        _ = SignType.sign (hK.gradient r s) := (sign_neg hg).symm
        _ = SignType.sign (N.reactionDirectionSign r s) := hK.sign_gradient r s
    · intro hz
      have hh := hK.sign_gradient r s
      rw [hz, sign_zero, sign_neg hg] at hh
      norm_num at hh

private theorem Kinetics.opposes_of_gradient_mul_neg
    {K : Kinetics N} {x : Concentration S}
    (hK : K.DifferentiablyTwoWayMonotonicAt x)
    (r : N.R) (σ : S → ℝ) (s : S)
    (hneg : hK.gradient r s * σ s < 0) :
    N.Opposes r σ s := by
  rcases (mul_neg_iff.mp hneg) with h | h
  · rcases h with ⟨hg, hs⟩
    refine ⟨?_, ?_⟩
    · have hdir : SignType.sign (N.reactionDirectionSign r s) = 1 := by
        rw [← hK.sign_gradient r s, sign_pos hg]
      rw [sign_neg hs, hdir]
    · intro hz
      have hh := hK.sign_gradient r s
      rw [hz, sign_zero, sign_pos hg] at hh
      norm_num at hh
  · rcases h with ⟨hg, hs⟩
    refine ⟨?_, ?_⟩
    · have hdir : SignType.sign (N.reactionDirectionSign r s) = -1 := by
        rw [← hK.sign_gradient r s, sign_neg hg]
      rw [sign_pos hs, hdir]
      norm_num
    · intro hz
      have hh := hK.sign_gradient r s
      rw [hz, sign_zero, sign_neg hg] at hh
      norm_num at hh

/-- **Strong concordance differential nonsingularity theorem.** -/
theorem StronglyConcordant.twoWayReducedDerivative_injective
    (hN : N.StronglyConcordant) (hsep : N.ReactantProductSeparated)
    {K : Kinetics N} {x : Concentration S}
    (hK : K.DifferentiablyTwoWayMonotonicAt x) :
    Function.Injective (K.twoWayReducedDerivative x hK) := by
  rw [← LinearMap.ker_eq_bot]
  apply le_antisymm
  · intro v hvker
    rw [Submodule.mem_bot]
    by_contra hv0
    let σ : S → ℝ := v.1
    let α : N.R → ℝ := fun r => ∑ s : S, hK.gradient r s * σ s
    have hambient : K.twoWayLinearization x hK σ = 0 := by
      have hh := congrArg Subtype.val hvker
      change K.twoWayLinearization x hK (v : S → ℝ) = 0 at hh
      simpa [σ] using hh
    have hkerL : N.InKerL α := by
      change ∑ r : N.R, α r • N.reactionVector r = 0
      simpa [Kinetics.twoWayLinearization, α] using hambient
    have hσmem : σ ∈ N.stoichSubspace := v.property
    have hσne : σ ≠ 0 := by
      intro hz
      apply hv0
      apply Subtype.ext
      simpa [σ] using hz
    apply hN
    refine ⟨α, σ, ?_⟩
    refine ⟨hkerL, hσmem, hσne, ?_, ?_, ?_⟩
    · intro r har
      have hex : ∃ s : S, 0 < hK.gradient r s * σ s := by
        by_contra hnone
        push_neg at hnone
        have hsum : α r ≤ 0 := by
          dsimp [α]
          exact Finset.sum_nonpos fun s _ => hnone s
        linarith
      rcases hex with ⟨s, hs⟩
      exact ⟨s, Kinetics.promotes_of_gradient_mul_pos hK r σ s hs⟩
    · intro r har
      have hex : ∃ s : S, hK.gradient r s * σ s < 0 := by
        by_contra hnone
        push_neg at hnone
        have hsum : 0 ≤ α r := by
          dsimp [α]
          exact Finset.sum_nonneg fun s _ => hnone s
        linarith
      rcases hex with ⟨s, hs⟩
      exact ⟨s, Kinetics.opposes_of_gradient_mul_neg hK r σ s hs⟩
    · intro r har
      by_cases hall : ∀ s : S, (N.reaction r).source s ≠ 0 → σ s = 0
      · exact Or.inl hall
      · right
        push_neg at hall
        rcases hall with ⟨s0, hs0src, hs0σ⟩
        have hdirpos : 0 < N.reactionDirectionSign r s0 := by
          rw [reactionDirectionSign, hsep r s0 hs0src]
          simp
          exact_mod_cast Nat.pos_of_ne_zero hs0src
        have hg0ne : hK.gradient r s0 ≠ 0 := by
          intro hg0
          have hh := hK.sign_gradient r s0
          rw [hg0, sign_zero, sign_pos hdirpos] at hh
          norm_num at hh
        have hterm0 : hK.gradient r s0 * σ s0 ≠ 0 := mul_ne_zero hg0ne hs0σ
        have hsumzero : ∑ s : S, hK.gradient r s * σ s = 0 := by
          simpa [α] using har
        have hpos : ∃ s : S, 0 < hK.gradient r s * σ s := by
          have hexne : ∃ s ∈ (Finset.univ : Finset S), hK.gradient r s * σ s ≠ 0 :=
            ⟨s0, Finset.mem_univ _, hterm0⟩
          rcases Finset.exists_pos_of_sum_zero_of_exists_nonzero
              (fun s : S => hK.gradient r s * σ s) hsumzero hexne with ⟨s, _, hs⟩
          exact ⟨s, hs⟩
        have hneg : ∃ s : S, hK.gradient r s * σ s < 0 := by
          rcases hpos with ⟨sp, hsp⟩
          by_contra hnone
          push_neg at hnone
          have hnn : ∀ s ∈ (Finset.univ : Finset S),
              0 ≤ hK.gradient r s * σ s := fun s _ => hnone s
          have hsumpos : 0 < ∑ s : S, hK.gradient r s * σ s :=
            (Finset.sum_pos_iff_of_nonneg hnn).2 ⟨sp, Finset.mem_univ _, hsp⟩
          rw [hsumzero] at hsumpos
          linarith
        rcases hpos with ⟨sp, hp⟩
        rcases hneg with ⟨sn, hn⟩
        exact ⟨sp, sn,
          Kinetics.promotes_of_gradient_mul_pos hK r σ sp hp,
          Kinetics.opposes_of_gradient_mul_neg hK r σ sn hn⟩
  · exact bot_le

/-- Hence zero is not a reduced eigenvalue at such a composition. -/
theorem StronglyConcordant.zero_not_reducedEigenvalue
    (hN : N.StronglyConcordant) (hsep : N.ReactantProductSeparated)
    {K : Kinetics N} {x : Concentration S}
    (hK : K.DifferentiablyTwoWayMonotonicAt x) :
    LinearMap.ker (K.twoWayReducedDerivative x hK) = ⊥ := by
  exact LinearMap.ker_eq_bot.mpr (hN.twoWayReducedDerivative_injective hsep hK)

/-- Fully-open strong concordance excludes positive real reduced eigenvalues.
This is the spectral half of Shinar--Feinberg Theorem 9.10. -/
def NoPositiveRealReducedEigenvalue
    (K : Kinetics N) (x : Concentration S)
    (hK : K.DifferentiablyTwoWayMonotonicAt x) : Prop :=
  ∀ (lam : ℝ), 0 < lam →
    ¬ ∃ v : N.stoichSubspace, v ≠ 0 ∧
      K.twoWayReducedDerivative x hK v = lam • v

/-- **Fully-open strong-concordance spectral theorem.** -/
theorem noPositiveRealReducedEigenvalue_of_fullyOpen_stronglyConcordant
    (hopen : N.fullyOpen.StronglyConcordant)
    (hsep : N.ReactantProductSeparated)
    {K : Kinetics N} {x : Concentration S}
    (hK : K.DifferentiablyTwoWayMonotonicAt x) :
    N.NoPositiveRealReducedEigenvalue K x hK := by
  intro lam hlam
  rintro ⟨v, hv, heig⟩
  let σ : S → ℝ := v.1
  let β : N.R → ℝ := fun r => ∑ s : S, hK.gradient r s * σ s
  let α : N.fullyOpen.R → ℝ := fun q =>
    match q with
    | Sum.inl r => β r
    | Sum.inr (Sum.inl _) => 0
    | Sum.inr (Sum.inr s) => lam * σ s
  have heigA : K.twoWayLinearization x hK σ = lam • σ := by
    have hh := congrArg Subtype.val heig
    change K.twoWayLinearization x hK (v : S → ℝ) = lam • (v : S → ℝ) at hh
    simpa [σ] using hh
  have hker : N.fullyOpen.InKerL α := by
    apply N.fullyOpen.inKerL_of_apply
    intro s
    have hsplit := Fintype.sum_sum_type (α₁ := N.R) (α₂ := S ⊕ S)
      (fun q : N.fullyOpen.R => α q * N.fullyOpen.reactionVector q s)
    have hsplit2 := Fintype.sum_sum_type (α₁ := S) (α₂ := S)
      (fun q : S ⊕ S => α (Sum.inr q) * N.fullyOpen.reactionVector (Sum.inr q) s)
    rw [hsplit2] at hsplit
    calc
      (∑ q : N.fullyOpen.R, α q * N.fullyOpen.reactionVector q s) =
          (∑ r : N.R, α (Sum.inl r) * N.fullyOpen.reactionVector (Sum.inl r) s) +
          ((∑ t : S, α (Sum.inr (Sum.inl t)) * N.fullyOpen.reactionVector (Sum.inr (Sum.inl t)) s) +
           (∑ t : S, α (Sum.inr (Sum.inr t)) * N.fullyOpen.reactionVector (Sum.inr (Sum.inr t)) s)) := hsplit
      _ = 0 := by
        have horig : (∑ r : N.R, α (Sum.inl r) *
            N.fullyOpen.reactionVector (Sum.inl r) s) = lam * σ s := by
          have hv := congrFun heigA s
          simp only [Kinetics.twoWayLinearization, LinearMap.coe_mk, AddHom.coe_mk,
            Finset.sum_apply, Pi.smul_apply, smul_eq_mul, Pi.smul_apply] at hv
          simpa [α, β, reactionVector_apply] using hv
        rw [horig]
        have hin : (∑ t : S, α (Sum.inr (Sum.inl t)) *
            N.fullyOpen.reactionVector (Sum.inr (Sum.inl t)) s) = 0 := by
          simp [α]
        rw [hin, zero_add]
        have hout : (∑ t : S, α (Sum.inr (Sum.inr t)) *
            N.fullyOpen.reactionVector (Sum.inr (Sum.inr t)) s) = -(lam * σ s) := by
          rw [Finset.sum_eq_single s]
          · rw [N.reactionVector_outflow s]
            simp [α]
          · intro t _ hts
            rw [N.reactionVector_outflow t]
            simp [α, Pi.single_eq_of_ne (Ne.symm hts)]
          · simp
        rw [hout]
        ring
  have hσmem : σ ∈ N.fullyOpen.stoichSubspace := by
    rw [N.stoichSubspace_fullyOpen_eq_top]
    exact Submodule.mem_top
  have hσne : σ ≠ 0 := by
    intro hz
    apply hv
    apply Subtype.ext
    exact hz
  apply hopen
  refine ⟨α, σ, ?_⟩
  refine ⟨hker, hσmem, hσne, ?_, ?_, ?_⟩
  · intro q hαpos
    rcases q with r | q
    · -- original reaction
      have hβpos : 0 < β r := hαpos
      have hex : ∃ s : S, 0 < hK.gradient r s * σ s := by
        by_contra hnone
        push_neg at hnone
        have : β r ≤ 0 := by
          dsimp [β]
          exact Finset.sum_nonpos fun s _ => hnone s
        linarith
      rcases hex with ⟨s, hs⟩
      have hp := Kinetics.promotes_of_gradient_mul_pos hK r σ s hs
      exact ⟨s, by simpa [Promotes, reactionDirectionSign] using hp⟩
    · rcases q with s | s
      · simp [α] at hαpos
      · have hspos : 0 < σ s := by
          dsimp [α] at hαpos
          rcases mul_pos_iff.mp hαpos with h | h
          · exact h.2
          · linarith
        refine ⟨s, ?_⟩
        refine ⟨?_, ?_⟩
        · simp [reactionDirectionSign, fullyOpen_reaction_outflow, outflowReaction,
            singletonComplex_apply, hspos]
        · simp [reactionDirectionSign, fullyOpen_reaction_outflow, outflowReaction,
            singletonComplex_apply]
  · intro q hαneg
    rcases q with r | q
    · have hβneg : β r < 0 := hαneg
      have hex : ∃ s : S, hK.gradient r s * σ s < 0 := by
        by_contra hnone
        push_neg at hnone
        have : 0 ≤ β r := by
          dsimp [β]
          exact Finset.sum_nonneg fun s _ => hnone s
        linarith
      rcases hex with ⟨s, hs⟩
      have hp := Kinetics.opposes_of_gradient_mul_neg hK r σ s hs
      exact ⟨s, by simpa [Opposes, reactionDirectionSign] using hp⟩
    · rcases q with s | s
      · simp [α] at hαneg
      · have hsneg : σ s < 0 := by
          dsimp [α] at hαneg
          rcases mul_neg_iff.mp hαneg with h | h
          · exact h.2
          · linarith
        refine ⟨s, ?_⟩
        refine ⟨?_, ?_⟩
        · simp [reactionDirectionSign, fullyOpen_reaction_outflow, outflowReaction,
            singletonComplex_apply, hsneg]
        · simp [reactionDirectionSign, fullyOpen_reaction_outflow, outflowReaction,
            singletonComplex_apply]
  · intro q hαzero
    rcases q with r | q
    · by_cases hall : ∀ s : S, (N.reaction r).source s ≠ 0 → σ s = 0
      · left
        simpa using hall
      · right
        push_neg at hall
        rcases hall with ⟨s0, hs0src, hs0σ⟩
        have hdirpos : 0 < N.reactionDirectionSign r s0 := by
          rw [reactionDirectionSign, hsep r s0 hs0src]
          simp
          exact_mod_cast Nat.pos_of_ne_zero hs0src
        have hg0ne : hK.gradient r s0 ≠ 0 := by
          intro hg0
          have hh := hK.sign_gradient r s0
          rw [hg0, sign_zero, sign_pos hdirpos] at hh
          norm_num at hh
        have hterm0 : hK.gradient r s0 * σ s0 ≠ 0 := mul_ne_zero hg0ne hs0σ
        have hsumzero : ∑ s : S, hK.gradient r s * σ s = 0 := by
          simpa [α, β] using hαzero
        have hpos : ∃ s : S, 0 < hK.gradient r s * σ s := by
          have hexne : ∃ s ∈ (Finset.univ : Finset S), hK.gradient r s * σ s ≠ 0 :=
            ⟨s0, Finset.mem_univ _, hterm0⟩
          rcases Finset.exists_pos_of_sum_zero_of_exists_nonzero
              (fun s : S => hK.gradient r s * σ s) hsumzero hexne with ⟨s, _, hs⟩
          exact ⟨s, hs⟩
        have hneg : ∃ s : S, hK.gradient r s * σ s < 0 := by
          rcases hpos with ⟨sp, hsp⟩
          by_contra hnone
          push_neg at hnone
          have hnn : ∀ s ∈ (Finset.univ : Finset S),
              0 ≤ hK.gradient r s * σ s := fun s _ => hnone s
          have hsumpos : 0 < ∑ s : S, hK.gradient r s * σ s :=
            (Finset.sum_pos_iff_of_nonneg hnn).2 ⟨sp, Finset.mem_univ _, hsp⟩
          rw [hsumzero] at hsumpos
          linarith
        rcases hpos with ⟨sp, hp⟩
        rcases hneg with ⟨sn, hn⟩
        refine ⟨sp, sn, ?_, ?_⟩
        · have hh := Kinetics.promotes_of_gradient_mul_pos hK r σ sp hp
          simpa [Promotes, reactionDirectionSign] using hh
        · have hh := Kinetics.opposes_of_gradient_mul_neg hK r σ sn hn
          simpa [Opposes, reactionDirectionSign] using hh
    · rcases q with s | s
      · left
        intro t hsrc
        simp [fullyOpen_reaction_inflow, inflowReaction] at hsrc
      · left
        intro t hsrc
        have hs0 : σ s = 0 := by
          have : lam * σ s = 0 := by simpa [α] using hαzero
          exact (mul_eq_zero.mp this).resolve_left hlam.ne'
        have hts : t = s := by
          simp [fullyOpen_reaction_outflow, outflowReaction, singletonComplex_apply] at hsrc
          exact hsrc
        simpa [hts] using hs0

/-- Under weak normality, descent of strong concordance plus the fully-open
spectral theorem leaves every real reduced eigenvalue strictly negative. -/
theorem realReducedEigenvalue_negative_of_weaklyNormal_of_fullyOpen_stronglyConcordant
    (hwn : N.WeaklyNormal) (hopen : N.fullyOpen.StronglyConcordant)
    (hsep : N.ReactantProductSeparated)
    {K : Kinetics N} {x : Concentration S}
    (hK : K.DifferentiablyTwoWayMonotonicAt x)
    {lam : ℝ} {v : N.stoichSubspace}
    (hv : v ≠ 0) (heig : K.twoWayReducedDerivative x hK v = lam • v) :
    lam < 0 := by
  have hsc : N.StronglyConcordant :=
    N.stronglyConcordant_of_fullyOpen_of_weaklyNormal hsep hwn hopen
  have hne0 : lam ≠ 0 := by
    intro h0
    subst h0
    apply hv
    exact hsc.twoWayReducedDerivative_injective hsep hK (by simpa using heig)
  have hnotpos := N.noPositiveRealReducedEigenvalue_of_fullyOpen_stronglyConcordant
    hopen hsep hK lam
  rcases lt_trichotomy lam 0 with hneg | hzero | hpos
  · exact hneg
  · exact False.elim (hne0 hzero)
  · exact False.elim (hnotpos hpos ⟨v, hv, heig⟩)

end Network
end CRNT
