import CRNT.Algebra.PositiveTorusIdeals

/-!
# Positive-torus saturation as an actual ideal

`PositiveTorusIdeals` already defines the correct membership predicate

  exists n, (product_s X_s)^n * p in I

and proves that adjoining all such polynomials does not change the strictly positive zero set.
This scaffold packages those elements into an honest ideal generated by the saturation predicate.
The next algebraic step is to prove that the predicate itself is ideal-closed, so this generated
ideal is exactly the usual saturation `I : (prod X_s)^infinity`, not merely the ideal it generates.
-/

namespace CRNT
namespace Network

open MvPolynomial

variable {S : Type} [DecidableEq S] [Fintype S]

/-- Ideal generated by all polynomials satisfying the positive-torus saturation predicate. -/
noncomputable def positiveTorusSaturationIdeal
    (I : Ideal (MvPolynomial S ℝ)) : Ideal (MvPolynomial S ℝ) :=
  Ideal.span {p | MemPositiveTorusSaturation I p}

/-- The original ideal is contained in its generated positive-torus saturation. -/
theorem le_positiveTorusSaturationIdeal (I : Ideal (MvPolynomial S ℝ)) :
    I ≤ positiveTorusSaturationIdeal I := by
  intro p hp
  apply Ideal.subset_span
  exact ⟨0, by simpa using hp⟩

/-- The saturation predicate contains zero. -/
theorem memPositiveTorusSaturation_zero (I : Ideal (MvPolynomial S ℝ)) :
    MemPositiveTorusSaturation I 0 := by
  refine ⟨0, ?_⟩
  simp

/-- The saturation predicate is closed under addition.  Different saturation exponents can be
raised to a common exponent by multiplying inside the ideal. -/
theorem memPositiveTorusSaturation_add (I : Ideal (MvPolynomial S ℝ))
    {p q : MvPolynomial S ℝ}
    (hp : MemPositiveTorusSaturation I p) (hq : MemPositiveTorusSaturation I q) :
    MemPositiveTorusSaturation I (p + q) := by
  rcases hp with ⟨m, hm⟩
  rcases hq with ⟨n, hn⟩
  refine ⟨m + n, ?_⟩
  rw [mul_add]
  apply I.add_mem
  · have hpm : speciesCoordinateProduct ^ n *
        (speciesCoordinateProduct ^ m * p) ∈ I :=
      Ideal.mul_mem_left _ _ hm
    simpa [pow_add, mul_assoc, mul_comm, mul_left_comm] using hpm
  · have hqn : speciesCoordinateProduct ^ m *
        (speciesCoordinateProduct ^ n * q) ∈ I :=
      Ideal.mul_mem_left _ _ hn
    simpa [pow_add, mul_assoc] using hqn

/-- The saturation predicate is closed under multiplication by an arbitrary ambient polynomial. -/
theorem memPositiveTorusSaturation_mul_left (I : Ideal (MvPolynomial S ℝ))
    (a : MvPolynomial S ℝ) {p : MvPolynomial S ℝ}
    (hp : MemPositiveTorusSaturation I p) :
    MemPositiveTorusSaturation I (a * p) := by
  rcases hp with ⟨n, hn⟩
  refine ⟨n, ?_⟩
  have hmul : a * (speciesCoordinateProduct ^ n * p) ∈ I :=
    Ideal.mul_mem_left _ _ hn
  simpa [mul_assoc, mul_comm, mul_left_comm] using hmul

/-- The generated ideal has exactly the intended saturation membership predicate; `Ideal.span` is
therefore only packaging, not an enlargement of the mathematical saturation. -/
theorem mem_positiveTorusSaturationIdeal_iff
    (I : Ideal (MvPolynomial S ℝ)) (p : MvPolynomial S ℝ) :
    p ∈ positiveTorusSaturationIdeal I ↔ MemPositiveTorusSaturation I p := by
  constructor
  · intro hp
    refine Submodule.span_induction
      (p := fun q _ => MemPositiveTorusSaturation I q) ?_ ?_ ?_ ?_ hp
    · intro q hq
      exact hq
    · exact memPositiveTorusSaturation_zero I
    · intro p q _ _ hp' hq'
      exact memPositiveTorusSaturation_add I hp' hq'
    · intro a p _ hp'
      simpa [smul_eq_mul] using memPositiveTorusSaturation_mul_left I a hp'
  · intro hp
    exact Ideal.subset_span hp

/-- Saturation is monotone in the input ideal. -/
theorem positiveTorusSaturationIdeal_mono {I J : Ideal (MvPolynomial S ℝ)} (h : I ≤ J) :
    positiveTorusSaturationIdeal I ≤ positiveTorusSaturationIdeal J := by
  intro p hp
  rw [mem_positiveTorusSaturationIdeal_iff] at hp ⊢
  rcases hp with ⟨n, hn⟩
  exact ⟨n, h hn⟩

/-- Saturating twice does nothing: the species-coordinate saturation is idempotent. -/
theorem positiveTorusSaturationIdeal_idem (I : Ideal (MvPolynomial S ℝ)) :
    positiveTorusSaturationIdeal (positiveTorusSaturationIdeal I) =
      positiveTorusSaturationIdeal I := by
  apply le_antisymm
  · intro p hp
    rw [mem_positiveTorusSaturationIdeal_iff] at hp ⊢
    rcases hp with ⟨n, hn⟩
    rw [mem_positiveTorusSaturationIdeal_iff] at hn
    rcases hn with ⟨m, hm⟩
    refine ⟨m + n, ?_⟩
    simpa [pow_add, mul_assoc] using hm
  · exact le_positiveTorusSaturationIdeal (positiveTorusSaturationIdeal I)

/-- Passing to the generated saturation ideal does not change the strictly positive zero set. -/
theorem vanishes_positiveTorusSaturationIdeal_iff
    (I : Ideal (MvPolynomial S ℝ)) {x : S -> ℝ} (hx : ∀ s, 0 < x s) :
    VanishesIdealAt (positiveTorusSaturationIdeal I) x <-> VanishesIdealAt I x := by
  constructor
  · intro h p hp
    exact h p (le_positiveTorusSaturationIdeal I hp)
  · intro h p hp
    refine Submodule.span_induction (p := fun q _ => eval x q = 0) ?_ ?_ ?_ ?_ hp
    · intro q hq
      exact (vanishes_positiveTorusSaturation_iff I hx).2 h q hq
    · simp
    · intro p q _ _ hp0 hq0
      simp [hp0, hq0]
    · intro p q _ hq0
      simp [smul_eq_mul, hq0]

end Network
end CRNT
