import Scaffold.CRNTExpansion.RealizationTheory
import CRNT.Translation.SourceCoefficientEquivalence

/-!
# Finite source-coefficient certificates for CRNT realizations

`SourceCoefficientEquivalence` already proves that equality of the finitely many source-monomial
coefficient vectors implies equality of the complete mass-action vector field.  This file turns that
fact into realization certificates that can be generated by an exact LP/Farkas search layer later.

The certificate itself is mathematical data only: a candidate network, positive rates, and the
source-coefficient equalities.  No optimizer is trusted.
-/

namespace CRNT
namespace Network

variable {S : Type} [DecidableEq S] [Fintype S]

/-- A finite certificate that `M` realizes the same mass-action vector field as `(N, κN)`. -/
structure SourceCoefficientRealizationCertificate
    (N : Network S) (κN : N.RateConstants) where
  network : Network S
  rates : network.RateConstants
  coefficients : N.SourceCoefficientEquivalent network κN rates

namespace SourceCoefficientRealizationCertificate

variable {N : Network S} {κN : N.RateConstants}

/-- A source-coefficient certificate is an ordinary mass-action realization. -/
def toMassActionRealization
    (C : SourceCoefficientRealizationCertificate N κN) : MassActionRealization N κN where
  network := C.network
  rates := C.rates
  equivalent := massActionDynamicallyEquivalent_of_sourceCoefficientEquivalent C.coefficients

/-- Every certified source-coefficient realization has exactly the original steady-state set. -/
theorem steadyState_iff (C : SourceCoefficientRealizationCertificate N κN)
    (x : Concentration S) :
    N.IsMassActionSteadyState κN x ↔ C.network.IsMassActionSteadyState C.rates x :=
  C.toMassActionRealization.steadyState_iff x

/-- A structural property of the certified target immediately gives the corresponding generic
realization predicate. -/
theorem hasDynamicallyEquivalentRealizationWith
    (C : SourceCoefficientRealizationCertificate N κN)
    {P : Network S → Prop} (hP : P C.network) :
    N.HasDynamicallyEquivalentRealizationWith κN P := by
  exact ⟨C.toMassActionRealization, hP⟩

/-- In particular, a weakly-reversible certified target proves existence of a weakly-reversible
realization. -/
theorem hasWeaklyReversibleRealization
    (C : SourceCoefficientRealizationCertificate N κN)
    (hwr : C.network.WeaklyReversible) : N.HasWeaklyReversibleRealization κN :=
  C.hasDynamicallyEquivalentRealizationWith hwr

end SourceCoefficientRealizationCertificate

/-- Source-coefficient realization certificate augmented by equality of stoichiometric subspaces.
This is the finite certificate form needed to transfer compatibility-class conclusions. -/
structure StoichiometricSourceCoefficientRealizationCertificate
    (N : Network S) (κN : N.RateConstants)
    extends SourceCoefficientRealizationCertificate N κN where
  stoich_eq : N.stoichSubspace = network.stoichSubspace

namespace StoichiometricSourceCoefficientRealizationCertificate

variable {N : Network S} {κN : N.RateConstants}

/-- Forget to the realization-theory package carrying dynamical equivalence and the shared
stoichiometric subspace. -/
def toStoichiometricMassActionRealization
    (C : StoichiometricSourceCoefficientRealizationCertificate N κN) :
    StoichiometricMassActionRealization N κN where
  network := C.network
  rates := C.rates
  equivalent := massActionDynamicallyEquivalent_of_sourceCoefficientEquivalent C.coefficients
  stoich_eq := C.stoich_eq

/-- A finite source-coefficient certificate for a weakly-reversible deficiency-zero target is a
complete classwise uniqueness certificate for the original mass-action system. -/
theorem existsUnique_steadyState_in_positiveClass_of_wr0Certificate
    (C : StoichiometricSourceCoefficientRealizationCertificate N κN)
    (hwr : C.network.WeaklyReversible) (hδ : C.network.DeficiencyZero)
    {x0 : Concentration S} (hx0 : x0.Positive) :
    ∃! x : Concentration S,
      x ∈ N.positiveCompatibilityClass x0 ∧ N.IsMassActionSteadyState κN x := by
  exact C.toStoichiometricMassActionRealization
    |>.existsUnique_steadyState_in_positiveClass_of_wr0 hwr hδ hx0

/-- The same WR0 certificate also produces the abstract WR0 realization predicate. -/
theorem hasStoichiometricWR0Realization
    (C : StoichiometricSourceCoefficientRealizationCertificate N κN)
    (hwr : C.network.WeaklyReversible) (hδ : C.network.DeficiencyZero) :
    N.HasStoichiometricWR0Realization κN := by
  exact ⟨C.toStoichiometricMassActionRealization, hwr, hδ⟩

end StoichiometricSourceCoefficientRealizationCertificate

end Network
end CRNT
