import CRNT.Geometry.FanSeparationWitness

/-!
# A proper exposed face forces a strictly-inward reaction

`CRNT.Geometry.FanSeparationWitness` reduces the strict-support verdict for the genuine toric
mass-action field to one geometric datum per wall: a strictly-inward reaction
`0 < ⟪toEuclid n₀, toEuclid (reactionVector r)⟫`, supplied by hand as the wall's non-triviality.
This module extracts that reaction from the convex geometry, so the non-triviality of a wall is read
off the structure of its exposed face rather than asserted.

## Properness of the face is a strictly-inward reaction

The ambient cone `C` of a wall is generated by the reaction directions: every point of `C` is a
conical combination of the `toEuclid (reactionVector r)`. The wall normal `toEuclid n₀` is a
supporting functional of `C`, so each reaction direction sits non-strictly inward,
`0 ≤ ⟪toEuclid n₀, toEuclid (reactionVector r)⟫`. The exposed face `exposedFace C (toEuclid n₀)` is
the locus of `C` where this functional is tight.

If *every* reaction direction were exactly tight — `⟪toEuclid n₀, toEuclid (reactionVector r)⟫ = 0`
for all `r` — then the supporting hyperplane contains every generator, hence the whole generated cone
`C`, so the exposed face is all of `C`: the face is *not* proper. Contrapositively, a proper exposed
face (`exposedFace C (toEuclid n₀) ⊊ C` as sets) forces some reaction direction strictly off the
hyperplane: a strictly-inward reaction. Together with cone-nonnegativity this is exactly the
non-triviality datum `FanSeparationWitness` consumes.

* `Network.GeneratedByReactions` — the structural clause the fan supplies: the cone `C` is contained
  in the conical hull of the reaction directions in Euclidean species space.
* `Network.exists_reaction_strictlyInward_of_properFace` — properness ⇒ strict reaction: a proper
  exposed face of a reaction-generated cone, under cone-nonnegativity, carries a strictly-inward
  reaction.
* `IsFanWall.exists_reaction_strictlyInward_of_properWall` — the same packaged on a fan wall whose
  cone `D` is a *proper* subcone of `C` (`D ⊊ C`): the wall's exposed-face properness is its
  strictly-inward reaction.
* `IsPolyhedralFan.toricMassActionField_isStrictSupportField_of_properFan` — the deliverable. Its
  per-wall input is fan-wall data, face-properness (`D ⊊ C`) of a reaction-generated cone,
  cone-nonnegativity, and boundary positivity; the strictly-inward reaction is *extracted* rather
  than supplied. It feeds `toricMassActionField_isStrictSupportField_of_fan`, so the toric
  strict-support verdict rests on fan structure, weak reversibility, and face-properness alone.

## Scope

The generation clause `GeneratedByReactions` is carried as the structural hypothesis the fan supplies
about how its cones arise from the reaction directions. Deriving that clause from the abstract
`IsPolyhedralFan.covers`/`inter_common` axioms for an arbitrary fan — identifying which cones of a
given fan are the reaction-generated ambient cones of walls — is the remaining convex-geometry input,
separate from the properness ⇒ strict-reaction extraction performed here.

This module is **stable** and `sorry`-free. Depends on: `CRNT.Geometry.FanSeparationWitness`.
-/

namespace CRNT

open scoped InnerProductSpace

namespace Network

variable {S : Type} [DecidableEq S] [Fintype S]

/-- **A reaction-generated cone.** The cone `C` is contained in the conical hull of the reaction
directions in Euclidean species space: every point of `C` is a nonnegative-coefficient combination of
the `toEuclid (reactionVector r)`. This is the structural way each ambient wall cone arises from the
reaction directions of the network. -/
def GeneratedByReactions (N : Network S) (C : ProperCone ℝ (EuclideanSpace ℝ S)) : Prop :=
  (C : PointedCone ℝ (EuclideanSpace ℝ S)) ≤
    PointedCone.hull ℝ (Set.range (fun r : N.R => toEuclid (N.reactionVector r)))

/-- A reaction-generated cone lies inside the supporting hyperplane of `toEuclid n₀` whenever every
reaction direction is tight against it: the hyperplane is a cone containing all generators, hence the
whole conical hull, hence `C`. -/
theorem GeneratedByReactions.le_supportingHyperplane {N : Network S}
    {C : ProperCone ℝ (EuclideanSpace ℝ S)} (hgen : N.GeneratedByReactions C) {n₀ : S → ℝ}
    (htight : ∀ r : N.R, ⟪toEuclid n₀, toEuclid (N.reactionVector r)⟫_ℝ = 0) :
    (C : PointedCone ℝ (EuclideanSpace ℝ S)) ≤ supportingHyperplane (toEuclid n₀) := by
  refine hgen.trans ?_
  rw [PointedCone.hull, Submodule.span_le]
  rintro _ ⟨r, rfl⟩
  rw [SetLike.mem_coe, mem_supportingHyperplane]
  exact htight r

/-- **Properness forces a strictly-inward reaction.** For a reaction-generated cone `C` whose every
reaction direction is non-strictly inward across the wall normal `toEuclid n₀`, if the exposed face
`exposedFace C (toEuclid n₀)` is a *proper* subset of `C`, then some reaction is *strictly* inward:
`0 < ⟪toEuclid n₀, toEuclid (reactionVector r)⟫`. Were every reaction tight, the supporting
hyperplane would contain all of `C`, making the exposed face the whole cone — contradicting
properness. The strictly-inward reaction is the wall's geometric non-triviality, extracted from the
face rather than supplied. -/
theorem exists_reaction_strictlyInward_of_properFace {N : Network S}
    {C : ProperCone ℝ (EuclideanSpace ℝ S)} (hgen : N.GeneratedByReactions C) {n₀ : S → ℝ}
    (hinward : ∀ r : N.R, 0 ≤ ⟪toEuclid n₀, toEuclid (N.reactionVector r)⟫_ℝ)
    (hproper : (exposedFace (C : PointedCone ℝ (EuclideanSpace ℝ S)) (toEuclid n₀) :
        Set (EuclideanSpace ℝ S)) ⊂ (C : Set (EuclideanSpace ℝ S))) :
    ∃ r : N.R, 0 < ⟪toEuclid n₀, toEuclid (N.reactionVector r)⟫_ℝ := by
  by_contra hcon
  push Not at hcon
  have htight : ∀ r : N.R, ⟪toEuclid n₀, toEuclid (N.reactionVector r)⟫_ℝ = 0 := fun r =>
    le_antisymm (hcon r) (hinward r)
  have hle : (C : PointedCone ℝ (EuclideanSpace ℝ S)) ≤ supportingHyperplane (toEuclid n₀) :=
    hgen.le_supportingHyperplane htight
  refine absurd (le_antisymm (exposedFace_subset _ _) ?_) (ne_of_lt hproper)
  intro x hx
  exact mem_exposedFace.mpr ⟨hx, (mem_supportingHyperplane).1 (hle hx)⟩

/-- **A proper fan wall carries a strictly-inward reaction.** A fan wall whose cone `D` is a proper
subcone of its reaction-generated ambient cone `C` (`D ⊊ C`) has, under cone-nonnegativity, a
strictly-inward reaction. The exposed-face properness of the wall — `D` is the exposed face and is
strictly smaller than `C` — is exactly the geometric non-triviality, read off as a strictly-inward
reaction. -/
theorem IsFanWall.exists_reaction_strictlyInward_of_properWall {N : Network S}
    {F : Fan (EuclideanSpace ℝ S)} {D C : ProperCone ℝ (EuclideanSpace ℝ S)} {n₀ : S → ℝ}
    (hwall : N.IsFanWall F D C n₀) (hgen : N.GeneratedByReactions C)
    (hinward : ∀ r : N.R, 0 ≤ ⟪toEuclid n₀, toEuclid (N.reactionVector r)⟫_ℝ)
    (hproper : (D : Set (EuclideanSpace ℝ S)) ⊂ (C : Set (EuclideanSpace ℝ S))) :
    ∃ r : N.R, 0 < ⟪toEuclid n₀, toEuclid (N.reactionVector r)⟫_ℝ :=
  N.exists_reaction_strictlyInward_of_properFace hgen hinward (hwall.is_face ▸ hproper)

end Network

/-- **The genuine toric field is a strict support field — from fan structure, weak reversibility, and
face-properness.** For a polyhedral fan and a weakly-reversible network, if every face of the angular
face list is an exposed-face wall whose cone `D` is a *proper* subcone (`D ⊊ C`) of its
reaction-generated ambient cone, is non-strictly inward across every reaction, and has
strictly-positive boundary concentrations, then the genuine toric mass-action field is a strict
support field for the faces. The strictly-inward reaction of
`toricMassActionField_isStrictSupportField_of_fan` is *extracted* from the face-properness
(`exists_reaction_strictlyInward_of_properWall`) rather than supplied by hand: the strict-support
verdict rests on fan structure, weak reversibility, and face-properness alone. -/
theorem IsPolyhedralFan.toricMassActionField_isStrictSupportField_of_properFan {S : Type}
    [DecidableEq S] [Fintype S] {N : Network S} (hwr : N.WeaklyReversible)
    {F : Fan (EuclideanSpace ℝ S)} (hF : IsPolyhedralFan F) (κ : N.RateConstants)
    {faces : List (EuclideanSpace ℝ S × ℝ)}
    (hfaces : ∀ nf ∈ faces, ∃ (n₀ : S → ℝ) (D C : ProperCone ℝ (EuclideanSpace ℝ S)),
      nf.1 = toEuclid n₀ ∧
      N.IsFanWall F D C n₀ ∧ N.GeneratedByReactions C ∧
      (D : Set (EuclideanSpace ℝ S)) ⊂ (C : Set (EuclideanSpace ℝ S)) ∧
      (∀ r : N.R, 0 ≤ ⟪toEuclid n₀, toEuclid (N.reactionVector r)⟫_ℝ) ∧
      (∀ p : EuclideanSpace ℝ S,
        ZeroSeparatingCurve2D.OnFaceBoundary faces (toEuclid n₀) nf.2 p →
          Concentration.Positive (toEuclid.symm p))) :
    ZeroSeparatingCurve2D.IsStrictSupportField (N.toricMassActionField κ) faces := by
  refine hF.toricMassActionField_isStrictSupportField_of_fan hwr κ ?_
  intro nf hnf
  obtain ⟨n₀, D, C, hn₀, hwall, hgen, hproper, hinward, hpos⟩ := hfaces nf hnf
  obtain ⟨r, hin⟩ := hwall.exists_reaction_strictlyInward_of_properWall hgen hinward hproper
  exact ⟨n₀, D, C, r, hn₀, hwall, hin, hinward, hpos⟩

end CRNT
