import CRNT.Stoich.Vector
import CRNT.Basic.Complex
import Mathlib.Geometry.Convex.Cone.Pointed
import Mathlib.Analysis.Convex.Cone.Dual
import Mathlib.Analysis.Convex.Hull
import Mathlib.Analysis.Convex.Topology
import Mathlib.Analysis.InnerProductSpace.Dual

/-!
# Polyhedral cones, dual cones, and Newton polytopes

This module provides convex-geometry scaffolding over the species space `S → ℝ`:
the convex cone generated by a finite family of vectors (the reaction vectors), the
dual cone of a set in an inner-product space together with the bipolar identity
`cone_dual_dual`, and the Newton polytope of a finite set of complexes as a convex
hull.

The generated cone is `PointedCone.hull ℝ`, the smallest convex cone containing `0`
and the given set, realized as a nonnegative-scalar submodule span. Its membership
characterization `mem_generatedCone_iff` exhibits each element as a finite conical
(nonnegative-coefficient) combination of generators.

The dual cone is `ProperCone.dual (innerₗ E)` for a real inner-product space `E`.
Because the inner product is its own flip, the Farkas-backed double-dual theorem of
Mathlib specializes to `cone_dual_dual`: the dual of the dual of a proper cone is
the cone itself. `mem_coneDual` records the defining membership condition.

The Newton polytope of a finite set of complexes is the convex hull of their real
exponent vectors. It is convex (`newtonPolytope_convex`), compact
(`newtonPolytope_isCompact`), and nonempty exactly when the underlying set is
nonempty (`newtonPolytope_nonempty`), and contains each generating exponent vector
(`exponentVector_mem_newtonPolytope`).

Depends on: `CRNT.Stoich.Vector`,
`CRNT.Basic.Complex`, Mathlib pointed/proper cones, convex hull and topology, and
inner-product duality.
-/

namespace CRNT

open scoped InnerProductSpace

section GeneratedCone

variable {S : Type} [DecidableEq S] [Fintype S]

/-- The convex cone generated by a finite family of vectors in `S → ℝ`: the smallest
pointed convex cone (containing `0`) that contains every `v i`. Realized as the
nonnegative-scalar span of the range of `v`. -/
def generatedCone {ι : Type*} (v : ι → (S → ℝ)) : PointedCone ℝ (S → ℝ) :=
  PointedCone.hull ℝ (Set.range v)

omit [DecidableEq S] [Fintype S] in
/-- Each generator lies in the cone it generates. -/
theorem mem_generatedCone {ι : Type*} (v : ι → (S → ℝ)) (i : ι) :
    v i ∈ generatedCone v :=
  PointedCone.subset_hull ⟨i, rfl⟩

omit [DecidableEq S] [Fintype S] in
/-- An element of the generated cone is exactly a finite conical (nonnegative-
coefficient) combination of the generating vectors. -/
theorem mem_generatedCone_iff {ι : Type*} (v : ι → (S → ℝ)) (x : S → ℝ) :
    x ∈ generatedCone v ↔
      ∃ c : (S → ℝ) →₀ ℝ, ↑c.support ⊆ Set.range v ∧ (∀ y, 0 ≤ c y) ∧
        c.sum (fun m r => r • m) = x :=
  PointedCone.mem_hull_set

/-- The cone generated by the reaction vectors of a network: the conical hull of the
reaction-vector family. Its conical combinations are the net production rates
achievable with nonnegative reaction extents. -/
def Network.reactionCone (N : Network S) : PointedCone ℝ (S → ℝ) :=
  generatedCone N.reactionVector

/-- Each reaction vector lies in the reaction cone. -/
theorem Network.reactionVector_mem_reactionCone (N : Network S) (r : N.R) :
    N.reactionVector r ∈ N.reactionCone :=
  mem_generatedCone _ r

end GeneratedCone

section Dual

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]

/-- The dual cone of a set `s` in a real inner-product space: the proper cone of
points `y` whose inner product with every `x ∈ s` is nonnegative. -/
noncomputable def coneDual (s : Set E) : ProperCone ℝ E :=
  ProperCone.dual (innerₗ E) s

/-- Membership in the dual cone: `y` lies in `coneDual s` iff it has nonnegative
inner product with every element of `s`. -/
@[simp] theorem mem_coneDual {s : Set E} {y : E} :
    y ∈ coneDual s ↔ ∀ ⦃x⦄, x ∈ s → 0 ≤ ⟪x, y⟫_ℝ := by
  simp only [coneDual, ProperCone.mem_dual, innerₗ_apply_apply]

/-- **Bipolar theorem.** The dual of the dual of a proper cone (with respect to the
inner product) is the cone itself. -/
@[simp] theorem cone_dual_dual (C : ProperCone ℝ E) :
    coneDual (coneDual (C : Set E) : Set E) = C := by
  have h := ProperCone.dual_dual_flip (innerₗ E) C
  simp only [flip_innerₗ] at h
  exact h

/-- **Farkas separation.** A point outside a proper cone is separated from it by a
member of the dual cone: there is a `y` in the dual cone with strictly negative inner
product against the excluded point. -/
theorem exists_mem_coneDual_of_notMem (C : ProperCone ℝ E) {x₀ : E} (hx₀ : x₀ ∉ C) :
    ∃ y ∈ coneDual (C : Set E), ⟪x₀, y⟫_ℝ < 0 := by
  obtain ⟨f, hf, hf₀⟩ := C.hyperplane_separation_point hx₀
  refine ⟨(InnerProductSpace.toDual ℝ E).symm f, ?_, ?_⟩
  · rw [mem_coneDual]
    intro x hx
    rw [real_inner_comm, InnerProductSpace.toDual_symm_apply]
    exact hf x hx
  · rw [real_inner_comm, InnerProductSpace.toDual_symm_apply]
    exact hf₀

end Dual

section NewtonPolytope

variable {S : Type} [DecidableEq S] [Fintype S]

omit [DecidableEq S] [Fintype S]

/-- The real exponent vector of a complex `y : S → ℕ`, viewed as a point of `S → ℝ`. -/
def exponentVector (y : Complex S) : S → ℝ := fun s => (y s : ℝ)

/-- The Newton polytope of a finite set of complexes: the convex hull of their real
exponent vectors in `S → ℝ`. -/
def newtonPolytope (Y : Finset (Complex S)) : Set (S → ℝ) :=
  convexHull ℝ (exponentVector '' (Y : Set (Complex S)))

/-- The Newton polytope is convex. -/
theorem newtonPolytope_convex (Y : Finset (Complex S)) :
    Convex ℝ (newtonPolytope Y) :=
  convex_convexHull ℝ _

/-- Each generating exponent vector lies in the Newton polytope. -/
theorem exponentVector_mem_newtonPolytope (Y : Finset (Complex S)) {y : Complex S}
    (hy : y ∈ Y) : exponentVector y ∈ newtonPolytope Y :=
  subset_convexHull ℝ _ ⟨y, hy, rfl⟩

/-- The Newton polytope is nonempty exactly when the underlying complex set is. -/
theorem newtonPolytope_nonempty (Y : Finset (Complex S)) :
    (newtonPolytope Y).Nonempty ↔ (Y : Set (Complex S)).Nonempty := by
  rw [newtonPolytope, convexHull_nonempty_iff, Set.image_nonempty]

/-- The Newton polytope is compact: it is the convex hull of a finite set. -/
theorem newtonPolytope_isCompact (Y : Finset (Complex S)) :
    IsCompact (newtonPolytope Y) :=
  (Y.finite_toSet.image exponentVector).isCompact_convexHull ℝ

/-- The Newton polytope is closed. -/
theorem newtonPolytope_isClosed (Y : Finset (Complex S)) :
    IsClosed (newtonPolytope Y) :=
  (newtonPolytope_isCompact Y).isClosed

end NewtonPolytope

end CRNT
