import CRNT.Geometry.FanFaceProperness

/-!
# Reaction generation as a fan-level property

`CRNT.Geometry.FanFaceProperness` extracts the strictly-inward reaction of a wall from the
properness of its exposed face, leaving one structural datum per wall: `Network.GeneratedByReactions C`
— the ambient cone of the wall is contained in the conical hull of the reaction directions. There it
is carried as a per-wall hypothesis. This module makes it a property of the *fan*, so the deliverable
no longer hand-carries it on each wall.

## Generation is closure under the hull

`GeneratedByReactions C` is `(C : PointedCone) ≤ PointedCone.hull ℝ (range reactionVector)`, a `≤`
between pointed cones, equivalently the set inclusion `(C : Set) ⊆ hull`. So any proper cone whose
points are conical combinations of the reaction directions is reaction-generated; in particular the
zero cone `⊥` is, and the property is monotone in `C`.

## A reaction-generated fan

A fan is *reaction-generated* when every one of its cones is reaction-generated. For such a fan every
wall's ambient cone `C` — a cone of the fan — is reaction-generated by membership alone, so the
per-wall generation clause of `toricMassActionField_isStrictSupportField_of_properFan` is read off the
fan rather than supplied. The empty fan is reaction-generated vacuously.

* `Network.GeneratedByReactions.of_subset_hull` — the set form: a cone whose points lie in the
  reaction hull is reaction-generated.
* `Network.generatedByReactions_bot` — the zero cone is reaction-generated.
* `Network.ReactionGeneratedFan` — every cone of the fan is reaction-generated.
* `Network.ReactionGeneratedFan.generatedByReactions_of_mem` — a cone of a reaction-generated fan is
  reaction-generated.
* `Network.reactionGeneratedFan_empty` — the empty fan is reaction-generated.
* `IsPolyhedralFan.toricMassActionField_isStrictSupportField_of_reactionFan` — the deliverable with
  generation discharged from the fan: for a polyhedral, reaction-generated fan, the per-wall input is
  fan-wall data, face-properness (`D ⊊ C`), cone-nonnegativity, and boundary positivity; the
  generation clause is supplied by the fan, not by hand. It feeds
  `toricMassActionField_isStrictSupportField_of_properFan`.

## Scope

Reaction generation is carried as the structural property `ReactionGeneratedFan` the fan supplies
about how its cones arise from the reaction directions. Deriving it from the abstract
`IsPolyhedralFan.covers`/`inter_common` clauses for an arbitrary fan — exhibiting the ambient wall
cones of a given fan as subcones of the reaction hull — is the remaining convex-geometry input,
separate from the fan-level packaging performed here.

This module is **stable** and `sorry`-free. Depends on: `CRNT.Geometry.FanFaceProperness`.
-/

namespace CRNT

open scoped InnerProductSpace

namespace Network

variable {S : Type} [DecidableEq S] [Fintype S]

/-- **Generation from set inclusion.** A proper cone whose points all lie in the conical hull of the
reaction directions is reaction-generated. This is `GeneratedByReactions` read as a set inclusion. -/
theorem GeneratedByReactions.of_subset_hull {N : Network S}
    {C : ProperCone ℝ (EuclideanSpace ℝ S)}
    (h : (C : Set (EuclideanSpace ℝ S)) ⊆
      (PointedCone.hull ℝ (Set.range (fun r : N.R => toEuclid (N.reactionVector r))) :
        Set (EuclideanSpace ℝ S))) :
    N.GeneratedByReactions C :=
  h

/-- The zero cone is reaction-generated: it contains only `0`, which is a conical combination of the
reaction directions. -/
theorem generatedByReactions_bot (N : Network S) :
    N.GeneratedByReactions (⊥ : ProperCone ℝ (EuclideanSpace ℝ S)) :=
  bot_le

/-- **A reaction-generated fan.** Every cone of the fan is reaction-generated: each is contained in
the conical hull of the reaction directions. This is the fan-level statement that the fan's cones
arise from the reaction directions of the network. -/
def ReactionGeneratedFan (N : Network S) (F : Fan (EuclideanSpace ℝ S)) : Prop :=
  ∀ C ∈ F, N.GeneratedByReactions C

/-- A cone of a reaction-generated fan is reaction-generated. -/
theorem ReactionGeneratedFan.generatedByReactions_of_mem {N : Network S}
    {F : Fan (EuclideanSpace ℝ S)} (hF : N.ReactionGeneratedFan F)
    {C : ProperCone ℝ (EuclideanSpace ℝ S)} (hC : C ∈ F) : N.GeneratedByReactions C :=
  hF C hC

/-- The empty fan is reaction-generated: there are no cones to constrain. -/
theorem reactionGeneratedFan_empty (N : Network S) :
    N.ReactionGeneratedFan (∅ : Fan (EuclideanSpace ℝ S)) :=
  fun C hC => absurd hC (Finset.notMem_empty C)

end Network

/-- **The genuine toric field is a strict support field — generation discharged from the fan.** For a
polyhedral fan that is reaction-generated and a weakly-reversible network, if every face of the
angular face list is an exposed-face wall whose cone `D` is a *proper* subcone (`D ⊊ C`) of its
ambient cone, is non-strictly inward across every reaction, and has strictly-positive boundary
concentrations, then the genuine toric mass-action field is a strict support field for the faces. The
per-wall `GeneratedByReactions` clause of
`IsPolyhedralFan.toricMassActionField_isStrictSupportField_of_properFan` is supplied by the fan: the
ambient cone of each wall is a cone of the fan, hence reaction-generated. The strict-support verdict
rests on fan structure (including reaction generation), weak reversibility, and face-properness, with
generation proved from fan membership rather than asserted per wall. -/
theorem IsPolyhedralFan.toricMassActionField_isStrictSupportField_of_reactionFan {S : Type}
    [DecidableEq S] [Fintype S] {N : Network S} (hwr : N.WeaklyReversible)
    {F : Fan (EuclideanSpace ℝ S)} (hF : IsPolyhedralFan F) (hgen : N.ReactionGeneratedFan F)
    (κ : N.RateConstants) {faces : List (EuclideanSpace ℝ S × ℝ)}
    (hfaces : ∀ nf ∈ faces, ∃ (n₀ : S → ℝ) (D C : ProperCone ℝ (EuclideanSpace ℝ S)),
      nf.1 = toEuclid n₀ ∧
      N.IsFanWall F D C n₀ ∧
      (D : Set (EuclideanSpace ℝ S)) ⊂ (C : Set (EuclideanSpace ℝ S)) ∧
      (∀ r : N.R, 0 ≤ ⟪toEuclid n₀, toEuclid (N.reactionVector r)⟫_ℝ) ∧
      (∀ p : EuclideanSpace ℝ S,
        ZeroSeparatingCurve2D.OnFaceBoundary faces (toEuclid n₀) nf.2 p →
          Concentration.Positive (toEuclid.symm p))) :
    ZeroSeparatingCurve2D.IsStrictSupportField (N.toricMassActionField κ) faces := by
  refine hF.toricMassActionField_isStrictSupportField_of_properFan hwr κ ?_
  intro nf hnf
  obtain ⟨n₀, D, C, hn₀, hwall, hproper, hinward, hpos⟩ := hfaces nf hnf
  exact ⟨n₀, D, C, hn₀, hwall,
    hgen.generatedByReactions_of_mem hwall.ambient_mem, hproper, hinward, hpos⟩

end CRNT
