import CRNT.Geometry.ReactionFanGeneration
import CRNT.Geometry.FiniteConeClosed

/-!
# The reaction cone as a genuine proper cone

The conical hull of the reaction directions of a network is closed
(`CRNT.Geometry.FiniteConeClosed`), so it carries a `ProperCone` structure. This module realizes that
hull as `Network.reactionHullCone`, a genuine `ProperCone ℝ (EuclideanSpace ℝ S)`, and proves it is
reaction-generated by reflexivity: its carrier *is* the reaction hull. Packaging the singleton fan
`{reactionHullCone}` then discharges `Network.ReactionGeneratedFan` from the geometry rather than
hand-supplying it, so the toric strict-support verdict no longer carries reaction generation as an
unproven datum.

## The reaction hull cone

The reaction directions `toEuclid (reactionVector r)` form a finite set — the image of the reaction
index `Finset.univ`. Its conical hull is closed, so `properConeOfFinset` turns it into a `ProperCone`.
The image of `univ` is the range of the direction map, so the carrier of `reactionHullCone` is exactly
the hull over `Set.range (fun r => toEuclid (reactionVector r))` that `GeneratedByReactions` measures
against.

* `Network.reactionHullCone` — the conical hull of the reaction directions, as a `ProperCone`.
* `Network.coe_reactionHullCone` — its carrier is the hull over the range of the reaction directions.
* `Network.generatedByReactions_reactionHullCone` — the reaction hull cone is reaction-generated
  (reflexivity: the carrier is the hull).
* `Network.reactionFan` — the singleton fan `{reactionHullCone}`.
* `Network.reactionGeneratedFan_reactionFan` — the reaction fan is reaction-generated.
* `IsPolyhedralFan.toricMassActionField_isStrictSupportField_of_reactionHull` — the strict-support
  deliverable over `reactionFan`, with `ReactionGeneratedFan` proved from the geometry.

## Scope

`reactionFan` is the singleton carrying the reaction hull cone; its reaction generation is proved, not
assumed. Exhibiting it as a full `IsPolyhedralFan` — the face-closure, common-intersection, and
covering clauses of `IsPolyhedralFan` — rests on polytope face theory beyond the cone-closedness
established here, so the deliverable carries `IsPolyhedralFan reactionFan` as a hypothesis while
supplying reaction generation itself.

Depends on: `CRNT.Geometry.ReactionFanGeneration`,
`CRNT.Geometry.FiniteConeClosed`.
-/

namespace CRNT

open scoped InnerProductSpace

namespace Network

variable {S : Type} [DecidableEq S] [Fintype S]

/-- **The reaction hull cone.** The conical hull of the reaction directions
`toEuclid (reactionVector r)` in Euclidean species space, packaged as a `ProperCone`. The hull of the
finite set of reaction directions is closed (`isClosed_coe_hull_of_finite`), so it is a genuine proper
cone, the structure the proper-cone API (duality, separation) consumes. -/
noncomputable def reactionHullCone (N : Network S) : ProperCone ℝ (EuclideanSpace ℝ S) :=
  properConeOfFinset (Finset.image (fun r : N.R => toEuclid (N.reactionVector r)) Finset.univ)

/-- The carrier of the reaction hull cone is the conical hull of the range of the reaction directions:
the image of the reaction index `univ` is exactly the range of the direction map. -/
@[simp] theorem coe_reactionHullCone (N : Network S) :
    (N.reactionHullCone : Set (EuclideanSpace ℝ S))
      = (PointedCone.hull ℝ
          (Set.range (fun r : N.R => toEuclid (N.reactionVector r))) :
        Set (EuclideanSpace ℝ S)) := by
  rw [reactionHullCone, coe_properConeOfFinset]
  congr 1
  rw [Finset.coe_image, Finset.coe_univ, Set.image_univ]

/-- **The reaction hull cone is reaction-generated.** Its carrier is exactly the conical hull of the
reaction directions, so the containment `GeneratedByReactions` demands is reflexivity. -/
theorem generatedByReactions_reactionHullCone (N : Network S) :
    N.GeneratedByReactions N.reactionHullCone := by
  refine GeneratedByReactions.of_subset_hull ?_
  rw [coe_reactionHullCone]

/-- **The reaction fan.** The singleton fan whose only cone is the reaction hull cone. -/
noncomputable def reactionFan (N : Network S) : Fan (EuclideanSpace ℝ S) :=
  {N.reactionHullCone}

@[simp] theorem mem_reactionFan {N : Network S} {C : ProperCone ℝ (EuclideanSpace ℝ S)} :
    C ∈ N.reactionFan ↔ C = N.reactionHullCone := by
  rw [reactionFan, Finset.mem_singleton]

/-- **The reaction fan is reaction-generated.** Its only cone is the reaction hull cone, which is
reaction-generated. The reaction generation of the fan is read off the geometry, not supplied. -/
theorem reactionGeneratedFan_reactionFan (N : Network S) :
    N.ReactionGeneratedFan N.reactionFan := by
  intro C hC
  rw [mem_reactionFan] at hC
  rw [hC]
  exact N.generatedByReactions_reactionHullCone

end Network

/-- **The genuine toric field is a strict support field — reaction generation from the geometry.** For
the reaction fan of a weakly-reversible network, assumed polyhedral, if every face of the angular face
list is an exposed-face wall whose cone `D` is a *proper* subcone (`D ⊊ C`) of its ambient cone, is
non-strictly inward across every reaction, and has strictly-positive boundary concentrations, then the
genuine toric mass-action field is a strict support field for the faces. The per-wall
`GeneratedByReactions` clause of
`IsPolyhedralFan.toricMassActionField_isStrictSupportField_of_reactionFan` is supplied by
`Network.reactionGeneratedFan_reactionFan` — proved from the reaction hull cone's carrier — rather than
hand-carried. The reaction cone is a genuine `ProperCone`, and reaction generation is no longer an
unproven datum of the verdict. -/
theorem IsPolyhedralFan.toricMassActionField_isStrictSupportField_of_reactionHull {S : Type}
    [DecidableEq S] [Fintype S] {N : Network S} (hwr : N.WeaklyReversible)
    (hF : IsPolyhedralFan N.reactionFan) (κ : N.RateConstants)
    {faces : List (EuclideanSpace ℝ S × ℝ)}
    (hfaces : ∀ nf ∈ faces, ∃ (n₀ : S → ℝ) (D C : ProperCone ℝ (EuclideanSpace ℝ S)),
      nf.1 = toEuclid n₀ ∧
      N.IsFanWall N.reactionFan D C n₀ ∧
      (D : Set (EuclideanSpace ℝ S)) ⊂ (C : Set (EuclideanSpace ℝ S)) ∧
      (∀ r : N.R, 0 ≤ ⟪toEuclid n₀, toEuclid (N.reactionVector r)⟫_ℝ) ∧
      (∀ p : EuclideanSpace ℝ S,
        ZeroSeparatingCurve2D.OnFaceBoundary faces (toEuclid n₀) nf.2 p →
          Concentration.Positive (toEuclid.symm p))) :
    ZeroSeparatingCurve2D.IsStrictSupportField (N.toricMassActionField κ) faces :=
  hF.toricMassActionField_isStrictSupportField_of_reactionFan hwr
    N.reactionGeneratedFan_reactionFan κ hfaces

end CRNT
