import CRNT.Dynamics.ComplexBalanceCycleDecomposition
import CRNT.Dynamics.ReactionConeWeakReversibility
import CRNT.Geometry.ReactionFanGeneration

/-!
# Reaction generation for the source-order cones

The sign-reversed source-order family is a finite cone family inside the stoichiometric subspace.
For weakly reversible networks the reaction cone equals that subspace, so every cone in this family
is generated by reaction vectors. This discharges the reaction-generation clause used by the toric
strict-support interfaces for this concrete family.
-/

namespace CRNT
namespace Network

open scoped NNReal

variable {S : Type} [DecidableEq S] [Fintype S]

/-- Every cone in the sign-reversed source-order family is reaction-generated for a weakly
reversible network. -/
theorem relativeSourceOrderNegativeConeFamily_reactionGenerated
    (N : Network S) (hwr : N.WeaklyReversible) :
    N.ReactionGeneratedFan N.relativeSourceOrderNegativeConeFamily := by
  intro C hC
  apply GeneratedByReactions.of_subset_hull
  intro z hz
  have hs : toEuclid.symm z ∈ N.stoichSubspace :=
    N.stoich_of_mem_relativeSourceOrderNegativeConeFamily hC hz
  have hcone : toEuclid.symm z ∈ N.reactionCone := by
    rw [N.reactionCone_eq_stoichSubspace_of_weaklyReversible hwr]
    exact hs
  have hmap : toEuclid (toEuclid.symm z) ∈
      N.reactionCone.map toEuclid.toLinearMap :=
    PointedCone.mem_map.mpr ⟨toEuclid.symm z, hcone, by simp⟩
  have hmapEq : N.reactionCone.map toEuclid.toLinearMap =
      PointedCone.hull ℝ (Set.range fun r : N.R => toEuclid (N.reactionVector r)) := by
    change
      (Submodule.span ℝ≥0 (Set.range N.reactionVector)).map
          (toEuclid.toLinearMap.restrictScalars ℝ≥0) =
        Submodule.span ℝ≥0 (Set.range fun r : N.R => toEuclid (N.reactionVector r))
    rw [Submodule.map_span]
    congr 1
    ext y
    constructor
    · rintro ⟨x, ⟨r, rfl⟩, rfl⟩
      exact ⟨r, rfl⟩
    · rintro ⟨r, rfl⟩
      exact ⟨N.reactionVector r, ⟨r, rfl⟩, rfl⟩
  rw [hmapEq] at hmap
  simpa using hmap

end Network
end CRNT
