import CRNT.Geometry.PolyhedralFan
import CRNT.Dynamics.DifferentialInclusion
import Mathlib.Topology.MetricSpace.HausdorffDistance

/-!
# Toric differential inclusions from a polyhedral fan

The toric differential inclusion of Craciun, _Toric differential inclusions and a
proof of the global attractor conjecture_. A *polyhedral fan* is a finite family of
polyhedral cones covering the ambient space, closed under faces, with pairwise
intersections being common faces. The toric differential inclusion attached to a
fan `F` and a scale `δ > 0` is the set-valued field

`F_{F,δ}(X) = cone ⋃ { Cᵒ : C ∈ F, dist(X, C) < δ }`,

the convex cone generated by the polar cones of the cones lying within distance `δ`
of `X`. The toric inclusion `ẋ ∈ F_{F,δ}(log x)` reads the logarithm of the state
into this field.

Mathlib lacks the polytope face theory needed to certify the full face-lattice
axioms (faces, intersection-is-a-face, covering), so `Fan E` here is the given
data: a `Finset` of proper cones. The face-lattice and covering conditions are
taken as a hypothesis, not formalized.

The field `toricField F δ X` is a genuine `PointedCone ℝ E` by construction
(`PointedCone.hull` of the union of admissible polar cones). It is **monotone in
`δ`** (`toricField_mono_delta`) because enlarging `δ` can only admit more cones, and
it **contains `Cᵒ`** whenever `dist(X, C) < δ` and `C ∈ F`
(`coneDual_le_toricField`).

`toricInclusionField` packages `x ↦ F_{F,δ}(log x)` over `E = EuclideanSpace ℝ S`,
with `Real.log` applied coordinatewise, as a `DifferentialInclusion.Field`, so it
plugs directly into the inclusion-solution layer.

This module is **stable** and `sorry`-free. Depends on: `CRNT.Geometry.PolyhedralFan`,
`CRNT.Dynamics.DifferentialInclusion`, and Mathlib Hausdorff distance.
-/

namespace CRNT

open scoped InnerProductSpace

section Fan

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]

/-- A polyhedral fan, represented pragmatically as a finite family of proper cones.
The full face-lattice and covering axioms rest on polytope face theory absent from
Mathlib and are not imposed here: this is the cone data the toric field consumes. -/
abbrev Fan (E : Type*) [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E] :=
  Finset (ProperCone ℝ E)

/-- The union of polar cones of the cones of `F` lying within distance `δ` of `X`. -/
def toricGenerators (F : Fan E) (δ : ℝ) (X : E) : Set E :=
  ⋃ C ∈ Finset.filter (fun C : ProperCone ℝ E => Metric.infDist X (C : Set E) < δ) F,
    (coneDual (C : Set E) : Set E)

/-- The toric differential-inclusion field `F_{F,δ}(X)`: the convex (pointed) cone
generated by the polar cones of the cones of `F` within distance `δ` of `X`. -/
noncomputable def toricField (F : Fan E) (δ : ℝ) (X : E) : PointedCone ℝ E :=
  PointedCone.hull ℝ (toricGenerators F δ X)

/-- A point of `toricGenerators` is a point of some admissible cone's polar. -/
theorem mem_toricGenerators {F : Fan E} {δ : ℝ} {X y : E} :
    y ∈ toricGenerators F δ X ↔
      ∃ C ∈ F, Metric.infDist X (C : Set E) < δ ∧ y ∈ coneDual (C : Set E) := by
  simp only [toricGenerators, Set.mem_iUnion, Finset.mem_filter, SetLike.mem_coe]
  constructor
  · rintro ⟨C, ⟨hCF, hCd⟩, hy⟩; exact ⟨C, hCF, hCd, hy⟩
  · rintro ⟨C, hCF, hCd, hy⟩; exact ⟨C, ⟨hCF, hCd⟩, hy⟩

/-- When `C ∈ F` lies within distance `δ` of `X`, its generators are admissible. -/
theorem coneDual_subset_toricGenerators {F : Fan E} {δ : ℝ} {X : E} {C : ProperCone ℝ E}
    (hCF : C ∈ F) (hCd : Metric.infDist X (C : Set E) < δ) :
    (coneDual (C : Set E) : Set E) ⊆ toricGenerators F δ X :=
  fun _ hy => mem_toricGenerators.2 ⟨C, hCF, hCd, hy⟩

/-- The toric generators are monotone in `δ`: enlarging the scale admits more cones. -/
theorem toricGenerators_mono_delta {F : Fan E} {δ₁ δ₂ : ℝ} (X : E) (hδ : δ₁ ≤ δ₂) :
    toricGenerators F δ₁ X ⊆ toricGenerators F δ₂ X := by
  intro y hy
  obtain ⟨C, hCF, hCd, hyC⟩ := mem_toricGenerators.1 hy
  exact mem_toricGenerators.2 ⟨C, hCF, lt_of_lt_of_le hCd hδ, hyC⟩

/-- **Monotonicity in `δ`.** A larger scale yields a larger toric field. -/
theorem toricField_mono_delta {F : Fan E} {δ₁ δ₂ : ℝ} (X : E) (hδ : δ₁ ≤ δ₂) :
    (toricField F δ₁ X : Set E) ⊆ (toricField F δ₂ X : Set E) :=
  Submodule.span_mono (toricGenerators_mono_delta X hδ)

/-- **Polar-cone membership.** If `C ∈ F` lies within distance `δ` of `X`, then the
whole polar cone `Cᵒ` is contained in the toric field at `X`. -/
theorem coneDual_le_toricField {F : Fan E} {δ : ℝ} {X : E} {C : ProperCone ℝ E}
    (hCF : C ∈ F) (hCd : Metric.infDist X (C : Set E) < δ) :
    (coneDual (C : Set E) : Set E) ⊆ (toricField F δ X : Set E) :=
  (coneDual_subset_toricGenerators hCF hCd).trans PointedCone.subset_hull

/-- The toric generators sit inside the toric field. -/
theorem toricGenerators_subset_toricField (F : Fan E) (δ : ℝ) (X : E) :
    toricGenerators F δ X ⊆ (toricField F δ X : Set E) :=
  PointedCone.subset_hull

end Fan

section Inclusion

variable {S : Type*}

/-- Coordinatewise real logarithm on `EuclideanSpace ℝ S`, mapping a state to its
log-coordinates so the toric inclusion `ẋ ∈ F_{F,δ}(log x)` can read them. -/
noncomputable def logCoords (x : EuclideanSpace ℝ S) : EuclideanSpace ℝ S :=
  WithLp.toLp 2 (fun s => Real.log (x.ofLp s))

@[simp] theorem logCoords_ofLp (x : EuclideanSpace ℝ S) (s : S) :
    (logCoords x).ofLp s = Real.log (x.ofLp s) := rfl

variable [Fintype S]

/-- The toric differential inclusion as a `DifferentialInclusion.Field`: the
set-valued velocity field `x ↦ F_{F,δ}(log x)`, with the cone coerced to a set so it
plugs into the inclusion-solution predicates. -/
noncomputable def toricInclusionField (F : Fan (EuclideanSpace ℝ S)) (δ : ℝ) :
    DifferentialInclusion.Field (EuclideanSpace ℝ S) :=
  fun x => (toricField F δ (logCoords x) : Set (EuclideanSpace ℝ S))

@[simp] theorem mem_toricInclusionField {F : Fan (EuclideanSpace ℝ S)} {δ : ℝ}
    {x v : EuclideanSpace ℝ S} :
    v ∈ toricInclusionField F δ x ↔ v ∈ toricField F δ (logCoords x) :=
  Iff.rfl

/-- The toric inclusion field is monotone in `δ`, as a field, hence — via the
inclusion monotonicity layer — a larger `δ` only acquires more solutions. -/
theorem toricInclusionField_mono_delta (F : Fan (EuclideanSpace ℝ S)) {δ₁ δ₂ : ℝ}
    (hδ : δ₁ ≤ δ₂) (x : EuclideanSpace ℝ S) :
    toricInclusionField F δ₁ x ⊆ toricInclusionField F δ₂ x :=
  toricField_mono_delta (logCoords x) hδ

end Inclusion

end CRNT
