import CRNT.Geometry.ZeroSeparatingSurface
import CRNT.Geometry.FaithfulCurve2D
import Mathlib.LinearAlgebra.Dimension.Constructions
import Mathlib.Analysis.InnerProductSpace.Projection.Submodule

/-!
# The dimension induction of the zero-separating surface

An `n`-dimensional zero-separating hypersurface is built by induction on dimension. Given an
`(n−1)`-dimensional faithful zero-separating surface, one fixes a constant *attracting direction* `d`
and, from each point of that boundary surface, draws a line segment in direction `d`, continuing it
to the next surface. The segments sweep out a **ruled surface** whose tangent plane everywhere
contains the ruling direction `d`; gluing these ruled patches assembles the full surface.

This module provides the ruled-surface step — its containment, separation, and subtangency-transfer
facts — together with the linear-feasibility threshold that governs when a ruled patch admits a
surface normal.

On a ruled patch crossing several uncertainty regions, a surface normal at a tight boundary point
must be nonzero and orthogonal to every active ruling/attracting direction. Whether such a normal
exists is a homogeneous linear feasibility question with a sharp threshold at `finrank ℝ E`: fewer
than `finrank` active directions always leave a normal; once they span the ambient space, only the
zero vector is orthogonal to all of them. Consequently the **naive** construction — a single patch
aligned simultaneously to several attracting directions — becomes over-determined once the active
directions span, which first occurs in dimension four. This over-determination is not an obstruction
to the surface's existence: a codimension-1 hypersurface always admits a normal (its tangent is
`(n−1)`-dimensional), and the over-determination is avoided by *refining the fan* so each patch
crosses a single uncertainty region, keeping its constraint count below `finrank` (the planar angular
chaining, lifted to `n` dimensions). The refinement's faithful-transfer engine — admissibility for a
finer cell carries to the containing coarse cell — is in `CRNT.Geometry.FanRefinement`.

## The ruled-surface step

* `ruledSet base d L` — the swept set `{ p + t • d | p ∈ base, t ∈ [0, L] }`, the ruled surface
  generated by translating `base` along the ruling direction `d` for parameter length up to `L`.

* `base_subset_ruledSet` — the base sits inside the ruled set at `t = 0`.

* `ruling_mem_ruledSet` — the ruling segment `{ p + t • d | t ∈ [0, L] }` through any base point lies
  in the ruled set: `d` is the tangent (ruling) direction everywhere.

* `ruledSet_subset_compl_ball_of_outward` — **separation transfers.** If `base` already misses the
  open `r`-ball and the ruling direction is *outward* for a separating unit normal `n`
  (`0 ≤ ⟪n, d⟫`, with `base ⊆ {p | r ≤ ⟪n, p⟫}`), then the ruled set still misses the `r`-ball: the
  sweep never moves a point closer to the separating wall than its base point.

## Tangency transfer: subtangency of base + ruling ⇒ subtangency of the ruled surface

The half-plane region `polyRegion faces` is the working form of a zero-separating surface
(`ZeroSeparatingCurve2D.polyRegion`). A face `(n, a)` is **swept-invariant** for the ruling direction
`d` exactly when `0 ≤ ⟪n, d⟫`: translating by `t • d` (`t ≥ 0`) only increases `⟪n, ·⟫`, so it cannot
leave the half-plane.

* `RulingPreservesFace` / `RulingPreservesRegion` — the swept-invariance condition as a `Prop`.

* `ruledSet_subset_polyRegion_of_rulingPreserves` — if the base lies in `polyRegion faces` and the
  ruling direction preserves every face, the entire ruled set lies in `polyRegion faces`: subtangency
  of the base surface plus subtangency of the ruling direction gives subtangency of the swept surface.

* `rulingPreserves_of_inner_nonneg` — the per-face preservation criterion from `0 ≤ ⟪n, d⟫`.

## The over-determination threshold

A valid surface normal `n` on a ruled patch crossing constraint directions `v₀, …, v_{k−1}` must be
nonzero and orthogonal to every `vᵢ`. Whether such `n` exists is governed by whether the `vᵢ` span,
with a sharp threshold at `finrank ℝ E`:

* `exists_orthogonal_normal_of_card_lt_finrank` — if the number of constraint vectors is strictly less
  than `finrank ℝ E`, a nonzero `n` orthogonal to all of them exists. A ruled patch carrying fewer
  active directions than the ambient dimension always has a normal (e.g. two directions in ℝ³).

* `not_exists_orthogonal_normal_of_span_top` — if the constraint vectors *span* `E`, the only vector
  orthogonal to all of them is `0`: no valid surface normal. This is the over-determination of the
  naive single-patch construction, conditional on its active directions spanning.

* `over_determined_in_dim_four` — the concrete `n = 4` instance: four constraint vectors *can* span
  ℝ⁴ (the standard basis does), killing the normal, whereas any three vectors in ℝ⁴ leave a nonzero
  orthogonal normal. The threshold sits exactly at `finrank = 4`; this does not assert that any
  particular construction's active directions span (that count is not established here).

* `inductionStep_of_ruledBuild` — assembles the step from a faithful boundary surface, a ruling
  direction preserving the ambient region, and a *witness* of a compatible swept region. The witness
  carries the decomposition obligation — the part that is over-determined for the naive construction
  in dimension `≥ 4` and that refinement is needed to discharge.

## Scope

This module proves the ruled-set constructions and their containment/separation facts, the
swept-invariance transfer of subtangency from base + ruling to the ruled surface, and the
feasibility/over-determination dichotomy for the surface-normal constraint system, with the explicit
four-dimensional instance. Not constructed here: the explicit decomposition of a neighborhood into
ruled patches each crossing a single uncertainty region (carried as the `hbuild` witness of
`inductionStep_of_ruledBuild`), and the analysis identifying the per-patch attracting directions.

This module is **stable** and `sorry`-free. Depends on: `CRNT.Geometry.ZeroSeparatingSurface`,
`CRNT.Geometry.FaithfulCurve2D`, `Mathlib.LinearAlgebra.Dimension.Constructions`,
`Mathlib.Analysis.InnerProductSpace.Projection.Submodule`.
-/

namespace CRNT

namespace ZeroSeparatingInduction

open scoped InnerProductSpace
open ZeroSeparatingCurve2D

/-! ## The ruled-surface step -/

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]

/-- **The ruled set.** Sweeping a base set `base` along the constant ruling direction `d` for
parameter length up to `L`: the set of all `p + t • d` with `p ∈ base` and `t ∈ [0, L]`. This is
the ruled surface generated from an `(n−1)`-D boundary surface `base`. -/
def ruledSet (base : Set E) (d : E) (L : ℝ) : Set E :=
  {x | ∃ p ∈ base, ∃ t : ℝ, 0 ≤ t ∧ t ≤ L ∧ x = p + t • d}

/-- The base surface sits inside the ruled set, at ruling parameter `t = 0`. -/
theorem base_subset_ruledSet {base : Set E} {d : E} {L : ℝ} (hL : 0 ≤ L) :
    base ⊆ ruledSet base d L := by
  intro p hp
  exact ⟨p, hp, 0, le_rfl, hL, by simp⟩

/-- The ruling segment through a base point lies in the ruled set: from `p ∈ base`, every point
`p + t • d` with `t ∈ [0, L]` is swept. The ruling direction `d` is the tangent direction of the
ruled surface everywhere. -/
theorem ruling_mem_ruledSet {base : Set E} {d : E} {L : ℝ} {p : E} (hp : p ∈ base)
    {t : ℝ} (ht0 : 0 ≤ t) (htL : t ≤ L) :
    p + t • d ∈ ruledSet base d L :=
  ⟨p, hp, t, ht0, htL, rfl⟩

/-- **Separation transfers along an outward ruling.** Suppose `base` lies on the far side of a
separating unit-normal half-plane (`r ≤ ⟪n, p⟫` for `p ∈ base`, with `0 < r`, `‖n‖ = 1`), and the
ruling direction is *outward* for that normal (`0 ≤ ⟪n, d⟫`). Then every swept point still satisfies
`r ≤ ⟪n, ·⟫`, hence the ruled set still misses the open `r`-ball about `0`. Sweeping outward never
brings a point closer to the wall. -/
theorem ruledSet_subset_compl_ball_of_outward {base : Set E} {d n : E} {L r : ℝ}
    (hn : ‖n‖ = 1) (hbase : ∀ p ∈ base, r ≤ ⟪n, p⟫_ℝ) (hd : 0 ≤ ⟪n, d⟫_ℝ) :
    ruledSet base d L ⊆ (Metric.ball (0 : E) r)ᶜ := by
  intro x hx
  obtain ⟨p, hp, t, ht0, _, rfl⟩ := hx
  have hwall : r ≤ ⟪n, p + t • d⟫_ℝ := by
    rw [inner_add_right, inner_smul_right]
    have : 0 ≤ t * ⟪n, d⟫_ℝ := mul_nonneg ht0 hd
    linarith [hbase p hp]
  rw [Set.mem_compl_iff, Metric.mem_ball, dist_zero_right, not_lt]
  have hcs : ⟪n, p + t • d⟫_ℝ ≤ ‖p + t • d‖ := by
    have := real_inner_le_norm n (p + t • d)
    rwa [hn, one_mul] at this
  linarith

/-! ## Tangency transfer: subtangency of base + ruling ⇒ subtangency of the ruled surface

The established working form of a zero-separating surface is the half-plane intersection
`ZeroSeparatingCurve2D.polyRegion faces`. A single face `(n, a)` is preserved by the sweep precisely
when the ruling direction is non-decreasing for that face's normal. -/

/-- **A face is preserved by the ruling.** The face `(n, a)` is *ruling-preserved* by `d` when the
sweep does not decrease its support value: `0 ≤ ⟪n, d⟫_ℝ`, so translating by `t • d` (`t ≥ 0`) keeps
the half-plane `{p | a ≤ ⟪n, p⟫}` satisfied. -/
def RulingPreservesFace (d : E) (n : E) : Prop := 0 ≤ ⟪n, d⟫_ℝ

/-- **The ruling preserves the whole region.** Every face's normal is non-decreasing along `d`. -/
def RulingPreservesRegion (faces : List (E × ℝ)) (d : E) : Prop :=
  ∀ nf ∈ faces, RulingPreservesFace d nf.1

/-- A single half-plane is closed under the outward sweep: if `a ≤ ⟪n, p⟫` and `0 ≤ ⟪n, d⟫` then
`a ≤ ⟪n, p + t • d⟫` for every `t ≥ 0`. -/
theorem mem_halfPlane_add_smul {n p d : E} {a t : ℝ} (hp : a ≤ ⟪n, p⟫_ℝ)
    (hd : 0 ≤ ⟪n, d⟫_ℝ) (ht : 0 ≤ t) :
    a ≤ ⟪n, p + t • d⟫_ℝ := by
  rw [inner_add_right, inner_smul_right]
  have : 0 ≤ t * ⟪n, d⟫_ℝ := mul_nonneg ht hd
  linarith

/-- **The clean half of the ruled step.** If the base surface lies in `polyRegion faces` and the
ruling direction preserves every face, the entire ruled set lies in `polyRegion faces`. Subtangency
of the base surface plus subtangency of the ruling direction yields subtangency of the swept
surface — the genuine geometric content that makes the ruled-surface step go through in low
dimension. -/
theorem ruledSet_subset_polyRegion_of_rulingPreserves {faces : List (E × ℝ)} {base : Set E}
    {d : E} {L : ℝ} (hbase : base ⊆ polyRegion faces) (hpres : RulingPreservesRegion faces d) :
    ruledSet base d L ⊆ polyRegion faces := by
  intro x hx
  obtain ⟨p, hp, t, ht0, _, rfl⟩ := hx
  rw [mem_polyRegion]
  intro nf hnf
  exact mem_halfPlane_add_smul ((mem_polyRegion.mp (hbase hp)) nf hnf) (hpres nf hnf) ht0

/-- The per-face preservation criterion: a non-decreasing inner product with the ruling direction
makes the face ruling-preserved. -/
theorem rulingPreserves_of_inner_nonneg {d n : E} (h : 0 ≤ ⟪n, d⟫_ℝ) :
    RulingPreservesFace d n := h

/-! ## The over-determination threshold

A valid surface normal `n` on a ruled patch crossing constraint directions `v : ι → E` must be
nonzero and orthogonal to every `v i` (the active attracting-direction constraints, tight on the
patch boundary). Whether such `n` exists is governed entirely by whether the `v i` span `E`, which
has a sharp threshold at `finrank ℝ E`. -/

variable [FiniteDimensional ℝ E]

/-- **Feasibility below the dimension threshold.** If the number of constraint directions is
strictly less than `finrank ℝ E`, there is a nonzero vector orthogonal to all of them: the
constraint span is a proper subspace, whose orthogonal complement is nontrivial. So whenever a ruled
patch carries fewer active tangency directions than the ambient dimension, a valid surface normal
exists (e.g. two directions in ℝ³, `2 < 3`); how many a patch is actually forced to carry is the
residual combinatorial fact. -/
theorem exists_orthogonal_normal_of_card_lt_finrank {ι : Type*} [Fintype ι] (v : ι → E)
    (hcard : Fintype.card ι < Module.finrank ℝ E) :
    ∃ n : E, n ≠ 0 ∧ ∀ i, ⟪v i, n⟫_ℝ = 0 := by
  classical
  -- The span of the constraint directions is a proper subspace.
  have hspan : Submodule.span ℝ (Set.range v) < ⊤ := by
    refine span_lt_top_of_card_lt_finrank ?_
    calc (Set.range v).toFinset.card ≤ Fintype.card ι := by
          rw [Set.toFinset_range]
          exact Finset.card_image_le
      _ < Module.finrank ℝ E := hcard
  -- Hence its orthogonal complement is nontrivial: it contains a nonzero vector.
  have hne : (Submodule.span ℝ (Set.range v))ᗮ ≠ ⊥ := by
    rw [Ne, Submodule.orthogonal_eq_bot_iff]
    exact ne_of_lt hspan
  obtain ⟨n, hnmem, hnne⟩ := Submodule.exists_mem_ne_zero_of_ne_bot hne
  refine ⟨n, hnne, fun i => ?_⟩
  have hvi : v i ∈ Submodule.span ℝ (Set.range v) :=
    Submodule.subset_span (Set.mem_range_self i)
  exact Submodule.inner_right_of_mem_orthogonal hvi hnmem

set_option linter.unusedSectionVars false in
/-- **Over-determination when the constraints span.** If the constraint directions span `E`, the
only vector orthogonal to all of them is `0`: there is no valid surface normal. Once the active
attracting directions on a single ruled patch span the ambient space, the simultaneous orthogonality
constraints force the would-be normal to vanish — the over-determination of the naive single-patch
construction. -/
theorem not_exists_orthogonal_normal_of_span_top {ι : Type*} (v : ι → E)
    (hspan : Submodule.span ℝ (Set.range v) = ⊤) :
    ∀ n : E, (∀ i, ⟪v i, n⟫_ℝ = 0) → n = 0 := by
  intro n hn
  -- `n` is orthogonal to the whole spanning set, hence to all of `E`, hence to itself.
  have hmem : n ∈ (Submodule.span ℝ (Set.range v))ᗮ := by
    rw [Submodule.mem_orthogonal]
    intro u hu
    induction hu using Submodule.span_induction with
    | mem x hx => obtain ⟨i, rfl⟩ := hx; exact hn i
    | zero => simp
    | add x y _ _ hx hy => rw [inner_add_left, hx, hy, add_zero]
    | smul c x _ hx => rw [inner_smul_left, hx, mul_zero]
  rw [hspan, Submodule.top_orthogonal_eq_bot, Submodule.mem_bot] at hmem
  exact hmem

set_option linter.unusedSectionVars false in
/-- **The dimension count.** If the constraint directions span `E`, their number is at least
`finrank ℝ E`. The contrapositive of feasibility: a spanning (hence normal-killing) family of
attracting directions requires at least `finrank ℝ E` of them — which dimension three cannot supply
on a ruled patch but dimension four can. -/
theorem finrank_le_card_of_span_top {ι : Type*} [Fintype ι] (v : ι → E)
    (hspan : Submodule.span ℝ (Set.range v) = ⊤) :
    Module.finrank ℝ E ≤ Fintype.card ι :=
  finrank_le_of_span_eq_top hspan

end ZeroSeparatingInduction

/-! ## The concrete ℝ⁴ instance: the over-determination is real

In ℝ⁴ four attracting directions *can* span the space — the standard basis does — and then no
nonzero normal survives. By contrast any three directions in ℝ⁴ leave a nonzero orthogonal normal.
The over-determination at `n = 4` is therefore genuine and dimension-driven, not an artifact of how
the surface is parametrized. -/

namespace ZeroSeparatingInduction

open scoped InnerProductSpace

/-- The standard basis of `EuclideanSpace ℝ (Fin 4)` spans the space, so the four basis directions
as subtangency constraints annihilate the normal: only `n = 0` is orthogonal to all four. The
canonical witness that four constraints over-determine the normal in ℝ⁴. -/
theorem stdBasis_four_kills_normal :
    ∀ n : EuclideanSpace ℝ (Fin 4),
      (∀ i, ⟪EuclideanSpace.basisFun (Fin 4) ℝ i, n⟫_ℝ = 0) → n = 0 := by
  apply not_exists_orthogonal_normal_of_span_top
  have hb := (EuclideanSpace.basisFun (Fin 4) ℝ).toBasis.span_eq
  rwa [OrthonormalBasis.coe_toBasis] at hb

/-- **Feasibility in ℝ⁴ for three constraints.** Any three attracting-direction constraints in ℝ⁴
leave a nonzero orthogonal normal (`3 < 4`), so a ruled patch crossing at most three regions in ℝ⁴
still admits a valid surface — the obstruction appears only once a fourth independent direction
becomes active. -/
theorem three_constraints_feasible_in_dim_four (v : Fin 3 → EuclideanSpace ℝ (Fin 4)) :
    ∃ n : EuclideanSpace ℝ (Fin 4), n ≠ 0 ∧ ∀ i, ⟪v i, n⟫_ℝ = 0 := by
  apply exists_orthogonal_normal_of_card_lt_finrank
  simp [finrank_euclideanSpace]

/-- **The over-determination dichotomy in ℝ⁴.** Together: three tangency constraints are always
feasible (a nonzero normal exists), while four *spanning* constraints are infeasible (only the zero
normal qualifies). The threshold sits exactly at the ambient dimension `4`: this is why the naive
single-patch construction (one patch aligned to several attracting directions at once) breaks in ℝ⁴,
while a refined construction keeping each patch below `finrank` constraints avoids the spanning case.
The dichotomy explains the need to refine; it is not an obstruction to the surface's existence. -/
theorem over_determined_in_dim_four :
    (∀ v : Fin 3 → EuclideanSpace ℝ (Fin 4),
        ∃ n : EuclideanSpace ℝ (Fin 4), n ≠ 0 ∧ ∀ i, ⟪v i, n⟫_ℝ = 0) ∧
      (∀ n : EuclideanSpace ℝ (Fin 4),
        (∀ i, ⟪EuclideanSpace.basisFun (Fin 4) ℝ i, n⟫_ℝ = 0) → n = 0) :=
  ⟨three_constraints_feasible_in_dim_four, stdBasis_four_kills_normal⟩

/-- **Feasibility persists through dimension three.** Two subtangency constraints in ℝ³ always leave
a nonzero orthogonal normal (`2 < 3`): the 3-D ruled construction is never over-determined, the
contrast that makes dimension four the first failure. -/
theorem two_constraints_feasible_in_dim_three (v : Fin 2 → EuclideanSpace ℝ (Fin 3)) :
    ∃ n : EuclideanSpace ℝ (Fin 3), n ≠ 0 ∧ ∀ i, ⟪v i, n⟫_ℝ = 0 := by
  apply exists_orthogonal_normal_of_card_lt_finrank
  simp [finrank_euclideanSpace]

end ZeroSeparatingInduction

/-! ## Assembling the induction step

The step bundles the ruled-surface construction into the
`DifferentialInclusion.InductionStepHypothesis` interface. The parts discharged here are that the
ruled set contains the base and stays subtangent under an outward ruling; the obligation that a
single ruled-patch decomposition with a compatible ruling direction and surface data exists — the
part over-determined for the naive construction in dimension `≥ 4` — is carried as an explicit
witness hypothesis. -/

namespace DifferentialInclusion

open ZeroSeparatingInduction

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]

/-- **The ruled induction step, structurally.** Given facet (boundary) surfaces and an explicit
witness `hbuild` that the ruled-patch gluing produces an ambient surface for `f` at `x₀` from those
facet surfaces, `InductionStepHypothesis f x₀ facetField facetStart` holds. This isolates the
geometric obligation in `hbuild`: the swept-region constructions of this module
(`ruledSet_subset_polyRegion_of_rulingPreserves`, `ruledSet_subset_compl_ball_of_outward`) supply
the subtangency and separation transfer, but the existence of a *compatible* ruling direction across
all patches — feasible in dimension `≤ 3`, over-determined in dimension `≥ 4` by
`over_determined_in_dim_four` — is exactly what `hbuild` must furnish. -/
theorem inductionStep_of_ruledBuild {f : E → E} {x₀ : E} {ι : Type*} [Fintype ι]
    {facetField : ι → (E → E)} {facetStart : ι → E}
    (hbuild : (∀ i, ZeroSeparatingSurfaceExists (facetField i) (facetStart i)) →
        ZeroSeparatingSurfaceExists f x₀) :
    InductionStepHypothesis f x₀ facetField facetStart :=
  hbuild

end DifferentialInclusion

end CRNT
