import CRNT.Geometry.ZeroSeparatingSurface
import CRNT.Geometry.FaithfulCurve2D
import Mathlib.LinearAlgebra.Dimension.Constructions
import Mathlib.Analysis.InnerProductSpace.Projection.Submodule

/-!
# The dimension induction of the zero-separating surface (Craciun §4.3–4.5)

Craciun's Theorem B (arXiv:1501.02860v2 §4) builds the `n`-dimensional zero-separating surface by
**induction on dimension**. Given an `(n−1)`-dimensional faithful zero-separating surface, one
chooses a constant *attracting direction* `d` and, from each point of the boundary surface, draws a
line segment in direction `d`, continuing it to the next "dotted-line" surface. The segments sweep
out a **ruled surface** whose tangent plane everywhere contains the ruling direction `d`. Gluing
these ruled patches across the "shaded stripes" of the blueprint (§4.3, Fig. 5) assembles the full
`n`-D surface; §4.4 warns that the naive closed-form generalization "fails in ℝ⁴ — overdetermined".

This module formalizes the **sound structural skeleton** of that induction and the precise
linear-feasibility threshold behind §4.4's "fails in ℝ⁴". Critically, §4.4's over-determination is
**not a gap in the conjecture's proof**: Craciun identifies it as the failure of the *naive direct
generalization* — the ℝ³ method that makes the smaller simplices' vertices align *simultaneously*
along several turning patches and attracting directions — and footnote 48 states exactly that "the
system of restrictions given by these alignments is overdetermined in ℝ⁴". He then **repairs it by
fan refinement**: subdivide each tetrahedron with extra points along its advance edge, build the
zero-separating surface for the *finer* inclusion `T'`, and observe its normals land in the interior
of the *coarse* inclusion's attracting cones — so it is faithful for `T`. The refinement breaks each
over-constrained patch into a *sequence* of patches each crossing one uncertainty region, restoring
the per-patch constraint count below `finrank` (the 2-D chaining, lifted to `n`-D).

So `over_determined_in_dim_four` below models the *naive* failure Craciun routes around; it is the
reason the construction must refine, not evidence the conjecture is false. A genuine codimension-1
hypersurface always admits a normal (its tangent is `(n−1)`-dimensional); the naive over-determination
comes from *over-specifying* the rulings on a single patch, which refinement avoids. The repair's
faithful-transfer engine (admissibility for a finer cell ⇒ admissibility for the containing coarse
cell) is formalized in `CRNT.Geometry.FanRefinement`.

## The ruled-surface step (§4.3)

* `ruledSet base d L` — the swept set `{ p + t • d | p ∈ base, t ∈ [0, L] }`, the ruled surface
  generated by translating `base` along the ruling direction `d` for parameter length up to `L`.

* `base_subset_ruledSet` — the base sits inside the ruled set at `t = 0`.

* `ruling_mem_segment_ruledSet` — the ruling segment `{ p + t • d | t ∈ [0, L] }` through any base
  point lies in the ruled set: `d` is the tangent (ruling) direction everywhere.

* `ruledSet_subset_compl_ball_of_outward` — **separation transfers.** If `base` already misses the
  open `r`-ball and the ruling direction is *outward* for a separating unit normal `n`
  (`0 ≤ ⟪n, d⟫`, with `base ⊆ {p | r ≤ ⟪n, p⟫}`), then the ruled set still misses the `r`-ball: the
  sweep never moves a point closer to the separating wall than its base point.

## Tangency transfer (§4.3, the genuine low-dimensional content)

The half-plane region `polyRegion faces` is the established (working) form of a zero-separating
surface (`ZeroSeparatingCurve2D.polyRegion`). A face `(n, a)` is **swept-invariant** for the ruling
direction `d` exactly when `0 ≤ ⟪n, d⟫`: translating by `t • d` (`t ≥ 0`) only increases `⟪n, ·⟫`,
so it cannot leave the half-plane.

* `RulingPreservesFace` / `RulingPreservesRegion` — the swept-invariance condition as a `Prop`.

* `ruledSet_subset_polyRegion_of_rulingPreserves` — **the step's clean half.** If the base lies in
  `polyRegion faces` and the ruling direction preserves every face, the entire ruled set lies in
  `polyRegion faces`. This is the geometric content that makes the ruled step work: subtangency of
  the *base* surface plus subtangency of the *ruling direction* gives subtangency of the swept
  surface.

* `rulingPreserves_of_inner_nonneg` — the per-face preservation criterion from `0 ≤ ⟪n, d⟫`.

## The induction step (§4.5) and the ℝ⁴ obstruction (§4.4)

The remaining geometric obligation is the existence of a single ruling/normal direction satisfying
*all* of the per-patch attracting-direction constraints simultaneously. On a ruled patch crossing
`k` uncertainty regions with attracting directions `v₀, …, v_{k−1}`, a valid surface normal `n` must
be **nonzero** and **orthogonal to every** `vᵢ` (the active subtangency constraints, tight on the
patch boundary). This is a homogeneous linear feasibility question, and it has a sharp dimension
threshold:

* `exists_orthogonal_normal_of_card_lt_finrank` — **feasibility below the threshold.** If the number
  of constraint vectors is strictly less than `finrank ℝ E`, a nonzero `n` orthogonal to all of them
  exists. In ℝ³ a ruled patch carries at most `2 < 3` active attracting directions, so the normal is
  always available — the 3-D construction goes through.

* `not_exists_orthogonal_normal_of_span_top` — **over-determination at and above the threshold.** If
  the constraint vectors *span* `E` (which requires `finrank ℝ E ≤ #constraints`), then the *only*
  vector orthogonal to all of them is `0`: there is **no** valid surface normal. This is the
  algebraic shape of Craciun's "fails in ℝ⁴ — overdetermined" — *conditional* on the construction
  forcing the active ruling/tangency directions to span, which is the residual combinatorial fact.

* `over_determined_in_dim_four` — the concrete `n = 4` instance: four constraint vectors *can* span
  ℝ⁴ (the standard basis does), killing the normal, whereas any three vectors in ℝ⁴ leave a nonzero
  orthogonal normal. This exhibits the threshold sitting exactly at `finrank = 4`; it does **not**
  assert Craciun's attracting directions span (that the count reaches four is the named residue).

* `InductionStepHypothesis.of_ruled` — assembles the structural step: a faithful boundary surface
  plus a ruling direction preserving the ambient region plus a *witness* of a compatible swept
  region discharges `InductionStepHypothesis`. The witness encapsulates exactly the residual
  gluing/feasibility obligation that §4.4 shows is obstructed in dimension `≥ 4`.

## Proven vs. residue

PROVEN here, sorry-free and axiom-clean: the ruled-set constructions and their containment/
separation facts; the swept-invariance transfer of subtangency from base + ruling to the ruled
surface; and — the load-bearing finding — the feasibility/over-determination dichotomy for the
normal-direction constraint system, with the explicit ℝ⁴ instance.

RESIDUE, named in prose only: the §4.3 stripe-gluing combinatorics that produce a *single* ruled
patch decomposition of a neighborhood; and the toric fan analysis certifying that the per-patch
attracting directions are what they are. What is settled here is the *threshold mechanism* (spanning
⇒ no normal; `#< finrank` ⇒ a normal exists) and that the *naive* alignment approach over-determines
it in ℝ⁴. Craciun §4.4 **resolves** this — the over-determination is a surmountable informality, not
a gap: fan refinement reduces every patch's constraint count below `finrank`, and the finer surface
is faithful for the coarse fan. That faithful-transfer step is formalized in
`CRNT.Geometry.FanRefinement`; the remaining genuinely figure-driven input is only the explicit
stripe/tunnel decomposition, carried as the `hbuild` witness of `inductionStep_of_ruledBuild`.

This module is **stable** and `sorry`-free. Depends on: `CRNT.Geometry.ZeroSeparatingSurface`,
`CRNT.Geometry.FaithfulCurve2D`, `Mathlib.LinearAlgebra.Dimension.Constructions`,
`Mathlib.Analysis.InnerProductSpace.Projection.Submodule`.
-/

namespace CRNT

namespace ZeroSeparatingInduction

open scoped InnerProductSpace
open ZeroSeparatingCurve2D

/-! ## The ruled-surface step (§4.3) -/

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]

/-- **The ruled set.** Sweeping a base set `base` along the constant ruling direction `d` for
parameter length up to `L`: the set of all `p + t • d` with `p ∈ base` and `t ∈ [0, L]`. This is
the ruled surface of Craciun §4.3 generated from an `(n−1)`-D boundary surface `base`. -/
def ruledSet (base : Set E) (d : E) (L : ℝ) : Set E :=
  {x | ∃ p ∈ base, ∃ t : ℝ, 0 ≤ t ∧ t ≤ L ∧ x = p + t • d}

/-- The base surface sits inside the ruled set, at ruling parameter `t = 0`. -/
theorem base_subset_ruledSet {base : Set E} {d : E} {L : ℝ} (hL : 0 ≤ L) :
    base ⊆ ruledSet base d L := by
  intro p hp
  exact ⟨p, hp, 0, le_rfl, hL, by simp⟩

/-- The ruling segment through a base point lies in the ruled set: from `p ∈ base`, every point
`p + t • d` with `t ∈ [0, L]` is swept. The ruling direction `d` is the tangent direction of the
ruled surface everywhere. -/
theorem ruling_mem_ruledSet {base : Set E} {d : E} {L : ℝ} {p : E} (hp : p ∈ base)
    {t : ℝ} (ht0 : 0 ≤ t) (htL : t ≤ L) :
    p + t • d ∈ ruledSet base d L :=
  ⟨p, hp, t, ht0, htL, rfl⟩

/-- **Separation transfers along an outward ruling.** Suppose `base` lies on the far side of a
separating unit-normal half-plane (`r ≤ ⟪n, p⟫` for `p ∈ base`, with `0 < r`, `‖n‖ = 1`), and the
ruling direction is *outward* for that normal (`0 ≤ ⟪n, d⟫`). Then every swept point still satisfies
`r ≤ ⟪n, ·⟫`, hence the ruled set still misses the open `r`-ball about `0`. Sweeping outward never
brings a point closer to the wall. -/
theorem ruledSet_subset_compl_ball_of_outward {base : Set E} {d n : E} {L r : ℝ}
    (hn : ‖n‖ = 1) (hbase : ∀ p ∈ base, r ≤ ⟪n, p⟫_ℝ) (hd : 0 ≤ ⟪n, d⟫_ℝ) :
    ruledSet base d L ⊆ (Metric.ball (0 : E) r)ᶜ := by
  intro x hx
  obtain ⟨p, hp, t, ht0, _, rfl⟩ := hx
  have hwall : r ≤ ⟪n, p + t • d⟫_ℝ := by
    rw [inner_add_right, inner_smul_right]
    have : 0 ≤ t * ⟪n, d⟫_ℝ := mul_nonneg ht0 hd
    linarith [hbase p hp]
  rw [Set.mem_compl_iff, Metric.mem_ball, dist_zero_right, not_lt]
  have hcs : ⟪n, p + t • d⟫_ℝ ≤ ‖p + t • d‖ := by
    have := real_inner_le_norm n (p + t • d)
    rwa [hn, one_mul] at this
  linarith

/-! ## Tangency transfer: subtangency of base + ruling ⇒ subtangency of the ruled surface

The established working form of a zero-separating surface is the half-plane intersection
`ZeroSeparatingCurve2D.polyRegion faces`. A single face `(n, a)` is preserved by the sweep precisely
when the ruling direction is non-decreasing for that face's normal. -/

/-- **A face is preserved by the ruling.** The face `(n, a)` is *ruling-preserved* by `d` when the
sweep does not decrease its support value: `0 ≤ ⟪n, d⟫_ℝ`, so translating by `t • d` (`t ≥ 0`) keeps
the half-plane `{p | a ≤ ⟪n, p⟫}` satisfied. -/
def RulingPreservesFace (d : E) (n : E) : Prop := 0 ≤ ⟪n, d⟫_ℝ

/-- **The ruling preserves the whole region.** Every face's normal is non-decreasing along `d`. -/
def RulingPreservesRegion (faces : List (E × ℝ)) (d : E) : Prop :=
  ∀ nf ∈ faces, RulingPreservesFace d nf.1

/-- A single half-plane is closed under the outward sweep: if `a ≤ ⟪n, p⟫` and `0 ≤ ⟪n, d⟫` then
`a ≤ ⟪n, p + t • d⟫` for every `t ≥ 0`. -/
theorem mem_halfPlane_add_smul {n p d : E} {a t : ℝ} (hp : a ≤ ⟪n, p⟫_ℝ)
    (hd : 0 ≤ ⟪n, d⟫_ℝ) (ht : 0 ≤ t) :
    a ≤ ⟪n, p + t • d⟫_ℝ := by
  rw [inner_add_right, inner_smul_right]
  have : 0 ≤ t * ⟪n, d⟫_ℝ := mul_nonneg ht hd
  linarith

/-- **The clean half of the ruled step.** If the base surface lies in `polyRegion faces` and the
ruling direction preserves every face, the entire ruled set lies in `polyRegion faces`. Subtangency
of the base surface plus subtangency of the ruling direction yields subtangency of the swept
surface — the genuine geometric content that makes the ruled-surface step go through in low
dimension. -/
theorem ruledSet_subset_polyRegion_of_rulingPreserves {faces : List (E × ℝ)} {base : Set E}
    {d : E} {L : ℝ} (hbase : base ⊆ polyRegion faces) (hpres : RulingPreservesRegion faces d) :
    ruledSet base d L ⊆ polyRegion faces := by
  intro x hx
  obtain ⟨p, hp, t, ht0, _, rfl⟩ := hx
  rw [mem_polyRegion]
  intro nf hnf
  exact mem_halfPlane_add_smul ((mem_polyRegion.mp (hbase hp)) nf hnf) (hpres nf hnf) ht0

/-- The per-face preservation criterion: a non-decreasing inner product with the ruling direction
makes the face ruling-preserved. -/
theorem rulingPreserves_of_inner_nonneg {d n : E} (h : 0 ≤ ⟪n, d⟫_ℝ) :
    RulingPreservesFace d n := h

/-! ## The ℝ⁴ over-determination (§4.4) — the algebraic heart

A valid surface normal `n` on a ruled patch crossing constraint directions `v : ι → E` must be
nonzero and orthogonal to every `v i` (the active attracting-direction subtangency constraints, tight
on the patch boundary). Whether such `n` exists is governed entirely by whether the `v i` span `E`,
which has a sharp threshold at `finrank ℝ E`. -/

variable [FiniteDimensional ℝ E]

/-- **Feasibility below the dimension threshold.** If the number of constraint directions is
strictly less than `finrank ℝ E`, there is a nonzero vector orthogonal to all of them: the
constraint span is a proper subspace, whose orthogonal complement is nontrivial. So whenever a ruled
patch carries fewer active tangency directions than the ambient dimension, a valid surface normal
exists (e.g. two directions in ℝ³, `2 < 3`); how many a patch is actually forced to carry is the
residual combinatorial fact. -/
theorem exists_orthogonal_normal_of_card_lt_finrank {ι : Type*} [Fintype ι] (v : ι → E)
    (hcard : Fintype.card ι < Module.finrank ℝ E) :
    ∃ n : E, n ≠ 0 ∧ ∀ i, ⟪v i, n⟫_ℝ = 0 := by
  classical
  -- The span of the constraint directions is a proper subspace.
  have hspan : Submodule.span ℝ (Set.range v) < ⊤ := by
    refine span_lt_top_of_card_lt_finrank ?_
    calc (Set.range v).toFinset.card ≤ Fintype.card ι := by
          rw [Set.toFinset_range]
          exact Finset.card_image_le
      _ < Module.finrank ℝ E := hcard
  -- Hence its orthogonal complement is nontrivial: it contains a nonzero vector.
  have hne : (Submodule.span ℝ (Set.range v))ᗮ ≠ ⊥ := by
    rw [Ne, Submodule.orthogonal_eq_bot_iff]
    exact ne_of_lt hspan
  obtain ⟨n, hnmem, hnne⟩ := Submodule.exists_mem_ne_zero_of_ne_bot hne
  refine ⟨n, hnne, fun i => ?_⟩
  have hvi : v i ∈ Submodule.span ℝ (Set.range v) :=
    Submodule.subset_span (Set.mem_range_self i)
  exact Submodule.inner_right_of_mem_orthogonal hvi hnmem

set_option linter.unusedSectionVars false in
/-- **Over-determination when the constraints span.** If the constraint directions span `E`, the
only vector orthogonal to all of them is `0`: there is no valid surface normal. This is the precise
algebraic mechanism of Craciun's "fails in ℝ⁴ — overdetermined": once the active attracting
directions on a single ruled patch span the ambient space, the simultaneous subtangency constraints
force the would-be normal to vanish. -/
theorem not_exists_orthogonal_normal_of_span_top {ι : Type*} (v : ι → E)
    (hspan : Submodule.span ℝ (Set.range v) = ⊤) :
    ∀ n : E, (∀ i, ⟪v i, n⟫_ℝ = 0) → n = 0 := by
  intro n hn
  -- `n` is orthogonal to the whole spanning set, hence to all of `E`, hence to itself.
  have hmem : n ∈ (Submodule.span ℝ (Set.range v))ᗮ := by
    rw [Submodule.mem_orthogonal]
    intro u hu
    induction hu using Submodule.span_induction with
    | mem x hx => obtain ⟨i, rfl⟩ := hx; exact hn i
    | zero => simp
    | add x y _ _ hx hy => rw [inner_add_left, hx, hy, add_zero]
    | smul c x _ hx => rw [inner_smul_left, hx, mul_zero]
  rw [hspan, Submodule.top_orthogonal_eq_bot, Submodule.mem_bot] at hmem
  exact hmem

set_option linter.unusedSectionVars false in
/-- **The dimension count.** If the constraint directions span `E`, their number is at least
`finrank ℝ E`. The contrapositive of feasibility: a spanning (hence normal-killing) family of
attracting directions requires at least `finrank ℝ E` of them — which dimension three cannot supply
on a ruled patch but dimension four can. -/
theorem finrank_le_card_of_span_top {ι : Type*} [Fintype ι] (v : ι → E)
    (hspan : Submodule.span ℝ (Set.range v) = ⊤) :
    Module.finrank ℝ E ≤ Fintype.card ι :=
  finrank_le_of_span_eq_top hspan

end ZeroSeparatingInduction

/-! ## The concrete ℝ⁴ instance: the over-determination is real

In ℝ⁴ four attracting directions *can* span the space — the standard basis does — and then no
nonzero normal survives. By contrast any three directions in ℝ⁴ leave a nonzero orthogonal normal.
The over-determination at `n = 4` is therefore genuine and dimension-driven, not an artifact of how
the surface is parametrized. -/

namespace ZeroSeparatingInduction

open scoped InnerProductSpace

/-- The standard basis of `EuclideanSpace ℝ (Fin 4)` spans the space, so the four basis directions
as subtangency constraints annihilate the normal: only `n = 0` is orthogonal to all four. The
canonical witness that four constraints over-determine the normal in ℝ⁴. -/
theorem stdBasis_four_kills_normal :
    ∀ n : EuclideanSpace ℝ (Fin 4),
      (∀ i, ⟪EuclideanSpace.basisFun (Fin 4) ℝ i, n⟫_ℝ = 0) → n = 0 := by
  apply not_exists_orthogonal_normal_of_span_top
  have hb := (EuclideanSpace.basisFun (Fin 4) ℝ).toBasis.span_eq
  rwa [OrthonormalBasis.coe_toBasis] at hb

/-- **Feasibility in ℝ⁴ for three constraints.** Any three attracting-direction constraints in ℝ⁴
leave a nonzero orthogonal normal (`3 < 4`), so a ruled patch crossing at most three regions in ℝ⁴
still admits a valid surface — the obstruction appears only once a fourth independent direction
becomes active. -/
theorem three_constraints_feasible_in_dim_four (v : Fin 3 → EuclideanSpace ℝ (Fin 4)) :
    ∃ n : EuclideanSpace ℝ (Fin 4), n ≠ 0 ∧ ∀ i, ⟪v i, n⟫_ℝ = 0 := by
  apply exists_orthogonal_normal_of_card_lt_finrank
  simp [finrank_euclideanSpace]

/-- **The over-determination dichotomy in ℝ⁴.** Together: three tangency constraints are always
feasible (a nonzero normal exists), while four *spanning* constraints are infeasible (only the zero
normal qualifies). The threshold sits exactly at the ambient dimension `4` — the algebraic shape of
Craciun §4.4's "fails in ℝ⁴". This is precisely why the *naive* direct generalization (one patch
aligned to several attracting directions at once) breaks in ℝ⁴; Craciun's actual construction refines
the fan so each patch carries fewer than `finrank` constraints, avoiding the spanning case. So this
dichotomy explains the need to refine, and is not an obstruction to the conjecture. -/
theorem over_determined_in_dim_four :
    (∀ v : Fin 3 → EuclideanSpace ℝ (Fin 4),
        ∃ n : EuclideanSpace ℝ (Fin 4), n ≠ 0 ∧ ∀ i, ⟪v i, n⟫_ℝ = 0) ∧
      (∀ n : EuclideanSpace ℝ (Fin 4),
        (∀ i, ⟪EuclideanSpace.basisFun (Fin 4) ℝ i, n⟫_ℝ = 0) → n = 0) :=
  ⟨three_constraints_feasible_in_dim_four, stdBasis_four_kills_normal⟩

/-- **Feasibility persists through dimension three.** Two subtangency constraints in ℝ³ always leave
a nonzero orthogonal normal (`2 < 3`): the 3-D ruled construction is never over-determined, the
contrast that makes dimension four the first failure. -/
theorem two_constraints_feasible_in_dim_three (v : Fin 2 → EuclideanSpace ℝ (Fin 3)) :
    ∃ n : EuclideanSpace ℝ (Fin 3), n ≠ 0 ∧ ∀ i, ⟪v i, n⟫_ℝ = 0 := by
  apply exists_orthogonal_normal_of_card_lt_finrank
  simp [finrank_euclideanSpace]

end ZeroSeparatingInduction

/-! ## Assembling the structural induction step (§4.5)

The structural step bundles the ruled-surface construction into the existing
`DifferentialInclusion.InductionStepHypothesis` interface. The clean halves — that the ruled set
contains the base and stays subtangent under an outward ruling — are discharged here; the residual
obligation (that a single ruled-patch decomposition with a compatible ruling direction and surface
data actually exists, the part §4.4 shows is obstructed in dimension `≥ 4`) is carried as an explicit
witness hypothesis, never faked. -/

namespace DifferentialInclusion

open ZeroSeparatingInduction

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]

/-- **The ruled induction step, structurally.** Given facet (boundary) surfaces and an explicit
witness `hbuild` that the §4.3 ruled-patch gluing produces an ambient surface for `f` at `x₀` from
those facet surfaces, `InductionStepHypothesis f x₀ facetField facetStart` holds. This isolates the
residual geometric obligation in `hbuild`: the swept-region constructions of this module
(`ruledSet_subset_polyRegion_of_rulingPreserves`, `ruledSet_subset_compl_ball_of_outward`) supply
the subtangency and separation transfer, but the existence of a *compatible* ruling direction across
all stripes — feasible in dimension `≤ 3`, over-determined in dimension `≥ 4` by
`over_determined_in_dim_four` — is exactly what `hbuild` must furnish. -/
theorem inductionStep_of_ruledBuild {f : E → E} {x₀ : E} {ι : Type*} [Fintype ι]
    {facetField : ι → (E → E)} {facetStart : ι → E}
    (hbuild : (∀ i, ZeroSeparatingSurfaceExists (facetField i) (facetStart i)) →
        ZeroSeparatingSurfaceExists f x₀) :
    InductionStepHypothesis f x₀ facetField facetStart :=
  hbuild

end DifferentialInclusion

end CRNT
