import CRNT.Dynamics.ToricBarrierTrapping

/-!
# Face localization for the relative-log fan state

The blueprint clause `hnear` of
`CRNT.Network.exists_positive_omegaPoint_of_toric_blueprint` asks, at each point of the orbit, for
normals lying in every cone of `N.relativeSourceOrderNegativeStoichFan` within `δ` of the
*relative-log state* `N.relativeLogFanState xstar x`.  Building a blueprint therefore requires
knowing **which** cones can possibly be near that state when `x` is near a coordinate face.  This
module answers that.

## The statement

Fix a species set `P`.  Write `w s = log (xstar s) - log (x s)`.  Then

```
relativeLogFanState xstar x = euclideanStoichStateL w,
```

which is `relativeLogFanState_eq` — the relative-log state is just the transport of `log x* - log x`
into the intrinsic stoichiometric space.  Splitting `w` into its `P` and off-`P` parts and using
linearity,

```
relativeLogFanState xstar x = ∑ s ∈ P, w s • euclideanStoichUnit s  +  (off-P part),
```

and when `x s ≤ xstar s` for `s ∈ P` the coefficients `w s` are nonnegative, so the first summand
lies in the fixed cone

```
faceDirectionCone P = PointedCone.hull ℝ (euclideanStoichUnit '' P),
```

which depends only on `P` and the network.  So the relative-log state sits within an explicit
distance — the norm of the off-`P` part, controlled by the coordinates that are *not* going to
zero — of a cone fixed once and for all.

`dist_lt_of_infDist_lt` then converts this into the localization a blueprint builder wants: any fan
cone within `δ` of the relative-log state comes within `δ + ‖off-P part‖` of
`faceDirectionCone P`.  On a tile where the off-`P` coordinates range over a compact set, that
bound is uniform, so the tile's relevant cone family is determined by `P` alone.

This is the content of Craciun v3 §6.1.3: outside the unit cube the toric field at `P` "will not
depend on `C`, but on the intersection between `C` and `∂₁D^H₂`", i.e. only the cones meeting the
face's direction cone matter.

Nothing here is an axiom or a `sorry`.

Depends on: `CRNT.Dynamics.ToricBarrierTrapping`.
-/

namespace CRNT
namespace Network

open Filter
open scoped RealInnerProductSpace NNReal Topology

variable {S : Type} [DecidableEq S] [Fintype S]

/-! ### The relative-log state is a transport -/

/-- **The relative-log fan state is the transport of `log x* - log x`.**  Unfolding
`relativeLogFanState` through `relativeLogStoichProjection` and the negation gives exactly the
continuous linear transport map `euclideanStoichStateL` applied to `log x* - log x`.  This is what
makes the splitting below available. -/
theorem relativeLogFanState_eq (N : Network S) (xstar x : Concentration S) :
    N.relativeLogFanState xstar x
      = N.euclideanStoichStateL (fun s => Real.log (xstar s) - Real.log (x s)) := by
  have hfun : (fun s => Real.log (xstar s) - Real.log (x s))
      = -(fun s => Real.log (x s) - Real.log (xstar s)) := by
    funext s; simp only [Pi.neg_apply]; ring
  apply Subtype.ext
  rw [hfun]
  simp only [Network.relativeLogFanState, Network.relativeLogStoichProjection,
    Network.euclideanStoichStateL, NegMemClass.coe_neg, LinearEquiv.apply_symm_apply,
    ContinuousLinearMap.coe_comp, Function.comp_apply,
    Submodule.coe_orthogonalProjectionOnto_apply, map_neg]
  rfl

/-! ### The face direction cone -/

/-- The projected coordinate direction of a species, inside the intrinsic stoichiometric space. -/
noncomputable def euclideanStoichUnit (N : Network S) (s : S) : N.euclideanStoichSubspace :=
  N.euclideanStoichStateL (Pi.single s 1)

/-- **The asymptotic direction cone of the `P`-face**: the pointed cone generated by the projected
coordinate directions of `P`.  As `x` approaches the `P`-face, `log (xstar s) - log (x s) → +∞` for
`s ∈ P` while the other coordinates stay bounded, so the relative-log state escapes to infinity
inside a bounded neighbourhood of this cone. -/
noncomputable def faceDirectionCone (N : Network S) (P : Finset S) :
    PointedCone ℝ N.euclideanStoichSubspace :=
  PointedCone.hull ℝ (N.euclideanStoichUnit '' (P : Set S))

theorem euclideanStoichUnit_mem_faceDirectionCone (N : Network S) {P : Finset S} {s : S}
    (hs : s ∈ P) : N.euclideanStoichUnit s ∈ N.faceDirectionCone P :=
  PointedCone.subset_hull ⟨s, hs, rfl⟩

/-- A nonnegative combination of the projected directions of `P` lies in the face direction cone. -/
theorem sum_smul_mem_faceDirectionCone (N : Network S) {P : Finset S} {c : S → ℝ}
    (hc : ∀ s ∈ P, 0 ≤ c s) :
    (∑ s ∈ P, c s • N.euclideanStoichUnit s) ∈ N.faceDirectionCone P := by
  refine Submodule.sum_mem _ fun s hs => ?_
  have hmem := N.euclideanStoichUnit_mem_faceDirectionCone hs
  simpa using Submodule.smul_mem (N.faceDirectionCone P) (⟨c s, hc s hs⟩ : ℝ≥0) hmem

/-! ### The splitting -/

/-- Restricting a coefficient vector to `P` expands it over the coordinate directions of `P`. -/
theorem euclideanStoichStateL_indicator (N : Network S) (P : Finset S) (w : S → ℝ) :
    N.euclideanStoichStateL (fun s => if s ∈ P then w s else 0)
      = ∑ s ∈ P, w s • N.euclideanStoichUnit s := by
  have hvec : (fun s => if s ∈ P then w s else 0)
      = ∑ s ∈ P, w s • (Pi.single s 1 : S → ℝ) := by
    funext t
    rw [Finset.sum_apply]
    by_cases ht : t ∈ P
    · rw [Finset.sum_eq_single t (fun u hu hut => by
        simp [Ne.symm hut]) (fun h => absurd ht h)]
      simp [ht]
    · have hzero : ∀ u ∈ P, (w u • (Pi.single u 1 : S → ℝ)) t = 0 := by
        intro u hu
        have htu : t ≠ u := fun h => ht (h ▸ hu)
        simp [Ne.symm htu]
      rw [Finset.sum_eq_zero hzero]
      simp [ht]
  rw [hvec, map_sum]
  exact Finset.sum_congr rfl fun s _ => by rw [map_smul]; rfl

/-- **The splitting of the relative-log state.**  The `P`-part is a nonnegative combination of the
projected directions of `P` (nonnegative exactly because `x` is below `xstar` on `P`), and the rest
is the transport of the off-`P` data. -/
theorem relativeLogFanState_eq_add (N : Network S) (P : Finset S)
    (xstar x : Concentration S) :
    N.relativeLogFanState xstar x
      = (∑ s ∈ P, (Real.log (xstar s) - Real.log (x s)) • N.euclideanStoichUnit s)
        + N.euclideanStoichStateL
            (fun s => if s ∈ P then 0 else Real.log (xstar s) - Real.log (x s)) := by
  rw [relativeLogFanState_eq, ← N.euclideanStoichStateL_indicator P, ← map_add]
  congr 1
  funext s
  by_cases hs : s ∈ P <;> simp [hs]

/-! ### Localization -/

/-- **Face localization, witness form.**  For `x` below `xstar` on `P`, the relative-log state is
at distance exactly `‖off-P part‖` from an explicit point of `faceDirectionCone P`. -/
theorem exists_mem_faceDirectionCone_dist_eq (N : Network S) (P : Finset S)
    {xstar x : Concentration S} (hxpos : x.Positive)
    (hx : ∀ s ∈ P, x s ≤ xstar s) :
    ∃ k ∈ N.faceDirectionCone P,
      dist (N.relativeLogFanState xstar x) k
        = ‖N.euclideanStoichStateL
            (fun s => if s ∈ P then 0 else Real.log (xstar s) - Real.log (x s))‖ := by
  refine ⟨∑ s ∈ P, (Real.log (xstar s) - Real.log (x s)) • N.euclideanStoichUnit s,
    N.sum_smul_mem_faceDirectionCone ?_, ?_⟩
  · intro s hs
    have := Real.log_le_log (hxpos s) (hx s hs)
    linarith
  · rw [relativeLogFanState_eq_add N P xstar x]
    simp [dist_eq_norm]

/-- **Face localization.**  The relative-log state of a point below `xstar` on `P` lies within the
norm of its off-`P` part of the fixed cone `faceDirectionCone P`. -/
theorem infDist_relativeLogFanState_faceDirectionCone_le (N : Network S) (P : Finset S)
    {xstar x : Concentration S} (hxpos : x.Positive) (hx : ∀ s ∈ P, x s ≤ xstar s) :
    Metric.infDist (N.relativeLogFanState xstar x)
        (N.faceDirectionCone P : Set N.euclideanStoichSubspace)
      ≤ ‖N.euclideanStoichStateL
          (fun s => if s ∈ P then 0 else Real.log (xstar s) - Real.log (x s))‖ := by
  obtain ⟨k, hk, hdist⟩ := N.exists_mem_faceDirectionCone_dist_eq P hxpos hx
  rw [← hdist]
  exact Metric.infDist_le_dist_of_mem hk

/-- **Only cones near the face direction cone are relevant.**

If a cone `C` of the fan comes within `δ` of the relative-log state of a point below `xstar` on
`P`, then `C` comes within `δ + ‖off-P part‖` of `faceDirectionCone P`.  On a tile where the
off-`P` coordinates range over a compact set that bound is uniform, so the cone family a blueprint
tile has to accommodate is determined by `P` alone — the localization used in Craciun v3 §6.1.3. -/
theorem exists_dist_lt_faceDirectionCone_of_infDist_lt (N : Network S) (P : Finset S)
    {xstar x : Concentration S} (hxpos : x.Positive) (hx : ∀ s ∈ P, x s ≤ xstar s)
    {δ : ℝ} {C : ProperCone ℝ N.euclideanStoichSubspace}
    (hC : Metric.infDist (N.relativeLogFanState xstar x)
      (C : Set N.euclideanStoichSubspace) < δ) :
    ∃ y ∈ (C : Set N.euclideanStoichSubspace), ∃ k ∈ N.faceDirectionCone P,
      dist y k < δ + ‖N.euclideanStoichStateL
        (fun s => if s ∈ P then 0 else Real.log (xstar s) - Real.log (x s))‖ := by
  have hCne : (C : Set N.euclideanStoichSubspace).Nonempty := ⟨0, C.zero_mem⟩
  obtain ⟨y, hyC, hy⟩ := (Metric.infDist_lt_iff hCne).mp hC
  obtain ⟨k, hk, hdist⟩ := N.exists_mem_faceDirectionCone_dist_eq P hxpos hx
  refine ⟨y, hyC, k, hk, ?_⟩
  calc dist y k ≤ dist y (N.relativeLogFanState xstar x)
        + dist (N.relativeLogFanState xstar x) k := dist_triangle _ _ _
    _ < δ + ‖N.euclideanStoichStateL
          (fun s => if s ∈ P then 0 else Real.log (xstar s) - Real.log (x s))‖ := by
        rw [hdist, dist_comm y]
        exact add_lt_add_of_lt_of_le hy le_rfl

/-! ### The two parts of the relative-log state -/

/-- The part of the relative-log state coming from the face coordinates. -/
noncomputable def faceLogPart (N : Network S) (P : Finset S) (xstar x : Concentration S) :
    N.euclideanStoichSubspace :=
  N.euclideanStoichStateL fun s => if s ∈ P then Real.log (xstar s) - Real.log (x s) else 0

/-- The part of the relative-log state coming from the coordinates off the face.  Near the face
these coordinates stay in a compact range, so this part stays bounded. -/
noncomputable def offFaceLogPart (N : Network S) (P : Finset S) (xstar x : Concentration S) :
    N.euclideanStoichSubspace :=
  N.euclideanStoichStateL fun s => if s ∈ P then 0 else Real.log (xstar s) - Real.log (x s)

theorem relativeLogFanState_eq_faceLogPart_add (N : Network S) (P : Finset S)
    (xstar x : Concentration S) :
    N.relativeLogFanState xstar x = N.faceLogPart P xstar x + N.offFaceLogPart P xstar x := by
  rw [relativeLogFanState_eq, Network.faceLogPart, Network.offFaceLogPart, ← map_add]
  congr 1
  funext s
  by_cases hs : s ∈ P <;> simp [hs]

theorem faceLogPart_mem_faceDirectionCone (N : Network S) (P : Finset S)
    {xstar x : Concentration S} (hxpos : x.Positive) (hx : ∀ s ∈ P, x s ≤ xstar s) :
    N.faceLogPart P xstar x ∈ N.faceDirectionCone P := by
  rw [Network.faceLogPart, N.euclideanStoichStateL_indicator]
  refine N.sum_smul_mem_faceDirectionCone fun s hs => ?_
  have := Real.log_le_log (hxpos s) (hx s hs)
  linarith

theorem dist_relativeLogFanState_faceLogPart (N : Network S) (P : Finset S)
    (xstar x : Concentration S) :
    dist (N.relativeLogFanState xstar x) (N.faceLogPart P xstar x)
      = ‖N.offFaceLogPart P xstar x‖ := by
  rw [relativeLogFanState_eq_faceLogPart_add N P xstar x]
  simp [dist_eq_norm]

/-! ### Relevant cones of an angular tile -/

/-- The cones of the source-order fan that an *angular tile* `σ` of the face has to accommodate:
those coming within `δ + B` of `σ`, where `B` bounds the off-face part.

Shrinking `σ` shrinks this family (`relevantCones_subset_of_subset`) and therefore *enlarges* the
core below.  That is the whole point of subdividing: one normal cannot serve the entire face
direction cone, but it can serve a small enough angular piece of it. -/
noncomputable def relevantCones (N : Network S) (σ : Set N.euclideanStoichSubspace) (δ B : ℝ) :
    Finset (ProperCone ℝ N.euclideanStoichSubspace) :=
  letI := Classical.decPred fun C : ProperCone ℝ N.euclideanStoichSubspace =>
    ∃ y ∈ (C : Set N.euclideanStoichSubspace), ∃ k ∈ σ, dist y k < δ + B
  N.relativeSourceOrderNegativeStoichFan.filter fun C =>
    ∃ y ∈ (C : Set N.euclideanStoichSubspace), ∃ k ∈ σ, dist y k < δ + B

theorem mem_relevantCones (N : Network S) {σ : Set N.euclideanStoichSubspace} {δ B : ℝ}
    {C : ProperCone ℝ N.euclideanStoichSubspace} :
    C ∈ N.relevantCones σ δ B ↔
      C ∈ N.relativeSourceOrderNegativeStoichFan ∧
        ∃ y ∈ (C : Set N.euclideanStoichSubspace), ∃ k ∈ σ, dist y k < δ + B := by
  classical
  simp only [Network.relevantCones, Finset.mem_filter]

theorem relevantCones_subset_of_subset (N : Network S) {σ σ' : Set N.euclideanStoichSubspace}
    (hσ : σ' ⊆ σ) (δ B : ℝ) : N.relevantCones σ' δ B ⊆ N.relevantCones σ δ B := by
  intro C hC
  obtain ⟨hCF, y, hyC, k, hk, hdist⟩ := N.mem_relevantCones.1 hC
  exact N.mem_relevantCones.2 ⟨hCF, y, hyC, k, hσ hk, hdist⟩

/-- **The core of an angular tile**: a single vector legal as a normal for every cone the tile can
force.  It is itself a cone of the fan. -/
noncomputable def relevantCore (N : Network S) (σ : Set N.euclideanStoichSubspace) (δ B : ℝ)
    (h : (N.relevantCones σ δ B).Nonempty) : ProperCone ℝ N.euclideanStoichSubspace :=
  CRNT.subfanCore (N.relevantCones σ δ B) h

theorem relevantCore_mem (N : Network S) {σ : Set N.euclideanStoichSubspace} {δ B : ℝ}
    (h : (N.relevantCones σ δ B).Nonempty) :
    N.relevantCore σ δ B h ∈ N.relativeSourceOrderNegativeStoichFan :=
  CRNT.subfanCore_mem N.relativeSourceOrderNegativeStoichFan_isPolyhedralFan
    (fun _ hC => (N.mem_relevantCones.1 hC).1) h

theorem mem_of_mem_relevantCore (N : Network S) {σ : Set N.euclideanStoichSubspace} {δ B : ℝ}
    (h : (N.relevantCones σ δ B).Nonempty) {m : N.euclideanStoichSubspace}
    (hm : m ∈ N.relevantCore σ δ B h) : ∀ C ∈ N.relevantCones σ δ B, m ∈ C :=
  CRNT.mem_of_mem_subfanCore h hm

/-- **Subdividing enlarges the core.**  A smaller angular tile has to accommodate fewer cones, so
its core is larger.  This is the quantitative reason a multi-tile blueprint can succeed where a
single tile cannot. -/
theorem relevantCore_le_of_subset (N : Network S) {σ σ' : Set N.euclideanStoichSubspace}
    (hσ : σ' ⊆ σ) {δ B : ℝ} (h' : (N.relevantCones σ' δ B).Nonempty)
    (h : (N.relevantCones σ δ B).Nonempty) :
    N.relevantCore σ δ B h ≤ N.relevantCore σ' δ B h' := by
  refine Finset.le_inf' h' id fun C hC => ?_
  exact CRNT.subfanCore_le h (N.relevantCones_subset_of_subset hσ δ B hC)

/-- **Localization to an angular tile.**  If the face part of the relative-log state lies in `σ`
and the off-face part has norm at most `B`, then every cone of the fan within `δ` of the
relative-log state is one that `σ` has to accommodate. -/
theorem mem_relevantCones_of_infDist_lt (N : Network S) (P : Finset S)
    {xstar x : Concentration S} {σ : Set N.euclideanStoichSubspace}
    (hσ : N.faceLogPart P xstar x ∈ σ) {B : ℝ} (hB : ‖N.offFaceLogPart P xstar x‖ ≤ B)
    {δ : ℝ} {C : ProperCone ℝ N.euclideanStoichSubspace}
    (hCF : C ∈ N.relativeSourceOrderNegativeStoichFan)
    (hC : Metric.infDist (N.relativeLogFanState xstar x)
      (C : Set N.euclideanStoichSubspace) < δ) :
    C ∈ N.relevantCones σ δ B := by
  have hCne : (C : Set N.euclideanStoichSubspace).Nonempty := ⟨0, C.zero_mem⟩
  obtain ⟨y, hyC, hy⟩ := (Metric.infDist_lt_iff hCne).mp hC
  refine N.mem_relevantCones.2 ⟨hCF, y, hyC, N.faceLogPart P xstar x, hσ, ?_⟩
  calc dist y (N.faceLogPart P xstar x)
      ≤ dist y (N.relativeLogFanState xstar x)
        + dist (N.relativeLogFanState xstar x) (N.faceLogPart P xstar x) := dist_triangle _ _ _
    _ < δ + B := by
        rw [N.dist_relativeLogFanState_faceLogPart P xstar x, dist_comm y]
        exact add_lt_add_of_lt_of_le hy hB

/-! ### The face-relevant core (the one-tile case) -/

/-- The cones a *single* tile covering the whole face direction cone must accommodate. -/
noncomputable def faceRelevantCones (N : Network S) (P : Finset S) (δ B : ℝ) :
    Finset (ProperCone ℝ N.euclideanStoichSubspace) :=
  N.relevantCones (N.faceDirectionCone P : Set N.euclideanStoichSubspace) δ B

theorem mem_faceRelevantCones (N : Network S) {P : Finset S} {δ B : ℝ}
    {C : ProperCone ℝ N.euclideanStoichSubspace} :
    C ∈ N.faceRelevantCones P δ B ↔
      C ∈ N.relativeSourceOrderNegativeStoichFan ∧
        ∃ y ∈ (C : Set N.euclideanStoichSubspace),
          ∃ k ∈ (N.faceDirectionCone P : Set N.euclideanStoichSubspace),
            dist y k < δ + B :=
  N.mem_relevantCones

/-- **The face-relevant core**: a normal legal for every cone the whole `P`-face can force.  It is
a cone of the fan, so "is one tile enough near this face?" is a concrete question about a named
cone.  When it is too small, subdivide — see `relevantCore_le_of_subset`. -/
noncomputable def faceRelevantCore (N : Network S) (P : Finset S) (δ B : ℝ)
    (h : (N.faceRelevantCones P δ B).Nonempty) : ProperCone ℝ N.euclideanStoichSubspace :=
  N.relevantCore (N.faceDirectionCone P : Set N.euclideanStoichSubspace) δ B h

theorem faceRelevantCore_mem (N : Network S) {P : Finset S} {δ B : ℝ}
    (h : (N.faceRelevantCones P δ B).Nonempty) :
    N.faceRelevantCore P δ B h ∈ N.relativeSourceOrderNegativeStoichFan :=
  N.relevantCore_mem h

theorem mem_of_mem_faceRelevantCore (N : Network S) {P : Finset S} {δ B : ℝ}
    (h : (N.faceRelevantCones P δ B).Nonempty) {m : N.euclideanStoichSubspace}
    (hm : m ∈ N.faceRelevantCore P δ B h) :
    ∀ C ∈ N.faceRelevantCones P δ B, m ∈ C :=
  N.mem_of_mem_relevantCore h hm

/-! ### The multi-tile criterion -/

/-- **Multi-tile repulsion criterion for a coordinate face.**

The blueprint data is a finite family of *angular tiles* `σ : ι' → Set` of the face direction cone,
one normal `m k` per tile drawn from that tile's core `relevantCore (σ k) δ B`, and one level
`b k` per tile; the guarded region is the min over tiles of the halfspaces
`⟪-m k, ·⟫ ≤ b k + R`.

All cone conditions are conditions on the fan, the tiles, and the two scalars `δ`, `B` — no orbit
times occur inside them.  The orbit supplies `hassign`: whenever the level is reached, some tile
`k` attains the minimum, the point is in the near-`P` regime (below `xstar` on `P`, off-face part
bounded by `B`), **and** its face part lies in that tile's `σ k`.  That last conjunct is the
log-to-linear coupling: the tile that wins the minimum in state space must be the one containing
the face part of the relative-log state.

Constructing `σ`, `m`, `b` and establishing `hassign` and `hsep` is exactly what remains of
Craciun v3 §7–§8.  `relevantCore_le_of_subset` says refining `σ` only helps on the cone side; the
difficulty is making the refinement compatible with `hassign`. -/
theorem exists_positive_omegaPoint_of_tiled_faceCores (N : Network S) (κ : N.RateConstants)
    {xstar : Concentration S} (hxs : xstar.Positive) (hcb : N.IsComplexBalanced κ xstar)
    {ϕ : Flow ℝ≥0 (Concentration S)}
    {γ : Concentration S → ℝ → Concentration S} {x₀ : Concentration S}
    (hϕγ : ∀ x (t : ℝ≥0), ϕ t x = γ x t)
    {K : Set (Concentration S)} (hK : IsCompact K) (hmaps : ∀ t : ℝ≥0, ϕ t x₀ ∈ K)
    (hΓcont : ContinuousOn (γ x₀) (Set.Ici 0))
    (hΓpos : ∀ t, 0 ≤ t → (γ x₀ t).Positive)
    (hΓd : ∀ t, 0 ≤ t → HasDerivAt (γ x₀) (N.massActionVectorField κ (γ x₀ t)) t)
    (hclass : ∀ t, 0 ≤ t → N.StoichCompatible (γ x₀ 0) (γ x₀ t))
    {δ : ℝ} (hδ : 0 < δ) {P : Finset S} {B R : ℝ}
    {ι' : Type*} [Fintype ι'] [Nonempty ι']
    {σ : ι' → Set N.euclideanStoichSubspace}
    (hσne : ∀ k, (N.relevantCones (σ k) δ B).Nonempty)
    {m : ι' → N.euclideanStoichSubspace} (hm : ∀ k, m k ∈ N.relevantCore (σ k) δ B (hσne k))
    {b : ι' → ℝ}
    (hstart : PolyhedralBarrier.minMaxBarrier
      (fun (k : ι') (_ : Unit) => innerSL ℝ (-m k)) (fun k _ => b k)
      (N.euclideanStoichState (γ x₀ 0)) ≤ R)
    (hassign : ∀ t, 0 ≤ t →
      R ≤ PolyhedralBarrier.minMaxBarrier
        (fun (k : ι') (_ : Unit) => innerSL ℝ (-m k)) (fun k _ => b k)
        (N.euclideanStoichState (γ x₀ t)) →
      ∃ k : ι',
        PolyhedralBarrier.barrier (fun (_ : Unit) => innerSL ℝ (-m k)) (fun _ => b k)
            (N.euclideanStoichState (γ x₀ t))
          = PolyhedralBarrier.minMaxBarrier
              (fun (k : ι') (_ : Unit) => innerSL ℝ (-m k)) (fun k _ => b k)
              (N.euclideanStoichState (γ x₀ t)) ∧
        (∀ s ∈ P, γ x₀ t s ≤ xstar s) ∧
        ‖N.offFaceLogPart P xstar (γ x₀ t)‖ ≤ B ∧
        N.faceLogPart P xstar (γ x₀ t) ∈ σ k)
    (hsep : ∀ s : S, ∃ ε : ℝ, 0 < ε ∧ ∀ x : Concentration S, x.Positive →
      N.StoichCompatible (γ x₀ 0) x →
      PolyhedralBarrier.minMaxBarrier
        (fun (k : ι') (_ : Unit) => innerSL ℝ (-m k)) (fun k _ => b k)
        (N.euclideanStoichState x) ≤ R → ε ≤ x s) :
    ∃ p ∈ omegaLimit atTop ϕ {x₀}, p.Positive := by
  refine N.exists_positive_omegaPoint_of_toric_blueprint κ hxs hcb hϕγ hK hmaps hΓcont hΓpos hΓd
    hclass hδ (n := fun k (_ : Unit) => m k) (b := fun k _ => b k) (R := R) hstart ?_ hsep
  intro t ht hlevel
  obtain ⟨k, hk, hbelow, hbound, hface⟩ := hassign t ht hlevel
  refine ⟨k, hk, ?_⟩
  intro i _ C hCF hCnear
  exact N.mem_of_mem_relevantCore (hσne k) (hm k) C
    (N.mem_relevantCones_of_infDist_lt P hface hbound hCF hCnear)

/-- The one-tile case of `exists_positive_omegaPoint_of_tiled_faceCores`, stated directly as a
single affine halfspace.  This is the strongest sufficient condition the framework gives with one
tile; several are needed in general. -/
theorem exists_positive_omegaPoint_of_faceRelevantCore (N : Network S) (κ : N.RateConstants)
    {xstar : Concentration S} (hxs : xstar.Positive) (hcb : N.IsComplexBalanced κ xstar)
    {ϕ : Flow ℝ≥0 (Concentration S)}
    {γ : Concentration S → ℝ → Concentration S} {x₀ : Concentration S}
    (hϕγ : ∀ x (t : ℝ≥0), ϕ t x = γ x t)
    {K : Set (Concentration S)} (hK : IsCompact K) (hmaps : ∀ t : ℝ≥0, ϕ t x₀ ∈ K)
    (hΓcont : ContinuousOn (γ x₀) (Set.Ici 0))
    (hΓpos : ∀ t, 0 ≤ t → (γ x₀ t).Positive)
    (hΓd : ∀ t, 0 ≤ t → HasDerivAt (γ x₀) (N.massActionVectorField κ (γ x₀ t)) t)
    (hclass : ∀ t, 0 ≤ t → N.StoichCompatible (γ x₀ 0) (γ x₀ t))
    {δ : ℝ} (hδ : 0 < δ) {P : Finset S} {B c : ℝ}
    (hcore : (N.faceRelevantCones P δ B).Nonempty)
    {m : N.euclideanStoichSubspace} (hm : m ∈ N.faceRelevantCore P δ B hcore)
    (hstart : ⟪-m, N.euclideanStoichState (γ x₀ 0)⟫ ≤ c)
    (hface : ∀ t, 0 ≤ t → c ≤ ⟪-m, N.euclideanStoichState (γ x₀ t)⟫ →
      (∀ s ∈ P, γ x₀ t s ≤ xstar s) ∧ ‖N.offFaceLogPart P xstar (γ x₀ t)‖ ≤ B)
    (hsep : ∀ s : S, ∃ ε : ℝ, 0 < ε ∧ ∀ x : Concentration S, x.Positive →
      N.StoichCompatible (γ x₀ 0) x → ⟪-m, N.euclideanStoichState x⟫ ≤ c → ε ≤ x s) :
    ∃ p ∈ omegaLimit atTop ϕ {x₀}, p.Positive := by
  refine N.exists_positive_omegaPoint_of_toric_halfspace κ hxs hcb hϕγ hK hmaps hΓcont hΓpos hΓd
    hclass hδ hstart ?_ hsep
  intro t ht hlevel C hCF hCnear
  obtain ⟨hbelow, hbound⟩ := hface t ht hlevel
  exact N.mem_of_mem_faceRelevantCore hcore hm C
    (N.mem_relevantCones_of_infDist_lt P
      (N.faceLogPart_mem_faceDirectionCone P (hΓpos t ht) hbelow) hbound hCF hCnear)

end Network
end CRNT
