import CRNT.Dynamics.ToricInclusion
import CRNT.Deficiency.ConsistentWR

/-!
# The reaction cone of a weakly reversible network

Weak reversibility gives a strictly positive linear dependence among all reaction vectors. Isolating
one term in that dependence shows that the negative of every reaction vector is in the reaction
cone. Thus the reaction cone is already a linear subspace, and it equals the stoichiometric
subspace. This identifies the constant reaction-cone inclusion with the exact compatibility
directions of a weakly reversible network.
-/

namespace CRNT
namespace Network

variable {S : Type} [DecidableEq S] [Fintype S]

/-- In a consistent network, the negative of each reaction vector is a nonnegative combination of
the other reaction vectors. -/
theorem neg_reactionVector_mem_reactionCone_of_isConsistent
    (N : Network S) (hcons : N.IsConsistent) (r : N.R) :
    -N.reactionVector r ∈ N.reactionCone := by
  obtain ⟨α, hαpos, hαsum⟩ := hcons
  have hrpos : 0 < α r := hαpos r
  have hsumRest :
      (∑ q ∈ Finset.univ.erase r, α q • N.reactionVector q) =
        -(α r • N.reactionVector r) := by
    have hsplit :
        (∑ q : N.R, α q • N.reactionVector q) =
          α r • N.reactionVector r +
            ∑ q ∈ Finset.univ.erase r, α q • N.reactionVector q := by
      calc
        (∑ q : N.R, α q • N.reactionVector q) =
            (∑ q ∈ Finset.univ.erase r, α q • N.reactionVector q) +
              α r • N.reactionVector r :=
          (Finset.sum_erase_add _ _ (Finset.mem_univ r)).symm
        _ = _ := add_comm _ _
    rw [hsplit] at hαsum
    have hcomm :
        (∑ q ∈ Finset.univ.erase r, α q • N.reactionVector q) +
          α r • N.reactionVector r = 0 := by
      rw [add_comm]
      exact hαsum
    exact eq_neg_of_add_eq_zero_left hcomm
  have hscaled :
      (∑ q ∈ Finset.univ.erase r, (α q / α r) • N.reactionVector q) =
        (α r)⁻¹ • ∑ q ∈ Finset.univ.erase r, α q • N.reactionVector q := by
    rw [Finset.smul_sum]
    apply Finset.sum_congr rfl
    intro q hq
    simp only [div_eq_mul_inv, smul_smul]
    congr 1
    ring
  have hrepresentation :
      (∑ q ∈ Finset.univ.erase r, (α q / α r) • N.reactionVector q) =
        -N.reactionVector r := by
    rw [hscaled, hsumRest]
    simp [smul_neg, smul_smul, inv_mul_cancel₀ hrpos.ne']
  have hsumMem :
      (∑ q ∈ Finset.univ.erase r, (α q / α r) • N.reactionVector q) ∈
        N.reactionCone := by
    refine Submodule.sum_mem _ fun q hq => ?_
    apply PointedCone.smul_mem
    · exact div_nonneg (le_of_lt (hαpos q)) (le_of_lt hrpos)
    · exact N.reactionVector_mem_reactionCone q
  rwa [hrepresentation] at hsumMem

/-- The reaction cone of a consistent network contains the lineality generated by its reaction
vectors, hence contains the whole stoichiometric subspace. -/
theorem stoichSubspace_le_reactionCone_of_isConsistent
    (N : Network S) (hcons : N.IsConsistent) :
    (N.stoichSubspace : PointedCone ℝ (S → ℝ)) ≤ N.reactionCone := by
  have hlineal : N.stoichSubspace ≤ N.reactionCone.lineal := by
    rw [stoichSubspace, Submodule.span_le]
    rintro v ⟨r, rfl⟩
    exact PointedCone.mem_lineal.mpr
      ⟨N.reactionVector_mem_reactionCone r,
        N.neg_reactionVector_mem_reactionCone_of_isConsistent hcons r⟩
  intro x hx
  exact (PointedCone.mem_lineal.mp (hlineal hx)).1

/-- Weak reversibility makes the reaction cone exactly the stoichiometric subspace. Every
stoichiometric direction is a conical combination of reaction vectors because positive circulation
puts both signs of each reaction vector in the cone. -/
theorem reactionCone_eq_stoichSubspace_of_weaklyReversible
    (N : Network S) (hwr : N.WeaklyReversible) :
    N.reactionCone = (N.stoichSubspace : PointedCone ℝ (S → ℝ)) := by
  have hcons : N.IsConsistent := N.isConsistent_of_weaklyReversible hwr
  apply le_antisymm
  · rw [reactionCone, generatedCone]
    simpa [stoichSubspace, Network.reactionVectors] using
      (PointedCone.hull_le_span ℝ (Set.range N.reactionVector))
  · exact N.stoichSubspace_le_reactionCone_of_isConsistent hcons

end Network
end CRNT
