import CRNT.Dynamics.TierDirectionFeasibility
import CRNT.Dynamics.TierLyapunov
import CRNT.LinearAlgebra.OrthogonalComplement
import Mathlib.Analysis.InnerProductSpace.Projection.FiniteDimensional
import Mathlib.Order.Filter.CountableInter

/-!
# Orthogonal-projection proof of the tier-direction lemma

For a finite network, every tier sequence admits one real linear functional that realizes its
asymptotic tier preorder exactly.  This is the finite-dimensional compactness step needed in the
strongly-endotactic/tier characterization.

The proof avoids choosing a single normalized limit of `log x_n`, which is insufficient for
multiscale sequences.  Instead:

1. let `L` be the span of all exponent differences between same-tier complexes;
2. pair `log x_n` with every vector in `L`; these pairings are eventually bounded because each
   same-tier monomial ratio converges to a positive finite constant;
3. subtract the orthogonal projection of `log x_n` onto `L`;
4. the residual is exactly orthogonal to all same-tier differences;
5. for every strict tier difference the original log pairing tends to `-∞`, while the projected
   correction is eventually bounded, so the residual pairing is eventually strictly negative;
6. there are only finitely many occurring complex pairs, hence one sufficiently late residual
   realizes all comparisons simultaneously.

This supplies the direction witness directly; the rational feasibility system from
`TierDirectionFeasibility` becomes a downstream finite certificate rather than an assumption.
-/

open Filter
open scoped BigOperators Topology

namespace CRNT
namespace Network

variable {S : Type} [DecidableEq S] [Fintype S]

private abbrev TierEuclid (S : Type) [Fintype S] := EuclideanSpace ℝ S

/-- Log-concentration vector, placed in Euclidean space so orthogonal projection is available. -/
noncomputable def tierLogEuclid (xs : ℕ → Concentration S) (n : ℕ) : TierEuclid S :=
  toEuclid (fun s => Real.log (xs n s))

/-- Euclidean exponent difference `y - y'`. -/
noncomputable def tierDiffEuclid (y y' : Complex S) : TierEuclid S :=
  toEuclid (fun s => (y s : ℝ) - (y' s : ℝ))

/-- The finite set of exponent differences generated by same-tier occurring complexes. -/
noncomputable def tierSameDiffSet (N : Network S) (xs : ℕ → Concentration S) : Set (TierEuclid S) :=
  {d | ∃ y : Complex S, y ∈ N.complexes ∧
      ∃ y' : Complex S, y' ∈ N.complexes ∧
        TierSame xs y y' ∧ d = tierDiffEuclid y y'}

/-- Linear span of all same-tier exponent differences. -/
noncomputable def tierSameSpan (N : Network S) (xs : ℕ → Concentration S) :
    Submodule ℝ (TierEuclid S) :=
  Submodule.span ℝ (N.tierSameDiffSet xs)

/-- A same-tier exponent difference belongs to `tierSameSpan`. -/
theorem tierDiffEuclid_mem_tierSameSpan (N : Network S) {xs : ℕ → Concentration S}
    {y y' : Complex S} (hy : y ∈ N.complexes) (hy' : y' ∈ N.complexes)
    (hsame : TierSame xs y y') : tierDiffEuclid y y' ∈ N.tierSameSpan xs := by
  apply Submodule.subset_span
  exact ⟨y, hy, y', hy', hsame, rfl⟩

/-- Pairing a complex difference with `log x` is the log of the corresponding monomial ratio. -/
theorem inner_tierDiffEuclid_tierLogEuclid (N : Network S) {xs : ℕ → Concentration S}
    (hpos : PositiveSequence xs) (n : ℕ) (y y' : Complex S) :
    @inner ℝ (TierEuclid S) _ (tierDiffEuclid y y') (tierLogEuclid xs n) =
      Real.log (tierMonomial (xs n) y / tierMonomial (xs n) y') := by
  rw [tierDiffEuclid, tierLogEuclid, inner_toEuclid]
  have hypos : 0 < tierMonomial (xs n) y := by
    simpa [tierMonomial_eq_massActionMonomial] using
      Complex.massActionMonomial_pos (hpos n) y
  have hy'pos : 0 < tierMonomial (xs n) y' := by
    simpa [tierMonomial_eq_massActionMonomial] using
      Complex.massActionMonomial_pos (hpos n) y'
  rw [Real.log_div hypos.ne' hy'pos.ne', log_tierMonomial (hpos n),
    log_tierMonomial (hpos n), ← Finset.sum_sub_distrib]
  apply Finset.sum_congr rfl
  intro s _
  ring

/-- Potential difference is the Euclidean pairing with the exponent-difference vector. -/
theorem complexWValue_sub_eq_inner_tierDiffEuclid (w : TierEuclid S)
    (y y' : Complex S) :
    complexWValue (fun s => w s) y - complexWValue (fun s => w s) y' =
      @inner ℝ (TierEuclid S) _ (tierDiffEuclid y y') w := by
  -- `inner_toEuclid` matches `inner (toEuclid _) (toEuclid _)`, but only the left argument is
  -- in that form here; put `w` in it first (`toEuclid` is the identity on coordinates).
  rw [tierDiffEuclid]
  have hw : (toEuclid fun s => w.ofLp s) = w := by ext s; rfl
  rw [← hw, inner_toEuclid]
  simp only [complexWValue, dotProduct, exponentVector]
  rw [← Finset.sum_sub_distrib]
  apply Finset.sum_congr rfl
  intro s _
  rw [hw]
  ring

/-- Eventual boundedness of pairing against the log sequence.  This is a submodule: finite linear
combinations of directions whose log-pairings are eventually bounded remain eventually bounded. -/
def EventuallyBoundedLogPairing (xs : ℕ → Concentration S) (v : TierEuclid S) : Prop :=
  ∃ C : ℝ, 0 ≤ C ∧
    ∀ᶠ n in atTop, |@inner ℝ (TierEuclid S) _ v (tierLogEuclid xs n)| ≤ C

/-- Directions with eventually bounded log pairing form a real subspace. -/
noncomputable def eventuallyBoundedLogPairingSubmodule (xs : ℕ → Concentration S) :
    Submodule ℝ (TierEuclid S) where
  carrier := {v | EventuallyBoundedLogPairing xs v}
  zero_mem' := by
    refine ⟨0, le_rfl, ?_⟩
    exact Filter.Eventually.of_forall (fun n => by simp)
  add_mem' := by
    intro u v hu hv
    obtain ⟨Cu, hCu, hu⟩ := hu
    obtain ⟨Cv, hCv, hv⟩ := hv
    refine ⟨Cu + Cv, add_nonneg hCu hCv, ?_⟩
    filter_upwards [hu, hv] with n hun hvn
    rw [inner_add_left]
    calc
      |@inner ℝ (TierEuclid S) _ u (tierLogEuclid xs n) +
          @inner ℝ (TierEuclid S) _ v (tierLogEuclid xs n)|
          ≤ |@inner ℝ (TierEuclid S) _ u (tierLogEuclid xs n)| +
              |@inner ℝ (TierEuclid S) _ v (tierLogEuclid xs n)| := abs_add_le _ _
      _ ≤ Cu + Cv := add_le_add hun hvn
  smul_mem' := by
    intro a v hv
    obtain ⟨C, hC, hv⟩ := hv
    refine ⟨|a| * C, mul_nonneg (abs_nonneg a) hC, ?_⟩
    filter_upwards [hv] with n hn
    simp only [inner_smul_left, RCLike.conj_to_real, abs_mul]
    exact mul_le_mul_of_nonneg_left hn (abs_nonneg a)

/-- A convergent real sequence is eventually bounded in absolute value, with an explicit coarse
bound. -/
theorem eventually_abs_le_of_tendsto_real {f : ℕ → ℝ} {a : ℝ}
    (h : Tendsto f atTop (𝓝 a)) :
    ∃ C : ℝ, 0 ≤ C ∧ ∀ᶠ n in atTop, |f n| ≤ C := by
  let C : ℝ := |a| + 1
  have hC : 0 ≤ C := by dsimp [C]; positivity
  have hball : Metric.ball a 1 ∈ 𝓝 a := Metric.ball_mem_nhds a zero_lt_one
  have hev : ∀ᶠ n in atTop, f n ∈ Metric.ball a 1 := h hball
  refine ⟨C, hC, ?_⟩
  filter_upwards [hev] with n hn
  rw [Metric.mem_ball, Real.dist_eq] at hn
  calc
    |f n| = |(f n - a) + a| := by ring_nf
    _ ≤ |f n - a| + |a| := abs_add_le _ _
    _ ≤ |a| + 1 := by linarith
    _ = C := rfl

/-- Same-tier exponent differences have eventually bounded log pairing. -/
theorem tierDiffEuclid_eventuallyBounded_of_tierSame (N : Network S)
    {xs : ℕ → Concentration S} (hpos : PositiveSequence xs)
    {y y' : Complex S} (hsame : TierSame xs y y') :
    EventuallyBoundedLogPairing xs (tierDiffEuclid y y') := by
  obtain ⟨c, hc, hratio⟩ := hsame
  have hlog : Tendsto
      (fun n => Real.log (tierMonomial (xs n) y / tierMonomial (xs n) y'))
      atTop (𝓝 (Real.log c)) := hratio.log hc.ne'
  have hinner : Tendsto
      (fun n => @inner ℝ (TierEuclid S) _ (tierDiffEuclid y y') (tierLogEuclid xs n))
      atTop (𝓝 (Real.log c)) := by
    apply hlog.congr'
    exact Filter.Eventually.of_forall (fun n =>
      (N.inner_tierDiffEuclid_tierLogEuclid hpos n y y').symm)
  exact eventually_abs_le_of_tendsto_real hinner

/-- Every vector in the span of same-tier differences has eventually bounded log pairing. -/
theorem tierSameSpan_le_eventuallyBounded (N : Network S) {xs : ℕ → Concentration S}
    (hpos : PositiveSequence xs) :
    N.tierSameSpan xs ≤ eventuallyBoundedLogPairingSubmodule xs := by
  apply Submodule.span_le.2
  intro d hd
  rcases hd with ⟨y, hy, y', hy', hsame, rfl⟩
  exact N.tierDiffEuclid_eventuallyBounded_of_tierSame hpos hsame

/-- Strictly lower tiers have log-monomial pairing tending to `-∞`. -/
theorem tendsto_inner_tierDiffEuclid_tierLogEuclid_atBot (N : Network S)
    {xs : ℕ → Concentration S} (hpos : PositiveSequence xs)
    {y y' : Complex S} (hbelow : TierStrictBelow xs y y') :
    Tendsto
      (fun n => @inner ℝ (TierEuclid S) _ (tierDiffEuclid y y') (tierLogEuclid xs n))
      atTop atBot := by
  let q : ℕ → ℝ := fun n => tierMonomial (xs n) y / tierMonomial (xs n) y'
  have hqpos : ∀ᶠ n in atTop, q n ∈ Set.Ioi (0 : ℝ) := by
    exact Filter.Eventually.of_forall (fun n => by
      have hypos : 0 < tierMonomial (xs n) y := by
        simpa [tierMonomial_eq_massActionMonomial] using
          Complex.massActionMonomial_pos (hpos n) y
      have hy'pos : 0 < tierMonomial (xs n) y' := by
        simpa [tierMonomial_eq_massActionMonomial] using
          Complex.massActionMonomial_pos (hpos n) y'
      exact div_pos hypos hy'pos)
  have hq : Tendsto q atTop (𝓝[>] (0 : ℝ)) :=
    tendsto_nhdsWithin_iff.mpr ⟨hbelow, hqpos⟩
  have hlog : Tendsto (fun n => Real.log (q n)) atTop atBot :=
    Real.tendsto_log_nhdsGT_zero.comp hq
  apply hlog.congr'
  exact Filter.Eventually.of_forall (fun n =>
    (N.inner_tierDiffEuclid_tierLogEuclid hpos n y y').symm)

/-- The orthogonal residual of `log x_n` after removing its same-tier-span component. -/
noncomputable def projectedTierLogDirection (N : Network S)
    (xs : ℕ → Concentration S) (n : ℕ) : TierEuclid S :=
  tierLogEuclid xs n - (N.tierSameSpan xs).starProjection (tierLogEuclid xs n)

/-- Every projected direction is exactly orthogonal to all same-tier differences. -/
theorem inner_tierDiff_projected_eq_zero_of_tierSame (N : Network S)
    {xs : ℕ → Concentration S} {y y' : Complex S}
    (hy : y ∈ N.complexes) (hy' : y' ∈ N.complexes)
    (hsame : TierSame xs y y') (n : ℕ) :
    @inner ℝ (TierEuclid S) _ (tierDiffEuclid y y')
      (N.projectedTierLogDirection xs n) = 0 := by
  have hd : tierDiffEuclid y y' ∈ N.tierSameSpan xs :=
    N.tierDiffEuclid_mem_tierSameSpan hy hy' hsame
  exact Submodule.inner_right_of_mem_orthogonal hd
    ((N.tierSameSpan xs).sub_starProjection_mem_orthogonal (tierLogEuclid xs n))

/-- For each strict tier comparison, the projected direction eventually gives a strict negative
pairing.  The correction term is bounded because the projection of the fixed exponent difference
lies in the same-tier span. -/
theorem eventually_inner_projected_lt_zero_of_tierStrictBelow (N : Network S)
    {xs : ℕ → Concentration S} (hpos : PositiveSequence xs)
    {y y' : Complex S} (hbelow : TierStrictBelow xs y y') :
    ∀ᶠ n in atTop,
      @inner ℝ (TierEuclid S) _ (tierDiffEuclid y y')
        (N.projectedTierLogDirection xs n) < 0 := by
  let L : Submodule ℝ (TierEuclid S) := N.tierSameSpan xs
  let d : TierEuclid S := tierDiffEuclid y y'
  have hPd_mem : L.starProjection d ∈ L := L.starProjection_apply_mem d
  have hspan : L ≤ eventuallyBoundedLogPairingSubmodule xs :=
    N.tierSameSpan_le_eventuallyBounded hpos
  obtain ⟨C, hC, hbounded⟩ := hspan hPd_mem
  have hstrict : Tendsto
      (fun n => @inner ℝ (TierEuclid S) _ d (tierLogEuclid xs n)) atTop atBot := by
    simpa [d] using N.tendsto_inner_tierDiffEuclid_tierLogEuclid_atBot hpos hbelow
  have hsmall : ∀ᶠ n in atTop,
      @inner ℝ (TierEuclid S) _ d (tierLogEuclid xs n) ≤ -C - 1 :=
    tendsto_atBot.1 hstrict (-C - 1)
  filter_upwards [hbounded, hsmall] with n hbn hsn
  have hcorr : -C ≤ @inner ℝ (TierEuclid S) _ (L.starProjection d) (tierLogEuclid xs n) :=
    (abs_le.mp hbn).1
  have hselfadj :
      @inner ℝ (TierEuclid S) _ d (L.starProjection (tierLogEuclid xs n)) =
        @inner ℝ (TierEuclid S) _ (L.starProjection d) (tierLogEuclid xs n) := by
    symm
    exact L.inner_starProjection_left_eq_right d (tierLogEuclid xs n)
  change @inner ℝ (TierEuclid S) _ d
      (tierLogEuclid xs n - L.starProjection (tierLogEuclid xs n)) < 0
  rw [inner_sub_right, hselfadj]
  linarith

/-- All strict comparisons on the finite network hold simultaneously for sufficiently large
projected-log directions. -/
theorem eventually_all_strict_tier_pairs_projected (N : Network S)
    {xs : ℕ → Concentration S} (htier : N.IsTierSequence xs) :
    ∀ᶠ n in atTop,
      ∀ y ∈ N.complexes, ∀ y' ∈ N.complexes,
        TierStrictBelow xs y y' →
          @inner ℝ (TierEuclid S) _ (tierDiffEuclid y y')
            (N.projectedTierLogDirection xs n) < 0 := by
  have hpairs : ∀ p : Complex S × Complex S, p ∈ N.complexes ×ˢ N.complexes →
      ∀ᶠ n in atTop,
        TierStrictBelow xs p.1 p.2 →
          @inner ℝ (TierEuclid S) _ (tierDiffEuclid p.1 p.2)
            (N.projectedTierLogDirection xs n) < 0 := by
    intro p hp
    by_cases hbelow : TierStrictBelow xs p.1 p.2
    · exact (N.eventually_inner_projected_lt_zero_of_tierStrictBelow htier.1 hbelow).mono
        (fun n hn _ => hn)
    · exact Filter.Eventually.of_forall (fun _ h => (hbelow h).elim)
  have hall := (Filter.eventually_all_finset (N.complexes ×ˢ N.complexes)).2 hpairs
  filter_upwards [hall] with n hn
  intro y hy y' hy' hbelow
  exact hn (y, y') (by simp [hy, hy']) hbelow

/-- A sufficiently late projected log vector realizes the entire tier preorder exactly. -/
theorem exists_projectedTierDirection_realizes (N : Network S)
    {xs : ℕ → Concentration S} (htier : N.IsTierSequence xs) :
    ∃ n : ℕ, N.TierRealizesDirection xs
      (fun s => (N.projectedTierLogDirection xs n) s) := by
  have hev := N.eventually_all_strict_tier_pairs_projected htier
  obtain ⟨n, hn⟩ := hev.exists
  refine ⟨n, ?_⟩
  constructor
  · intro y hy y' hy'
    constructor
    · intro hsame
      have hzero := N.inner_tierDiff_projected_eq_zero_of_tierSame hy hy' hsame n
      rw [← complexWValue_sub_eq_inner_tierDiffEuclid
        (N.projectedTierLogDirection xs n) y y'] at hzero
      linarith
    · intro heq
      rcases htier.2.2 y hy y' hy' with hle | hrev
      · rcases hle with hbelow | hsame
        · have hneg := hn y hy y' hy' hbelow
          rw [← complexWValue_sub_eq_inner_tierDiffEuclid
            (N.projectedTierLogDirection xs n) y y'] at hneg
          linarith
        · exact hsame
      · have hneg := hn y' hy' y hy hrev
        rw [← complexWValue_sub_eq_inner_tierDiffEuclid
          (N.projectedTierLogDirection xs n) y' y] at hneg
        linarith
  · intro y hy y' hy'
    constructor
    · intro hbelow
      have hneg := hn y hy y' hy' hbelow
      rw [← complexWValue_sub_eq_inner_tierDiffEuclid
        (N.projectedTierLogDirection xs n) y y'] at hneg
      linarith
    · intro hlt
      rcases htier.2.2 y hy y' hy' with hle | hrev
      · rcases hle with hbelow | hsame
        · exact hbelow
        · have hzero := N.inner_tierDiff_projected_eq_zero_of_tierSame hy hy' hsame n
          rw [← complexWValue_sub_eq_inner_tierDiffEuclid
            (N.projectedTierLogDirection xs n) y y'] at hzero
          linarith
      · have hneg := hn y' hy' y hy hrev
        rw [← complexWValue_sub_eq_inner_tierDiffEuclid
          (N.projectedTierLogDirection xs n) y' y] at hneg
        linarith

/-- **Tier-direction lemma, completed.** Every tier sequence on a finite network admits one exact
linear direction witness.  In particular every transversal tier sequence does. -/
theorem hasTierDirectionWitness (N : Network S) {xs : ℕ → Concentration S}
    (htier : N.IsTierSequence xs) : N.HasTierDirectionWitness xs := by
  obtain ⟨n, hn⟩ := N.exists_projectedTierDirection_realizes htier
  exact ⟨fun s => (N.projectedTierLogDirection xs n) s, hn⟩

/-- The old transversal witness premise is now unconditional. -/
theorem everyTransversalTierSequenceHasDirectionWitness (N : Network S) :
    N.EveryTransversalTierSequenceHasDirectionWitness := by
  intro xs htrans
  exact N.hasTierDirectionWitness htrans.1

/-- **Completed hard direction of the structural characterization.** -/
theorem StronglyEndotacticStd.tierDescending {N : Network S}
    (hse : N.StronglyEndotacticStd) : N.TierDescending :=
  hse.tierDescending_of_directionWitnesses N.everyTransversalTierSequenceHasDirectionWitness

/-- **Strong endotacticity is equivalent to the tier-descending property.** -/
theorem stronglyEndotacticStd_iff_tierDescending (N : Network S) :
    N.StronglyEndotacticStd ↔ N.TierDescending :=
  ⟨StronglyEndotacticStd.tierDescending, TierDescending.stronglyEndotacticStd⟩

end Network
end CRNT
