import CRNT.Geometry.FanFaceLattice

/-!
# Toric barrier trapping for complex-balanced mass-action systems

This module assembles the analytic half of Craciun v3 Theorem B for the systems the Global
Attractor Theorem needs.  Everything is proved; the *only* input left unconstructed is the §7
blueprint data — the tiles, their normals, and their levels.

## The pieces being joined

* `CRNT.Network.inner_euclideanMassActionField_nonneg` (in `CRNT.Geometry.FanFaceLattice`): if a
  vector `n` lies in every cone of the source-order fan within `δ` of the relative-log state of a
  positive point `x`, then `0 ≤ ⟪n, euclideanMassActionField κ x⟫`.  This is Craciun's Remark 4.5
  composed with the embedding of Theorem 3.1.
* `CRNT.PolyhedralBarrier.barrier_le_of_local_descent` and
  `CRNT.PolyhedralBarrier.minMaxBarrier_le_of_local_descent`: a polyhedral region — convex or not
  — traps a forward trajectory as soon as the pieces active at the boundary level are
  nonincreasing along the velocity.

The missing link was coordinates.  A mass-action trajectory lives in `Concentration S`, while the
fan and the barrier live in the intrinsic Euclidean stoichiometric space
`N.euclideanStoichSubspace`.  `Network.euclideanStoichState` transports the state, and
`Network.hasDerivAt_euclideanStoichState` is the chain rule saying its velocity is exactly
`Network.euclideanMassActionField`: the orthogonal projection is a continuous linear map, and it
fixes the mass-action velocity because that velocity already lies in the stoichiometric subspace.

## What a caller still has to supply

Only `hnear`: for each piece `i` of the barrier, at every point of the trajectory where piece `i`
is *active* and the barrier has reached the level `R`, the normal `n i` must lie in every cone of
the fan within `δ` of the relative-log state.  `Network.deltaCore_mem` says the canonical source of
such a normal — the δ-core — is itself a cone of the fan, so what remains is the combinatorial
choice of tiles and levels, not any further analysis.

Note the barrier normals are the negatives of the fan vectors: `toricField` is generated by
`coneDual` (nonnegative inner product) while a barrier must decrease.  See
`CRNT.Geometry.FanFaceLattice`.

Convexity is not available in general — see `CRNT.Geometry.ConvexBarrierObstruction` — so the
min-max form below is the one a blueprint should target.

Nothing here is an axiom or a `sorry`.

Depends on: `CRNT.Geometry.FanFaceLattice`.
-/

namespace CRNT
namespace Network

open scoped RealInnerProductSpace

variable {S : Type} [DecidableEq S] [Fintype S]

/-! ### Transporting the state and the ODE -/

/-- The state, transported into the intrinsic Euclidean stoichiometric space: the orthogonal
projection of `toEuclid x` onto `N.euclideanStoichSubspace`.  The barrier is a function of this. -/
noncomputable def euclideanStoichState (N : Network S) (x : Concentration S) :
    N.euclideanStoichSubspace :=
  N.euclideanStoichSubspace.orthogonalProjectionOnto
    ((CRNT.toEuclid.toLinearMap.toContinuousLinearMap : (S → ℝ) →L[ℝ] EuclideanSpace ℝ S) x)

/-- The transport map, packaged as a continuous linear map. -/
noncomputable def euclideanStoichStateL (N : Network S) :
    (S → ℝ) →L[ℝ] N.euclideanStoichSubspace :=
  N.euclideanStoichSubspace.orthogonalProjectionOnto ∘L
    (CRNT.toEuclid.toLinearMap.toContinuousLinearMap : (S → ℝ) →L[ℝ] EuclideanSpace ℝ S)

@[simp] theorem euclideanStoichStateL_apply (N : Network S) (x : Concentration S) :
    N.euclideanStoichStateL x = N.euclideanStoichState x := rfl

/-- The transport map fixes the mass-action velocity: since that velocity lies in the
stoichiometric subspace, projecting it is the identity, so it transports to
`Network.euclideanMassActionField`. -/
theorem euclideanStoichStateL_massActionVectorField (N : Network S) (κ : N.RateConstants)
    (x : Concentration S) :
    N.euclideanStoichStateL (N.massActionVectorField κ x) = N.euclideanMassActionField κ x := by
  have hmem : CRNT.toEuclid (N.massActionVectorField κ x) ∈ N.euclideanStoichSubspace := by
    rw [Network.euclideanStoichSubspace, Submodule.mem_map]
    exact ⟨N.massActionVectorField κ x, N.massActionVectorField_mem_stoichSubspace κ x, rfl⟩
  exact N.euclideanStoichSubspace.orthogonalProjectionOnto_mem_subspace_eq_self
    (⟨CRNT.toEuclid (N.massActionVectorField κ x), hmem⟩ : N.euclideanStoichSubspace)

/-- **The transported trajectory solves the transported ODE.**  Chain rule through the continuous
linear transport map, using that it fixes the mass-action velocity. -/
theorem hasDerivAt_euclideanStoichState (N : Network S) (κ : N.RateConstants)
    {Γ : ℝ → Concentration S} {t : ℝ}
    (hΓ : HasDerivAt Γ (N.massActionVectorField κ (Γ t)) t) :
    HasDerivAt (fun s => N.euclideanStoichState (Γ s)) (N.euclideanMassActionField κ (Γ t)) t := by
  have h := (N.euclideanStoichStateL).hasFDerivAt.comp_hasDerivAt t hΓ
  rw [euclideanStoichStateL_massActionVectorField] at h
  exact h

theorem continuous_euclideanStoichState_comp (N : Network S) {Γ : ℝ → Concentration S}
    (hΓ : Continuous Γ) : Continuous fun t => N.euclideanStoichState (Γ t) :=
  (N.euclideanStoichStateL).continuous.comp hΓ

/-- The transported trajectory is continuous wherever the trajectory is.  Only continuity on
`Set.Ici 0` is available from a forward solution, which is what the trapping theorems now ask
for. -/
theorem continuousOn_euclideanStoichState_comp (N : Network S) {Γ : ℝ → Concentration S}
    {A : Set ℝ} (hΓ : ContinuousOn Γ A) :
    ContinuousOn (fun t => N.euclideanStoichState (Γ t)) A :=
  (N.euclideanStoichStateL).continuous.comp_continuousOn hΓ

/-! ### Trapping, convex form -/

variable {ι : Type*} [Fintype ι] [Nonempty ι]

/-- **A polyhedral barrier whose normals lie in the nearby fan cones traps a complex-balanced
mass-action trajectory.**

`hnear` is the only geometric input: wherever piece `i` is the active one and the barrier has
reached `R`, the fan vector `n i` lies in every cone of `N.relativeSourceOrderNegativeStoichFan`
within `δ` of the relative-log state.  Nothing is assumed about inactive pieces, and nothing at
all at times where the barrier is below `R`.

This is the analytic half of Craciun v3 Theorem B for complex-balanced mass action. -/
theorem barrier_le_of_toric_descent (N : Network S) (κ : N.RateConstants)
    {xstar : Concentration S} (hxs : xstar.Positive) (hcb : N.IsComplexBalanced κ xstar)
    {δ : ℝ} (hδ : 0 < δ)
    {n : ι → N.euclideanStoichSubspace} {b : ι → ℝ} {R : ℝ}
    {Γ : ℝ → Concentration S}
    (hΓcont : ContinuousOn Γ (Set.Ici 0))
    (hΓpos : ∀ t, 0 ≤ t → (Γ t).Positive)
    (hΓd : ∀ t, 0 ≤ t → HasDerivAt Γ (N.massActionVectorField κ (Γ t)) t)
    (hstart : PolyhedralBarrier.barrier (fun i => innerSL ℝ (-n i)) b
      (N.euclideanStoichState (Γ 0)) ≤ R)
    (hnear : ∀ t, 0 ≤ t →
      R ≤ PolyhedralBarrier.barrier (fun i => innerSL ℝ (-n i)) b
        (N.euclideanStoichState (Γ t)) →
      ∀ i : ι,
        innerSL ℝ (-n i) (N.euclideanStoichState (Γ t)) - b i
          = PolyhedralBarrier.barrier (fun i => innerSL ℝ (-n i)) b
              (N.euclideanStoichState (Γ t)) →
        ∀ C ∈ N.relativeSourceOrderNegativeStoichFan,
          Metric.infDist (N.relativeLogFanState xstar (Γ t))
            (C : Set N.euclideanStoichSubspace) < δ → n i ∈ C) :
    ∀ t, 0 ≤ t →
      PolyhedralBarrier.barrier (fun i => innerSL ℝ (-n i)) b
        (N.euclideanStoichState (Γ t)) ≤ R := by
  refine PolyhedralBarrier.barrier_le_of_local_descent
    (v := fun t => N.euclideanMassActionField κ (Γ t))
    (N.continuousOn_euclideanStoichState_comp hΓcont)
    (fun t ht => N.hasDerivAt_euclideanStoichState κ (hΓd t ht)) hstart ?_
  intro t ht hlevel i hactive
  have hfield : 0 ≤ ⟪n i, N.euclideanMassActionField κ (Γ t)⟫ :=
    N.inner_euclideanMassActionField_nonneg κ (hΓpos t ht) hxs hcb hδ
      (hnear t ht hlevel i hactive)
  have hneg : innerSL ℝ (-n i) (N.euclideanMassActionField κ (Γ t))
      = -⟪n i, N.euclideanMassActionField κ (Γ t)⟫ := by
    simp [innerSL_apply_apply]
  rw [hneg]
  linarith

/-- **Band form for complex-balanced mass action.**  The fan condition is required only while the
barrier lies in `[R, R']`.

This is the form a blueprint should target.  The side conditions of `hnear` — coordinate floors and
the off-face bound — are only available *inside* the guarded region, so requiring them wherever
`R ≤ barrier` would mean establishing them at points the argument has not yet excluded.  Confining
the requirement to the band `[R, R']` breaks that circularity: it suffices that they hold on
`{barrier ≤ R'}`. -/
theorem barrier_le_of_toric_descent_in_band (N : Network S) (κ : N.RateConstants)
    {xstar : Concentration S} (hxs : xstar.Positive) (hcb : N.IsComplexBalanced κ xstar)
    {δ : ℝ} (hδ : 0 < δ)
    {n : ι → N.euclideanStoichSubspace} {b : ι → ℝ} {R R' : ℝ} (hRR' : R < R')
    {Γ : ℝ → Concentration S}
    (hΓcont : ContinuousOn Γ (Set.Ici 0))
    (hΓpos : ∀ t, 0 ≤ t → (Γ t).Positive)
    (hΓd : ∀ t, 0 ≤ t → HasDerivAt Γ (N.massActionVectorField κ (Γ t)) t)
    (hstart : PolyhedralBarrier.barrier (fun i => innerSL ℝ (-n i)) b
      (N.euclideanStoichState (Γ 0)) ≤ R)
    (hnear : ∀ t, 0 ≤ t →
      R ≤ PolyhedralBarrier.barrier (fun i => innerSL ℝ (-n i)) b
        (N.euclideanStoichState (Γ t)) →
      PolyhedralBarrier.barrier (fun i => innerSL ℝ (-n i)) b
        (N.euclideanStoichState (Γ t)) ≤ R' →
      ∀ i : ι,
        innerSL ℝ (-n i) (N.euclideanStoichState (Γ t)) - b i
          = PolyhedralBarrier.barrier (fun i => innerSL ℝ (-n i)) b
              (N.euclideanStoichState (Γ t)) →
        ∀ C ∈ N.relativeSourceOrderNegativeStoichFan,
          Metric.infDist (N.relativeLogFanState xstar (Γ t))
            (C : Set N.euclideanStoichSubspace) < δ → n i ∈ C) :
    ∀ t, 0 ≤ t →
      PolyhedralBarrier.barrier (fun i => innerSL ℝ (-n i)) b
        (N.euclideanStoichState (Γ t)) ≤ R := by
  refine PolyhedralBarrier.barrier_le_of_local_descent_in_band hRR'
    (v := fun t => N.euclideanMassActionField κ (Γ t))
    (N.continuousOn_euclideanStoichState_comp hΓcont)
    (fun t ht => N.hasDerivAt_euclideanStoichState κ (hΓd t ht)) hstart ?_
  intro t ht hlevel hband i hactive
  have hfield : 0 ≤ ⟪n i, N.euclideanMassActionField κ (Γ t)⟫ :=
    N.inner_euclideanMassActionField_nonneg κ (hΓpos t ht) hxs hcb hδ
      (hnear t ht hlevel hband i hactive)
  have hneg : innerSL ℝ (-n i) (N.euclideanMassActionField κ (Γ t))
      = -⟪n i, N.euclideanMassActionField κ (Γ t)⟫ := by
    simp [innerSL_apply_apply]
  rw [hneg]
  linarith

/-! ### Trapping, non-convex form -/

variable {ι' : Type*} [Fintype ι'] [Nonempty ι']

/-- **The non-convex version: a minimum of polyhedral barriers, one branch per tile.**

At a time where the level is reached it suffices that *one* branch attaining the minimum has all
of its active pieces' normals in the nearby fan cones.  Because a globally homogeneous convex
barrier is impossible in dimension `≥ 3`
(`CRNT.Geometry.ConvexBarrierObstruction.not_exists_weights_vector`), this — not
`barrier_le_of_toric_descent` — is the statement a §7 blueprint should be built to feed. -/
theorem minMaxBarrier_le_of_toric_descent (N : Network S) (κ : N.RateConstants)
    {xstar : Concentration S} (hxs : xstar.Positive) (hcb : N.IsComplexBalanced κ xstar)
    {δ : ℝ} (hδ : 0 < δ)
    {n : ι' → ι → N.euclideanStoichSubspace} {b : ι' → ι → ℝ} {R : ℝ}
    {Γ : ℝ → Concentration S}
    (hΓcont : ContinuousOn Γ (Set.Ici 0))
    (hΓpos : ∀ t, 0 ≤ t → (Γ t).Positive)
    (hΓd : ∀ t, 0 ≤ t → HasDerivAt Γ (N.massActionVectorField κ (Γ t)) t)
    (hstart : PolyhedralBarrier.minMaxBarrier (fun k i => innerSL ℝ (-n k i)) b
      (N.euclideanStoichState (Γ 0)) ≤ R)
    (hnear : ∀ t, 0 ≤ t →
      R ≤ PolyhedralBarrier.minMaxBarrier (fun k i => innerSL ℝ (-n k i)) b
        (N.euclideanStoichState (Γ t)) →
      ∃ k : ι',
        PolyhedralBarrier.barrier (fun i => innerSL ℝ (-n k i)) (b k)
            (N.euclideanStoichState (Γ t))
          = PolyhedralBarrier.minMaxBarrier (fun k i => innerSL ℝ (-n k i)) b
              (N.euclideanStoichState (Γ t)) ∧
        ∀ i : ι,
          innerSL ℝ (-n k i) (N.euclideanStoichState (Γ t)) - b k i
            = PolyhedralBarrier.barrier (fun i => innerSL ℝ (-n k i)) (b k)
                (N.euclideanStoichState (Γ t)) →
          ∀ C ∈ N.relativeSourceOrderNegativeStoichFan,
            Metric.infDist (N.relativeLogFanState xstar (Γ t))
              (C : Set N.euclideanStoichSubspace) < δ → n k i ∈ C) :
    ∀ t, 0 ≤ t →
      PolyhedralBarrier.minMaxBarrier (fun k i => innerSL ℝ (-n k i)) b
        (N.euclideanStoichState (Γ t)) ≤ R := by
  refine PolyhedralBarrier.minMaxBarrier_le_of_local_descent
    (v := fun t => N.euclideanMassActionField κ (Γ t))
    (N.continuousOn_euclideanStoichState_comp hΓcont)
    (fun t ht => N.hasDerivAt_euclideanStoichState κ (hΓd t ht)) hstart ?_
  intro t ht hlevel
  obtain ⟨k, hk, hact⟩ := hnear t ht hlevel
  refine ⟨k, hk, ?_⟩
  intro i hactive
  have hfield : 0 ≤ ⟪n k i, N.euclideanMassActionField κ (Γ t)⟫ :=
    N.inner_euclideanMassActionField_nonneg κ (hΓpos t ht) hxs hcb hδ (hact i hactive)
  have hneg : innerSL ℝ (-n k i) (N.euclideanMassActionField κ (Γ t))
      = -⟪n k i, N.euclideanMassActionField κ (Γ t)⟫ := by
    simp [innerSL_apply_apply]
  rw [hneg]
  linarith

/-! ### The separation conclusion -/

/-- **From trapping to a hard distance bound.**  If in addition the guarded region misses the open
`r`-ball about a point `p` of the transported space, the transported trajectory stays at distance
at least `r` from `p` for all time.  With `p` the transported image of a boundary point, this is
the persistence statement the Global Attractor Theorem consumes. -/
theorem dist_ge_of_toric_descent (N : Network S) (κ : N.RateConstants)
    {xstar : Concentration S} (hxs : xstar.Positive) (hcb : N.IsComplexBalanced κ xstar)
    {δ : ℝ} (hδ : 0 < δ)
    {n : ι' → ι → N.euclideanStoichSubspace} {b : ι' → ι → ℝ} {R r : ℝ}
    {p : N.euclideanStoichSubspace}
    {Γ : ℝ → Concentration S}
    (hΓcont : ContinuousOn Γ (Set.Ici 0))
    (hΓpos : ∀ t, 0 ≤ t → (Γ t).Positive)
    (hΓd : ∀ t, 0 ≤ t → HasDerivAt Γ (N.massActionVectorField κ (Γ t)) t)
    (hstart : PolyhedralBarrier.minMaxBarrier (fun k i => innerSL ℝ (-n k i)) b
      (N.euclideanStoichState (Γ 0)) ≤ R)
    (hnear : ∀ t, 0 ≤ t →
      R ≤ PolyhedralBarrier.minMaxBarrier (fun k i => innerSL ℝ (-n k i)) b
        (N.euclideanStoichState (Γ t)) →
      ∃ k : ι',
        PolyhedralBarrier.barrier (fun i => innerSL ℝ (-n k i)) (b k)
            (N.euclideanStoichState (Γ t))
          = PolyhedralBarrier.minMaxBarrier (fun k i => innerSL ℝ (-n k i)) b
              (N.euclideanStoichState (Γ t)) ∧
        ∀ i : ι,
          innerSL ℝ (-n k i) (N.euclideanStoichState (Γ t)) - b k i
            = PolyhedralBarrier.barrier (fun i => innerSL ℝ (-n k i)) (b k)
                (N.euclideanStoichState (Γ t)) →
          ∀ C ∈ N.relativeSourceOrderNegativeStoichFan,
            Metric.infDist (N.relativeLogFanState xstar (Γ t))
              (C : Set N.euclideanStoichSubspace) < δ → n k i ∈ C)
    (hsep : {y : N.euclideanStoichSubspace |
      PolyhedralBarrier.minMaxBarrier (fun k i => innerSL ℝ (-n k i)) b y ≤ R}
        ⊆ (Metric.ball p r)ᶜ) :
    ∀ t, 0 ≤ t → r ≤ dist (N.euclideanStoichState (Γ t)) p := by
  intro t ht
  have hmem := N.minMaxBarrier_le_of_toric_descent κ hxs hcb hδ hΓcont hΓpos hΓd hstart hnear t ht
  simpa [Metric.mem_ball, not_lt] using hsep hmem

/-! ### From trapping to the residual conclusion -/

/-- **Coordinate lower bounds from a toric barrier.**  The trapping theorem keeps the transported
trajectory inside the guarded region for all time; if the region — intersected with the positive
compatibility class of the start — is bounded away from each coordinate hyperplane, every
coordinate of the trajectory has a uniform positive floor.

`hsep` is the separation clause of Craciun's zero-separating hypersurface, condition (i) of v3
Definition 4.6: the upper region stays at positive distance from `∂ℝⁿ₊`. -/
theorem coordinate_lower_bounds_of_toric_barrier (N : Network S) (κ : N.RateConstants)
    {xstar : Concentration S} (hxs : xstar.Positive) (hcb : N.IsComplexBalanced κ xstar)
    {δ : ℝ} (hδ : 0 < δ)
    {n : ι' → ι → N.euclideanStoichSubspace} {b : ι' → ι → ℝ} {R : ℝ}
    {Γ : ℝ → Concentration S}
    (hΓcont : ContinuousOn Γ (Set.Ici 0))
    (hΓpos : ∀ t, 0 ≤ t → (Γ t).Positive)
    (hΓd : ∀ t, 0 ≤ t → HasDerivAt Γ (N.massActionVectorField κ (Γ t)) t)
    (hclass : ∀ t, 0 ≤ t → N.StoichCompatible (Γ 0) (Γ t))
    (hstart : PolyhedralBarrier.minMaxBarrier (fun k i => innerSL ℝ (-n k i)) b
      (N.euclideanStoichState (Γ 0)) ≤ R)
    (hnear : ∀ t, 0 ≤ t →
      R ≤ PolyhedralBarrier.minMaxBarrier (fun k i => innerSL ℝ (-n k i)) b
        (N.euclideanStoichState (Γ t)) →
      ∃ k : ι',
        PolyhedralBarrier.barrier (fun i => innerSL ℝ (-n k i)) (b k)
            (N.euclideanStoichState (Γ t))
          = PolyhedralBarrier.minMaxBarrier (fun k i => innerSL ℝ (-n k i)) b
              (N.euclideanStoichState (Γ t)) ∧
        ∀ i : ι,
          innerSL ℝ (-n k i) (N.euclideanStoichState (Γ t)) - b k i
            = PolyhedralBarrier.barrier (fun i => innerSL ℝ (-n k i)) (b k)
                (N.euclideanStoichState (Γ t)) →
          ∀ C ∈ N.relativeSourceOrderNegativeStoichFan,
            Metric.infDist (N.relativeLogFanState xstar (Γ t))
              (C : Set N.euclideanStoichSubspace) < δ → n k i ∈ C)
    (hsep : ∀ s : S, ∃ ε : ℝ, 0 < ε ∧ ∀ x : Concentration S, x.Positive →
      N.StoichCompatible (Γ 0) x →
      PolyhedralBarrier.minMaxBarrier (fun k i => innerSL ℝ (-n k i)) b
        (N.euclideanStoichState x) ≤ R → ε ≤ x s) :
    ∀ s : S, ∃ ε : ℝ, 0 < ε ∧ ∀ t : ℝ, 0 ≤ t → ε ≤ Γ t s := by
  intro s
  obtain ⟨ε, hε, hbound⟩ := hsep s
  refine ⟨ε, hε, fun t ht => ?_⟩
  exact hbound (Γ t) (hΓpos t ht) (hclass t ht)
    (N.minMaxBarrier_le_of_toric_descent κ hxs hcb hδ hΓcont hΓpos hΓd hstart hnear t ht)

end Network
end CRNT

section OmegaPoint

open Filter
open scoped NNReal Topology RealInnerProductSpace

namespace CRNT
namespace Network

variable {S : Type} [DecidableEq S] [Fintype S]

omit [DecidableEq S] [Fintype S] in
/-- **Uniform coordinate floors on a compact orbit give a positive ω-limit point.**

This duplicates `CRNT.Network.exists_positive_omegaPoint_of_uniform_coordinate_lower_bounds` from
`CRNT.Dynamics.GlobalAttractorTheorem`; that module sits on the frontier ledger, so it cannot be
imported into the verified core, and the statement is needed here to express the reduction below.
The two proofs are the same: the orbit lies in the closed set `{y | ε ≤ y s}`, so its closure does,
and the ω-limit set is inside that closure and nonempty by compactness. -/
theorem exists_positive_omegaPoint_of_coordinate_floors
    {ϕ : Flow ℝ≥0 (Concentration S)}
    {γ : Concentration S → ℝ → Concentration S} {x₀ : Concentration S}
    (hϕγ : ∀ x (t : ℝ≥0), ϕ t x = γ x t)
    {K : Set (Concentration S)} (hK : IsCompact K) (hmaps : ∀ t : ℝ≥0, ϕ t x₀ ∈ K)
    (hlower : ∀ s : S, ∃ ε : ℝ, 0 < ε ∧ ∀ t : ℝ, 0 ≤ t → ε ≤ γ x₀ t s) :
    ∃ p ∈ omegaLimit atTop ϕ {x₀}, p.Positive := by
  have hsubK : Set.image2 ϕ (Set.univ : Set ℝ≥0) {x₀} ⊆ K := by
    rintro z ⟨t, -, x, hx, rfl⟩
    rw [Set.mem_singleton_iff] at hx
    subst x
    exact hmaps t
  have habs : ∃ v ∈ (atTop : Filter ℝ≥0), closure (Set.image2 ϕ v {x₀}) ⊆ K :=
    ⟨Set.univ, univ_mem, (IsClosed.closure_subset_iff hK.isClosed).mpr hsubK⟩
  obtain ⟨p, hp⟩ :=
    nonempty_omegaLimit_of_isCompact_absorbing atTop ϕ {x₀} hK habs (Set.singleton_nonempty x₀)
  refine ⟨p, hp, ?_⟩
  intro s
  obtain ⟨ε, hε, hfloor⟩ := hlower s
  have hclosed : IsClosed {y : Concentration S | ε ≤ y s} :=
    isClosed_Ici.preimage (continuous_apply s)
  have horbit : Set.image2 ϕ (Set.univ : Set ℝ≥0) {x₀} ⊆ {y : Concentration S | ε ≤ y s} := by
    rintro y ⟨t, -, x, hx, rfl⟩
    rw [Set.mem_singleton_iff] at hx
    subst x
    rw [hϕγ]
    exact hfloor t t.coe_nonneg
  have hωsub : omegaLimit atTop ϕ {x₀} ⊆
      closure (Set.image2 ϕ (Set.univ : Set ℝ≥0) {x₀}) :=
    omegaLimit_subset_closure_image2 (f := atTop) (ϕ := ϕ) (s := {x₀}) (u := Set.univ) univ_mem
  exact lt_of_lt_of_le hε
    ((hωsub.trans ((IsClosed.closure_subset_iff hclosed).mpr horbit)) hp)

variable {ι : Type*} [Fintype ι] [Nonempty ι]
variable {ι' : Type*} [Fintype ι'] [Nonempty ι']

/-- **The §7 blueprint discharges the residual obligation of the Global Attractor Theorem.**

Given the blueprint data — tiles `ι'`, pieces `ι`, fan vectors `n`, levels `b`, a level `R`, and a
band `δ > 0` — together with

* `hstart`: the orbit starts inside the guarded region,
* `hnear`: on each tile the active normals lie in every fan cone within `δ` of the relative-log
  state (Craciun v3 Lemma 9.5 with the `δ`-slack of Lemma 9.7),
* `hsep`: the guarded region, inside the positive compatibility class, is bounded away from every
  coordinate hyperplane (v3 Definition 4.6(i)),

the ω-limit set of the orbit contains a strictly positive point — which is exactly the conclusion
of `CRNT.Network.exists_positive_omegaPoint_of_highCodimension_siphonFace`, the one remaining
`sorry` in the tree.

So the open problem is now purely geometric: *produce the blueprint*.  No dynamics, no analysis and
no limit arguments are left in it; `Network.deltaCore_mem` even supplies the canonical cone each
normal may be drawn from.  Because a globally homogeneous convex barrier is impossible in dimension
`≥ 3` (`CRNT.Geometry.ConvexBarrierObstruction`), the blueprint must use at least two tiles in
general, which is why this is stated for `minMaxBarrier` rather than `barrier`. -/
theorem exists_positive_omegaPoint_of_toric_blueprint (N : Network S) (κ : N.RateConstants)
    {xstar : Concentration S} (hxs : xstar.Positive) (hcb : N.IsComplexBalanced κ xstar)
    {ϕ : Flow ℝ≥0 (Concentration S)}
    {γ : Concentration S → ℝ → Concentration S} {x₀ : Concentration S}
    (hϕγ : ∀ x (t : ℝ≥0), ϕ t x = γ x t)
    {K : Set (Concentration S)} (hK : IsCompact K) (hmaps : ∀ t : ℝ≥0, ϕ t x₀ ∈ K)
    (hΓcont : ContinuousOn (γ x₀) (Set.Ici 0))
    (hΓpos : ∀ t, 0 ≤ t → (γ x₀ t).Positive)
    (hΓd : ∀ t, 0 ≤ t → HasDerivAt (γ x₀) (N.massActionVectorField κ (γ x₀ t)) t)
    (hclass : ∀ t, 0 ≤ t → N.StoichCompatible (γ x₀ 0) (γ x₀ t))
    {δ : ℝ} (hδ : 0 < δ)
    {n : ι' → ι → N.euclideanStoichSubspace} {b : ι' → ι → ℝ} {R : ℝ}
    (hstart : PolyhedralBarrier.minMaxBarrier (fun k i => innerSL ℝ (-n k i)) b
      (N.euclideanStoichState (γ x₀ 0)) ≤ R)
    (hnear : ∀ t, 0 ≤ t →
      R ≤ PolyhedralBarrier.minMaxBarrier (fun k i => innerSL ℝ (-n k i)) b
        (N.euclideanStoichState (γ x₀ t)) →
      ∃ k : ι',
        PolyhedralBarrier.barrier (fun i => innerSL ℝ (-n k i)) (b k)
            (N.euclideanStoichState (γ x₀ t))
          = PolyhedralBarrier.minMaxBarrier (fun k i => innerSL ℝ (-n k i)) b
              (N.euclideanStoichState (γ x₀ t)) ∧
        ∀ i : ι,
          innerSL ℝ (-n k i) (N.euclideanStoichState (γ x₀ t)) - b k i
            = PolyhedralBarrier.barrier (fun i => innerSL ℝ (-n k i)) (b k)
                (N.euclideanStoichState (γ x₀ t)) →
          ∀ C ∈ N.relativeSourceOrderNegativeStoichFan,
            Metric.infDist (N.relativeLogFanState xstar (γ x₀ t))
              (C : Set N.euclideanStoichSubspace) < δ → n k i ∈ C)
    (hsep : ∀ s : S, ∃ ε : ℝ, 0 < ε ∧ ∀ x : Concentration S, x.Positive →
      N.StoichCompatible (γ x₀ 0) x →
      PolyhedralBarrier.minMaxBarrier (fun k i => innerSL ℝ (-n k i)) b
        (N.euclideanStoichState x) ≤ R → ε ≤ x s) :
    ∃ p ∈ omegaLimit atTop ϕ {x₀}, p.Positive :=
  exists_positive_omegaPoint_of_coordinate_floors hϕγ hK hmaps
    (N.coordinate_lower_bounds_of_toric_barrier κ hxs hcb hδ hΓcont hΓpos hΓd hclass
      hstart hnear hsep)

/-- **The one-tile, one-piece instance: a single affine halfspace.**

The smallest possible blueprint.  A single fan vector `m` and a single level `c` give the region
`{y | ⟪-m, y⟫ ≤ c}`, and the blueprint clauses collapse to: the orbit starts in the halfspace, `m`
lies in every fan cone near the relative-log state whenever the boundary level is reached, and the
halfspace meets the positive compatibility class only away from the coordinate hyperplanes.

This is the mechanism behind the conservative and strongly-endotactic special cases — one inward
direction that works everywhere — now expressed inside the toric framework.  It is *not* enough in
general: `CRNT.Geometry.ConvexBarrierObstruction.not_exists_weights_vector` shows a single tile
cannot suffice in dimension `≥ 3`, which is why `exists_positive_omegaPoint_of_toric_blueprint`
takes a family.  Its role here is to exhibit the blueprint interface at its simplest and to show
the clauses are inhabitable. -/
theorem exists_positive_omegaPoint_of_toric_halfspace (N : Network S) (κ : N.RateConstants)
    {xstar : Concentration S} (hxs : xstar.Positive) (hcb : N.IsComplexBalanced κ xstar)
    {ϕ : Flow ℝ≥0 (Concentration S)}
    {γ : Concentration S → ℝ → Concentration S} {x₀ : Concentration S}
    (hϕγ : ∀ x (t : ℝ≥0), ϕ t x = γ x t)
    {K : Set (Concentration S)} (hK : IsCompact K) (hmaps : ∀ t : ℝ≥0, ϕ t x₀ ∈ K)
    (hΓcont : ContinuousOn (γ x₀) (Set.Ici 0))
    (hΓpos : ∀ t, 0 ≤ t → (γ x₀ t).Positive)
    (hΓd : ∀ t, 0 ≤ t → HasDerivAt (γ x₀) (N.massActionVectorField κ (γ x₀ t)) t)
    (hclass : ∀ t, 0 ≤ t → N.StoichCompatible (γ x₀ 0) (γ x₀ t))
    {δ : ℝ} (hδ : 0 < δ)
    {m : N.euclideanStoichSubspace} {c : ℝ}
    (hstart : ⟪-m, N.euclideanStoichState (γ x₀ 0)⟫ ≤ c)
    (hnear : ∀ t, 0 ≤ t → c ≤ ⟪-m, N.euclideanStoichState (γ x₀ t)⟫ →
      ∀ C ∈ N.relativeSourceOrderNegativeStoichFan,
        Metric.infDist (N.relativeLogFanState xstar (γ x₀ t))
          (C : Set N.euclideanStoichSubspace) < δ → m ∈ C)
    (hsep : ∀ s : S, ∃ ε : ℝ, 0 < ε ∧ ∀ x : Concentration S, x.Positive →
      N.StoichCompatible (γ x₀ 0) x → ⟪-m, N.euclideanStoichState x⟫ ≤ c → ε ≤ x s) :
    ∃ p ∈ omegaLimit atTop ϕ {x₀}, p.Positive := by
  refine N.exists_positive_omegaPoint_of_toric_blueprint κ hxs hcb hϕγ hK hmaps hΓcont hΓpos hΓd
    hclass hδ (ι := Unit) (ι' := Unit) (n := fun _ _ => m) (b := fun _ _ => 0) (R := c)
    ?_ ?_ ?_
  · simpa [PolyhedralBarrier.minMaxBarrier_unique, PolyhedralBarrier.barrier_unique] using hstart
  · intro t ht hlevel
    refine ⟨(), rfl, ?_⟩
    intro i _
    simp only [PolyhedralBarrier.minMaxBarrier_unique,
      PolyhedralBarrier.barrier_unique, sub_zero, innerSL_apply_apply] at hlevel
    exact hnear t ht hlevel
  · intro s
    obtain ⟨ε, hε, hbound⟩ := hsep s
    refine ⟨ε, hε, fun x hxpos hxclass hxregion => hbound x hxpos hxclass ?_⟩
    simpa [PolyhedralBarrier.minMaxBarrier_unique, PolyhedralBarrier.barrier_unique]
      using hxregion

end Network
end CRNT

end OmegaPoint
