import CRNT.Dynamics.ToricEmbedding
import Mathlib.Geometry.Convex.Cone.Pointed
import Mathlib.Analysis.InnerProductSpace.Basic
import Mathlib.Algebra.BigOperators.Module
import Mathlib.Data.Fin.Tuple.Sort

/-!
# The single-cycle projection-ordering step: velocity in the polar cone

This module completes the single-cycle case of the toric-embedding argument of Craciun,
_Toric differential inclusions and a proof of the global attractor conjecture_, by turning
the Abel-summation kernel into a **polar-cone membership**. The kernel
`cycle_velocity_eq_nonneg_combination`
(in `CRNT.Dynamics.ToricEmbedding`) shows that, with monotone coefficients `Monotone a`
and a closed cycle `u n = u 0`, the cyclic velocity is a nonnegative combination of the
vertex differences `u 0 − u (i+1)`. The remaining geometric step landed here is: when the
chosen base vertex `u 0` is `C`-minimal — its projection `⟪z, u 0⟫` is least among the
cycle vertices for every `z` in a cone `C` — each generator `u 0 − u (i+1)` lies in the
polar of `C`, hence so does the whole cone they generate, hence so does the velocity.

## Sign and polar conventions

The dual cone `coneDual s` of `CRNT.Geometry.PolyhedralFan` is the **nonnegative** dual
`{y : ∀ x ∈ s, 0 ≤ ⟪x, y⟫}`. The polar `Cᵒ` is the **nonpositive** cone
`{y : ∀ x ∈ C, ⟪x, y⟫ ≤ 0}`. To make the statement true with no sign confusion we work
directly with the nonpositive convention: `polarCone C` is defined here as the pointed
cone `{y : ∀ x ∈ C, ⟪x, y⟫ ≤ 0}` (`mem_polarCone`). This is exactly the polar `Cᵒ`, and
`u 0 − u (i+1)` lands in `polarCone C` because `C`-minimality gives
`⟪z, u 0 − u (i+1)⟫ = ⟪z, u 0⟫ − ⟪z, u (i+1)⟫ ≤ 0` for all `z ∈ C`.

## Space convention

All statements live over a general real inner-product space `E`
(`NormedAddCommGroup E`, `InnerProductSpace ℝ E`); the abstract Abel kernel
`cycle_velocity_eq_nonneg_combination` already holds over any `ℝ`-module, so no transport
along `(S → ℝ) ≃ EuclideanSpace ℝ S` is needed. To specialize to species space, take
`E := EuclideanSpace ℝ S`.

## Results

The generated cone of polar-cone generators sits inside the polar cone
(`generatedConeE_le_polarCone`); each vertex difference is polar to a `C`-minimal base
(`vertexDiff_mem_polarCone`); and the assembled single-cycle velocity lies in the polar cone
under `Monotone a`, `u n = u 0`, and `C`-minimality (`cycle_velocity_mem_polarCone`). A
sorting lemma turning a generic interior direction with distinct projections into a relabeling
realizing both `C`-minimality and coefficient monotonicity (`exists_sorted_reindex`) is
provided over a finite cycle.

Taken as hypotheses: that `Monotone a` actually holds for the mass-action coefficients (it
does, away from the `δ`-uncertainty region where `log x ∈ C`), and the full multi-cycle
weakly-reversible assembly across cycles and uncertainty regions.

This module is **stable** and `sorry`-free. Depends on: `CRNT.Dynamics.ToricEmbedding`,
Mathlib pointed cones, inner-product spaces, and module big operators.
-/

namespace CRNT

open scoped InnerProductSpace
open Finset

section PolarCone

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]

/-- **The polar cone** `Cᵒ` of a set `s`, in the nonpositive convention: the pointed
cone of points `y` whose inner product with every `x ∈ s` is nonpositive. This is a pointed
cone because the conditions `⟪x, y⟫ ≤ 0` are preserved under addition and nonnegative
scaling of `y`. Note the sign: this is the negation-flipped twin of the nonnegative dual
`coneDual` of `CRNT.Geometry.PolyhedralFan`. -/
def polarCone (s : Set E) : PointedCone ℝ E where
  carrier := {y | ∀ ⦃x⦄, x ∈ s → ⟪x, y⟫_ℝ ≤ 0}
  add_mem' := by
    intro y z hy hz x hx
    rw [inner_add_right]
    exact add_nonpos (hy hx) (hz hx)
  zero_mem' := by
    intro x _
    simp
  smul_mem' := by
    intro c y hy x hx
    rw [show c • y = (c : ℝ) • y from rfl, real_inner_smul_right]
    exact mul_nonpos_of_nonneg_of_nonpos c.2 (hy hx)

/-- Membership in the polar cone: `y ∈ polarCone s` iff `⟪x, y⟫ ≤ 0` for every `x ∈ s`. -/
@[simp] theorem mem_polarCone {s : Set E} {y : E} :
    y ∈ polarCone s ↔ ∀ ⦃x⦄, x ∈ s → ⟪x, y⟫_ℝ ≤ 0 :=
  Iff.rfl

end PolarCone

section GeneratedConeE

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]

/-- The convex cone generated by a finite family of vectors in a general inner-product
space `E`: the smallest pointed cone (containing `0`) that contains every `g i`. Realized
as the nonnegative-scalar span of the range of `g`. This is the inner-product-space twin of
`CRNT.generatedCone`, which is fixed to species space `S → ℝ`. -/
def generatedConeE {ι : Type*} (g : ι → E) : PointedCone ℝ E :=
  PointedCone.hull ℝ (Set.range g)

/-- Each generator lies in the cone it generates. -/
theorem mem_generatedConeE {ι : Type*} (g : ι → E) (i : ι) :
    g i ∈ generatedConeE g :=
  PointedCone.subset_hull ⟨i, rfl⟩

/-- **A cone contains the cone generated by its members.** If every generator `g i` lies in
a pointed cone `C`, then the whole generated cone is contained in `C`. This is the cone
analogue of `Submodule.span_le`: `generatedConeE g = span ℝ≥0 (range g)`, so it is the
least pointed cone containing the generators. -/
theorem generatedConeE_le {ι : Type*} (g : ι → E) (C : PointedCone ℝ E)
    (hg : ∀ i, g i ∈ C) : generatedConeE g ≤ C := by
  rw [generatedConeE, PointedCone.hull, Submodule.span_le]
  rintro x ⟨i, rfl⟩
  exact hg i

/-- **Item 1.** When every generator `g i` lies in the polar cone of `s`, the entire
generated cone lies in the polar cone of `s` — a polar cone contains the cone generated by
its members. -/
theorem generatedConeE_le_polarCone {ι : Type*} (g : ι → E) (s : Set E)
    (hg : ∀ i, g i ∈ polarCone s) : generatedConeE g ≤ polarCone s :=
  generatedConeE_le g (polarCone s) hg

end GeneratedConeE

section CMinimal

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]

/-- `u 0` is `C`-minimal for a cone (or any set) `C` and a family of vertices `u` when its
projection onto every direction `z ∈ C` is least among the vertices: `⟪z, u 0⟫ ≤ ⟪z, u i⟫`
for all `i` and all `z ∈ C`. This is the geometric input Craciun extracts from choosing a
generic direction and sorting the cycle vertices by their projection. -/
def CMinimal (C : Set E) (u : ℕ → E) : Prop :=
  ∀ ⦃z⦄, z ∈ C → ∀ i, ⟪z, u 0⟫_ℝ ≤ ⟪z, u i⟫_ℝ

/-- **Item 2.** From `C`-minimality of the base vertex `u 0`, each vertex difference
`u 0 − u (i+1)` lies in the polar cone of `C`: for every `z ∈ C`,
`⟪z, u 0 − u (i+1)⟫ = ⟪z, u 0⟫ − ⟪z, u (i+1)⟫ ≤ 0`. -/
theorem vertexDiff_mem_polarCone {C : Set E} {u : ℕ → E} (hmin : CMinimal C u) (i : ℕ) :
    u 0 - u (i + 1) ∈ polarCone C := by
  rw [mem_polarCone]
  intro z hz
  rw [inner_sub_right, sub_nonpos]
  exact hmin hz (i + 1)

end CMinimal

section Velocity

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]

/-- **Item 3 — single-cycle velocity in the polar cone.** With monotone coefficients
`Monotone a`, a closed cycle `u n = u 0`, and the base vertex `u 0` `C`-minimal, the cyclic
mass-action velocity `∑_{i<n} a i • (u (i+1) − u i)` lies in the polar cone `Cᵒ` of `C`.

The proof chains the three established pieces: the Abel kernel
`cycle_velocity_eq_nonneg_combination` rewrites the velocity as a nonnegative combination of
the vertex differences `u 0 − u (i+1)`; each such difference lies in `polarCone C` by
`C`-minimality (`vertexDiff_mem_polarCone`); and `polarCone C`, being a pointed cone, is
closed under the nonnegative combination (`Submodule.sum_mem` and `smul_mem`). -/
theorem cycle_velocity_mem_polarCone {C : Set E} (u : ℕ → E) (a : ℕ → ℝ) (n : ℕ)
    (hcyc : u n = u 0) (hmono : Monotone a) (hmin : CMinimal C u) :
    (∑ i ∈ range n, a i • (u (i + 1) - u i)) ∈ polarCone C := by
  rw [cycle_velocity_eq_nonneg_combination u a n hcyc]
  refine Submodule.sum_mem _ ?_
  intro i _
  have hc : (0 : ℝ) ≤ a (i + 1) - a i := forwardDiff_nonneg hmono i
  exact (polarCone C).smul_mem hc (vertexDiff_mem_polarCone hmin i)

/-- The same membership stated through the generated cone, exhibiting the full chain
"velocity ∈ generated cone of vertex differences ⊆ polar cone": with the vertex-difference
family as generators, the velocity lies in their generated cone, which sits inside the polar
cone of `C` whenever `u 0` is `C`-minimal. -/
theorem cycle_velocity_generatedConeE_le_polarCone {C : Set E} (u : ℕ → E) (n : ℕ)
    (hmin : CMinimal C u) :
    generatedConeE (fun i : Fin (n - 1) => u 0 - u (i + 1)) ≤ polarCone C :=
  generatedConeE_le_polarCone _ C (fun i => vertexDiff_mem_polarCone hmin i)

end Velocity

section Sorting

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]

/-- **Item 4 — the sorting reindexing.** A direction `w` whose projections `⟪w, u i⟫` onto
the cycle vertices are all distinct induces a permutation `σ` of the indices that sorts the
vertices by projection: along the relabeled vertices `u ∘ σ` the projection map
`fun i => ⟪w, (u ∘ σ) i⟫` is monotone, and the relabeled base `(u ∘ σ) 0` is minimal for the
ray `ℝ≥0 • w` — it realizes `CMinimal {t • w | 0 ≤ t}`-style minimality along `w`. This is
the combinatorial step that produces the monotone coefficients and `C`-minimal base the
velocity argument consumes.

We package it as: given any finite vertex family `u : Fin m → E` and direction `w`, there is
a sorting permutation `σ` such that `Monotone (fun i => ⟪w, u (σ i)⟫)`; sortedness gives
both the monotone coefficient ordering (the coefficients are functions of the projections)
and the projection-minimality of the first sorted vertex. -/
theorem exists_sorted_reindex {m : ℕ} (u : Fin m → E) (w : E) :
    ∃ σ : Equiv.Perm (Fin m), Monotone (fun i => ⟪w, u (σ i)⟫_ℝ) :=
  ⟨Tuple.sort (fun i => ⟪w, u i⟫_ℝ), Tuple.monotone_sort (fun i => ⟪w, u i⟫_ℝ)⟩

/-- Sortedness gives projection-minimality of the first sorted vertex: along a monotone
relabeling of the projections, the first vertex has the least projection onto `w` among all
vertices. This is the `CMinimal`-flavoured consequence of `exists_sorted_reindex`. -/
theorem sorted_head_proj_min {m : ℕ} [NeZero m] (u : Fin m → E) (w : E)
    {σ : Equiv.Perm (Fin m)} (hσ : Monotone (fun i => ⟪w, u (σ i)⟫_ℝ)) (i : Fin m) :
    ⟪w, u (σ ⟨0, Nat.pos_of_neZero m⟩)⟫_ℝ ≤ ⟪w, u (σ i)⟫_ℝ :=
  hσ (by simp)

end Sorting

end CRNT
