import CRNT.Geometry.PolyhedralFan
import CRNT.Kinetics.MassAction
import Mathlib.Algebra.BigOperators.Module

/-!
# The single-cycle monomial-ordering embedding

This module formalizes the algebraic kernel of the toric-embedding argument of Craciun,
_Toric differential inclusions and a proof of the global attractor conjecture_: the velocity
of a single oriented weakly-reversible mass-action cycle, once its monomial coefficients are
placed in increasing order, is a nonnegative combination of the differences of the reordered
cycle vertices, hence lies in the convex cone they generate.

The key tool is summation by parts (Abel's transformation). For a cyclic family of points
`u 0, …, u n` with `u n = u 0` and coefficients `0 ≤ a 0 ≤ … ≤ a (n-1)`, the cyclic
velocity
`v = ∑_{i < n} a i • (u (i+1) − u i)`
re-expresses, after Abel summation and the telescoping `∑_{i<n} (u (i+1) − u i) = 0`, as
`v = ∑_{i < n-1} (a (i+1) − a i) • (u 0 − u (i+1))`,
a combination with manifestly nonnegative coefficients `a (i+1) − a i ≥ 0`. The general
identity before imposing the cycle condition is `abelCycle_velocity_eq`; the nonnegative
regrouping is `cycle_velocity_eq_nonneg_combination`.

Specialized to species space `S → ℝ`, the velocity lies in the `generatedCone` of the
vertex-difference family `fun i => u 0 − u (i+1)` (`cycle_velocity_mem_generatedCone`),
which is the polar-cone membership the embedding needs once that cone is shown to contain
the chosen direction. The single-cycle mass-action velocity at a concentration, written
over its reordered monomials, is the network specialization `singleCycle_velocity_eq`.

The projection-ordering step (choosing a direction `w` and sorting vertices by their
`w`-projection so the coefficient ordering is realized) and the general weakly-reversible
assembly over many cycles and uncertainty regions are not constructed here; this module
supplies the per-cycle algebraic kernel they are built from.

Depends on: `CRNT.Geometry.PolyhedralFan`,
`CRNT.Kinetics.MassAction`, Mathlib summation by parts.
-/

namespace CRNT

open Finset

section AbelKernel

variable {M : Type*} [AddCommGroup M] [Module ℝ M]

/-- **Abel-summation kernel.** For a family of points `u : ℕ → M` and reals
`a : ℕ → ℝ`, the weighted sum of consecutive differences re-expresses by summation by
parts as a boundary term plus a sum of forward-difference-weighted partial telescopes:
`∑_{i<n} a i • (u (i+1) − u i) = a (n-1) • (u n − u 0)`
`  − ∑_{i<n-1} (a (i+1) − a i) • (u (i+1) − u 0)`.
This is `Finset.sum_range_by_parts` applied to the consecutive-difference family, with
the telescoping `∑_{j<m} (u (j+1) − u j) = u m − u 0` substituted for each partial sum. -/
theorem abelCycle_velocity_eq (u : ℕ → M) (a : ℕ → ℝ) (n : ℕ) :
    ∑ i ∈ range n, a i • (u (i + 1) - u i) =
      a (n - 1) • (u n - u 0)
        - ∑ i ∈ range (n - 1), (a (i + 1) - a i) • (u (i + 1) - u 0) := by
  have htel : ∀ m, ∑ j ∈ range m, (u (j + 1) - u j) = u m - u 0 :=
    fun m => Finset.sum_range_sub u m
  have hbp := Finset.sum_range_by_parts a (fun i => u (i + 1) - u i) n
  simp only [htel] at hbp
  exact hbp

/-- The cyclic case `u n = u 0` of `abelCycle_velocity_eq`: the boundary term vanishes
and the velocity is exactly the nonnegative regrouping
`∑_{i<n-1} (a (i+1) − a i) • (u 0 − u (i+1))`. With monotone coefficients
`a i ≤ a (i+1)` the forward differences `a (i+1) − a i` are nonnegative, so this exhibits
the cyclic velocity as a nonnegative combination of the vectors `u 0 − u (i+1)`. -/
theorem cycle_velocity_eq_nonneg_combination (u : ℕ → M) (a : ℕ → ℝ) (n : ℕ)
    (hcyc : u n = u 0) :
    ∑ i ∈ range n, a i • (u (i + 1) - u i) =
      ∑ i ∈ range (n - 1), (a (i + 1) - a i) • (u 0 - u (i + 1)) := by
  rw [abelCycle_velocity_eq u a n, hcyc, sub_self, smul_zero, zero_sub, ← Finset.sum_neg_distrib]
  refine Finset.sum_congr rfl ?_
  intro i _
  rw [← smul_neg, neg_sub]

/-- Along a monotone coefficient sequence the forward differences are nonnegative. -/
theorem forwardDiff_nonneg {a : ℕ → ℝ} (hmono : Monotone a) (i : ℕ) :
    0 ≤ a (i + 1) - a i :=
  sub_nonneg.mpr (hmono (Nat.le_succ i))

end AbelKernel

section ConeMembership

variable {S : Type} [DecidableEq S] [Fintype S]

omit [DecidableEq S] [Fintype S] in
/-- **Single-cycle cone embedding.** With monotone coefficients `a i ≤ a (i+1)` and a
closed cycle `u n = u 0` in species space `S → ℝ`, the cyclic velocity
`∑_{i<n} a i • (u (i+1) − u i)` lies in the convex cone generated by the vertex-difference
family `fun i => u 0 − u (i+1)`. This is the polar-cone membership at the heart of the
toric embedding: each generator `u 0 − u (i+1)` lies in the polar of any cone containing
the sorting direction, and a nonnegative combination of them stays in that polar. -/
theorem cycle_velocity_mem_generatedCone (u : ℕ → S → ℝ) (a : ℕ → ℝ)
    (n : ℕ) (hcyc : u n = u 0) (hmono : Monotone a) :
    (∑ i ∈ range n, a i • (u (i + 1) - u i)) ∈
      generatedCone (fun i : Fin (n - 1) => u 0 - u (i + 1)) := by
  rw [cycle_velocity_eq_nonneg_combination u a n hcyc]
  rw [← Fin.sum_univ_eq_sum_range (fun i => (a (i + 1) - a i) • (u 0 - u (i + 1))) (n - 1)]
  refine Submodule.sum_mem _ ?_
  intro i _
  have hgen : (u 0 - u (i + 1)) ∈ generatedCone (fun j : Fin (n - 1) => u 0 - u (j + 1)) :=
    mem_generatedCone _ i
  have hc : (0 : ℝ) ≤ a (i + 1) - a i := forwardDiff_nonneg hmono i
  exact (generatedCone (fun j : Fin (n - 1) => u 0 - u (j + 1))).smul_mem hc hgen

end ConeMembership

section NetworkVelocity

variable {S : Type} [DecidableEq S] [Fintype S]

/-- **Single-cycle mass-action velocity lies in the vertex-difference cone.** A single
oriented cycle is presented as a length-`n` sequence of reactions `e : Fin n → N.R` whose
reaction vectors are the consecutive differences `u (i+1) − u i` of a closed vertex
sequence `u : ℕ → S → ℝ` (`u n = u 0`). Write the mass-action coefficients as a sequence
`a : ℕ → ℝ` with `a i = massActionRate (e i)` on the cycle indices. When the cycle is
ordered so these coefficients increase (`Monotone a`), the mass-action velocity
contributed by the cycle's reactions at `x` lies in the convex cone generated by the
vertex-difference family `fun i => u 0 − u (i+1)` — the polar-cone membership of the toric
embedding. -/
theorem singleCycle_velocity_mem_generatedCone (N : Network S) (κ : N.RateConstants)
    (x : Concentration S) {n : ℕ} (e : Fin n → N.R) (u : ℕ → S → ℝ) (a : ℕ → ℝ)
    (hvec : ∀ i : Fin n, N.reactionVector (e i) = u (i + 1) - u i)
    (hcoeff : ∀ i : Fin n, N.massActionRate κ (e i) x = a i)
    (hcyc : u n = u 0) (hmono : Monotone a) :
    (∑ i : Fin n, N.massActionRate κ (e i) x • N.reactionVector (e i)) ∈
      generatedCone (fun i : Fin (n - 1) => u 0 - u (i + 1)) := by
  have hrw : (∑ i : Fin n, N.massActionRate κ (e i) x • N.reactionVector (e i)) =
      ∑ i ∈ range n, a i • (u (i + 1) - u i) := by
    rw [← Fin.sum_univ_eq_sum_range (fun i => a i • (u (i + 1) - u i)) n]
    refine Finset.sum_congr rfl ?_
    intro i _
    rw [hvec i, hcoeff i]
  rw [hrw]
  exact cycle_velocity_mem_generatedCone u a n hcyc hmono

end NetworkVelocity

end CRNT
