import CRNT.Algebra.SteadyStateIdeal
import CRNT.Algebra.DeficiencyIdeal
import CRNT.Theorems.DeficiencyZero.Statement

/-!
# Positive-torus equivalence of CRNT polynomial ideals

CRNT equilibrium ideals are most naturally compared on the algebraic torus rather than on
coordinate hyperplanes.  This module avoids overclaiming literal equality of polynomial ideals:
it records the exact positive-variety statements needed in chemical kinetics.

For weakly reversible networks the complex-balance ideal and tree-binomial ideal have the
same positive zero set.  Under deficiency zero, the steady-state ideal has that same positive
zero set as well.  Thus deficiency-zero mass-action steady states are toric on the chemical
positive orthant even when the unsaturated ideals differ on the boundary.
-/

namespace CRNT
namespace Network

open MvPolynomial

variable {S : Type} [DecidableEq S] [Fintype S]

/-- A point annihilates an ideal. -/
def VanishesIdealAt (I : Ideal (MvPolynomial S ℝ)) (x : S → ℝ) : Prop :=
  ∀ p ∈ I, eval x p = 0

/-- Two polynomial ideals are equivalent on the strictly positive chemical torus. -/
def PositiveTorusEquivalent
    (I J : Ideal (MvPolynomial S ℝ)) : Prop :=
  ∀ x : S → ℝ, (∀ s, 0 < x s) →
    (VanishesIdealAt I x ↔ VanishesIdealAt J x)

@[refl] theorem positiveTorusEquivalent_refl (I : Ideal (MvPolynomial S ℝ)) :
    PositiveTorusEquivalent I I := by intro x hx; rfl

@[symm] theorem positiveTorusEquivalent_symm
    {I J : Ideal (MvPolynomial S ℝ)} :
    PositiveTorusEquivalent I J → PositiveTorusEquivalent J I := by
  intro h x hx
  exact (h x hx).symm

@[trans] theorem positiveTorusEquivalent_trans
    {I J K : Ideal (MvPolynomial S ℝ)} :
    PositiveTorusEquivalent I J → PositiveTorusEquivalent J K →
      PositiveTorusEquivalent I K := by
  intro hIJ hJK x hx
  exact (hIJ x hx).trans (hJK x hx)

/-- Vanishing of the steady-state ideal is exactly the mass-action steady-state equation. -/
theorem vanishes_steadyStateIdeal_iff
    (N : Network S) (κ : N.RateConstants) (x : Concentration S) :
    VanishesIdealAt (N.steadyStateIdeal κ) x ↔
      N.IsMassActionSteadyState κ x := by
  constructor
  · intro h s
    have hz := h (N.steadyStatePolynomial κ s)
      (Ideal.subset_span ⟨s, rfl⟩)
    simpa [N.eval_steadyStatePolynomial κ s x] using hz
  · intro h p hp
    -- Evaluation is a ring homomorphism, so it annihilates the ideal generated by
    -- the coordinate steady-state polynomials once it annihilates every generator.
    refine Submodule.span_induction (p := fun q _ => eval x q = 0) ?_ ?_ ?_ ?_ hp
    · rintro _ ⟨s, rfl⟩
      simpa [N.eval_steadyStatePolynomial κ s x] using h s
    · simp
    · intro p q _ _ hp hq
      simp [hp, hq]
    · intro p q _ hq
      simp [smul_eq_mul, hq]

/-- Vanishing of the complex-balance ideal is exactly complex balance. -/
theorem vanishes_complexBalanceIdeal_iff
    (N : Network S) (κ : N.RateConstants) (x : Concentration S) :
    VanishesIdealAt (N.complexBalanceIdeal κ) x ↔
      N.IsComplexBalanced κ x := by
  exact ⟨N.complexBalanced_of_vanishesComplexBalanceIdeal κ,
    N.vanishesComplexBalanceIdeal_of_complexBalanced κ⟩

/-- On the positive torus of a weakly reversible network, the tree-binomial ideal cuts out
exactly the complex-balanced equilibrium set. -/
theorem vanishes_treeBinomialIdeal_iff_complexBalanced
    (N : Network S) (κ : N.RateConstants) (hwr : N.WeaklyReversible)
    {x : Concentration S} (hx : x.Positive) :
    VanishesIdealAt (N.treeBinomialIdeal κ) x ↔ N.IsComplexBalanced κ x := by
  constructor
  · intro h
    apply (N.complexBalanced_iff_treeBinomialGenerators_vanish κ hwr hx).2
    intro i j hij
    exact h (N.treeBinomialPolynomial κ i j)
      (Ideal.subset_span ⟨i, j, hij, rfl⟩)
  · intro hcb p hp
    refine Submodule.span_induction (p := fun q _ => eval x q = 0) ?_ ?_ ?_ ?_ hp
    · rintro p ⟨i, j, hij, rfl⟩
      exact N.treeBinomial_vanishes_of_complexBalanced κ hwr hx hcb hij
    · simp
    · intro p q _ _ hp hq; simp [hp, hq]
    · intro p q _ hq; simp [smul_eq_mul, hq]

/-- Weak reversibility makes the complex-balance and tree-binomial ideals positive-torus
equivalent. -/
theorem complexBalanceIdeal_positiveTorusEquivalent_treeBinomialIdeal
    (N : Network S) (κ : N.RateConstants) (hwr : N.WeaklyReversible) :
    PositiveTorusEquivalent (N.complexBalanceIdeal κ) (N.treeBinomialIdeal κ) := by
  intro x hx
  rw [N.vanishes_complexBalanceIdeal_iff κ x,
    N.vanishes_treeBinomialIdeal_iff_complexBalanced κ hwr hx]

/-- **Deficiency-zero positive toric ideal theorem.**  For a weakly reversible deficiency-zero
network, the steady-state, complex-balance, and tree-binomial ideals all have the same
strictly positive zero set. -/
theorem deficiencyZero_steadyStateIdeal_positiveTorusEquivalent_treeBinomialIdeal
    (N : Network S) (κ : N.RateConstants)
    (hwr : N.WeaklyReversible) (hδ : N.DeficiencyZero) :
    PositiveTorusEquivalent (N.steadyStateIdeal κ) (N.treeBinomialIdeal κ) := by
  intro x hx
  rw [N.vanishes_steadyStateIdeal_iff κ x,
    N.vanishes_treeBinomialIdeal_iff_complexBalanced κ hwr hx]
  constructor
  · intro hss
    apply N.complexBalanced_of_steadyState_deficiencyZero_polynomial κ hδ
    funext s
    exact hss s
  · intro hcb
    exact hcb.isMassActionSteadyState N κ

/-- The corresponding steady-state and complex-balance ideals are positive-torus equivalent. -/
theorem deficiencyZero_steadyStateIdeal_positiveTorusEquivalent_complexBalanceIdeal
    (N : Network S) (κ : N.RateConstants)
    (hwr : N.WeaklyReversible) (hδ : N.DeficiencyZero) :
    PositiveTorusEquivalent (N.steadyStateIdeal κ) (N.complexBalanceIdeal κ) := by
  exact positiveTorusEquivalent_trans
    (N.deficiencyZero_steadyStateIdeal_positiveTorusEquivalent_treeBinomialIdeal κ hwr hδ)
    (positiveTorusEquivalent_symm
      (N.complexBalanceIdeal_positiveTorusEquivalent_treeBinomialIdeal κ hwr))

/-- Product of all species variables, the polynomial inverted when passing from affine
concentration space to the algebraic torus. -/
noncomputable def speciesCoordinateProduct : MvPolynomial S ℝ :=
  ∏ s : S, X s

/-- Elementary algebraic saturation predicate by the species-coordinate product.  It is
stated membership-wise so downstream code need not depend on a particular localization API. -/
def MemPositiveTorusSaturation
    (I : Ideal (MvPolynomial S ℝ)) (p : MvPolynomial S ℝ) : Prop :=
  ∃ n : ℕ, speciesCoordinateProduct ^ n * p ∈ I

/-- Saturating an ideal by species coordinates does not change its strictly positive zero set. -/
theorem vanishes_positiveTorusSaturation_iff
    (I : Ideal (MvPolynomial S ℝ)) {x : S → ℝ} (hx : ∀ s, 0 < x s) :
    (∀ p, MemPositiveTorusSaturation I p → eval x p = 0) ↔
      VanishesIdealAt I x := by
  -- On the positive torus `eval x speciesCoordinateProduct ≠ 0`, so multiplication
  -- by a coordinate-product power can be cancelled.
  constructor
  · intro h p hp
    exact h p ⟨0, by simpa using hp⟩
  · intro h p hp
    obtain ⟨n, hn⟩ := hp
    have hz := h (speciesCoordinateProduct ^ n * p) hn
    have hprodPos : 0 < eval x (speciesCoordinateProduct : MvPolynomial S ℝ) := by
      simpa [speciesCoordinateProduct] using
        (Finset.prod_pos (fun s (_ : s ∈ (Finset.univ : Finset S)) => hx s))
    have hprod : eval x (speciesCoordinateProduct : MvPolynomial S ℝ) ≠ 0 := hprodPos.ne'
    rw [map_mul, map_pow] at hz
    exact (mul_eq_zero.mp hz).resolve_left (pow_ne_zero n hprod)

end Network
end CRNT
