import CRNT.Dynamics.Siphon
import CRNT.Graph.Reversibility

/-!
# Algebraic characterization of siphons

For a species set `P`, let `𝔭_P = ⟨x_s | s ∈ P⟩` be the corresponding coordinate
monomial prime.  A complex monomial `x^y` belongs to `𝔭_P` exactly when `y` uses at
least one species of `P`.  Hence the siphon condition is equivalent to

`x^{y'} ∈ 𝔭_P  →  x^y ∈ 𝔭_P`

for every reaction `y → y'`.

This is the support-theoretic content behind the Shiu--Sturmfels ideal-saturation
characterization of siphons.  The file formalizes the exact CRNT/algebra bridge without
requiring a multivariate-polynomial factorization algorithm.
-/

namespace CRNT

namespace Network

variable {S : Type} [DecidableEq S] [Fintype S]

/-- A complex monomial belongs to the coordinate prime generated by `P` iff at least one
species from `P` occurs in the complex. -/
def CoordinatePrimeContains (P : Finset S) (y : Complex S) : Prop :=
  ∃ s ∈ P, y s ≠ 0

/-- Reaction-binomial backward closure of the coordinate prime. -/
def ReactionPrimeBackwardClosed (N : Network S) (P : Finset S) : Prop :=
  ∀ r : N.R,
    CoordinatePrimeContains P (N.reaction r).target →
      CoordinatePrimeContains P (N.reaction r).source

/-- Reaction-binomial forward closure. -/
def ReactionPrimeForwardClosed (N : Network S) (P : Finset S) : Prop :=
  ∀ r : N.R,
    CoordinatePrimeContains P (N.reaction r).source →
      CoordinatePrimeContains P (N.reaction r).target

/-- Product-complex coordinate-prime membership is exactly "the reaction produces a
species in `P`". -/
theorem coordinatePrimeContains_target_iff (N : Network S) (P : Finset S) (r : N.R) :
    CoordinatePrimeContains P (N.reaction r).target ↔
      ∃ s ∈ P, N.IsProduct r s :=
  Iff.rfl

/-- Source-complex coordinate-prime membership is exactly "the reaction consumes a
species in `P`". -/
theorem coordinatePrimeContains_source_iff (N : Network S) (P : Finset S) (r : N.R) :
    CoordinatePrimeContains P (N.reaction r).source ↔
      ∃ s ∈ P, N.IsReactant r s :=
  Iff.rfl

/-- **Algebraic siphon criterion.** A species set is a siphon iff its coordinate prime is
backward closed under every reaction binomial. -/
theorem isSiphon_iff_reactionPrimeBackwardClosed (N : Network S) (P : Finset S) :
    N.IsSiphon P ↔ N.ReactionPrimeBackwardClosed P := by
  rfl

/-- A nonempty coordinate-prime support satisfying the binomial closure criterion. -/
def IsSiphonPrimeSupport (N : Network S) (P : Finset S) : Prop :=
  P.Nonempty ∧ N.ReactionPrimeBackwardClosed P

/-- Siphon prime supports are exactly nonempty siphons. -/
theorem isSiphonPrimeSupport_iff (N : Network S) (P : Finset S) :
    N.IsSiphonPrimeSupport P ↔ P.Nonempty ∧ N.IsSiphon P := by
  simp [IsSiphonPrimeSupport, isSiphon_iff_reactionPrimeBackwardClosed]

/-- Inclusion-minimal nonempty coordinate-prime support with reaction-binomial closure. -/
def IsMinimalSiphonPrimeSupport (N : Network S) (P : Finset S) : Prop :=
  N.IsSiphonPrimeSupport P ∧
    ∀ Q : Finset S, Q ⊆ P → Q ≠ P → Q.Nonempty → ¬ N.IsSiphonPrimeSupport Q

/-- **Minimal siphons are precisely minimal reaction-binomial coordinate-prime supports.** -/
theorem isMinimalSiphon_iff_minimalPrimeSupport (N : Network S) (P : Finset S) :
    N.IsMinimalSiphon P ↔ N.IsMinimalSiphonPrimeSupport P := by
  constructor
  · intro h
    refine ⟨(N.isSiphonPrimeSupport_iff P).2 ⟨h.1, h.2.1⟩, ?_⟩
    intro Q hQP hne hQne hQprime
    have hQpow : Q ∈ P.powerset := Finset.mem_powerset.mpr hQP
    exact h.2.2 Q hQpow hQne hne ((N.isSiphonPrimeSupport_iff Q).1 hQprime).2
  · rintro ⟨hP, hmin⟩
    have hPs := (N.isSiphonPrimeSupport_iff P).1 hP
    refine ⟨hPs.1, hPs.2, ?_⟩
    intro Q hQpow hQne hne hQs
    have hQP : Q ⊆ P := Finset.mem_powerset.mp hQpow
    exact hmin Q hQP hne hQne ((N.isSiphonPrimeSupport_iff Q).2 ⟨hQne, hQs⟩)

/-- On a reversible network, reaction-binomial backward closure automatically implies
forward closure.  Algebraically, coordinate-prime membership is invariant along every
reversible reaction pair. -/
theorem reactionPrimeForwardClosed_of_reversible (N : Network S) (hrev : N.Reversible)
    {P : Finset S} (hback : N.ReactionPrimeBackwardClosed P) :
    N.ReactionPrimeForwardClosed P := by
  intro r hsrc
  obtain ⟨r', hsrc', htgt'⟩ := hrev r
  -- the reverse reaction has target = original source and source = original target
  have hrevTarget : CoordinatePrimeContains P (N.reaction r').target := by
    simpa [htgt'] using hsrc
  have hrevSource := hback r' hrevTarget
  simpa [hsrc'] using hrevSource

/-- Thus on reversible networks, membership in the coordinate prime is equivalent at the
two endpoints of every reaction. -/
theorem coordinatePrimeContains_source_iff_target_of_reversible
    (N : Network S) (hrev : N.Reversible) {P : Finset S} (hP : N.IsSiphon P) (r : N.R) :
    CoordinatePrimeContains P (N.reaction r).source ↔
      CoordinatePrimeContains P (N.reaction r).target := by
  constructor
  · exact N.reactionPrimeForwardClosed_of_reversible hrev
      ((N.isSiphon_iff_reactionPrimeBackwardClosed P).1 hP) r
  · exact ((N.isSiphon_iff_reactionPrimeBackwardClosed P).1 hP) r

end Network

end CRNT
