import CRNT.Dynamics.MassActionAlgebra
import CRNT.Equilibria.TreeConstantCriterion
import Mathlib.RingTheory.MvPolynomial.Basic
import Mathlib.RingTheory.Ideal.Operations

/-!
# Polynomial steady-state and complex-balance ideals

Mass-action CRNT is polynomial.  This file packages the algebraic objects that are
usually implicit in CRNT:

* the species steady-state polynomials `f_s(x)`;
* the complex-balance polynomials `(A_k Ψ(x))_c`;
* their generated ideals;
* tree-constant binomials on weakly reversible linkage classes.

The key structural containment is immediate from `f = Y A_k Ψ`: every species
steady-state polynomial is a linear combination of complex-balance polynomials, so the
steady-state ideal is contained in the complex-balance ideal.  Consequently every
complex-balanced point is a steady state algebraically, not merely dynamically.
-/

namespace CRNT
namespace Network

open scoped BigOperators
open MvPolynomial

variable {S : Type} [DecidableEq S] [Fintype S]

/-- Convert a finite complex `S → ℕ` to the finitely supported exponent vector used by
`MvPolynomial`. -/
noncomputable def complexExponent (c : Complex S) : S →₀ ℕ :=
  Finsupp.equivFunOnFinite.symm c

/-- Monomial corresponding to a CRNT complex. -/
noncomputable def complexMonomialPolynomial (c : Complex S) : MvPolynomial S ℝ :=
  monomial (complexExponent c) 1

/-- Evaluation of the polynomial complex monomial agrees with the ordinary mass-action
monomial. -/
theorem eval_complexMonomialPolynomial (c : Complex S) (x : S → ℝ) :
    eval x (complexMonomialPolynomial c) = c.massActionMonomial x := by
  simp [complexMonomialPolynomial, complexExponent, MvPolynomial.eval_monomial,
    Finsupp.prod_fintype, Complex.massActionMonomial]

/-- Polynomial reaction-rate monomial. -/
noncomputable def reactionRatePolynomial (N : Network S) (κ : N.RateConstants)
    (r : N.R) : MvPolynomial S ℝ :=
  C (κ.k r) * complexMonomialPolynomial (N.reaction r).source

/-- Species component of the mass-action vector field as a polynomial. -/
noncomputable def steadyStatePolynomial (N : Network S) (κ : N.RateConstants)
    (s : S) : MvPolynomial S ℝ :=
  ∑ r : N.R, C (N.reactionVector r s) * N.reactionRatePolynomial κ r

/-- Evaluation of the steady-state polynomial is the species ODE component. -/
theorem eval_steadyStatePolynomial (N : Network S) (κ : N.RateConstants)
    (s : S) (x : Concentration S) :
    eval x (N.steadyStatePolynomial κ s) = N.massActionVectorField κ x s := by
  simp only [steadyStatePolynomial, reactionRatePolynomial, map_sum, map_mul, eval_C,
    eval_complexMonomialPolynomial, massActionVectorField_apply, massActionRate,
    reactionVector_apply]
  refine Finset.sum_congr rfl fun r _ => ?_
  ring

/-- Mass-action steady-state ideal generated by the species ODE polynomials. -/
noncomputable def steadyStateIdeal (N : Network S) (κ : N.RateConstants) :
    Ideal (MvPolynomial S ℝ) :=
  Ideal.span (Set.range (N.steadyStatePolynomial κ))

/-- Complex-balance polynomial at a graph complex. -/
noncomputable def complexBalancePolynomial (N : Network S) (κ : N.RateConstants)
    (c : N.ComplexIdx) : MvPolynomial S ℝ :=
  (∑ r : N.R,
      if N.targetIdx r = c then N.reactionRatePolynomial κ r else 0) -
    (∑ r : N.R,
      if N.sourceIdx r = c then N.reactionRatePolynomial κ r else 0)

/-- Evaluation is inflow minus outflow at the complex. -/
theorem eval_complexBalancePolynomial (N : Network S) (κ : N.RateConstants)
    (c : N.ComplexIdx) (x : Concentration S) :
    eval x (N.complexBalancePolynomial κ c) =
      N.inflow κ x c - N.outflow κ x c := by
  simp only [complexBalancePolynomial, map_sub, map_sum, apply_ite, map_zero,
    reactionRatePolynomial, map_mul, eval_C, eval_complexMonomialPolynomial,
    inflow, outflow, massActionRate, sourceIdx, targetIdx, Subtype.ext_iff]

/-- Ideal generated by the complex-balance equations. -/
noncomputable def complexBalanceIdeal (N : Network S) (κ : N.RateConstants) :
    Ideal (MvPolynomial S ℝ) :=
  Ideal.span (Set.range (N.complexBalancePolynomial κ))

/-- Polynomial form of `f = Y A_k Ψ`: each species steady-state polynomial is the
stoichiometric linear combination of the complex-balance polynomials. -/
theorem steadyStatePolynomial_eq_complexBalanceCombination
    (N : Network S) (κ : N.RateConstants) (s : S) :
    N.steadyStatePolynomial κ s =
      ∑ c : N.ComplexIdx, C (c.val s : ℝ) * N.complexBalancePolynomial κ c := by
  simp only [steadyStatePolynomial, complexBalancePolynomial, mul_sub, Finset.mul_sum,
    Finset.sum_sub_distrib]
  rw [← Finset.sum_sub_distrib]
  simp_rw [← Finset.sum_sub_distrib]
  rw [Finset.sum_comm]
  apply Finset.sum_congr rfl
  intro r _
  have ht : (∑ c : N.ComplexIdx, C (c.val s : ℝ) *
      (if N.targetIdx r = c then N.reactionRatePolynomial κ r else 0)) =
      C ((N.targetIdx r).val s : ℝ) * N.reactionRatePolynomial κ r := by
    rw [Finset.sum_eq_single (N.targetIdx r)]
    · simp
    · intro c _ hc
      rw [if_neg (Ne.symm hc), mul_zero]
    · intro h
      exact (h (Finset.mem_univ _)).elim
  have hs : (∑ c : N.ComplexIdx, C (c.val s : ℝ) *
      (if N.sourceIdx r = c then N.reactionRatePolynomial κ r else 0)) =
      C ((N.sourceIdx r).val s : ℝ) * N.reactionRatePolynomial κ r := by
    rw [Finset.sum_eq_single (N.sourceIdx r)]
    · simp
    · intro c _ hc
      rw [if_neg (Ne.symm hc), mul_zero]
    · intro h
      exact (h (Finset.mem_univ _)).elim
  rw [Finset.sum_sub_distrib, ht, hs]
  simp only [targetIdx, sourceIdx, reactionVector_apply]
  rw [map_sub]
  ring

/-- Therefore the steady-state ideal is contained in the complex-balance ideal. -/
theorem steadyStateIdeal_le_complexBalanceIdeal
    (N : Network S) (κ : N.RateConstants) :
    N.steadyStateIdeal κ ≤ N.complexBalanceIdeal κ := by
  rw [steadyStateIdeal, Ideal.span_le]
  rintro _ ⟨s, rfl⟩
  rw [N.steadyStatePolynomial_eq_complexBalanceCombination κ s]
  apply Submodule.sum_mem
  intro c _
  exact Ideal.mul_mem_left _ _ (Ideal.subset_span ⟨c, rfl⟩)

/-- Vanishing of the complex-balance ideal at a point is equivalent to graph complex
balance. -/
def VanishesComplexBalanceIdeal (N : Network S) (κ : N.RateConstants)
    (x : Concentration S) : Prop :=
  ∀ p ∈ N.complexBalanceIdeal κ, eval x p = 0

/-- Complex balance implies vanishing of the whole complex-balance ideal. -/
theorem vanishesComplexBalanceIdeal_of_complexBalanced
    (N : Network S) (κ : N.RateConstants) {x : Concentration S}
    (hcb : N.IsComplexBalanced κ x) :
    N.VanishesComplexBalanceIdeal κ x := by
  intro p hp
  refine Submodule.span_induction (p := fun q _ => eval x q = 0) ?_ ?_ ?_ ?_ hp
  · intro q hq
    obtain ⟨c, rfl⟩ := hq
    rw [N.eval_complexBalancePolynomial κ c x]
    exact sub_eq_zero.mpr (hcb c.val c.property)
  · simp
  · intro a b _ _ ha hb
    simp [ha, hb]
  · intro a q _ hq
    simp [smul_eq_mul, hq]

/-- Conversely it is enough to annihilate the generators. -/
theorem complexBalanced_of_vanishesComplexBalanceIdeal
    (N : Network S) (κ : N.RateConstants) {x : Concentration S}
    (hvan : N.VanishesComplexBalanceIdeal κ x) :
    N.IsComplexBalanced κ x := by
  intro c hc
  let ci : N.ComplexIdx := ⟨c, hc⟩
  have hz := hvan (N.complexBalancePolynomial κ ci)
    (Ideal.subset_span ⟨ci, rfl⟩)
  rw [N.eval_complexBalancePolynomial κ ci x] at hz
  exact sub_eq_zero.mp hz

/-- Tree-constant binomial associated with two complexes. -/
noncomputable def treeBinomialPolynomial (N : Network S) (κ : N.RateConstants)
    (i j : N.ComplexIdx) : MvPolynomial S ℝ :=
  C (N.treeConstant κ j) * complexMonomialPolynomial i.val -
    C (N.treeConstant κ i) * complexMonomialPolynomial j.val

/-- Evaluation is exactly the tree-constant binomial from CRNT. -/
theorem eval_treeBinomialPolynomial (N : Network S) (κ : N.RateConstants)
    (i j : N.ComplexIdx) (x : Concentration S) :
    eval x (N.treeBinomialPolynomial κ i j) =
      N.treeConstant κ j * N.complexMonomial x i -
        N.treeConstant κ i * N.complexMonomial x j := by
  simp [treeBinomialPolynomial, eval_complexMonomialPolynomial, complexMonomial]

/-- Binomial ideal generated by tree-constant relations within linkage classes. -/
noncomputable def treeBinomialIdeal (N : Network S) (κ : N.RateConstants) :
    Ideal (MvPolynomial S ℝ) :=
  Ideal.span {p | ∃ i j : N.ComplexIdx, N.Linked i.1 j.1 ∧
    p = N.treeBinomialPolynomial κ i j}

/-- Positive complex-balanced points annihilate all tree-constant binomials. -/
theorem treeBinomial_vanishes_of_complexBalanced
    (N : Network S) (κ : N.RateConstants) (hwr : N.WeaklyReversible)
    {x : Concentration S} (hx : x.Positive) (hcb : N.IsComplexBalanced κ x)
    {i j : N.ComplexIdx} (hij : N.Linked i.1 j.1) :
    eval x (N.treeBinomialPolynomial κ i j) = 0 := by
  rw [N.eval_treeBinomialPolynomial κ i j x]
  exact sub_eq_zero.mpr (N.treeConstant_binomial_of_complexBalanced κ hwr hx hcb hij)

/-- On the positive orthant of a weakly reversible network, vanishing of all linkage
class tree binomials is equivalent to complex balance. -/
theorem complexBalanced_iff_treeBinomialGenerators_vanish
    (N : Network S) (κ : N.RateConstants) (hwr : N.WeaklyReversible)
    {x : Concentration S} (hx : x.Positive) :
    N.IsComplexBalanced κ x ↔
      ∀ i j : N.ComplexIdx, N.Linked i.1 j.1 →
        eval x (N.treeBinomialPolynomial κ i j) = 0 := by
  constructor
  · intro hcb i j hij
    exact N.treeBinomial_vanishes_of_complexBalanced κ hwr hx hcb hij
  · intro hvan
    apply N.complexBalanced_of_treeConstantBinomials κ hwr hx
    intro i j hij
    have hz := hvan i j hij
    rw [N.eval_treeBinomialPolynomial κ i j x] at hz
    exact sub_eq_zero.mp hz

end Network
end CRNT
