import CRNT.Oscillation.PlanarFrontier
import CRNT.Dynamics.ButlerMcGehee

/-!
# Omega-limit reduction for the planar Poincare--Bendixson route

`PlanarFrontier.TrappedOrbit` records the intuitive certificate.  This module connects that idea to
CRNT's existing semiflow / omega-limit infrastructure.  The result is that almost all of the global
compactness work needed before Poincare--Bendixson is already closed in Lean:

* the omega-limit set is nonempty;
* it is compact;
* it is forward invariant (and carries the repository's two-sided invariance interface);
* it lies inside the compact trapping region;
* hence it contains no equilibrium when the trapping region is equilibrium-free.

The only remaining frontier is the genuinely planar classification theorem saying that such an
omega-limit set contains a periodic orbit.
-/

open Filter Set Topology
open scoped NNReal Topology

namespace CRNT

namespace Planar

/-- A planar autonomous field together with a genuine forward flow and a compact trapping region.

`trajectory` provides global real-time integral curves only to state unambiguously that the supplied
semiflow is generated by `field`; the omega-limit construction itself uses nonnegative time. -/
structure FlowTrappingData (field : Phase2 → Phase2) where
  flow : Flow ℝ≥0 Phase2
  trajectory : Phase2 → ℝ → Phase2
  trajectory_zero : ∀ x, trajectory x 0 = x
  trajectory_solution : ∀ x t, HasDerivAt (trajectory x) (field (trajectory x t)) t
  flow_eq_trajectory : ∀ x (t : ℝ≥0), flow t x = trajectory x (t : ℝ)
  seed : Phase2
  region : Set Phase2
  compact : IsCompact region
  trapped : ∀ t : ℝ≥0, flow t seed ∈ region
  equilibriumFree : ∀ x ∈ region, field x ≠ 0

namespace FlowTrappingData

variable {field : Phase2 → Phase2}

/-- The omega-limit set of the certified trapped forward orbit. -/
def omegaSet (D : FlowTrappingData field) : Set Phase2 :=
  omegaLimit Filter.atTop D.flow {D.seed}

/-- The whole forward orbit image lies in the trapping region. -/
theorem image2_univ_subset_region (D : FlowTrappingData field) :
    Set.image2 D.flow (Set.univ : Set ℝ≥0) {D.seed} ⊆ D.region := by
  rintro y ⟨t, _ht, x, hx, rfl⟩
  rw [Set.mem_singleton_iff.mp hx]
  exact D.trapped t

/-- The compact trapping region is an absorbing compact set in exactly the form expected by the
repository's omega-limit lemmas. -/
theorem absorbing (D : FlowTrappingData field) :
    ∃ v ∈ (Filter.atTop : Filter ℝ≥0),
      closure (Set.image2 D.flow v {D.seed}) ⊆ D.region := by
  refine ⟨Set.univ, Filter.univ_mem, ?_⟩
  exact closure_minimal D.image2_univ_subset_region D.compact.isClosed

/-- The certified omega-limit set is nonempty. -/
theorem omegaSet_nonempty (D : FlowTrappingData field) : D.omegaSet.Nonempty := by
  exact nonempty_omegaLimit_of_isCompact_absorbing Filter.atTop D.flow {D.seed}
    D.compact D.absorbing (Set.singleton_nonempty D.seed)

/-- The certified omega-limit set is compact. -/
theorem omegaSet_compact (D : FlowTrappingData field) : IsCompact D.omegaSet :=
  isCompact_omegaLimit_of_absorbing D.flow D.seed D.compact D.absorbing

/-- The certified omega-limit set is invariant under the semiflow. -/
theorem omegaSet_invariant (D : FlowTrappingData field) : IsInvariant D.flow D.omegaSet :=
  omegaLimit_isInvariant_two_sided D.flow D.seed

/-- The omega-limit set remains inside the original compact trapping region. -/
theorem omegaSet_subset_region (D : FlowTrappingData field) : D.omegaSet ⊆ D.region := by
  have hsub := omegaLimit_subset_closure_image2 Filter.atTop D.flow {D.seed}
    (Filter.univ_mem : (Set.univ : Set ℝ≥0) ∈ (Filter.atTop : Filter ℝ≥0))
  exact hsub.trans (closure_minimal D.image2_univ_subset_region D.compact.isClosed)

/-- Consequently the omega-limit set is equilibrium-free. -/
theorem omegaSet_equilibriumFree (D : FlowTrappingData field) :
    ∀ x ∈ D.omegaSet, field x ≠ 0 := by
  intro x hx
  exact D.equilibriumFree x (D.omegaSet_subset_region hx)

/-- Every point of the omega-limit set is visited arbitrarily late in every neighbourhood by the
original trapped orbit.  This is the recurrence input from the definition of omega-limit; the
remaining Poincare--Bendixson geometry must turn such arbitrarily late near-returns into a genuine
transversal return interval. -/
theorem omegaSet_frequently_near (D : FlowTrappingData field)
    {q : Phase2} (hq : q ∈ D.omegaSet) {U : Set Phase2} (hU : U ∈ 𝓝 q) :
    ∃ᶠ t : ℝ≥0 in Filter.atTop, D.flow t D.seed ∈ U := by
  have hcluster : MapClusterPt q Filter.atTop (fun t : ℝ≥0 => D.flow t D.seed) := by
    exact (mem_omegaLimit_singleton_iff_mapClusterPt
      (f := Filter.atTop) (ϕ := D.flow) D.seed q).mp hq
  exact hcluster.frequently hU

/-- Bundle the already-proved omega-limit properties for downstream global-dynamics arguments. -/
structure OmegaCertificate (D : FlowTrappingData field) : Prop where
  nonempty : D.omegaSet.Nonempty
  compact : IsCompact D.omegaSet
  invariant : IsInvariant D.flow D.omegaSet
  trapped : D.omegaSet ⊆ D.region
  equilibriumFree : ∀ x ∈ D.omegaSet, field x ≠ 0

/-- Every `FlowTrappingData` automatically supplies the full pre-Poincare--Bendixson omega-limit
certificate. -/
theorem omegaCertificate (D : FlowTrappingData field) : D.OmegaCertificate where
  nonempty := D.omegaSet_nonempty
  compact := D.omegaSet_compact
  invariant := D.omegaSet_invariant
  trapped := D.omegaSet_subset_region
  equilibriumFree := D.omegaSet_equilibriumFree

end FlowTrappingData

/-- The now-small Poincare--Bendixson frontier: the compact, invariant, nonempty,
equilibrium-free omega-limit set of a `C¹` planar flow contains a nonconstant periodic orbit.

All compactness/nonemptiness/trapping obligations are discharged by `FlowTrappingData.omegaCertificate`;
this proposition isolates only the genuinely planar classification theorem. -/
def PoincareBendixsonOmegaClassificationTarget : Prop :=
  ∀ (field : Phase2 → Phase2) (D : FlowTrappingData field),
    ContDiff ℝ 1 field →
    ∃ P : PeriodicTrajectory field, P.orbitSet ⊆ D.omegaSet

/-- Consume a future proof of the planar omega-limit classification theorem. -/
theorem periodicTrajectory_in_omegaSet_of_classification
    (hPB : PoincareBendixsonOmegaClassificationTarget)
    {field : Phase2 → Phase2} (D : FlowTrappingData field)
    (hsmooth : ContDiff ℝ 1 field) :
    ∃ P : PeriodicTrajectory field, P.orbitSet ⊆ D.omegaSet :=
  hPB field D hsmooth

end Planar

end CRNT
