import CRNT.Oscillation.PlanarOmega
import CRNT.Oscillation.ReturnInterval

/-!
# Recurrent transversals for the planar Poincare--Bendixson route

The omega-limit preprocessing in `PlanarOmega` already supplies the compact, invariant,
equilibrium-free set on which the genuinely planar part of Poincare--Bendixson operates.  The
remaining geometric step is to find a transversal through a recurrent point and a compact interval
of that section whose positive return map is a continuous self-map.

This module makes that step explicit and closes everything after it.  In particular, once a
`RecurrentSectionData` object has been constructed, no further planar topology is needed: the
one-dimensional fixed-point theorem in `ReturnInterval` gives a genuine nonconstant periodic
trajectory immediately.
-/

namespace CRNT

namespace Planar

/-- A recurrent transversal extracted from a compact equilibrium-free omega-limit set.

The section carries the actual ambient field.  `returnInterval` contains all first-return facts on a
compact scalar interval, while `point_in_omega` records that the interval lies on the recurrent
omega-limit set rather than being an arbitrary local section. -/
structure RecurrentSectionData {field : Phase2 → Phase2}
    (D : FlowTrappingData field) where
  section : TransversalSection (E := Phase2)
  field_eq : section.field = field
  returnInterval : section.ReturnIntervalData
  point_in_omega : ∀ u ∈ Set.Icc returnInterval.left returnInterval.right,
    returnInterval.point u ∈ D.omegaSet

namespace RecurrentSectionData

variable {field : Phase2 → Phase2} {D : FlowTrappingData field}

/-- A recurrent return interval gives an exact nonconstant periodic trajectory of the original
planar field. -/
noncomputable theorem exists_periodicTrajectory
    (R : RecurrentSectionData D) : Nonempty (PeriodicTrajectory field) := by
  obtain ⟨P⟩ := R.returnInterval.exists_periodicTrajectory
  exact ⟨P.congrField R.field_eq⟩

/-- Witness-producing version, retaining that the periodic orbit is generated by the recurrent
section. -/
noncomputable theorem periodicTrajectory
    (R : RecurrentSectionData D) : ∃ P : PeriodicTrajectory field, True := by
  obtain ⟨P⟩ := R.exists_periodicTrajectory
  exact ⟨P, trivial⟩

end RecurrentSectionData

/-- The exact geometric residue of the planar Poincare--Bendixson theorem after omega-limit
compactness/invariance and the one-dimensional return-map fixed-point argument have been discharged.

A proof of this proposition needs to construct a recurrent transversal interval from a nonempty
compact invariant equilibrium-free omega-limit set of a `C¹` planar flow.  It does **not** need to
prove existence of a fixed point of the return map or close that fixed point into a periodic orbit;
those pieces are already formalized. -/
def RecurrentSectionConstructionTarget : Prop :=
  ∀ (field : Phase2 → Phase2) (D : FlowTrappingData field),
    ContDiff ℝ 1 field → Nonempty (RecurrentSectionData D)

/-- Constructing a recurrent interval alone yields periodicity, but not automatically the stronger
claim that the *entire* resulting orbit lies in the omega-limit set.  The latter needs compatibility
between the real-time section flow and the `NNReal` semiflow used to define `omegaSet`.  The stronger
object below records exactly that compatibility rather than silently assuming it. -/

/-- Stronger recurrent-section data carrying the precise orbit containment needed by
`PoincareBendixsonOmegaClassificationTarget`.

Only flow lines launched from the **certified return interval** are required to remain in the
omega-limit set.  Requiring every periodic orbit of the ambient field to lie in one omega-set would
be both unnecessary and generally false. -/
structure OmegaRecurrentSectionData {field : Phase2 → Phase2}
    (D : FlowTrappingData field) extends RecurrentSectionData D where
  intervalFlowInOmega :
    ∀ u ∈ Set.Icc returnInterval.left returnInterval.right, ∀ t : ℝ,
      section.flow (returnInterval.point u) t ∈ D.omegaSet

/-- Minimal theorem target for the remaining geometric Poincare--Bendixson step. -/
def OmegaRecurrentSectionConstructionTarget : Prop :=
  ∀ (field : Phase2 → Phase2) (D : FlowTrappingData field),
    ContDiff ℝ 1 field → Nonempty (OmegaRecurrentSectionData D)

/-- The stronger recurrent-section construction immediately proves the public omega-limit
classification target. -/
theorem poincareBendixsonOmegaClassification_of_omegaRecurrentSection
    (hsec : OmegaRecurrentSectionConstructionTarget) :
    PoincareBendixsonOmegaClassificationTarget := by
  intro field D hsmooth
  obtain ⟨R⟩ := hsec field D hsmooth
  let I := R.toRecurrentSectionData.returnInterval
  obtain ⟨u, hu, hufix⟩ := I.exists_scalar_fixedPoint
  let Psec : PeriodicTrajectory R.toRecurrentSectionData.section.field :=
    R.toRecurrentSectionData.section.periodicTrajectoryOfReturnMapFixedPoint
      (I.semigroup u hu)
      (I.flow_zero u hu)
      (I.returnMap_fixed_of_scalar_fixed hu hufix)
      (I.crossing_pos u hu)
      (I.field_ne_zero u hu)
  let P : PeriodicTrajectory field :=
    Psec.congrField R.toRecurrentSectionData.field_eq
  refine ⟨P, ?_⟩
  rintro x ⟨t, rfl⟩
  change Psec.orbit t ∈ D.omegaSet
  change R.toRecurrentSectionData.section.flow (I.point u) t ∈ D.omegaSet
  exact R.intervalFlowInOmega u hu t

end Planar

end CRNT
