#!/usr/bin/env python3
"""Generate `lakefile.toml` from `scripts/unverified_modules.txt`.

The previous lakefile enumerated all 449 verified modules by name, which meant a new
file was silently left out of the build unless someone remembered to add it.  This
inverts that: the library globs everything (`CRNT.+`) and the ledger is the only list
anyone maintains.  Two targets:

    CRNT           everything except the ledger  -- must build green
    CRNTFrontier   exactly the ledger            -- allowed to fail, error count tracked

Run after editing the ledger:

    python3 scripts/gen_lakefile.py
    python3 scripts/check_exclusions.py     # verifies the two are in sync
"""

from __future__ import annotations

import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LEDGER = os.path.join(ROOT, "scripts", "unverified_modules.txt")
LAKEFILE = os.path.join(ROOT, "lakefile.toml")

# Test modules that cannot build.  Kept tiny and explicit; same shrink-only rule.
UNVERIFIED_TESTS = [
    # Stale: five of its `#check`s name declarations that do not exist anywhere
    # (globalPersistenceCertificate_of_persistenceCertified, ...), and it imports
    # CRNT.Dynamics.GlobalPersistenceFrontier, which is itself unverified.
    "test.GlobalPersistenceSmoke",
    # Staged: imports CRNTFrontier, which does not elaborate yet.  Remove this line the
    # moment `lake build CRNTFrontier` is clean -- it is the acceptance test for the
    # oscillation development's central claim.
    "test.FrontierAudit",
    # Staged: imports CRNT.Examples.Lotka, which is still in the frontier target.  Holds the
    # strongest negative control for the exclusion route; move into test/NonVacuity.lean as soon
    # as the example elaborates.
    "test.LotkaNonVacuity",
]

MATHLIB_REV = "v4.34.0"


def read_ledger() -> list[str]:
    with open(LEDGER, encoding="utf-8") as fh:
        return [ln.strip() for ln in fh if ln.strip() and not ln.startswith("#")]


def toml_list(items: list[str], indent: int = 2) -> str:
    if not items:
        return "[]"
    pad = " " * indent
    body = ",\n".join(f'{pad}"{i}"' for i in items)
    return "[\n" + body + "\n]"


def main() -> int:
    unverified = read_ledger()
    frontier_globs = ["CRNTFrontier"] + unverified

    text = f"""# GENERATED by scripts/gen_lakefile.py -- do not edit by hand.
# The single source of truth for what is and is not verified is
# scripts/unverified_modules.txt.  Edit that, then regenerate.

name = "crnt-lean"
defaultTargets = ["CRNT"]
testRunner = "test"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "{MATHLIB_REV}"

# The verified core: everything under CRNT/ except the ledger.  Globbing by pattern
# (rather than enumerating modules) means a newly added file is in the build by default
# and has to be deliberately excluded, not the other way round.
[[lean_lib]]
name = "CRNT"
globs = ["CRNT", "CRNT.+"]
excludeGlobs = {toml_list(unverified)}

# The frontier: exactly the modules in the ledger.  Expected to fail; CI records the
# error count instead of gating on it.  See CRNTFrontier.lean.
[[lean_lib]]
name = "CRNTFrontier"
globs = {toml_list(frontier_globs)}

[[lean_lib]]
name = "test"
globs = ["test.+"]
excludeGlobs = {toml_list(UNVERIFIED_TESTS)}

[[lean_exe]]
name = "analyze"
root = "Analyze"
"""
    with open(LAKEFILE, "w", encoding="utf-8") as fh:
        fh.write(text)
    print(f"wrote lakefile.toml: {len(unverified)} excluded from CRNT, "
          f"{len(frontier_globs)} in CRNTFrontier, "
          f"{len(UNVERIFIED_TESTS)} test module(s) excluded")
    return 0


if __name__ == "__main__":
    sys.exit(main())
