#!/usr/bin/env python3
"""Probe the convex-geometry input needed by a *convex* polyhedral zero-separating surface.

Setting.  Craciun's toric differential inclusion is built from a polyhedral fan; the simplest and
most relevant case (v3, section 3) is the fan `F_H` generated by a finite set `H` of hyperplanes
through the origin, with normals `a_1, ..., a_m`.  Its cones are indexed by realizable sign
vectors ("covectors") `sigma in {-1,0,+1}^m`:

    C_sigma = { X : sigma_k (a_k . X) >= 0 for sigma_k != 0, a_k . X = 0 for sigma_k = 0 }.

A barrier of the form `g(X) = max_sigma (<n_sigma, X> - beta_sigma)` guards a convex polyhedron.
Lemma 9.5 of the paper forces `n_sigma in C_sigma`, and the max structure forces the *monotone
selection* property `<n_sigma, X> >= <n_tau, X>` for all `X in C_sigma`.  Those two together say
exactly: the `n_sigma` are the face points of a polytope whose normal fan refines `F_H`, each
lying inside its own normal cone.

`F_H` is the normal fan of the zonotope `Z_w = sum_j w_j [-a_j, a_j]` for ANY positive weights
`w`, since `h_{Z_w}(X) = sum_j w_j |a_j . X|` has the arrangement as its linearity decomposition.
The vertex of `Z_w` dual to a maximal covector `sigma` is `v_sigma(w) = sum_j w_j sigma_j a_j`, and

    v_sigma(w) in C_sigma   <=>   sigma_k ( a_k . v_sigma(w) ) >= 0  for every k,

which is **linear in w**.  This script asks three questions.

  Q1  Does the unweighted choice `w = 1` work?  (Answer: no.  An explicit witness is checked.)
  Q2  Is the weighted system ever infeasible?  If it always admits `w > 0` the convex route
      survives; if some arrangement admits no `w`, the convex route is dead and only a
      non-convex (tile-by-tile) surface can work.
  Q3  When feasible, is it feasible *strictly* (`> 0`, i.e. `v_sigma` in the relative interior of
      its cone) or only weakly (`= 0`, i.e. `v_sigma` on a wall)?  Strictness is what makes the
      maximal cone the unique argmax away from the walls.

Usage:  python3 scripts/probe_zonotope_cone_selection.py [trials]
"""

from __future__ import annotations

import itertools
import sys

import numpy as np
from scipy.optimize import linprog

RNG = np.random.default_rng(20260927)


def maximal_covectors(A: np.ndarray) -> list[np.ndarray]:
    """All sign vectors in {-1,+1}^m realized by some X with all a_k . X != 0.

    Enumerated by LP feasibility of the open system sigma_k (a_k . X) >= 1, which is
    equivalent to realizability since the system is homogeneous and scale invariant.
    """
    m, n = A.shape
    out = []
    for signs in itertools.product([-1, 1], repeat=m):
        s = np.array(signs, dtype=float)
        # feasibility of  -diag(s) A X <= -1
        res = linprog(
            c=np.zeros(n),
            A_ub=-(s[:, None] * A),
            b_ub=-np.ones(m),
            bounds=[(None, None)] * n,
            method="highs",
        )
        if res.status == 0:
            out.append(s)
    return out


def selection_constraints(A: np.ndarray, covectors: list[np.ndarray]) -> np.ndarray:
    """Rows `r` with the meaning `r . w >= 0`, one per (covector, coordinate) pair.

    For covector `sigma` and index `k` the requirement `sigma_k (a_k . sum_j w_j sigma_j a_j) >= 0`
    reads `sum_j w_j * sigma_k sigma_j (a_k . a_j) >= 0`.
    """
    G = A @ A.T
    rows = []
    for s in covectors:
        for k in range(A.shape[0]):
            rows.append(s[k] * s * G[k])
    return np.array(rows)


def unweighted_violations(A: np.ndarray, covectors: list[np.ndarray], tol=1e-9):
    M = selection_constraints(A, covectors)
    vals = M @ np.ones(A.shape[0])
    return int(np.sum(vals < -tol)), float(vals.min())


def weighted_feasibility(A: np.ndarray, covectors: list[np.ndarray], margin: float):
    """Maximize t subject to  M w >= t * 1,  1 <= w_j <= 1e6.

    `t > 0` means a strictly interior selection exists; `t = 0` means the best possible selection
    puts some vertex on a wall of its own cone; `t < 0` means no positive weighting works.
    """
    M = selection_constraints(A, covectors)
    m = A.shape[0]
    # variables (w, t); maximize t  ==>  minimize -t
    c = np.concatenate([np.zeros(m), [-1.0]])
    A_ub = np.hstack([-M, np.ones((M.shape[0], 1))])
    b_ub = np.zeros(M.shape[0])
    bounds = [(1.0, 1e6)] * m + [(None, margin)]
    res = linprog(c=c, A_ub=A_ub, b_ub=b_ub, bounds=bounds, method="highs")
    if res.status != 0:
        return None, None
    return float(res.x[-1]), res.x[:m]


def q1_explicit_witness():
    """The unweighted zonotope vertex can fall outside its own normal cone."""
    degs = list(range(0, 11)) + [178]
    A = np.array([[np.cos(np.deg2rad(d)), np.sin(np.deg2rad(d))] for d in degs])
    s = np.ones(len(degs))
    # realizability of the all-positive covector
    res = linprog(
        c=np.zeros(2), A_ub=-(s[:, None] * A), b_ub=-np.ones(len(degs)),
        bounds=[(None, None)] * 2, method="highs")
    v = A.T @ s
    dots = A @ v
    print("Q1  explicit witness: 11 normals at 0..10 degrees plus one at 178 degrees")
    print(f"    all-positive covector realizable : {res.status == 0}")
    print(f"    v_sigma = sum_j a_j             : {np.round(v, 5)}")
    print(f"    min_k sigma_k (a_k . v_sigma)   : {dots.min():.5f}"
          f"   (attained at index {int(np.argmin(dots))}, normal at {degs[int(np.argmin(dots))]} deg)")
    print(f"    => unweighted selection {'FAILS' if dots.min() < 0 else 'holds'}")
    return A


def q4_exact_witness_dim3():
    """An exact, RNG-free proof that no positive weighting works in dimension three.

    Take three unit normals in `R^3` with all pairwise inner products equal to `c = 3/5`.  The
    Gram matrix `[[1,c,c],[c,1,c],[c,c,1]]` has eigenvalues `1 + 2c = 11/5` and `1 - c = 2/5`, so
    it is positive definite and the three vectors are a basis; consequently **all eight** sign
    vectors are realizable.

    Realizability of every sign vector means that for each `k` the products `sigma_k sigma_j`
    (`j != k`) take all sign patterns, so the selection constraints
    `w_k |a_k|^2 + sum_{j != k} w_j sigma_k sigma_j (a_k . a_j) >= 0` collapse to strict diagonal
    dominance

        w_k  >=  c * sum_{j != k} w_j      for k = 1, 2, 3.

    Summing the three inequalities gives `W >= 2 c W = (6/5) W` with `W = w_1 + w_2 + w_3 > 0`,
    i.e. `W <= 0` -- a contradiction.  The obstruction is exact and needs `c >= 1/2` only.
    """
    from fractions import Fraction as Fr

    c = Fr(3, 5)
    G = [[Fr(1) if i == j else c for j in range(3)] for i in range(3)]
    # positive definiteness via leading principal minors
    m1 = G[0][0]
    m2 = G[0][0] * G[1][1] - G[0][1] * G[1][0]
    m3 = (G[0][0] * (G[1][1] * G[2][2] - G[1][2] * G[2][1])
          - G[0][1] * (G[1][0] * G[2][2] - G[1][2] * G[2][0])
          + G[0][2] * (G[1][0] * G[2][1] - G[1][1] * G[2][0]))
    print("\nQ4  exact witness in dimension 3 (pairwise inner product c = 3/5)")
    print(f"    leading principal minors of the Gram matrix: {m1}, {m2}, {m3}"
          f"   (all > 0: {m1 > 0 and m2 > 0 and m3 > 0})")
    print("    => the three normals are a basis, so all 8 sign vectors are realizable")
    print(f"    => selection forces  w_k >= {c} * (w_i + w_j)  for each k")
    print(f"    => summing:  W >= {2 * c} * W  with W > 0, i.e. W <= 0.  Contradiction.")
    print("    => NO positive weighting of the zonotope works.  Exact, no floating point.")
    # cross-check the same arrangement numerically through the LP
    L = np.linalg.cholesky(np.array([[float(x) for x in row] for row in G]))
    A = L  # rows have the prescribed Gram matrix
    cov = maximal_covectors(A)
    t, _ = weighted_feasibility(A, cov, margin=10.0)
    print(f"    LP cross-check: {len(cov)} maximal covectors, best margin t = {t:.6f}"
          f"  ({'INFEASIBLE' if t < -1e-9 else 'feasible'})")


def main() -> int:
    trials = int(sys.argv[1]) if len(sys.argv) > 1 else 40
    A_wit = q1_explicit_witness()

    print("\nQ2/Q3  does a positive weighting repair it?")
    cov = maximal_covectors(A_wit)
    t, w = weighted_feasibility(A_wit, cov, margin=10.0)
    print(f"    witness arrangement: {len(cov)} maximal covectors, best margin t = {t:.3e}")
    if t is not None:
        kind = "strict" if t > 1e-7 else ("weak (some vertex on a wall)" if t > -1e-7 else "INFEASIBLE")
        print(f"    => weighted selection: {kind}")

    q4_exact_witness_dim3()

    print("\nQ2/Q3  random arrangements")
    print(f"    {'dim':>3} {'m':>3} {'covectors':>10} {'w=1 viol':>9} {'best t':>12}  verdict")
    worst = None
    for _ in range(trials):
        n = int(RNG.integers(2, 5))
        m = int(RNG.integers(n, n + 4))
        A = RNG.normal(size=(m, n))
        # occasionally force a near-degenerate cluster of almost parallel normals
        if RNG.random() < 0.5 and m >= 3:
            base = A[0] / np.linalg.norm(A[0])
            for j in range(1, min(m, 3)):
                A[j] = base + 0.02 * RNG.normal(size=n)
        A /= np.linalg.norm(A, axis=1, keepdims=True)
        cov = maximal_covectors(A)
        if not cov:
            continue
        nviol, vmin = unweighted_violations(A, cov)
        t, _ = weighted_feasibility(A, cov, margin=10.0)
        if t is None:
            verdict = "LP failed"
        elif t > 1e-7:
            verdict = "strict"
        elif t > -1e-7:
            verdict = "weak"
        else:
            verdict = "INFEASIBLE"
        if worst is None or (t is not None and t < worst[0]):
            worst = (t, n, m, A.copy())
        print(f"    {n:>3} {m:>3} {len(cov):>10} {nviol:>9} {t:>12.3e}  {verdict}")

    if worst is not None:
        print(f"\n    worst margin over trials: t = {worst[0]:.3e} in dimension {worst[1]}"
              f" with {worst[2]} hyperplanes")
        print("    (t <= 0 means no strictly interior convex selection exists for that"
              " arrangement,\n     so the max-of-affine barrier must be replaced by a non-convex"
              " one.)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
