import CRNT.Stability.BDC
import CRNT.Deficiency.KernelDimension

/-!
# Robust piecewise-linear Lyapunov certificates in reaction-rate coordinates

Following Al-Radhawi--Angeli--Sontag, write the dynamics in reaction-rate coordinates
`z = R(x)`.  The structural linearized family is the positive cone generated by the
rank-one matrices

`Q_(r,s) = e_r (row_s S)`

for every reaction--reactant pair `(r,s)`.  This file formalizes those extremals and a
finite active-piece certificate for a convex PWL common Lyapunov function.  It contains
no LP/search algorithm: a candidate family of pieces is simply a mathematical
certificate.
-/

namespace CRNT
namespace Network

open scoped BigOperators

variable {S K : Type} [DecidableEq S] [Fintype S]
  [DecidableEq K] [Fintype K]

/-- Reaction-rate-coordinate rank-one extremal `Q_(r,s) = e_r row_s(S)`. -/
def rateCoordinateExtremal (N : Network S) (r : N.R) (s : S) :
    Matrix N.R N.R ℝ :=
  fun a b => if a = r then N.reactionVector b s else 0

/-- Action of one rate-coordinate extremal. -/
def rateCoordinateExtremalAction (N : Network S) (r : N.R) (s : S)
    (z : N.R → ℝ) : N.R → ℝ :=
  (N.rateCoordinateExtremal r s).mulVec z

@[simp] theorem rateCoordinateExtremalAction_apply (N : Network S)
    (r a : N.R) (s : S) (z : N.R → ℝ) :
    N.rateCoordinateExtremalAction r s z a =
      if a = r then N.stoichMap z s else 0 := by
  unfold rateCoordinateExtremalAction Matrix.mulVec
  by_cases h : a = r
  · subst a
    simp only [rateCoordinateExtremal, if_pos]
    rw [dotProduct_comm, stoichMap_apply]
    rfl
  · simp [rateCoordinateExtremal, h]

/-- Reaction-rate-coordinate structural generator for a family of nonnegative
rate derivatives. -/
def rateCoordinateGenerator (N : Network S) (d : N.R → S → ℝ) :
    Matrix N.R N.R ℝ :=
  fun a b => ∑ s : S, d a s * N.reactionVector b s

/-- The structural rate-coordinate generator is the conic sum of rank-one extremals. -/
theorem rateCoordinateGenerator_eq_sum_extremals (N : Network S)
    (d : N.R → S → ℝ) :
    N.rateCoordinateGenerator d =
      ∑ r : N.R, ∑ s : S, d r s • N.rateCoordinateExtremal r s := by
  ext a b
  change (∑ s : S, d a s * N.reactionVector b s) =
    (∑ r ∈ Finset.univ, ∑ s ∈ Finset.univ, d r s • N.rateCoordinateExtremal r s) a b
  simp_rw [Matrix.sum_apply]
  simp [rateCoordinateExtremal]

/-- Pairing of a PWL coefficient row with a reaction-rate vector. -/
def ratePairing {N : Network S} (c z : N.R → ℝ) : ℝ :=
  ∑ r : N.R, c r * z r

/-- Piece `k` is active at `z` when it maximizes the finite family of linear forms. -/
def IsActiveRatePiece {N : Network S} (C : K → (N.R → ℝ)) (k : K)
    (z : N.R → ℝ) : Prop :=
  ∀ j : K, ratePairing (C j) z ≤ ratePairing (C k) z

/-- Structural PWL decay certificate: every active piece has nonpositive directional
slope along every admissible rank-one extremal. -/
def IsRobustPWLDecayCertificate (N : Network S) (C : K → (N.R → ℝ)) : Prop :=
  ∀ (k : K) (z : N.R → ℝ), IsActiveRatePiece C k z →
    ∀ r : N.R, ∀ s : S, N.IsReactantPair r s →
      ratePairing (C k) (N.rateCoordinateExtremalAction r s z) ≤ 0

/-- A stronger strict certificate away from the stationary-flux subspace. -/
def IsStrictRobustPWLDecayCertificate (N : Network S) (C : K → (N.R → ℝ)) : Prop :=
  ∀ (k : K) (z : N.R → ℝ), IsActiveRatePiece C k z → N.stoichMap z ≠ 0 →
    ∀ r : N.R, ∀ s : S, N.IsReactantPair r s →
      ratePairing (C k) (N.rateCoordinateExtremalAction r s z) ≤ 0 ∧
      (N.rateCoordinateExtremalAction r s z ≠ 0 →
        ratePairing (C k) (N.rateCoordinateExtremalAction r s z) < 0)

/-- Closed monotone reactivities are nonnegative on every reactant pair. -/
theorem closedAdmissible_nonneg_on_pair (N : Network S)
    {d : N.R → S → ℝ} (hd : N.IsClosedAdmissibleReactivity d)
    {r : N.R} {s : S} (hrs : N.IsReactantPair r s) :
    0 ≤ d r s := by
  simpa [IsClosedAdmissibleReactivity, hrs] using hd r s

/-- Closed monotone reactivities vanish away from reactant pairs. -/
theorem closedAdmissible_eq_zero_off_pair (N : Network S)
    {d : N.R → S → ℝ} (hd : N.IsClosedAdmissibleReactivity d)
    {r : N.R} {s : S} (hrs : ¬ N.IsReactantPair r s) :
    d r s = 0 := by
  simpa [IsClosedAdmissibleReactivity, hrs] using hd r s

/-- Pairing with the full structural generator expands as the nonnegative conic sum of
pairings with the rank-one extremals. -/
theorem ratePairing_generator_mulVec (N : Network S)
    (c z : N.R → ℝ) (d : N.R → S → ℝ) :
    ratePairing c ((N.rateCoordinateGenerator d).mulVec z) =
      ∑ r : N.R, ∑ s : S,
        d r s * ratePairing c (N.rateCoordinateExtremalAction r s z) := by
  simp only [ratePairing, rateCoordinateGenerator, Matrix.mulVec,
    rateCoordinateExtremalAction_apply, stoichMap_apply, dotProduct]
  simp only [Finset.mul_sum, Finset.sum_mul]
  simp
  simp_rw [Finset.mul_sum]
  apply Finset.sum_congr rfl
  intro r _
  rw [Finset.sum_comm]
  apply Finset.sum_congr rfl
  intro s _
  apply Finset.sum_congr rfl
  intro q _
  ring


/-- **Common-Lyapunov cone theorem.**  An active-piece certificate checked only on the
finite rank-one extremals automatically holds for every closed admissible monotone
reactivity matrix. -/
theorem robustPWL_decay_on_structural_cone
    (N : Network S) {C : K → (N.R → ℝ)}
    (hC : N.IsRobustPWLDecayCertificate C)
    {d : N.R → S → ℝ} (hd : N.IsClosedAdmissibleReactivity d)
    {k : K} {z : N.R → ℝ} (hk : IsActiveRatePiece C k z) :
    ratePairing (C k) ((N.rateCoordinateGenerator d).mulVec z) ≤ 0 := by
  rw [N.ratePairing_generator_mulVec (C k) z d]
  refine Finset.sum_nonpos fun r _ => Finset.sum_nonpos fun s _ => ?_
  by_cases hrs : N.IsReactantPair r s
  · exact mul_nonpos_of_nonneg_of_nonpos
      (N.closedAdmissible_nonneg_on_pair hd hrs)
      (hC k z hk r s hrs)
  · rw [N.closedAdmissible_eq_zero_off_pair hd hrs, zero_mul]

/-- A PWL family is positive definite modulo stationary reaction fluxes when zero value
of every piece is equivalent to `S z = 0`.  This is the natural CRNT null set for a
reaction-coordinate robust Lyapunov function. -/
def IsRatePWLPositiveDefiniteModuloFlux (N : Network S)
    (C : K → (N.R → ℝ)) : Prop :=
  ∀ z : N.R → ℝ,
    (∀ k : K, ratePairing (C k) z ≤ 0) ↔ N.stoichMap z = 0

/-- Package of the two theorem-level obligations defining a robust PWL Lyapunov
certificate. -/
structure RobustPWLLyapunovCertificate (N : Network S) (K : Type)
    [DecidableEq K] [Fintype K] where
  pieces : K → (N.R → ℝ)
  decay : N.IsRobustPWLDecayCertificate pieces
  positiveDefinite : N.IsRatePWLPositiveDefiniteModuloFlux pieces

/-- Every robust PWL certificate gives active-piece decay for every admissible structural
generator. -/
theorem RobustPWLLyapunovCertificate.decay_structural
    {N : Network S} (C : RobustPWLLyapunovCertificate N K)
    {d : N.R → S → ℝ} (hd : N.IsClosedAdmissibleReactivity d)
    {k : K} {z : N.R → ℝ} (hk : IsActiveRatePiece C.pieces k z) :
    ratePairing (C.pieces k) ((N.rateCoordinateGenerator d).mulVec z) ≤ 0 :=
  N.robustPWL_decay_on_structural_cone C.decay hd hk

/-- Duality-ready transpose extremal.  The transpose exchanges the reaction selector and
the stoichiometric row and is the basic algebraic object in dual-CRN theory. -/
def rateCoordinateDualExtremal (N : Network S) (r : N.R) (s : S) :
    Matrix N.R N.R ℝ :=
  Matrix.transpose (N.rateCoordinateExtremal r s)

@[simp] theorem dualExtremal_transpose (N : Network S) (r : N.R) (s : S) :
    Matrix.transpose (N.rateCoordinateDualExtremal r s) = N.rateCoordinateExtremal r s := by
  simp [rateCoordinateDualExtremal]

end Network
end CRNT
