import CRNT.Decomposition.ReactionPartition
import CRNT.LinearAlgebra.FinrankSup

/-!
# Rank identities for Feinberg reaction decompositions

This module supplies the linear-algebra bookkeeping behind the classical decomposition
theorems.  For a finite partition of the reaction set, the full stoichiometric and
incidence spaces are finite joins of the corresponding block spaces.  Stoichiometric
independence and incidence independence therefore become exact rank-additivity
statements.
-/

namespace CRNT
namespace Network
namespace ReactionPartition

open scoped BigOperators

variable {S : Type} [DecidableEq S] [Fintype S]
variable {N : Network S} {ι : Type} [DecidableEq ι] [Fintype ι]

/-- Finite-family subadditivity of `finrank` over a supremum of submodules.  Mathlib has the
binary form (`Submodule.finrank_sup_add_finrank_inf_eq`) but no `finrank_iSup_le_sum_finrank`,
so it is derived here by induction over the index `Finset`. -/
theorem finrank_iSup_le_sum_finrank {V : Type*} [AddCommGroup V] [Module ℝ V]
    [FiniteDimensional ℝ V] (p : ι → Submodule ℝ V) :
    Module.finrank ℝ ↥(⨆ i, p i) ≤ ∑ i : ι, Module.finrank ℝ ↥(p i) := by
  classical
  have key : ∀ t : Finset ι,
      Module.finrank ℝ ↥(⨆ i ∈ t, p i) ≤ ∑ i ∈ t, Module.finrank ℝ ↥(p i) := by
    intro t
    induction t using Finset.induction with
    | empty => simp
    | insert a t ha ih =>
        have hsup : (⨆ i ∈ insert a t, p i) = p a ⊔ ⨆ i ∈ t, p i := by
          rw [Finset.iSup_insert]
        have hle : Module.finrank ℝ ↥(p a ⊔ ⨆ i ∈ t, p i)
            ≤ Module.finrank ℝ ↥(p a) + Module.finrank ℝ ↥(⨆ i ∈ t, p i) := by
          have h := Submodule.finrank_sup_add_finrank_inf_eq (p a) (⨆ i ∈ t, p i)
          omega
        rw [hsup, Finset.sum_insert ha]
        exact hle.trans (by omega)
  have huniv : (⨆ i, p i) = ⨆ i ∈ (Finset.univ : Finset ι), p i := by simp
  rw [huniv]
  simpa using key Finset.univ

/-- The full stoichiometric rank is bounded by the sum of the block ranks. -/
theorem stoichRank_le_sum_blockStoichRank (D : ReactionPartition N ι) :
    N.stoichRank ≤ ∑ i : ι, D.blockStoichRank i := by
  rw [Network.stoichRank, D.stoichSubspace_eq_span_blocks]
  exact finrank_iSup_le_sum_finrank _

/-- The full incidence space is generated by the block incidence spaces. -/
theorem incidenceRange_eq_span_blocks (D : ReactionPartition N ι) :
    LinearMap.range N.incidenceMap = ⨆ i, D.blockIncidenceSubspace i := by
  apply le_antisymm
  · rintro y ⟨v, rfl⟩
    have hsum : N.incidenceMap v =
        ∑ r : N.R, v r • (fun c =>
          (if N.targetIdx r = c then (1 : ℝ) else 0) -
          (if N.sourceIdx r = c then 1 else 0)) := by
      funext c
      simp [Network.incidenceMap_apply, Finset.sum_apply, Pi.smul_apply, smul_eq_mul]
    rw [hsum]
    apply Submodule.sum_mem
    intro r hr
    obtain ⟨i, hri⟩ := D.exists_block r
    apply (le_iSup (fun i => D.blockIncidenceSubspace i) i)
    exact Submodule.smul_mem _ _ (Submodule.subset_span ⟨r, hri, rfl⟩)
  · refine iSup_le ?_
    intro i
    rw [blockIncidenceSubspace, Submodule.span_le]
    rintro w ⟨r, hr, rfl⟩
    refine ⟨Pi.single r 1, ?_⟩
    funext c
    rw [Network.incidenceMap_apply, Finset.sum_eq_single r]
    · simp
    · intro b hb hbr
      simp [hbr]
    · simp

/-- The decomposition definition of stoichiometric independence agrees with Mathlib's
`iSupIndep` for the finite family of block stoichiometric subspaces. -/
theorem stoichIndependent_iff_iSupIndep (D : ReactionPartition N ι) :
    D.StoichIndependent ↔ iSupIndep (fun i => D.blockStoichSubspace i) := by
  constructor
  · intro h
    rw [iSupIndep_iff_finsetSum_eq_zero_imp_eq_zero]
    intro s v hv hsum i hi
    let z : ι → (S → ℝ) := fun j => if j ∈ s then v j else 0
    have hzmem : ∀ j, z j ∈ D.blockStoichSubspace j := by
      intro j
      by_cases hj : j ∈ s
      · simpa [z, hj] using hv j hj
      · simp [z, hj]
    have hzsum : (∑ j, z j) = 0 := by
      simpa [z] using hsum
    have hz0 := h z hzmem hzsum i
    simpa [z, hi] using hz0
  · intro h z hzmem hzsum i
    have hh := (iSupIndep_iff_finsetSum_eq_zero_imp_eq_zero
      (fun i => D.blockStoichSubspace i)).mp h
    exact hh Finset.univ z (fun j _ => hzmem j) hzsum i (Finset.mem_univ i)

/-- The decomposition definition of incidence independence agrees with Mathlib's
`iSupIndep` for the finite family of block incidence subspaces. -/
theorem incidenceIndependent_iff_iSupIndep (D : ReactionPartition N ι) :
    D.IncidenceIndependent ↔ iSupIndep (fun i => D.blockIncidenceSubspace i) := by
  constructor
  · intro h
    rw [iSupIndep_iff_finsetSum_eq_zero_imp_eq_zero]
    intro s v hv hsum i hi
    let z : ι → (N.ComplexIdx → ℝ) := fun j => if j ∈ s then v j else 0
    have hzmem : ∀ j, z j ∈ D.blockIncidenceSubspace j := by
      intro j
      by_cases hj : j ∈ s
      · simpa [z, hj] using hv j hj
      · simp [z, hj]
    have hzsum : (∑ j, z j) = 0 := by
      simpa [z] using hsum
    have hz0 := h z hzmem hzsum i
    simpa [z, hi] using hz0
  · intro h z hzmem hzsum i
    have hh := (iSupIndep_iff_finsetSum_eq_zero_imp_eq_zero
      (fun i => D.blockIncidenceSubspace i)).mp h
    exact hh Finset.univ z (fun j _ => hzmem j) hzsum i (Finset.mem_univ i)

/-- Incidence rank is subadditive over a reaction decomposition. -/
theorem incidenceRank_le_sum_blockIncidenceRank (D : ReactionPartition N ι) :
    N.incidenceRank ≤ ∑ i : ι, D.blockIncidenceRank i := by
  rw [Network.incidenceRank, D.incidenceRange_eq_span_blocks]
  exact finrank_iSup_le_sum_finrank _

/-- Stoichiometric independence gives exact rank additivity. -/
theorem sum_blockStoichRank_eq_stoichRank_of_independent
    (D : ReactionPartition N ι) (h : D.StoichIndependent) :
    (∑ i : ι, D.blockStoichRank i) = N.stoichRank := by
  rw [Network.stoichRank, D.stoichSubspace_eq_span_blocks]
  exact (CRNT.finrank_iSup_eq_sum_of_iSupIndep _
    ((D.stoichIndependent_iff_iSupIndep).mp h)).symm

/-- Incidence independence gives exact incidence-rank additivity. -/
theorem sum_blockIncidenceRank_eq_incidenceRank_of_independent
    (D : ReactionPartition N ι) (h : D.IncidenceIndependent) :
    (∑ i : ι, D.blockIncidenceRank i) = N.incidenceRank := by
  rw [Network.incidenceRank, D.incidenceRange_eq_span_blocks]
  exact (CRNT.finrank_iSup_eq_sum_of_iSupIndep _
    ((D.incidenceIndependent_iff_iSupIndep).mp h)).symm

/-- Equivalent numerical formulation of stoichiometric independence. -/
theorem stoichIndependent_iff_rank_additive (D : ReactionPartition N ι) :
    D.StoichIndependent ↔ (∑ i : ι, D.blockStoichRank i) = N.stoichRank := by
  rw [D.stoichIndependent_iff_iSupIndep]
  rw [Network.stoichRank, D.stoichSubspace_eq_span_blocks]
  unfold blockStoichRank
  constructor
  · intro h
    exact (CRNT.finrank_iSup_eq_sum_of_iSupIndep _ h).symm
  · intro h
    apply CRNT.iSupIndep_of_finrank_iSup_eq_sum
    exact h.symm

/-- Equivalent numerical formulation of incidence independence. -/
theorem incidenceIndependent_iff_rank_additive (D : ReactionPartition N ι) :
    D.IncidenceIndependent ↔ (∑ i : ι, D.blockIncidenceRank i) = N.incidenceRank := by
  rw [D.incidenceIndependent_iff_iSupIndep]
  rw [Network.incidenceRank, D.incidenceRange_eq_span_blocks]
  unfold blockIncidenceRank
  constructor
  · intro h
    exact (CRNT.finrank_iSup_eq_sum_of_iSupIndep _ h).symm
  · intro h
    apply CRNT.iSupIndep_of_finrank_iSup_eq_sum
    exact h.symm

/-- Bi-independence is simultaneous rank additivity on the stoichiometric and incidence
sides. -/
theorem biIndependent_iff_rank_additive (D : ReactionPartition N ι) :
    D.BiIndependent ↔
      ((∑ i : ι, D.blockStoichRank i) = N.stoichRank ∧
       (∑ i : ι, D.blockIncidenceRank i) = N.incidenceRank) := by
  constructor
  · intro h
    exact ⟨D.sum_blockStoichRank_eq_stoichRank_of_independent h.1,
      D.sum_blockIncidenceRank_eq_incidenceRank_of_independent h.2⟩
  · intro h
    exact ⟨(D.stoichIndependent_iff_rank_additive).2 h.1,
      (D.incidenceIndependent_iff_rank_additive).2 h.2⟩

/-- The complex map sends the incidence vector of a single reaction to its reaction vector.
This is `complexMap ∘ incidenceMap = stoichMap` read off one reaction at a time. -/
theorem complexMap_incidenceVector (N : Network S) (r : N.R) :
    N.complexMap (fun c => (if N.targetIdx r = c then (1 : ℝ) else 0) -
      (if N.sourceIdx r = c then 1 else 0)) = N.reactionVector r := by
  funext s
  simp only [Network.complexMap, LinearMap.coe_mk, AddHom.coe_mk, sub_mul,
    reactionVector_apply]
  rw [Finset.sum_sub_distrib]
  simp only [ite_mul, one_mul, zero_mul,
    Finset.sum_ite_eq Finset.univ (N.targetIdx r) (fun c => ((c.val s : ℕ) : ℝ)),
    Finset.sum_ite_eq Finset.univ (N.sourceIdx r) (fun c => ((c.val s : ℕ) : ℝ))]
  simp [targetIdx, sourceIdx]

/-- The block stoichiometric subspace is exactly the image of the block incidence subspace. -/
theorem map_complexMap_blockIncidence (D : ReactionPartition N ι) (i : ι) :
    Submodule.map N.complexMap (D.blockIncidenceSubspace i) = D.blockStoichSubspace i := by
  apply le_antisymm
  · -- generators map to generators
    rw [blockIncidenceSubspace, Submodule.map_span]
    refine Submodule.span_le.mpr ?_
    rintro v ⟨w, ⟨r, hr, rfl⟩, rfl⟩
    exact Submodule.subset_span ⟨r, hr, (complexMap_incidenceVector N r).symm⟩
  · -- every reaction vector is the image of its own incidence vector
    rw [blockStoichSubspace]
    refine Submodule.span_le.mpr ?_
    rintro v ⟨r, hr, rfl⟩
    exact ⟨_, Submodule.subset_span ⟨r, hr, rfl⟩, complexMap_incidenceVector N r⟩

/-- The complex map sends the block incidence space into the block stoichiometric
subspace. -/
theorem complexMap_blockIncidence_le_blockStoich (D : ReactionPartition N ι) (i : ι) :
    Submodule.map N.complexMap (D.blockIncidenceSubspace i) ≤ D.blockStoichSubspace i :=
  le_of_eq (D.map_complexMap_blockIncidence i)

/-- Each block stoichiometric rank is at most its block incidence rank. -/
theorem blockStoichRank_le_blockIncidenceRank (D : ReactionPartition N ι) (i : ι) :
    D.blockStoichRank i ≤ D.blockIncidenceRank i := by
  unfold blockStoichRank blockIncidenceRank
  rw [← D.map_complexMap_blockIncidence i]
  exact Submodule.finrank_map_le _ _


end ReactionPartition
end Network
end CRNT
