import CRNT.Deficiency.KernelDimension
import Mathlib.LinearAlgebra.Dimension.Finrank

/-!
# Reaction decompositions

A CRN decomposition is a partition of the reaction set into finitely many blocks.
Each block has a stoichiometric subspace and an incidence subspace.  A decomposition is
**stoichiometrically independent** when a vanishing sum of vectors chosen from the block
stoichiometric subspaces forces every block vector to vanish.  Incidence independence is
the analogous graph-level property.

This formulation captures exactly the linear algebra used by Feinberg decomposition
theory without introducing any numerical solver or temporary model format.
-/

namespace CRNT

namespace Network

open scoped BigOperators

variable {S : Type} [DecidableEq S] [Fintype S]

/-- A finite partition of the reaction index type. -/
structure ReactionPartition (N : Network S) (ι : Type) [DecidableEq ι] [Fintype ι] where
  block : ι → Finset N.R
  disjoint : ∀ i j, i ≠ j → Disjoint (block i) (block j)
  covers : (Finset.univ.biUnion block) = Finset.univ

namespace ReactionPartition

variable {N : Network S} {ι : Type} [DecidableEq ι] [Fintype ι]

/-- Every reaction belongs to at least one block. -/
theorem exists_block (D : ReactionPartition N ι) (r : N.R) :
    ∃ i, r ∈ D.block i := by
  have hr : r ∈ (Finset.univ : Finset N.R) := Finset.mem_univ r
  rw [← D.covers, Finset.mem_biUnion] at hr
  simpa using hr

/-- A reaction belongs to at most one block. -/
theorem block_unique (D : ReactionPartition N ι) {r : N.R} {i j : ι}
    (hi : r ∈ D.block i) (hj : r ∈ D.block j) : i = j := by
  by_contra hij
  have hd := D.disjoint i j hij
  exact Finset.disjoint_left.mp hd hi hj

/-- Stoichiometric subspace generated by one reaction block. -/
def blockStoichSubspace (D : ReactionPartition N ι) (i : ι) : Submodule ℝ (S → ℝ) :=
  Submodule.span ℝ {v | ∃ r ∈ D.block i, N.reactionVector r = v}

/-- Incidence subspace generated by one reaction block. -/
def blockIncidenceSubspace (D : ReactionPartition N ι) (i : ι) :
    Submodule ℝ (N.ComplexIdx → ℝ) :=
  Submodule.span ℝ {v | ∃ r ∈ D.block i,
    (fun c => (if N.targetIdx r = c then (1 : ℝ) else 0) -
      (if N.sourceIdx r = c then 1 else 0)) = v}

/-- Block stoichiometric rank. -/
noncomputable def blockStoichRank (D : ReactionPartition N ι) (i : ι) : ℕ :=
  Module.finrank ℝ (D.blockStoichSubspace i)

/-- Block incidence rank. -/
noncomputable def blockIncidenceRank (D : ReactionPartition N ι) (i : ι) : ℕ :=
  Module.finrank ℝ (D.blockIncidenceSubspace i)

/-- Stoichiometric contribution of block `i` for an arbitrary reaction-rate vector `v`. -/
def blockStoichContribution (D : ReactionPartition N ι) (i : ι) (v : N.R → ℝ) : S → ℝ :=
  ∑ r ∈ D.block i, v r • N.reactionVector r

/-- Incidence contribution of block `i`. -/
def blockIncidenceContribution (D : ReactionPartition N ι) (i : ι)
    (v : N.R → ℝ) : N.ComplexIdx → ℝ :=
  ∑ r ∈ D.block i, v r •
    (fun c => (if N.targetIdx r = c then (1 : ℝ) else 0) -
      (if N.sourceIdx r = c then 1 else 0))

/-- Every block stoichiometric contribution lies in its block subspace. -/
theorem blockStoichContribution_mem (D : ReactionPartition N ι) (i : ι)
    (v : N.R → ℝ) : D.blockStoichContribution i v ∈ D.blockStoichSubspace i := by
  apply Submodule.sum_mem
  intro r hr
  apply Submodule.smul_mem
  exact Submodule.subset_span ⟨r, hr, rfl⟩

/-- The whole stoichiometric map is the sum of block contributions. -/
theorem sum_blockStoichContribution (D : ReactionPartition N ι) (v : N.R → ℝ) :
    (∑ i : ι, D.blockStoichContribution i v) = N.stoichMap v := by
  funext s
  simp only [blockStoichContribution, Finset.sum_apply, Pi.smul_apply, smul_eq_mul,
    stoichMap_apply]
  -- rearrange the finite partition sum
  rw [← Finset.sum_biUnion]
  · simpa [D.covers]
  · intro i hi j hj hij
    exact D.disjoint i j hij

/-- Stoichiometric independence: the sum of vectors drawn from distinct block
stoichiometric subspaces can vanish only componentwise. -/
def StoichIndependent (D : ReactionPartition N ι) : Prop :=
  ∀ z : ι → (S → ℝ),
    (∀ i, z i ∈ D.blockStoichSubspace i) →
    (∑ i, z i) = 0 →
    ∀ i, z i = 0

/-- Incidence independence. -/
def IncidenceIndependent (D : ReactionPartition N ι) : Prop :=
  ∀ z : ι → (N.ComplexIdx → ℝ),
    (∀ i, z i ∈ D.blockIncidenceSubspace i) →
    (∑ i, z i) = 0 →
    ∀ i, z i = 0

/-- Bi-independence in Feinberg's sense. -/
def BiIndependent (D : ReactionPartition N ι) : Prop :=
  D.StoichIndependent ∧ D.IncidenceIndependent

/-- **Steady-state decomposition theorem.** Under stoichiometric independence, global
stationarity of an arbitrary reaction-rate vector is equivalent to stationarity of every
reaction block separately. -/
theorem stationary_iff_blocks_stationary (D : ReactionPartition N ι)
    (hind : D.StoichIndependent) (v : N.R → ℝ) :
    N.stoichMap v = 0 ↔ ∀ i, D.blockStoichContribution i v = 0 := by
  constructor
  · intro h
    apply hind (fun i => D.blockStoichContribution i v)
    · exact fun i => D.blockStoichContribution_mem i v
    · rw [D.sum_blockStoichContribution v, h]
  · intro h
    rw [← D.sum_blockStoichContribution v]
    simp [h]

/-- The full stoichiometric subspace is generated by the block subspaces. -/
theorem stoichSubspace_eq_span_blocks (D : ReactionPartition N ι) :
    N.stoichSubspace = ⨆ i, D.blockStoichSubspace i := by
  apply le_antisymm
  · rw [stoichSubspace, Submodule.span_le]
    rintro v ⟨r, rfl⟩
    obtain ⟨i, hri⟩ := D.exists_block r
    exact le_iSup (fun i => D.blockStoichSubspace i) i
      (Submodule.subset_span ⟨r, hri, rfl⟩)
  · refine iSup_le ?_
    intro i
    rw [blockStoichSubspace, Submodule.span_le]
    rintro v ⟨r, hr, rfl⟩
    exact N.reactionVector_mem_stoichSubspace r

end ReactionPartition

end Network

end CRNT
