name: CI

on:
  push:
    branches: [master]
    paths:
      - '**.lean'
      - 'lakefile.toml'
      - 'lake-manifest.json'
      - 'lean-toolchain'
      - '.github/workflows/ci.yml'
  pull_request:
    paths:
      - '**.lean'
      - 'lakefile.toml'
      - 'lake-manifest.json'
      - 'lean-toolchain'
      - '.github/workflows/ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: leanprover/lean-action@v1
        with:
          test: true
          use-mathlib-cache: true
