import CRNT.Flux.Elementary
import CRNT.LinearAlgebra.ConformalDecomposition
import Mathlib.LinearAlgebra.FiniteDimensional.Basic

/-!
# Conformal decomposition of steady fluxes into elementary flux modes

The steady flux cone is a finite-dimensional polyhedral cone.  Every nonzero
nonnegative steady flux admits a finite conformal decomposition into support-minimal
nonnegative steady fluxes (elementary flux modes).  This is the structural theorem
behind the use of EFMs as generators of steady-state pathway space.
-/

namespace CRNT
namespace Network

open scoped BigOperators

variable {S : Type} [DecidableEq S] [Fintype S]

/-- `w` is a conformal subflux of `v`: it lies in the same nonnegative orthant and
never exceeds `v` coordinatewise.  For nonnegative vectors this is the usual conformal
order. -/
def IsConformalSubflux (N : Network S) (w v : N.R → ℝ) : Prop :=
  w ∈ N.FluxCone ∧ ∀ r, w r ≤ v r

/-- Finite EFM decomposition of a steady flux. -/
structure EFMDecomposition (N : Network S) (v : N.R → ℝ) where
  n : ℕ
  mode : Fin n → (N.R → ℝ)
  coeff : Fin n → ℝ
  coeff_pos : ∀ i, 0 < coeff i
  elementary : ∀ i, N.IsElementaryFluxMode (mode i)
  conformal : ∀ i r, mode i r ≠ 0 → v r ≠ 0
  reconstruct : v = ∑ i, coeff i • mode i

/-- Every term of an EFM decomposition belongs to the original support. -/
theorem EFMDecomposition.support_subset
    {N : Network S} {v : N.R → ℝ} (D : N.EFMDecomposition v) (i : Fin D.n) :
    N.fluxSupport (D.mode i) ⊆ N.fluxSupport v := by
  intro r hr
  exact (N.mem_fluxSupport_iff _ _).2 (D.conformal i r ((N.mem_fluxSupport_iff _ _).1 hr))

theorem nonnegElementary_fluxSpace_iff_EFM (N : Network S) (v : N.R → ℝ) :
    CRNT.NonnegElementary N.fluxSpace v ↔ N.IsElementaryFluxMode v := by
  constructor
  · rintro ⟨hvS, hv0, hvnn, hmin⟩
    refine ⟨⟨hvnn, ?_⟩, hv0, ?_⟩
    · exact hvS
    · intro w hw hw0 hsub
      have hsub' : CRNT.support w ⊆ CRNT.support v := by
        simpa [CRNT.support, Network.fluxSupport] using hsub
      have hrev := hmin w hw.2 hw0 hw.1 hsub'
      simpa [CRNT.support, Network.fluxSupport] using hrev
  · rintro ⟨hv, hv0, hmin⟩
    refine ⟨hv.2, hv0, hv.1, ?_⟩
    intro w hwS hw0 hwnn hsub
    have hw : w ∈ N.FluxCone := ⟨hwnn, hwS⟩
    have hsub' : N.fluxSupport w ⊆ N.fluxSupport v := by
      simpa [CRNT.support, Network.fluxSupport] using hsub
    have hrev := hmin w hw hw0 hsub'
    simpa [CRNT.support, Network.fluxSupport] using hrev

/-- **Conformal decomposition theorem.** Every nonzero point of the steady flux cone is
an exact positive sum of EFMs with no support cancellation. -/
theorem exists_EFMDecomposition (N : Network S) {v : N.R → ℝ}
    (hv : v ∈ N.FluxCone) (hv0 : v ≠ 0) :
    Nonempty (N.EFMDecomposition v) := by
  have hvS : v ∈ N.fluxSpace := hv.2
  obtain ⟨L, hsum, hL⟩ := CRNT.exists_nonnegElementarySum hvS hv0 hv.1
  let mode : Fin L.length → (N.R → ℝ) := fun i => L.get i
  let coeff : Fin L.length → ℝ := fun _ => 1
  refine ⟨{
    n := L.length
    mode := mode
    coeff := coeff
    coeff_pos := ?_
    elementary := ?_
    conformal := ?_
    reconstruct := ?_ }⟩
  · intro i
    exact one_pos
  · intro i
    apply (nonnegElementary_fluxSpace_iff_EFM N (mode i)).1
    exact (hL (mode i) (List.get_mem L i)).1
  · intro i r hir
    have hsupp := (hL (mode i) (List.get_mem L i)).2
    have hmem : r ∈ CRNT.support (mode i) := CRNT.mem_support.mpr hir
    exact CRNT.mem_support.mp (hsupp hmem)
  · calc
      v = L.sum := hsum.symm
      _ = ∑ i : Fin L.length, L.get i := (CRNT.sum_get_eq_list_sum L).symm
      _ = ∑ i : Fin L.length, coeff i • mode i := by simp [coeff, mode]

/-- Zero has the empty EFM decomposition. -/
noncomputable def zeroEFMDecomposition (N : Network S) :
    N.EFMDecomposition (0 : N.R → ℝ) where
  n := 0
  mode := Fin.elim0
  coeff := Fin.elim0
  coeff_pos := by intro i; exact Fin.elim0 i
  elementary := by intro i; exact Fin.elim0 i
  conformal := by intro i; exact Fin.elim0 i
  reconstruct := by simp

/-- Every steady nonnegative flux, including zero, is generated by finitely many EFMs. -/
theorem fluxCone_generated_by_EFMs (N : Network S) (v : N.R → ℝ) :
    v ∈ N.FluxCone ↔
      ∃ n : ℕ, ∃ mode : Fin n → (N.R → ℝ), ∃ coeff : Fin n → ℝ,
        (∀ i, N.IsElementaryFluxMode (mode i)) ∧
        (∀ i, 0 ≤ coeff i) ∧
        v = ∑ i, coeff i • mode i := by
  constructor
  · intro hv
    by_cases hv0 : v = 0
    · subst v
      exact ⟨0, Fin.elim0, Fin.elim0,
        (fun i => Fin.elim0 i), (fun i => Fin.elim0 i), by simp⟩
    · rcases N.exists_EFMDecomposition hv hv0 with ⟨D⟩
      exact ⟨D.n, D.mode, D.coeff, D.elementary,
        fun i => (D.coeff_pos i).le, D.reconstruct⟩
  · rintro ⟨n, mode, coeff, he, hc, rfl⟩
    refine Finset.sum_induction (fun i : Fin n => coeff i • mode i)
      (fun z => z ∈ N.FluxCone) ?_ (N.zero_mem_fluxCone) ?_
    · intro a b ha hb
      exact N.fluxCone_add_mem ha hb
    · intro i _
      exact N.fluxCone_smul_mem (he i).1 (hc i)

/-- A strictly positive stationary flux admits an EFM decomposition whose union of
supports covers every reaction. -/
theorem positive_flux_EFM_support_cover (N : Network S) {v : N.R → ℝ}
    (hv : v ∈ N.FluxCone) (hpos : N.IsPositiveFlux v) :
    ∃ D : N.EFMDecomposition v,
      ∀ r : N.R, ∃ i : Fin D.n, r ∈ N.fluxSupport (D.mode i) := by
  by_cases hv0 : v = 0
  · subst v
    refine ⟨N.zeroEFMDecomposition, ?_⟩
    intro r
    have hr := hpos r
    simp at hr
  · rcases N.exists_EFMDecomposition hv hv0 with ⟨D⟩
    refine ⟨D, ?_⟩
    intro r
    by_contra hnone
    push Not at hnone
    have hzmode : ∀ i : Fin D.n, D.mode i r = 0 := by
      intro i
      exact not_ne_iff.mp (fun hne => hnone i ((N.mem_fluxSupport_iff _ _).2 hne))
    have hr := congrFun D.reconstruct r
    simp only [Finset.sum_apply, Pi.smul_apply, smul_eq_mul] at hr
    have hrsum : (∑ i : Fin D.n, D.coeff i * D.mode i r) = 0 := by
      apply Finset.sum_eq_zero
      intro i _
      rw [hzmode i, mul_zero]
    rw [hrsum] at hr
    exact (hpos r).ne' hr

/-- CRN consistency can therefore be characterized by a finite family of EFMs whose
supports cover the entire reaction set. -/
theorem consistent_iff_EFM_support_cover (N : Network S) :
    N.IsConsistent ↔
      ∃ n : ℕ, ∃ e : Fin n → (N.R → ℝ),
        (∀ i, N.IsElementaryFluxMode (e i)) ∧
        (∀ r : N.R, ∃ i, r ∈ N.fluxSupport (e i)) := by
  constructor
  · intro hcon
    rcases (N.isConsistent_iff_exists_positive_fluxCone).1 hcon with ⟨v, hv, hpos⟩
    rcases N.positive_flux_EFM_support_cover hv hpos with ⟨D, hcover⟩
    exact ⟨D.n, D.mode, D.elementary, hcover⟩
  · rintro ⟨n, e, he, hcover⟩
    apply (N.isConsistent_iff_exists_positive_fluxCone).2
    let v : N.R → ℝ := ∑ i : Fin n, e i
    refine ⟨v, ?_, ?_⟩
    · dsimp [v]
      refine Finset.sum_induction (fun i : Fin n => e i)
        (fun z => z ∈ N.FluxCone) ?_ (N.zero_mem_fluxCone) ?_
      · intro a b ha hb
        exact N.fluxCone_add_mem ha hb
      · intro i _
        exact (he i).1
    · intro r
      rcases hcover r with ⟨i, hi⟩
      have hine : e i r ≠ 0 := (N.mem_fluxSupport_iff _ _).1 hi
      have hipos : 0 < e i r := lt_of_le_of_ne ((he i).1.1 r) (Ne.symm hine)
      dsimp [v]
      simp only [Finset.sum_apply]
      apply Finset.sum_pos'
      · intro j _
        exact (he j).1.1 r
      · exact ⟨i, Finset.mem_univ i, hipos⟩

/-- Every extreme ray of the flux cone is support-minimal, hence represented by an
EFM.  `IsExtremeFluxRay` is stated intrinsically to avoid choosing a cone library. -/
def IsExtremeFluxRay (N : Network S) (v : N.R → ℝ) : Prop :=
  v ∈ N.FluxCone ∧ v ≠ 0 ∧
    ∀ a b : N.R → ℝ, a ∈ N.FluxCone → b ∈ N.FluxCone → v = a + b →
      (∃ α : ℝ, 0 ≤ α ∧ a = α • v) ∨
      (∃ β : ℝ, 0 ≤ β ∧ b = β • v)

/-- Extreme nonnegative steady-flux rays are elementary. -/
theorem elementary_of_extremeFluxRay (N : Network S) {v : N.R → ℝ}
    (hv : N.IsExtremeFluxRay v) : N.IsElementaryFluxMode v := by
  obtain ⟨D⟩ := N.exists_EFMDecomposition hv.1 hv.2.1
  have hn : 0 < D.n := by
    by_contra h
    have hn0 : D.n = 0 := Nat.eq_zero_of_not_pos h
    have hsum0 : (∑ j : Fin D.n, D.coeff j • D.mode j) = 0 := by
      apply Finset.sum_eq_zero
      intro j _
      have hj : j.val < 0 := by simpa [hn0] using j.isLt
      omega
    have hv0 : v = 0 := D.reconstruct.trans hsum0
    exact hv.2.1 hv0
  let i : Fin D.n := ⟨0, hn⟩
  let a : N.R → ℝ := D.coeff i • D.mode i
  let b : N.R → ℝ := ∑ j ∈ (Finset.univ.erase i), D.coeff j • D.mode j
  have haCone : a ∈ N.FluxCone :=
    N.fluxCone_smul_mem (D.elementary i).1 (D.coeff_pos i).le
  have hbCone : b ∈ N.FluxCone := by
    dsimp [b]
    refine Finset.sum_induction (fun j : Fin D.n => D.coeff j • D.mode j)
      (fun z => z ∈ N.FluxCone) ?_ (N.zero_mem_fluxCone) ?_
    · intro x y hx hy
      exact N.fluxCone_add_mem hx hy
    · intro j _
      exact N.fluxCone_smul_mem (D.elementary j).1 (D.coeff_pos j).le
  have hab : v = a + b := by
    rw [D.reconstruct]
    dsimp [a, b]
    rw [← Finset.add_sum_erase _ _ (Finset.mem_univ i)]
  have ha0 : a ≠ 0 := by
    intro h
    apply (D.elementary i).2.1
    funext r
    have hr := congrFun h r
    simp only [a, Pi.smul_apply, smul_eq_mul] at hr
    exact (mul_eq_zero.mp hr).resolve_left (D.coeff_pos i).ne'
  have hprop : ∃ γ : ℝ, 0 < γ ∧ a = γ • v := by
    rcases hv.2.2 a b haCone hbCone hab with ha | hb
    · obtain ⟨γ, hγ, hEq⟩ := ha
      refine ⟨γ, lt_of_le_of_ne hγ ?_, hEq⟩
      intro hγ0
      subst γ
      simp at hEq
      exact ha0 hEq
    · obtain ⟨β, hβ, hbEq⟩ := hb
      let γ : ℝ := 1 - β
      have haEq : a = γ • v := by
        funext r
        have habr := congrFun hab r
        have hbr := congrFun hbEq r
        simp only [Pi.add_apply] at habr
        simp only [Pi.smul_apply, smul_eq_mul] at hbr ⊢
        dsimp [γ]
        linarith
      have hγne : γ ≠ 0 := by
        intro hγ0
        rw [hγ0, zero_smul] at haEq
        exact ha0 haEq
      have hγnonneg : 0 ≤ γ := by
        by_contra hneg
        have hγneg : γ < 0 := lt_of_not_ge hneg
        have hvpos : ∃ r, 0 < v r := by
          obtain ⟨r, hr⟩ := Function.ne_iff.mp hv.2.1
          have hvr : v r ≠ 0 := by simpa using hr
          exact ⟨r, lt_of_le_of_ne (hv.1.1 r) (Ne.symm hvr)⟩
        obtain ⟨r, hvr⟩ := hvpos
        have har := haCone.1 r
        have hcoord := congrFun haEq r
        simp only [Pi.smul_apply, smul_eq_mul] at hcoord
        nlinarith
      exact ⟨γ, lt_of_le_of_ne hγnonneg (Ne.symm hγne), haEq⟩
  obtain ⟨γ, hγ, haEq⟩ := hprop
  have hvEq : v = γ⁻¹ • a := by
    rw [haEq]
    ext r
    simp only [Pi.smul_apply, smul_eq_mul]
    field_simp
  have haElem : N.IsElementaryFluxMode a := by
    simpa [a] using N.elementaryFluxMode_pos_smul (D.elementary i) (D.coeff_pos i)
  rw [hvEq]
  exact N.elementaryFluxMode_pos_smul haElem (inv_pos.mpr hγ)

end Network
end CRNT
