import CRNT.Flux.ConformalDecomposition
import CRNT.Decision.RationalFarkas
import CRNT.Decision.CriticalSiphonDecide
import CRNT.Stochastic.IntegerLattice
import CRNT.Stoich.RationalVector
import CRNT.LinearAlgebra.RationalDenominator

/-!
# Rational and integer T-invariants

CRN stoichiometry is integral.  Therefore the nonnegative steady-flux cone is a rational
polyhedral cone.  Every extreme/support-minimal ray contains a rational point and hence,
after clearing denominators, a nonzero natural-valued T-invariant.  More generally the
whole real flux cone is generated by finitely many natural T-invariants.

This is the exact bridge between continuous CRNT flux cones and Petri-net T-invariants /
finite reaction multiplicity vectors.
-/

namespace CRNT
namespace Network

open scoped BigOperators
open RationalFarkas

variable {S : Type} [DecidableEq S] [Fintype S]

/-- Integer-valued stationary reaction vector. -/
def IsIntegerTInvariant (N : Network S) (z : N.R → ℤ) : Prop :=
  ∀ s : S, ∑ r : N.R, z r * N.integerReactionVector r s = 0

/-- Natural-valued T-invariant / reaction multiplicity cycle. -/
def IsNaturalTInvariant (N : Network S) (m : N.R → ℕ) : Prop :=
  N.IsIntegerTInvariant (fun r => (m r : ℤ))

/-- Realification of a natural reaction multiplicity vector. -/
def realOfNaturalFlux {N : Network S} (m : N.R → ℕ) : N.R → ℝ :=
  fun r => (m r : ℝ)

/-- Natural T-invariants realify to nonnegative steady fluxes. -/
theorem realOfNaturalTInvariant_mem_fluxCone
    (N : Network S) {m : N.R → ℕ} (hm : N.IsNaturalTInvariant m) :
    realOfNaturalFlux m ∈ N.FluxCone := by
  refine ⟨fun r => Nat.cast_nonneg _, ?_⟩
  rw [N.isStationaryFlux_iff_species_balance]
  intro s
  have hs := hm s
  calc
    ∑ r : N.R, realOfNaturalFlux m r * N.reactionVector r s =
        ∑ r : N.R, ((m r : ℤ) : ℝ) * ((N.integerReactionVector r s : ℤ) : ℝ) := by
          apply Finset.sum_congr rfl
          intro r _
          simp [realOfNaturalFlux, integerReactionVector, reactionVector_apply]
    _ = ((∑ r : N.R, (m r : ℤ) * N.integerReactionVector r s : ℤ) : ℝ) := by
          push_cast
          rfl
    _ = 0 := by rw [hs]; simp

/-- Support of a natural multiplicity vector. -/
def naturalFluxSupport (N : Network S) (m : N.R → ℕ) : Finset N.R :=
  Finset.univ.filter fun r => m r ≠ 0

/-- Realification preserves support. -/
theorem fluxSupport_realOfNaturalFlux (N : Network S) (m : N.R → ℕ) :
    N.fluxSupport (realOfNaturalFlux m) = N.naturalFluxSupport m := by
  ext r
  simp [fluxSupport, naturalFluxSupport, realOfNaturalFlux]

noncomputable def rationalFluxSupportSystem (N : Network S)
    (eR : N.R ≃ Fin (Fintype.card N.R)) (eS : S ≃ Fin (Fintype.card S))
    (P : Finset N.R) : List (Ineq (Fintype.card N.R)) :=
  let A := (enumOfEquiv eR).map fun r : N.R =>
      encodeRow eR (fun q => if q = r then -1 else 0) 0
  let B := ((enumOfEquiv eR).filter (fun r => r ∉ P)).map
      (fun r => encodeRow eR (fun q => if q = r then 1 else 0) 0)
  let C := (enumOfEquiv eS).flatMap fun s : S =>
      [encodeRow eR (fun r => N.reactionCoeffQ r s) 0,
       encodeRow eR (fun r => -(N.reactionCoeffQ r s)) 0]
  let D := P.toList.map (fun r => encodeRow eR (fun q => if q = r then -1 else 0) (-1))
  A ++ (B ++ (C ++ D))

theorem lhsQ_encodeRow {A : Type} [DecidableEq A] [Fintype A]
    (e : A ≃ Fin (Fintype.card A)) (c : A → ℚ) (b : ℚ)
    (x : Fin (Fintype.card A) → ℚ) :
    (encodeRow e c b).lhs x = ∑ a : A, c a * x (e a) := by
  rw [Ineq.lhs, encodeRow]
  rw [← Equiv.sum_comp e (fun i => c (e.symm i) * x i)]
  apply Finset.sum_congr rfl
  intro a _
  rw [Equiv.symm_apply_apply]

/-- A rational point exists on every nonzero support-minimal ray of the rational
stoichiometric cone. -/
theorem elementaryFluxMode_has_rational_representative
    (N : Network S) {v : N.R → ℝ} (hv : N.IsElementaryFluxMode v) :
    ∃ q : N.R → ℚ,
      (∀ r, 0 ≤ q r) ∧ q ≠ 0 ∧
      (∀ s : S, ∑ r : N.R, q r * N.reactionCoeffQ r s = 0) ∧
      N.fluxSupport (fun r => (q r : ℝ)) = N.fluxSupport v := by
  classical
  let P := N.fluxSupport v
  let eR : N.R ≃ Fin (Fintype.card N.R) := Fintype.equivFin N.R
  let eS : S ≃ Fin (Fintype.card S) := Fintype.equivFin S
  have hPne : P.Nonempty := by
    by_contra h
    have hPe : P = ∅ := Finset.not_nonempty_iff_eq_empty.mp h
    apply hv.2.1
    funext r
    by_contra hr
    have : r ∈ P := by simpa [P] using (N.mem_fluxSupport_iff v r).2 hr
    simpa [hPe] using this
  let C : ℝ := ∑ r ∈ P, (v r)⁻¹
  have hvpos : ∀ r ∈ P, 0 < v r := by
    intro r hr
    have hn := hv.1.1 r
    have hne : v r ≠ 0 := by simpa [P] using hr
    exact lt_of_le_of_ne hn (Ne.symm hne)
  have hCnonneg : 0 ≤ C := by
    dsimp [C]
    exact Finset.sum_nonneg fun r hr => inv_nonneg.mpr (hvpos r hr).le
  have hmargin : ∀ r ∈ P, 1 ≤ C * v r := by
    intro r hr
    have hsingle : (v r)⁻¹ ≤ C := by
      dsimp [C]
      exact Finset.single_le_sum (fun q hq => inv_nonneg.mpr (hvpos q hq).le) hr
    have hmul := mul_le_mul_of_nonneg_right hsingle (hvpos r hr).le
    rw [inv_mul_cancel₀ (hvpos r hr).ne'] at hmul
    exact hmul
  let u : N.R → ℝ := fun r => C * v r
  have hu_nonneg : ∀ r, 0 ≤ u r := fun r => mul_nonneg hCnonneg (hv.1.1 r)
  have hu_off : ∀ r ∉ P, u r = 0 := by
    intro r hr
    have hvzero : v r = 0 := by
      by_contra hn
      exact hr (by simpa [P] using (N.mem_fluxSupport_iff v r).2 hn)
    simp [u, hvzero]
  have hvbal : ∀ s : S, ∑ r : N.R, v r * N.reactionVector r s = 0 :=
    (N.isStationaryFlux_iff_species_balance v).1 hv.1.2
  have hubal : ∀ s : S, ∑ r : N.R, u r * N.reactionVector r s = 0 := by
    intro s
    simp only [u, Finset.mul_sum]
    calc
      ∑ r : N.R, C * v r * N.reactionVector r s =
          C * ∑ r : N.R, v r * N.reactionVector r s := by
            rw [Finset.mul_sum]
            apply Finset.sum_congr rfl
            intro r _
            ring
      _ = 0 := by rw [hvbal s, mul_zero]
  have hReal : Feasibleℝ (N.rationalFluxSupportSystem eR eS P) := by
    refine ⟨fun i => u (eR.symm i), ?_⟩
    intro I hI
    rw [rationalFluxSupportSystem] at hI
    simp only [List.mem_append] at hI
    rcases hI with hnonneg | hoff | hbal | hmarginrow
    · rw [List.mem_map] at hnonneg
      obtain ⟨r, _hr, rfl⟩ := hnonneg
      rw [Ineq.holdsℝ, lhsℝ_encodeRow]
      simp only [Equiv.symm_apply_apply, encodeRow_bound, Rat.cast_zero]
      have key : (∑ q : N.R, ((if q = r then (-1 : ℚ) else 0 : ℚ) : ℝ) * u q) = -u r := by
        rw [Finset.sum_eq_single r]
        · simp
        · intro b _ hb; simp [hb]
        · intro h; simp at h
      rw [key]
      linarith [hu_nonneg r]
    · rw [List.mem_map] at hoff
      obtain ⟨r, hr, rfl⟩ := hoff
      have hrP : r ∉ P := by
        rw [List.mem_filter] at hr
        simpa using hr.2
      rw [Ineq.holdsℝ, lhsℝ_encodeRow]
      simp only [Equiv.symm_apply_apply, encodeRow_bound, Rat.cast_zero]
      have key : (∑ q : N.R, ((if q = r then (1 : ℚ) else 0 : ℚ) : ℝ) * u q) = u r := by
        rw [Finset.sum_eq_single r]
        · simp
        · intro b _ hb; simp [hb]
        · intro h; simp at h
      rw [key, hu_off r hrP]
    · rw [List.mem_flatMap] at hbal
      obtain ⟨s, hs, hrow⟩ := hbal
      rw [List.mem_cons] at hrow
      rcases hrow with rfl | hrow
      · rw [Ineq.holdsℝ, lhsℝ_encodeRow]
        simp only [Equiv.symm_apply_apply, encodeRow_bound, Rat.cast_zero]
        have hcast : (∑ r : N.R, (N.reactionCoeffQ r s : ℝ) * u r) = 0 := by
          calc
            _ = ∑ r : N.R, u r * N.reactionVector r s := by
              apply Finset.sum_congr rfl
              intro r _
              rw [N.cast_reactionCoeffQ]
              ring
            _ = 0 := hubal s
        exact hcast.le
      · simp only [List.mem_singleton] at hrow
        subst I
        rw [Ineq.holdsℝ, lhsℝ_encodeRow]
        simp only [Equiv.symm_apply_apply, encodeRow_bound, Rat.cast_zero, Rat.cast_neg]
        have hcast : (∑ r : N.R, (-(N.reactionCoeffQ r s) : ℝ) * u r) = 0 := by
          calc
            ∑ r : N.R, (-(N.reactionCoeffQ r s) : ℝ) * u r =
                -(∑ r : N.R, u r * N.reactionVector r s) := by
                  rw [← Finset.sum_neg_distrib]
                  congr 1
                  funext r
                  rw [N.cast_reactionCoeffQ]
                  ring
            _ = 0 := by rw [hubal s]; simp
        exact hcast.le
    · rw [List.mem_map] at hmarginrow
      obtain ⟨r, hr, rfl⟩ := hmarginrow
      have hrP : r ∈ P := by simpa using hr
      rw [Ineq.holdsℝ, lhsℝ_encodeRow]
      simp only [Equiv.symm_apply_apply, encodeRow_bound, Rat.cast_neg, Rat.cast_one]
      have key : (∑ q : N.R, ((if q = r then (-1 : ℚ) else 0 : ℚ) : ℝ) * u q) = -u r := by
        rw [Finset.sum_eq_single r]
        · simp
        · intro b _ hb; simp [hb]
        · intro h; simp at h
      rw [key]
      linarith [hmargin r hrP]
  have hQ : Feasible (N.rationalFluxSupportSystem eR eS P) :=
    (feasibleℝ_iff_feasible _).mp hReal
  rcases hQ with ⟨x, hx⟩
  let q : N.R → ℚ := fun r => x (eR r)
  have hqnonneg : ∀ r, 0 ≤ q r := by
    intro r
    have hrow := hx (encodeRow eR (fun z => if z = r then -1 else 0) 0) (by
      rw [rationalFluxSupportSystem]
      simp only [List.mem_append]
      exact Or.inl (List.mem_map.mpr ⟨r, mem_enumOfEquiv eR r, rfl⟩))
    rw [Ineq.holds, lhsQ_encodeRow] at hrow
    simpa [q] using hrow
  have hqoff : ∀ r ∉ P, q r = 0 := by
    intro r hr
    have hrow := hx (encodeRow eR (fun z => if z = r then 1 else 0) 0) (by
      rw [rationalFluxSupportSystem]
      simp only [List.mem_append]
      apply Or.inr; apply Or.inl
      exact List.mem_map.mpr ⟨r, by rw [List.mem_filter]; exact ⟨mem_enumOfEquiv eR r, by simpa using hr⟩, rfl⟩)
    rw [Ineq.holds, lhsQ_encodeRow] at hrow
    have hle : q r ≤ 0 := by simpa [q] using hrow
    exact le_antisymm hle (hqnonneg r)
  have hqmargin : ∀ r ∈ P, 1 ≤ q r := by
    intro r hr
    have hrow := hx (encodeRow eR (fun z => if z = r then -1 else 0) (-1)) (by
      rw [rationalFluxSupportSystem]
      simp only [List.mem_append]
      apply Or.inr; apply Or.inr; apply Or.inr
      exact List.mem_map.mpr ⟨r, by simpa using hr, rfl⟩)
    rw [Ineq.holds, lhsQ_encodeRow] at hrow
    simpa [q] using hrow
  have hqbal : ∀ s : S, ∑ r : N.R, q r * N.reactionCoeffQ r s = 0 := by
    intro s
    have hpos := hx (encodeRow eR (fun r => N.reactionCoeffQ r s) 0) (by
      rw [rationalFluxSupportSystem]
      simp only [List.mem_append]
      apply Or.inr; apply Or.inr; apply Or.inl
      rw [List.mem_flatMap]
      exact ⟨s, mem_enumOfEquiv eS s, by simp⟩)
    have hneg := hx (encodeRow eR (fun r => -(N.reactionCoeffQ r s)) 0) (by
      rw [rationalFluxSupportSystem]
      simp only [List.mem_append]
      apply Or.inr; apply Or.inr; apply Or.inl
      rw [List.mem_flatMap]
      exact ⟨s, mem_enumOfEquiv eS s, by simp⟩)
    rw [Ineq.holds, lhsQ_encodeRow] at hpos hneg
    have hneg' : -(∑ r : N.R, q r * N.reactionCoeffQ r s) ≤ 0 := by
      simpa [q, mul_comm, ← Finset.sum_neg_distrib] using hneg
    have hpos' : (∑ r : N.R, q r * N.reactionCoeffQ r s) ≤ 0 := by simpa [q, mul_comm] using hpos
    linarith
  have hq0 : q ≠ 0 := by
    intro hz
    obtain ⟨r, hr⟩ := hPne
    have hm := hqmargin r hr
    have : q r = 0 := congrFun hz r
    linarith
  refine ⟨q, hqnonneg, hq0, hqbal, ?_⟩
  ext r
  rw [N.mem_fluxSupport_iff, N.mem_fluxSupport_iff]
  constructor
  · intro hqr
    by_contra hvr
    have hrNotP : r ∉ P := by
      simpa [P] using hvr
    exact hqr (by exact_mod_cast hqoff r hrNotP)
  · intro hvr
    have hrP : r ∈ P := by simpa [P] using hvr
    have hm := hqmargin r hrP
    have hqne : q r ≠ 0 := by linarith
    exact_mod_cast hqne

/-- **Every EFM ray contains an integer T-invariant with the same support.** -/
theorem elementaryFluxMode_has_naturalTInvariant
    (N : Network S) {v : N.R → ℝ} (hv : N.IsElementaryFluxMode v) :
    ∃ m : N.R → ℕ,
      N.IsNaturalTInvariant m ∧
      m ≠ 0 ∧
      N.naturalFluxSupport m = N.fluxSupport v := by
  rcases N.elementaryFluxMode_has_rational_representative hv with
    ⟨q, hqnonneg, hq0, hqbal, hqsupp⟩
  let D : ℕ := rationalCommonDenominator q
  let m : N.R → ℕ := clearRationalToNat q
  have hDpos : 0 < D := rationalCommonDenominator_pos q
  have hcast : ∀ r : N.R, ((m r : ℕ) : ℚ) = (D : ℚ) * q r := by
    intro r
    exact cast_clearRationalToNat q hqnonneg r
  have hcoeff : ∀ r : N.R, ∀ s : S,
      ((N.integerReactionVector r s : ℤ) : ℚ) = N.reactionCoeffQ r s := by
    intro r s
    simp [integerReactionVector, reactionCoeffQ]
  have hm : N.IsNaturalTInvariant m := by
    intro s
    apply Rat.intCast_injective
    change ((∑ r : N.R, (m r : ℤ) * N.integerReactionVector r s : ℤ) : ℚ) = 0
    push_cast
    simp_rw [hcoeff]
    simp_rw [hcast]
    simp_rw [mul_assoc]
    rw [← Finset.mul_sum, hqbal s, mul_zero]
  have hm0 : m ≠ 0 := by
    intro hmzero
    apply hq0
    funext r
    have hz : m r = 0 := by simpa [hmzero]
    have hc := hcast r
    rw [hz] at hc
    simp only [Nat.cast_zero] at hc
    have hDq : (D : ℚ) ≠ 0 := by exact_mod_cast hDpos.ne'
    exact (mul_eq_zero.mp hc.symm).resolve_left hDq
  have hsuppmq : N.naturalFluxSupport m = N.fluxSupport (fun r => (q r : ℝ)) := by
    ext r
    simp only [naturalFluxSupport, fluxSupport, Finset.mem_filter, Finset.mem_univ, true_and]
    constructor
    · intro hmr hqr
      have hqz : q r = 0 := by exact_mod_cast hqr
      have hc := hcast r
      rw [hqz, mul_zero] at hc
      have hmz : m r = 0 := by exact_mod_cast hc
      exact hmr hmz
    · intro hqr hmr
      have hc := hcast r
      rw [hmr] at hc
      simp only [Nat.cast_zero] at hc
      have hDq : (D : ℚ) ≠ 0 := by exact_mod_cast hDpos.ne'
      have hqzero : q r = 0 := (mul_eq_zero.mp hc.symm).resolve_left hDq
      exact hqr (by exact_mod_cast hqzero)
  exact ⟨m, hm, hm0, hsuppmq.trans hqsupp⟩

/-- Conversely, support-minimal nonzero natural T-invariants realify to EFMs. -/
theorem elementaryFluxMode_of_supportMinimal_naturalTInvariant
    (N : Network S) {m : N.R → ℕ}
    (hm : N.IsNaturalTInvariant m) (hm0 : m ≠ 0)
    (hmin : ∀ n : N.R → ℕ,
      N.IsNaturalTInvariant n → n ≠ 0 →
      N.naturalFluxSupport n ⊆ N.naturalFluxSupport m →
      N.naturalFluxSupport m ⊆ N.naturalFluxSupport n) :
    N.IsElementaryFluxMode (realOfNaturalFlux m) := by
  have hv : realOfNaturalFlux m ∈ N.FluxCone :=
    N.realOfNaturalTInvariant_mem_fluxCone hm
  have hv0 : realOfNaturalFlux m ≠ 0 := by
    intro hzero
    apply hm0
    funext r
    have hr := congrFun hzero r
    simp [realOfNaturalFlux] at hr
    exact_mod_cast hr
  refine ⟨hv, hv0, ?_⟩
  intro w hw hw0 hsub
  rcases N.exists_EFMDecomposition hw hw0 with ⟨D⟩
  have hnpos : 0 < D.n := by
    by_contra hn
    have hn0 : D.n = 0 := Nat.eq_zero_of_not_pos hn
    have hempty : IsEmpty (Fin D.n) := by
      rw [hn0]
      infer_instance
    have hsum : (∑ i : Fin D.n, D.coeff i • D.mode i) = 0 := by
      apply Finset.sum_eq_zero
      intro i _
      exact isEmptyElim i
    exact hw0 (D.reconstruct.trans hsum)
  let i0 : Fin D.n := ⟨0, hnpos⟩
  rcases N.elementaryFluxMode_has_naturalTInvariant (D.elementary i0) with
    ⟨n, hn, hn0, hnsupp⟩
  have hni_sub_w : N.naturalFluxSupport n ⊆ N.fluxSupport w := by
    rw [hnsupp]
    exact D.support_subset i0
  have hni_sub_m : N.naturalFluxSupport n ⊆ N.naturalFluxSupport m := by
    rw [← N.fluxSupport_realOfNaturalFlux m]
    exact Set.Subset.trans hni_sub_w hsub
  have hm_sub_n : N.naturalFluxSupport m ⊆ N.naturalFluxSupport n :=
    hmin n hn hn0 hni_sub_m
  rw [N.fluxSupport_realOfNaturalFlux m]
  intro r hr
  exact hni_sub_w (hm_sub_n hr)

/-- The real flux cone is generated by finitely many natural T-invariants. -/
theorem fluxCone_generated_by_naturalTInvariants (N : Network S) :
    ∃ n : ℕ, ∃ m : Fin n → (N.R → ℕ),
      (∀ i, N.IsNaturalTInvariant (m i)) ∧
      ∀ v : N.R → ℝ, v ∈ N.FluxCone →
        ∃ a : Fin n → ℝ, (∀ i, 0 ≤ a i) ∧
          v = ∑ i, a i • realOfNaturalFlux (m i) := by
  classical
  let T := {A : Finset N.R // ∃ e : N.R → ℝ,
    N.IsElementaryFluxMode e ∧ N.fluxSupport e = A}
  letI : Fintype T := Fintype.ofFinite T
  let rep : T → (N.R → ℝ) := fun A => Classical.choose A.property
  have hrepElem : ∀ A : T, N.IsElementaryFluxMode (rep A) := fun A =>
    (Classical.choose_spec A.property).1
  have hrepSupp : ∀ A : T, N.fluxSupport (rep A) = A.1 := fun A =>
    (Classical.choose_spec A.property).2
  let natrep : T → (N.R → ℕ) := fun A =>
    Classical.choose (N.elementaryFluxMode_has_naturalTInvariant (hrepElem A))
  have hnat : ∀ A : T, N.IsNaturalTInvariant (natrep A) := fun A =>
    (Classical.choose_spec (N.elementaryFluxMode_has_naturalTInvariant (hrepElem A))).1
  have hnat0 : ∀ A : T, natrep A ≠ 0 := fun A =>
    (Classical.choose_spec (N.elementaryFluxMode_has_naturalTInvariant (hrepElem A))).2.1
  have hnatsupp : ∀ A : T, N.naturalFluxSupport (natrep A) = A.1 := fun A => by
    exact (Classical.choose_spec (N.elementaryFluxMode_has_naturalTInvariant (hrepElem A))).2.2.trans (hrepSupp A)
  let e : T ≃ Fin (Fintype.card T) := Fintype.equivFin T
  let m : Fin (Fintype.card T) → (N.R → ℕ) := fun i => natrep (e.symm i)
  refine ⟨Fintype.card T, m, ?_, ?_⟩
  · intro i
    exact hnat (e.symm i)
  · intro v hv
    by_cases hv0 : v = 0
    · refine ⟨0, (fun i => le_rfl), ?_⟩
      simp [hv0]
    rcases N.exists_EFMDecomposition hv hv0 with ⟨D⟩
    let cls : Fin D.n → T := fun i =>
      ⟨N.fluxSupport (D.mode i), D.mode i, D.elementary i, rfl⟩
    have hwCone : ∀ A : T, realOfNaturalFlux (natrep A) ∈ N.FluxCone := fun A =>
      N.realOfNaturalTInvariant_mem_fluxCone (hnat A)
    have hw0 : ∀ A : T, realOfNaturalFlux (natrep A) ≠ 0 := by
      intro A hz
      apply hnat0 A
      funext r
      have hr := congrFun hz r
      simp [realOfNaturalFlux] at hr
      exact_mod_cast hr
    have hwsupp : ∀ A : T,
        N.fluxSupport (realOfNaturalFlux (natrep A)) = A.1 := by
      intro A
      rw [N.fluxSupport_realOfNaturalFlux, hnatsupp A]
    have hmodeScale : ∀ i : Fin D.n, ∃ t : ℝ, 0 < t ∧
        D.mode i = t • realOfNaturalFlux (natrep (cls i)) := by
      intro i
      have he : CRNT.NonnegElementary N.fluxSpace (D.mode i) :=
        (N.nonnegElementary_fluxSpace_iff_EFM (D.mode i)).2 (D.elementary i)
      have hsuppFlux : N.fluxSupport (realOfNaturalFlux (natrep (cls i))) =
          N.fluxSupport (D.mode i) := by
        rw [hwsupp (cls i)]
      have hsuppEq : CRNT.support (realOfNaturalFlux (natrep (cls i))) = CRNT.support (D.mode i) := by
        simpa only [CRNT.support, Network.fluxSupport] using hsuppFlux
      have hsub : CRNT.support (realOfNaturalFlux (natrep (cls i))) ⊆ CRNT.support (D.mode i) := by
        rw [hsuppEq]
      exact he.eq_pos_smul_of_support_subset (hwCone (cls i)).2 (hw0 (cls i))
        (hwCone (cls i)).1 hsub
    choose scale hscalePos hscale using hmodeScale
    let aT : T → ℝ := fun A =>
      ∑ i : Fin D.n, if cls i = A then D.coeff i * scale i else 0
    have haT : ∀ A, 0 ≤ aT A := by
      intro A
      dsimp [aT]
      apply Finset.sum_nonneg
      intro i _
      split_ifs
      · exact mul_nonneg (D.coeff_pos i).le (hscalePos i).le
      · exact le_rfl
    let a : Fin (Fintype.card T) → ℝ := fun i => aT (e.symm i)
    refine ⟨a, ?_, ?_⟩
    · intro i; exact haT _
    rw [D.reconstruct]
    -- reindex the finite global generator family by T
    have hreindex :
        (∑ i : Fin (Fintype.card T), a i • realOfNaturalFlux (m i)) =
          ∑ A : T, aT A • realOfNaturalFlux (natrep A) := by
      exact Fintype.sum_equiv e.symm (fun i => a i • realOfNaturalFlux (m i))
        (fun A => aT A • realOfNaturalFlux (natrep A)) (fun i => by rfl)
    rw [hreindex]
    -- regroup the EFM decomposition by support class
    ext r
    simp only [Finset.sum_apply, Pi.smul_apply, smul_eq_mul, aT]
    simp_rw [Finset.sum_mul]
    rw [Finset.sum_comm]
    apply Finset.sum_congr rfl
    intro i _
    rw [hscale i]
    simp only [Pi.smul_apply, smul_eq_mul]
    have hinner : (∑ A : T, (if cls i = A then D.coeff i * scale i else 0) *
          realOfNaturalFlux (natrep A) r) =
        (D.coeff i * scale i) * realOfNaturalFlux (natrep (cls i)) r := by
      rw [Finset.sum_eq_single (cls i)]
      · simp
      · intro A _ hA
        have hne : cls i ≠ A := fun h => hA h.symm
        simp [hne]
      · simp
    rw [hinner]
    ring

/-- Consistency is equivalent to having finitely many natural T-invariants whose
supports cover every reaction. -/
theorem consistent_iff_naturalTInvariant_support_cover (N : Network S) :
    N.IsConsistent ↔
      ∃ n : ℕ, ∃ m : Fin n → (N.R → ℕ),
        (∀ i, N.IsNaturalTInvariant (m i)) ∧
        (∀ i, m i ≠ 0) ∧
        ∀ r : N.R, ∃ i, r ∈ N.naturalFluxSupport (m i) := by
  constructor
  · intro hcon
    rcases (N.consistent_iff_EFM_support_cover).1 hcon with ⟨n, e, he, hcover⟩
    choose m hm hm0 hsupp using fun i => N.elementaryFluxMode_has_naturalTInvariant (he i)
    refine ⟨n, m, hm, hm0, ?_⟩
    intro r
    rcases hcover r with ⟨i, hi⟩
    exact ⟨i, by simpa [hsupp i] using hi⟩
  · rintro ⟨n, m, hm, _hm0, hcover⟩
    apply (N.isConsistent_iff_exists_positive_fluxCone).2
    let v : N.R → ℝ := ∑ i : Fin n, realOfNaturalFlux (m i)
    refine ⟨v, ?_, ?_⟩
    · dsimp [v]
      refine Finset.sum_induction (fun i : Fin n => realOfNaturalFlux (m i))
        (fun z => z ∈ N.FluxCone) ?_ (N.zero_mem_fluxCone) ?_
      · intro a b ha hb
        exact N.fluxCone_add_mem ha hb
      · intro i _
        exact N.realOfNaturalTInvariant_mem_fluxCone (hm i)
    · intro r
      rcases hcover r with ⟨i, hi⟩
      have hmne : m i r ≠ 0 := by
        simpa [naturalFluxSupport] using hi
      have hmpos : 0 < (m i r : ℝ) := by
        exact_mod_cast Nat.pos_of_ne_zero hmne
      dsimp [v, realOfNaturalFlux]
      simp only [Finset.sum_apply]
      apply Finset.sum_pos'
      · intro j _
        exact Nat.cast_nonneg _
      · exact ⟨i, Finset.mem_univ i, hmpos⟩

/-- Weakly reversible networks therefore admit natural cycle multiplicities covering
all reaction channels. -/
theorem weaklyReversible_has_naturalTInvariant_cover
    (N : Network S) (hwr : N.WeaklyReversible) :
    ∃ n : ℕ, ∃ m : Fin n → (N.R → ℕ),
      (∀ i, N.IsNaturalTInvariant (m i)) ∧
      (∀ i, m i ≠ 0) ∧
      ∀ r : N.R, ∃ i, r ∈ N.naturalFluxSupport (m i) := by
  exact (N.consistent_iff_naturalTInvariant_support_cover).1
    (N.isConsistent_of_weaklyReversible hwr)

end Network
end CRNT
